-- generated by tools/import-mushmap.py — do not edit
-- rooms 12751..13500
local M = {}
M[#M+1] = {uid=18174,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=23,y=17,z=0,building=""}
M[#M+1] = {uid=18175,name="Astarchia",area="gelidus",terrain="snow",info="",notes="",x=24,y=17,z=0,building=""}
M[#M+1] = {uid=18176,name="Astarchia",area="gelidus",terrain="snow",info="",notes="",x=25,y=17,z=0,building=""}
M[#M+1] = {uid=18177,name="Astarchia",area="gelidus",terrain="snow",info="",notes="",x=26,y=17,z=0,building=""}
M[#M+1] = {uid=18178,name="Astarchia",area="gelidus",terrain="snow",info="",notes="",x=27,y=17,z=0,building=""}
M[#M+1] = {uid=18179,name="Astarchia",area="gelidus",terrain="snow",info="",notes="",x=28,y=17,z=0,building=""}
M[#M+1] = {uid=18180,name="Astarchia",area="gelidus",terrain="snow",info="",notes="",x=29,y=17,z=0,building=""}
M[#M+1] = {uid=18181,name="Astarchia",area="gelidus",terrain="snow",info="",notes="",x=30,y=17,z=0,building=""}
M[#M+1] = {uid=18182,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=31,y=17,z=0,building=""}
M[#M+1] = {uid=18183,name="Snowfields",area="gelidus",terrain="snow",info="",notes="",x=32,y=17,z=0,building=""}
M[#M+1] = {uid=18184,name="Snowfields",area="gelidus",terrain="snow",info="",notes="",x=33,y=17,z=0,building=""}
M[#M+1] = {uid=18185,name="Snowfields",area="gelidus",terrain="snow",info="",notes="",x=34,y=17,z=0,building=""}
M[#M+1] = {uid=18186,name="Snowfields",area="gelidus",terrain="snow",info="",notes="",x=35,y=17,z=0,building=""}
M[#M+1] = {uid=18187,name="Snowfields",area="gelidus",terrain="snow",info="",notes="",x=36,y=17,z=0,building=""}
M[#M+1] = {uid=18188,name="Snowfields",area="gelidus",terrain="snow",info="",notes="",x=37,y=17,z=0,building=""}
M[#M+1] = {uid=18189,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=38,y=17,z=0,building=""}
M[#M+1] = {uid=18190,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=39,y=17,z=0,building=""}
M[#M+1] = {uid=18191,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=40,y=17,z=0,building=""}
M[#M+1] = {uid=18192,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=41,y=17,z=0,building=""}
M[#M+1] = {uid=18193,name="Snowfields",area="gelidus",terrain="snow",info="",notes="",x=42,y=17,z=0,building=""}
M[#M+1] = {uid=18194,name="Nordaustlandet",area="gelidus",terrain="snow",info="",notes="",x=43,y=17,z=0,building=""}
M[#M+1] = {uid=18195,name="Nordaustlandet",area="gelidus",terrain="snow",info="",notes="",x=44,y=17,z=0,building=""}
M[#M+1] = {uid=18196,name="Nordaustlandet",area="gelidus",terrain="field4",info="",notes="",x=45,y=17,z=0,building=""}
M[#M+1] = {uid=18197,name="Nordaustlandet",area="gelidus",terrain="snow",info="",notes="",x=46,y=17,z=0,building=""}
M[#M+1] = {uid=18198,name="Nordaustlandet",area="gelidus",terrain="snow",info="",notes="",x=47,y=17,z=0,building=""}
M[#M+1] = {uid=18199,name="Nordaustlandet",area="gelidus",terrain="snow",info="",notes="",x=48,y=17,z=0,building=""}
M[#M+1] = {uid=18200,name="Nordaustlandet",area="gelidus",terrain="snow",info="",notes="",x=49,y=17,z=0,building=""}
M[#M+1] = {uid=18201,name="Nordaustlandet",area="gelidus",terrain="snow",info="",notes="",x=50,y=17,z=0,building=""}
M[#M+1] = {uid=18202,name="Nordaustlandet",area="gelidus",terrain="snow",info="",notes="",x=51,y=17,z=0,building=""}
M[#M+1] = {uid=18203,name="Nordaustlandet",area="gelidus",terrain="snow",info="",notes="",x=52,y=17,z=0,building=""}
M[#M+1] = {uid=18204,name="L'Aquantina",area="gelidus",terrain="snow",info="",notes="",x=53,y=17,z=0,building=""}
M[#M+1] = {uid=18205,name="Nordaustlandet",area="gelidus",terrain="field4",info="",notes="",x=54,y=17,z=0,building=""}
M[#M+1] = {uid=18206,name="L'Aquantina",area="gelidus",terrain="snow",info="",notes="",x=55,y=17,z=0,building=""}
M[#M+1] = {uid=18207,name="A Marble Beacon",area="gelidus",terrain="field4",info="",notes="",x=56,y=17,z=0,building=""}
M[#M+1] = {uid=18208,name="L'Aquantina",area="gelidus",terrain="snow",info="",notes="",x=57,y=17,z=0,building=""}
M[#M+1] = {uid=18209,name="L'Aquantina",area="gelidus",terrain="snow",info="",notes="",x=58,y=17,z=0,building=""}
M[#M+1] = {uid=18210,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=59,y=17,z=0,building=""}
M[#M+1] = {uid=18211,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=0,y=18,z=0,building=""}
M[#M+1] = {uid=18212,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=1,y=18,z=0,building=""}
M[#M+1] = {uid=18213,name="Steinsvik",area="gelidus",terrain="ocean2",info="",notes="",x=2,y=18,z=0,building=""}
M[#M+1] = {uid=18214,name="Steinsvik Badlands",area="gelidus",terrain="snow",info="",notes="",x=3,y=18,z=0,building=""}
M[#M+1] = {uid=18215,name="Steinsvik Badlands",area="gelidus",terrain="icehills",info="",notes="",x=4,y=18,z=0,building=""}
M[#M+1] = {uid=18216,name="Steinsvik Badlands",area="gelidus",terrain="icehills",info="",notes="",x=5,y=18,z=0,building=""}
M[#M+1] = {uid=18217,name="Steinsvik Badlands",area="gelidus",terrain="snow",info="",notes="",x=6,y=18,z=0,building=""}
M[#M+1] = {uid=18218,name="The Shivering Grounds",area="gelidus",terrain="snow",info="",notes="",x=7,y=18,z=0,building=""}
M[#M+1] = {uid=18219,name="The Shivering Grounds",area="gelidus",terrain="snow",info="",notes="",x=8,y=18,z=0,building=""}
M[#M+1] = {uid=18220,name="The Shivering Grounds",area="gelidus",terrain="icehills",info="",notes="",x=9,y=18,z=0,building=""}
M[#M+1] = {uid=18221,name="Megara Lavafields",area="gelidus",terrain="icehills",info="",notes="",x=10,y=18,z=0,building=""}
M[#M+1] = {uid=18222,name="A Trapdoor in the Mountains",area="gelidus",terrain="snow",info="",notes="",x=11,y=18,z=0,building=""}
M[#M+1] = {uid=18223,name="Megara Lavafields",area="gelidus",terrain="icehills",info="",notes="",x=12,y=18,z=0,building=""}
M[#M+1] = {uid=18224,name="Megara Snowfields",area="gelidus",terrain="snow",info="",notes="",x=13,y=18,z=0,building=""}
M[#M+1] = {uid=18225,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=14,y=18,z=0,building=""}
M[#M+1] = {uid=18226,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=15,y=18,z=0,building=""}
M[#M+1] = {uid=18227,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=16,y=18,z=0,building=""}
M[#M+1] = {uid=18228,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=17,y=18,z=0,building=""}
M[#M+1] = {uid=18229,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=18,y=18,z=0,building=""}
M[#M+1] = {uid=18230,name="Iceridge Snowfields",area="gelidus",terrain="snow",info="",notes="",x=19,y=18,z=0,building=""}
M[#M+1] = {uid=18231,name="Icereach Rim",area="gelidus",terrain="icehills",info="",notes="",x=20,y=18,z=0,building=""}
M[#M+1] = {uid=18232,name="Iceridge Snowfields",area="gelidus",terrain="snow",info="",notes="",x=21,y=18,z=0,building=""}
M[#M+1] = {uid=18233,name="Sapphire Mesa",area="gelidus",terrain="icehills",info="",notes="",x=22,y=18,z=0,building=""}
M[#M+1] = {uid=18234,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=23,y=18,z=0,building=""}
M[#M+1] = {uid=18235,name="Icereach Rim",area="gelidus",terrain="icehills",info="",notes="",x=24,y=18,z=0,building=""}
M[#M+1] = {uid=18236,name="Astarchia",area="gelidus",terrain="snow",info="",notes="",x=25,y=18,z=0,building=""}
M[#M+1] = {uid=18237,name="Icereach Rim",area="gelidus",terrain="icehills",info="",notes="",x=26,y=18,z=0,building=""}
M[#M+1] = {uid=18238,name="Icereach Rim",area="gelidus",terrain="icehills",info="",notes="",x=27,y=18,z=0,building=""}
M[#M+1] = {uid=18239,name="Astarchia",area="gelidus",terrain="snow",info="",notes="",x=28,y=18,z=0,building=""}
M[#M+1] = {uid=18240,name="Astarchia",area="gelidus",terrain="snow",info="",notes="",x=29,y=18,z=0,building=""}
M[#M+1] = {uid=18241,name="Astarchia",area="gelidus",terrain="snow",info="",notes="",x=30,y=18,z=0,building=""}
M[#M+1] = {uid=18242,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=31,y=18,z=0,building=""}
M[#M+1] = {uid=18243,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=32,y=18,z=0,building=""}
M[#M+1] = {uid=18244,name="An Icy Gorge",area="gelidus",terrain="snow",info="",notes="",x=33,y=18,z=0,building=""}
M[#M+1] = {uid=18245,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=34,y=18,z=0,building=""}
M[#M+1] = {uid=18246,name="Snowfields",area="gelidus",terrain="snow",info="",notes="",x=35,y=18,z=0,building=""}
M[#M+1] = {uid=18247,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=36,y=18,z=0,building=""}
M[#M+1] = {uid=18248,name="Snowfields",area="gelidus",terrain="snow",info="",notes="",x=37,y=18,z=0,building=""}
M[#M+1] = {uid=18249,name="Fireforge Hollow",area="gelidus",terrain="icehills",info="",notes="",x=38,y=18,z=0,building=""}
M[#M+1] = {uid=18250,name="Fireforge Hollow",area="gelidus",terrain="icehills",info="",notes="",x=39,y=18,z=0,building=""}
M[#M+1] = {uid=18251,name="Fireforge Hollow",area="gelidus",terrain="icehills",info="",notes="",x=40,y=18,z=0,building=""}
M[#M+1] = {uid=18252,name="Snowfields",area="gelidus",terrain="snow",info="",notes="",x=41,y=18,z=0,building=""}
M[#M+1] = {uid=18253,name="Snowfields",area="gelidus",terrain="snow",info="",notes="",x=42,y=18,z=0,building=""}
M[#M+1] = {uid=18254,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=43,y=18,z=0,building=""}
M[#M+1] = {uid=18255,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=44,y=18,z=0,building=""}
M[#M+1] = {uid=18256,name="Nordaustlandet",area="gelidus",terrain="snow",info="",notes="",x=45,y=18,z=0,building=""}
M[#M+1] = {uid=18257,name="Nordaustlandet",area="gelidus",terrain="snow",info="",notes="",x=46,y=18,z=0,building=""}
M[#M+1] = {uid=18258,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=47,y=18,z=0,building=""}
M[#M+1] = {uid=18259,name="Nordaustlandet",area="gelidus",terrain="snow",info="",notes="",x=48,y=18,z=0,building=""}
M[#M+1] = {uid=18260,name="Nordaustlandet",area="gelidus",terrain="snow",info="",notes="",x=49,y=18,z=0,building=""}
M[#M+1] = {uid=18261,name="Valley of the Frost Giants",area="gelidus",terrain="icehills",info="",notes="",x=50,y=18,z=0,building=""}
M[#M+1] = {uid=18262,name="Valley of the Frost Giants",area="gelidus",terrain="icehills",info="",notes="",x=51,y=18,z=0,building=""}
M[#M+1] = {uid=18263,name="Nordaustlandet",area="gelidus",terrain="snow",info="",notes="",x=52,y=18,z=0,building=""}
M[#M+1] = {uid=18264,name="L'Aquantina",area="gelidus",terrain="snow",info="",notes="",x=53,y=18,z=0,building=""}
M[#M+1] = {uid=18265,name="L'Aquantina",area="gelidus",terrain="icehills",info="",notes="",x=54,y=18,z=0,building=""}
M[#M+1] = {uid=18266,name="L'Aquantina",area="gelidus",terrain="icehills",info="",notes="",x=55,y=18,z=0,building=""}
M[#M+1] = {uid=18267,name="L'Aquantina",area="gelidus",terrain="icehills",info="",notes="",x=56,y=18,z=0,building=""}
M[#M+1] = {uid=18268,name="L'Aquantina",area="gelidus",terrain="snow",info="",notes="",x=57,y=18,z=0,building=""}
M[#M+1] = {uid=18269,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=58,y=18,z=0,building=""}
M[#M+1] = {uid=18270,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=59,y=18,z=0,building=""}
M[#M+1] = {uid=18271,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=0,y=19,z=0,building=""}
M[#M+1] = {uid=18272,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=1,y=19,z=0,building=""}
M[#M+1] = {uid=18273,name="Steinsvik",area="gelidus",terrain="ocean",info="",notes="",x=2,y=19,z=0,building=""}
M[#M+1] = {uid=18274,name="Steinsvik Badlands",area="gelidus",terrain="icehills",info="",notes="",x=3,y=19,z=0,building=""}
M[#M+1] = {uid=18275,name="Steinsvik Badlands",area="gelidus",terrain="icehills",info="",notes="",x=4,y=19,z=0,building=""}
M[#M+1] = {uid=18276,name="Steinsvik Badlands",area="gelidus",terrain="icehills",info="",notes="",x=5,y=19,z=0,building=""}
M[#M+1] = {uid=18277,name="The Shivering Grounds",area="gelidus",terrain="icehills",info="",notes="",x=6,y=19,z=0,building=""}
M[#M+1] = {uid=18278,name="The Shivering Grounds",area="gelidus",terrain="icehills",info="",notes="",x=7,y=19,z=0,building=""}
M[#M+1] = {uid=18279,name="The Shivering Grounds",area="gelidus",terrain="icehills",info="",notes="",x=8,y=19,z=0,building=""}
M[#M+1] = {uid=18280,name="Megara Lavafields",area="gelidus",terrain="icehills",info="",notes="",x=9,y=19,z=0,building=""}
M[#M+1] = {uid=18281,name="Megara Lavafields",area="gelidus",terrain="icehills",info="",notes="",x=10,y=19,z=0,building=""}
M[#M+1] = {uid=18282,name="Megara Lavafields",area="gelidus",terrain="icehills",info="",notes="",x=11,y=19,z=0,building=""}
M[#M+1] = {uid=18283,name="Megara Lavafields",area="gelidus",terrain="icehills",info="",notes="",x=12,y=19,z=0,building=""}
M[#M+1] = {uid=18284,name="Megara Lavafields",area="gelidus",terrain="icehills",info="",notes="",x=13,y=19,z=0,building=""}
M[#M+1] = {uid=18285,name="Megara Lavafields",area="gelidus",terrain="icehills",info="",notes="",x=14,y=19,z=0,building=""}
M[#M+1] = {uid=18286,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=15,y=19,z=0,building=""}
M[#M+1] = {uid=18287,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=16,y=19,z=0,building=""}
M[#M+1] = {uid=18288,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=17,y=19,z=0,building=""}
M[#M+1] = {uid=18289,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=18,y=19,z=0,building=""}
M[#M+1] = {uid=18290,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=19,y=19,z=0,building=""}
M[#M+1] = {uid=18291,name="Icereach Rim",area="gelidus",terrain="icehills",info="",notes="",x=20,y=19,z=0,building=""}
M[#M+1] = {uid=18292,name="Icereach Rim",area="gelidus",terrain="icehills",info="",notes="",x=21,y=19,z=0,building=""}
M[#M+1] = {uid=18293,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=22,y=19,z=0,building=""}
M[#M+1] = {uid=18294,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=23,y=19,z=0,building=""}
M[#M+1] = {uid=18295,name="Icereach Rim",area="gelidus",terrain="icehills",info="",notes="",x=24,y=19,z=0,building=""}
M[#M+1] = {uid=18296,name="Icereach Rim",area="gelidus",terrain="icehills",info="",notes="",x=25,y=19,z=0,building=""}
M[#M+1] = {uid=18297,name="Icereach Rim",area="gelidus",terrain="icehills",info="",notes="",x=26,y=19,z=0,building=""}
M[#M+1] = {uid=18298,name="Icereach Rim",area="gelidus",terrain="icehills",info="",notes="",x=27,y=19,z=0,building=""}
M[#M+1] = {uid=18299,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=28,y=19,z=0,building=""}
M[#M+1] = {uid=18300,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=29,y=19,z=0,building=""}
M[#M+1] = {uid=18301,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=30,y=19,z=0,building=""}
M[#M+1] = {uid=18302,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=31,y=19,z=0,building=""}
M[#M+1] = {uid=18303,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=32,y=19,z=0,building=""}
M[#M+1] = {uid=18304,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=33,y=19,z=0,building=""}
M[#M+1] = {uid=18305,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=34,y=19,z=0,building=""}
M[#M+1] = {uid=18306,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=35,y=19,z=0,building=""}
M[#M+1] = {uid=18307,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=36,y=19,z=0,building=""}
M[#M+1] = {uid=18308,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=37,y=19,z=0,building=""}
M[#M+1] = {uid=18309,name="Fireforge Hollow",area="gelidus",terrain="icehills",info="",notes="",x=38,y=19,z=0,building=""}
M[#M+1] = {uid=18310,name="Dwarven Ruins",area="gelidus",terrain="cave",info="",notes="",x=39,y=19,z=0,building=""}
M[#M+1] = {uid=18311,name="Fireforge Hollow",area="gelidus",terrain="icehills",info="",notes="",x=40,y=19,z=0,building=""}
M[#M+1] = {uid=18312,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=41,y=19,z=0,building=""}
M[#M+1] = {uid=18313,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=42,y=19,z=0,building=""}
M[#M+1] = {uid=18314,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=43,y=19,z=0,building=""}
M[#M+1] = {uid=18315,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=44,y=19,z=0,building=""}
M[#M+1] = {uid=18316,name="Crystal Valley",area="gelidus",terrain="icehills",info="",notes="",x=45,y=19,z=0,building=""}
M[#M+1] = {uid=18317,name="Crystal Valley",area="gelidus",terrain="icehills",info="",notes="",x=46,y=19,z=0,building=""}
M[#M+1] = {uid=18318,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=47,y=19,z=0,building=""}
M[#M+1] = {uid=18319,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=48,y=19,z=0,building=""}
M[#M+1] = {uid=18320,name="Valley of the Frost Giants",area="gelidus",terrain="icehills",info="",notes="",x=49,y=19,z=0,building=""}
M[#M+1] = {uid=18321,name="Valley of the Frost Giants",area="gelidus",terrain="icehills",info="",notes="",x=50,y=19,z=0,building=""}
M[#M+1] = {uid=18322,name="Valley of the Frost Giants",area="gelidus",terrain="icehills",info="",notes="",x=51,y=19,z=0,building=""}
M[#M+1] = {uid=18323,name="Valley of the Frost Giants",area="gelidus",terrain="icehills",info="",notes="",x=52,y=19,z=0,building=""}
M[#M+1] = {uid=18324,name="L'Aquantina",area="gelidus",terrain="icehills",info="",notes="",x=53,y=19,z=0,building=""}
M[#M+1] = {uid=18325,name="L'Aquantina",area="gelidus",terrain="icehills",info="",notes="",x=54,y=19,z=0,building=""}
M[#M+1] = {uid=18326,name="L'Aquantina",area="gelidus",terrain="icehills",info="",notes="",x=55,y=19,z=0,building=""}
M[#M+1] = {uid=18327,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=56,y=19,z=0,building=""}
M[#M+1] = {uid=18328,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=57,y=19,z=0,building=""}
M[#M+1] = {uid=18329,name="Ynnas Mon Icebridge",area="gelidus",terrain="icehills",info="",notes="",x=58,y=19,z=0,building=""}
M[#M+1] = {uid=18330,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=59,y=19,z=0,building=""}
M[#M+1] = {uid=18331,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=0,y=20,z=0,building=""}
M[#M+1] = {uid=18332,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=1,y=20,z=0,building=""}
M[#M+1] = {uid=18333,name="Steinsvik",area="gelidus",terrain="ocean",info="",notes="",x=2,y=20,z=0,building=""}
M[#M+1] = {uid=18334,name="Negharantha",area="gelidus",terrain="icemount",info="",notes="",x=3,y=20,z=0,building=""}
M[#M+1] = {uid=18335,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=4,y=20,z=0,building=""}
M[#M+1] = {uid=18336,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=5,y=20,z=0,building=""}
M[#M+1] = {uid=18337,name="The Shivering Grounds",area="gelidus",terrain="icehills",info="",notes="",x=6,y=20,z=0,building=""}
M[#M+1] = {uid=18338,name="The Shivering Grounds",area="gelidus",terrain="icehills",info="",notes="",x=7,y=20,z=0,building=""}
M[#M+1] = {uid=18339,name="Toivo",area="gelidus",terrain="icemount",info="",notes="",x=8,y=20,z=0,building=""}
M[#M+1] = {uid=18340,name="The Shivering Grounds",area="gelidus",terrain="icehills",info="",notes="",x=9,y=20,z=0,building=""}
M[#M+1] = {uid=18341,name="Megara Range",area="gelidus",terrain="volcano",info="",notes="",x=10,y=20,z=0,building=""}
M[#M+1] = {uid=18342,name="Megara Lavafields",area="gelidus",terrain="icehills",info="",notes="",x=11,y=20,z=0,building=""}
M[#M+1] = {uid=18343,name="Megara Range",area="gelidus",terrain="icemount",info="",notes="",x=12,y=20,z=0,building=""}
M[#M+1] = {uid=18344,name="Megara Range",area="gelidus",terrain="icemount",info="",notes="",x=13,y=20,z=0,building=""}
M[#M+1] = {uid=18345,name="Megara Lavafields",area="gelidus",terrain="icehills",info="",notes="",x=14,y=20,z=0,building=""}
M[#M+1] = {uid=18346,name="Megara Lavafields",area="gelidus",terrain="icehills",info="",notes="",x=15,y=20,z=0,building=""}
M[#M+1] = {uid=18347,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=16,y=20,z=0,building=""}
M[#M+1] = {uid=18348,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=17,y=20,z=0,building=""}
M[#M+1] = {uid=18349,name="Gorge of the Wyrm",area="gelidus",terrain="icehills",info="",notes="",x=18,y=20,z=0,building=""}
M[#M+1] = {uid=18350,name="Gorge of the Wyrm",area="gelidus",terrain="icehills",info="",notes="",x=19,y=20,z=0,building=""}
M[#M+1] = {uid=18351,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=20,y=20,z=0,building=""}
M[#M+1] = {uid=18352,name="Icereach Rim",area="gelidus",terrain="icehills",info="",notes="",x=21,y=20,z=0,building=""}
M[#M+1] = {uid=18353,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=22,y=20,z=0,building=""}
M[#M+1] = {uid=18354,name="Icereach Rim",area="gelidus",terrain="icehills",info="",notes="",x=23,y=20,z=0,building=""}
M[#M+1] = {uid=18355,name="Icereach Rim",area="gelidus",terrain="icehills",info="",notes="",x=24,y=20,z=0,building=""}
M[#M+1] = {uid=18356,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=25,y=20,z=0,building=""}
M[#M+1] = {uid=18357,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=26,y=20,z=0,building=""}
M[#M+1] = {uid=18358,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=27,y=20,z=0,building=""}
M[#M+1] = {uid=18359,name="Mundo Borealis",area="gelidus",terrain="icemount",info="",notes="",x=28,y=20,z=0,building=""}
M[#M+1] = {uid=18360,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=29,y=20,z=0,building=""}
M[#M+1] = {uid=18361,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=30,y=20,z=0,building=""}
M[#M+1] = {uid=18362,name="Mundo Borealis",area="gelidus",terrain="icemount",info="",notes="",x=31,y=20,z=0,building=""}
M[#M+1] = {uid=18363,name="Lucia Crag",area="gelidus",terrain="icemount",info="",notes="",x=32,y=20,z=0,building=""}
M[#M+1] = {uid=18364,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=33,y=20,z=0,building=""}
M[#M+1] = {uid=18365,name="Daemondale Iceridge",area="gelidus",terrain="icehills",info="",notes="",x=34,y=20,z=0,building=""}
M[#M+1] = {uid=18366,name="West Windy Mountains",area="gelidus",terrain="areaexit",info="",notes="",x=35,y=20,z=0,building=""}
M[#M+1] = {uid=18367,name="West Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=36,y=20,z=0,building=""}
M[#M+1] = {uid=18368,name="West Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=37,y=20,z=0,building=""}
M[#M+1] = {uid=18369,name="Fireforge Hollow",area="gelidus",terrain="icehills",info="",notes="",x=38,y=20,z=0,building=""}
M[#M+1] = {uid=18370,name="Fireforge Hollow",area="gelidus",terrain="icehills",info="",notes="",x=39,y=20,z=0,building=""}
M[#M+1] = {uid=18371,name="Fireforge Hollow",area="gelidus",terrain="icehills",info="",notes="",x=40,y=20,z=0,building=""}
M[#M+1] = {uid=18372,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=41,y=20,z=0,building=""}
M[#M+1] = {uid=18373,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=42,y=20,z=0,building=""}
M[#M+1] = {uid=18374,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=43,y=20,z=0,building=""}
M[#M+1] = {uid=18375,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=44,y=20,z=0,building=""}
M[#M+1] = {uid=18376,name="Crystal Valley",area="gelidus",terrain="icehills",info="",notes="",x=45,y=20,z=0,building=""}
M[#M+1] = {uid=18377,name="Crystal Valley",area="gelidus",terrain="icehills",info="",notes="",x=46,y=20,z=0,building=""}
M[#M+1] = {uid=18378,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=47,y=20,z=0,building=""}
M[#M+1] = {uid=18379,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=48,y=20,z=0,building=""}
M[#M+1] = {uid=18380,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=49,y=20,z=0,building=""}
M[#M+1] = {uid=18381,name="Valley of the Frost Giants",area="gelidus",terrain="icehills",info="",notes="",x=50,y=20,z=0,building=""}
M[#M+1] = {uid=18382,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=51,y=20,z=0,building=""}
M[#M+1] = {uid=18383,name="A Massacre!",area="gelidus",terrain="icehills",info="",notes="",x=52,y=20,z=0,building=""}
M[#M+1] = {uid=18384,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=53,y=20,z=0,building=""}
M[#M+1] = {uid=18385,name="Snow Elf Hills",area="gelidus",terrain="icehills",info="",notes="",x=54,y=20,z=0,building=""}
M[#M+1] = {uid=18386,name="Snow Elf Hills",area="gelidus",terrain="icehills",info="",notes="",x=55,y=20,z=0,building=""}
M[#M+1] = {uid=18387,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=56,y=20,z=0,building=""}
M[#M+1] = {uid=18388,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=57,y=20,z=0,building=""}
M[#M+1] = {uid=18389,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=58,y=20,z=0,building=""}
M[#M+1] = {uid=18390,name="Gelidus",area="gelidus",terrain="areaexit",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=18391,name="Ice Floe",area="gelidus",terrain="ocean",info="",notes="",x=0,y=21,z=0,building=""}
M[#M+1] = {uid=18392,name="Ice Floe",area="gelidus",terrain="ocean",info="",notes="",x=1,y=21,z=0,building=""}
M[#M+1] = {uid=18393,name="Istraesk Gorge",area="gelidus",terrain="icehills",info="",notes="",x=2,y=21,z=0,building=""}
M[#M+1] = {uid=18394,name="Istraesk Gorge",area="gelidus",terrain="icehills",info="",notes="",x=3,y=21,z=0,building=""}
M[#M+1] = {uid=18395,name="Istraesk Gorge",area="gelidus",terrain="icehills",info="",notes="",x=4,y=21,z=0,building=""}
M[#M+1] = {uid=18396,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=5,y=21,z=0,building=""}
M[#M+1] = {uid=18397,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=6,y=21,z=0,building=""}
M[#M+1] = {uid=18398,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=7,y=21,z=0,building=""}
M[#M+1] = {uid=18399,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=8,y=21,z=0,building=""}
M[#M+1] = {uid=18400,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=9,y=21,z=0,building=""}
M[#M+1] = {uid=18401,name="Megara Range",area="gelidus",terrain="areaexit",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=18402,name="Geysirjokull",area="gelidus",terrain="icemount",info="",notes="",x=11,y=21,z=0,building=""}
M[#M+1] = {uid=18403,name="Megara Range",area="gelidus",terrain="volcano",info="",notes="",x=12,y=21,z=0,building=""}
M[#M+1] = {uid=18404,name="Megara Range",area="gelidus",terrain="icemount",info="",notes="",x=13,y=21,z=0,building=""}
M[#M+1] = {uid=18405,name="Megara Range",area="gelidus",terrain="icemount",info="",notes="",x=14,y=21,z=0,building=""}
M[#M+1] = {uid=18406,name="Edge of Megara",area="gelidus",terrain="icemount",info="",notes="",x=15,y=21,z=0,building=""}
M[#M+1] = {uid=18407,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=16,y=21,z=0,building=""}
M[#M+1] = {uid=18408,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=17,y=21,z=0,building=""}
M[#M+1] = {uid=18409,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=18,y=21,z=0,building=""}
M[#M+1] = {uid=18410,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=19,y=21,z=0,building=""}
M[#M+1] = {uid=18411,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=20,y=21,z=0,building=""}
M[#M+1] = {uid=18412,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=21,y=21,z=0,building=""}
M[#M+1] = {uid=18413,name="Dragon Peak",area="gelidus",terrain="icemount",info="",notes="",x=22,y=21,z=0,building=""}
M[#M+1] = {uid=18414,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=23,y=21,z=0,building=""}
M[#M+1] = {uid=18415,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=24,y=21,z=0,building=""}
M[#M+1] = {uid=18416,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=25,y=21,z=0,building=""}
M[#M+1] = {uid=18417,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=26,y=21,z=0,building=""}
M[#M+1] = {uid=18418,name="Serpent's Peak",area="gelidus",terrain="icemount",info="",notes="",x=27,y=21,z=0,building=""}
M[#M+1] = {uid=18419,name="Mundo Borealis",area="gelidus",terrain="icemount",info="",notes="",x=28,y=21,z=0,building=""}
M[#M+1] = {uid=18420,name="Mundo Borealis",area="gelidus",terrain="icemount",info="",notes="",x=29,y=21,z=0,building=""}
M[#M+1] = {uid=18421,name="Anomaly Peak",area="gelidus",terrain="areaexit",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=18422,name="Mundo Borealis",area="gelidus",terrain="icemount",info="",notes="",x=31,y=21,z=0,building=""}
M[#M+1] = {uid=18423,name="Mundo Borealis",area="gelidus",terrain="icemount",info="",notes="",x=32,y=21,z=0,building=""}
M[#M+1] = {uid=18424,name="West Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=33,y=21,z=0,building=""}
M[#M+1] = {uid=18425,name="West Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=34,y=21,z=0,building=""}
M[#M+1] = {uid=18426,name="West Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=35,y=21,z=0,building=""}
M[#M+1] = {uid=18427,name="Rashara Bheigh",area="gelidus",terrain="icemount",info="",notes="",x=36,y=21,z=0,building=""}
M[#M+1] = {uid=18428,name="West Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=37,y=21,z=0,building=""}
M[#M+1] = {uid=18429,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=38,y=21,z=0,building=""}
M[#M+1] = {uid=18430,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=39,y=21,z=0,building=""}
M[#M+1] = {uid=18431,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=40,y=21,z=0,building=""}
M[#M+1] = {uid=18432,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=41,y=21,z=0,building=""}
M[#M+1] = {uid=18433,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=42,y=21,z=0,building=""}
M[#M+1] = {uid=18434,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=43,y=21,z=0,building=""}
M[#M+1] = {uid=18435,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=44,y=21,z=0,building=""}
M[#M+1] = {uid=18436,name="A Shrine to an Unnamed God",area="gelidus",terrain="icemount",info="",notes="",x=45,y=21,z=0,building=""}
M[#M+1] = {uid=18437,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=46,y=21,z=0,building=""}
M[#M+1] = {uid=18438,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=47,y=21,z=0,building=""}
M[#M+1] = {uid=18439,name="Sarakhalah",area="gelidus",terrain="icemount",info="",notes="",x=48,y=21,z=0,building=""}
M[#M+1] = {uid=18440,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=49,y=21,z=0,building=""}
M[#M+1] = {uid=18441,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=50,y=21,z=0,building=""}
M[#M+1] = {uid=18442,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=51,y=21,z=0,building=""}
M[#M+1] = {uid=18443,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=52,y=21,z=0,building=""}
M[#M+1] = {uid=18444,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=53,y=21,z=0,building=""}
M[#M+1] = {uid=18445,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=54,y=21,z=0,building=""}
M[#M+1] = {uid=18446,name="Snow Elf Hills",area="gelidus",terrain="icehills",info="",notes="",x=55,y=21,z=0,building=""}
M[#M+1] = {uid=18447,name="Snow Elf Hills",area="gelidus",terrain="icehills",info="",notes="",x=56,y=21,z=0,building=""}
M[#M+1] = {uid=18448,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=57,y=21,z=0,building=""}
M[#M+1] = {uid=18449,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=58,y=21,z=0,building=""}
M[#M+1] = {uid=18450,name="Ynnas Mon",area="gelidus",terrain="rocks",info="",notes="",x=59,y=21,z=0,building=""}
M[#M+1] = {uid=18451,name="Ice Floe",area="gelidus",terrain="ocean",info="",notes="",x=0,y=22,z=0,building=""}
M[#M+1] = {uid=18452,name="Ice Floe",area="gelidus",terrain="ocean",info="",notes="",x=1,y=22,z=0,building=""}
M[#M+1] = {uid=18453,name="Celilo Peak",area="gelidus",terrain="icemount",info="",notes="",x=2,y=22,z=0,building=""}
M[#M+1] = {uid=18454,name="Istraesk Gorge",area="gelidus",terrain="icehills",info="",notes="",x=3,y=22,z=0,building=""}
M[#M+1] = {uid=18455,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=4,y=22,z=0,building=""}
M[#M+1] = {uid=18456,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=5,y=22,z=0,building=""}
M[#M+1] = {uid=18457,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=6,y=22,z=0,building=""}
M[#M+1] = {uid=18458,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=7,y=22,z=0,building=""}
M[#M+1] = {uid=18459,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=8,y=22,z=0,building=""}
M[#M+1] = {uid=18460,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=9,y=22,z=0,building=""}
M[#M+1] = {uid=18461,name="Megara Range",area="gelidus",terrain="volcano",info="",notes="",x=10,y=22,z=0,building=""}
M[#M+1] = {uid=18462,name="Megara Range",area="gelidus",terrain="icemount",info="",notes="",x=11,y=22,z=0,building=""}
M[#M+1] = {uid=18463,name="Megara Range",area="gelidus",terrain="icemount",info="",notes="",x=12,y=22,z=0,building=""}
M[#M+1] = {uid=18464,name="Megara Range",area="gelidus",terrain="icemount",info="",notes="",x=13,y=22,z=0,building=""}
M[#M+1] = {uid=18465,name="Megara Range",area="gelidus",terrain="volcano",info="",notes="",x=14,y=22,z=0,building=""}
M[#M+1] = {uid=18466,name="Edge of Megara",area="gelidus",terrain="icemount",info="",notes="",x=15,y=22,z=0,building=""}
M[#M+1] = {uid=18467,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=16,y=22,z=0,building=""}
M[#M+1] = {uid=18468,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=17,y=22,z=0,building=""}
M[#M+1] = {uid=18469,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=18,y=22,z=0,building=""}
M[#M+1] = {uid=18470,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=19,y=22,z=0,building=""}
M[#M+1] = {uid=18471,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=20,y=22,z=0,building=""}
M[#M+1] = {uid=18472,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=21,y=22,z=0,building=""}
M[#M+1] = {uid=18473,name="High Pass of Itineris Draconii",area="gelidus",terrain="icemount",info="",notes="",x=22,y=22,z=0,building=""}
M[#M+1] = {uid=18474,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=23,y=22,z=0,building=""}
M[#M+1] = {uid=18475,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=24,y=22,z=0,building=""}
M[#M+1] = {uid=18476,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=25,y=22,z=0,building=""}
M[#M+1] = {uid=18477,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=26,y=22,z=0,building=""}
M[#M+1] = {uid=18478,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=27,y=22,z=0,building=""}
M[#M+1] = {uid=18479,name="Mundo Borealis",area="gelidus",terrain="icemount",info="",notes="",x=28,y=22,z=0,building=""}
M[#M+1] = {uid=18480,name="Mundo Borealis",area="gelidus",terrain="icemount",info="",notes="",x=29,y=22,z=0,building=""}
M[#M+1] = {uid=18481,name="Before the North Pole",area="gelidus",terrain="icemount",info="",notes="",x=30,y=22,z=0,building=""}
M[#M+1] = {uid=18482,name="Mundo Borealis",area="gelidus",terrain="icemount",info="",notes="",x=31,y=22,z=0,building=""}
M[#M+1] = {uid=18483,name="Mundo Borealis",area="gelidus",terrain="icemount",info="",notes="",x=32,y=22,z=0,building=""}
M[#M+1] = {uid=18484,name="West Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=33,y=22,z=0,building=""}
M[#M+1] = {uid=18485,name="West Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=34,y=22,z=0,building=""}
M[#M+1] = {uid=18486,name="West Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=35,y=22,z=0,building=""}
M[#M+1] = {uid=18487,name="West Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=36,y=22,z=0,building=""}
M[#M+1] = {uid=18488,name="West Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=37,y=22,z=0,building=""}
M[#M+1] = {uid=18489,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=38,y=22,z=0,building=""}
M[#M+1] = {uid=18490,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=39,y=22,z=0,building=""}
M[#M+1] = {uid=18491,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=40,y=22,z=0,building=""}
M[#M+1] = {uid=18492,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=41,y=22,z=0,building=""}
M[#M+1] = {uid=18493,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=42,y=22,z=0,building=""}
M[#M+1] = {uid=18494,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=43,y=22,z=0,building=""}
M[#M+1] = {uid=18495,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=44,y=22,z=0,building=""}
M[#M+1] = {uid=18496,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=45,y=22,z=0,building=""}
M[#M+1] = {uid=18497,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=46,y=22,z=0,building=""}
M[#M+1] = {uid=18498,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=47,y=22,z=0,building=""}
M[#M+1] = {uid=18499,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=48,y=22,z=0,building=""}
M[#M+1] = {uid=18500,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=49,y=22,z=0,building=""}
M[#M+1] = {uid=18501,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=50,y=22,z=0,building=""}
M[#M+1] = {uid=18502,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=51,y=22,z=0,building=""}
M[#M+1] = {uid=18503,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=52,y=22,z=0,building=""}
M[#M+1] = {uid=18504,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=53,y=22,z=0,building=""}
M[#M+1] = {uid=18505,name="Snow Elf Hills",area="gelidus",terrain="icehills",info="",notes="",x=54,y=22,z=0,building=""}
M[#M+1] = {uid=18506,name="Snow Elf Hills",area="gelidus",terrain="icehills",info="",notes="",x=55,y=22,z=0,building=""}
M[#M+1] = {uid=18507,name="Snow Elf Hills",area="gelidus",terrain="icehills",info="",notes="",x=56,y=22,z=0,building=""}
M[#M+1] = {uid=18508,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=57,y=22,z=0,building=""}
M[#M+1] = {uid=18509,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=58,y=22,z=0,building=""}
M[#M+1] = {uid=18510,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=59,y=22,z=0,building=""}
M[#M+1] = {uid=18511,name="Ice Floe",area="gelidus",terrain="ocean",info="",notes="",x=0,y=23,z=0,building=""}
M[#M+1] = {uid=18512,name="Ice Floe",area="gelidus",terrain="ocean",info="",notes="",x=1,y=23,z=0,building=""}
M[#M+1] = {uid=18513,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=2,y=23,z=0,building=""}
M[#M+1] = {uid=18514,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=3,y=23,z=0,building=""}
M[#M+1] = {uid=18515,name="A Dead End Gorge",area="gelidus",terrain="icehills",info="",notes="",x=4,y=23,z=0,building=""}
M[#M+1] = {uid=18516,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=5,y=23,z=0,building=""}
M[#M+1] = {uid=18517,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=6,y=23,z=0,building=""}
M[#M+1] = {uid=18518,name="Remorhaz Valley",area="gelidus",terrain="ice",info="",notes="",x=7,y=23,z=0,building=""}
M[#M+1] = {uid=18519,name="Remorhaz Valley",area="gelidus",terrain="ice",info="",notes="",x=8,y=23,z=0,building=""}
M[#M+1] = {uid=18520,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=9,y=23,z=0,building=""}
M[#M+1] = {uid=18521,name="Unnoneq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=10,y=23,z=0,building=""}
M[#M+1] = {uid=18522,name="Unnoneq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=11,y=23,z=0,building=""}
M[#M+1] = {uid=18523,name="Unnoneq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=12,y=23,z=0,building=""}
M[#M+1] = {uid=18524,name="Gelidus",area="gelidus",terrain="areaexit",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=18525,name="Megara Range",area="gelidus",terrain="icemount",info="",notes="",x=14,y=23,z=0,building=""}
M[#M+1] = {uid=18526,name="Darasesseq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=15,y=23,z=0,building=""}
M[#M+1] = {uid=18527,name="Darasesseq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=16,y=23,z=0,building=""}
M[#M+1] = {uid=18528,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=17,y=23,z=0,building=""}
M[#M+1] = {uid=18529,name="Secluded Valley",area="gelidus",terrain="ice",info="",notes="",x=18,y=23,z=0,building=""}
M[#M+1] = {uid=18530,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=19,y=23,z=0,building=""}
M[#M+1] = {uid=18531,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=20,y=23,z=0,building=""}
M[#M+1] = {uid=18532,name="Darasesseq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=21,y=23,z=0,building=""}
M[#M+1] = {uid=18533,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=22,y=23,z=0,building=""}
M[#M+1] = {uid=18534,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=23,y=23,z=0,building=""}
M[#M+1] = {uid=18535,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=24,y=23,z=0,building=""}
M[#M+1] = {uid=18536,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=25,y=23,z=0,building=""}
M[#M+1] = {uid=18537,name="Glaciers of Hypergelidus",area="gelidus",terrain="icehills",info="",notes="",x=26,y=23,z=0,building=""}
M[#M+1] = {uid=18538,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=27,y=23,z=0,building=""}
M[#M+1] = {uid=18539,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=28,y=23,z=0,building=""}
M[#M+1] = {uid=18540,name="Mundo Borealis",area="gelidus",terrain="icemount",info="",notes="",x=29,y=23,z=0,building=""}
M[#M+1] = {uid=18541,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=30,y=23,z=0,building=""}
M[#M+1] = {uid=18542,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=31,y=23,z=0,building=""}
M[#M+1] = {uid=18543,name="Glaciers of Hypergelidus",area="gelidus",terrain="icehills",info="",notes="",x=32,y=23,z=0,building=""}
M[#M+1] = {uid=18544,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=33,y=23,z=0,building=""}
M[#M+1] = {uid=18545,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=34,y=23,z=0,building=""}
M[#M+1] = {uid=18546,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=35,y=23,z=0,building=""}
M[#M+1] = {uid=18547,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=36,y=23,z=0,building=""}
M[#M+1] = {uid=18548,name="Glaciers of Hypergelidus",area="gelidus",terrain="icehills",info="",notes="",x=37,y=23,z=0,building=""}
M[#M+1] = {uid=18549,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=38,y=23,z=0,building=""}
M[#M+1] = {uid=18550,name="Gelidus",area="gelidus",terrain="areaexit",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=18551,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=40,y=23,z=0,building=""}
M[#M+1] = {uid=18552,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=41,y=23,z=0,building=""}
M[#M+1] = {uid=18553,name="The Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=42,y=23,z=0,building=""}
M[#M+1] = {uid=18554,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=43,y=23,z=0,building=""}
M[#M+1] = {uid=18555,name="Esaaneq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=44,y=23,z=0,building=""}
M[#M+1] = {uid=18556,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=45,y=23,z=0,building=""}
M[#M+1] = {uid=18557,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=46,y=23,z=0,building=""}
M[#M+1] = {uid=18558,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=47,y=23,z=0,building=""}
M[#M+1] = {uid=18559,name="Esaaneq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=48,y=23,z=0,building=""}
M[#M+1] = {uid=18560,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=49,y=23,z=0,building=""}
M[#M+1] = {uid=18561,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=50,y=23,z=0,building=""}
M[#M+1] = {uid=18562,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=51,y=23,z=0,building=""}
M[#M+1] = {uid=18563,name="East Windy Mountains",area="gelidus",terrain="icemount",info="",notes="",x=52,y=23,z=0,building=""}
M[#M+1] = {uid=18564,name="Snow Elf Hills",area="gelidus",terrain="icehills",info="",notes="",x=53,y=23,z=0,building=""}
M[#M+1] = {uid=18565,name="Snow Elf Hills",area="gelidus",terrain="icehills",info="",notes="",x=54,y=23,z=0,building=""}
M[#M+1] = {uid=18566,name="Snow Elf Peak",area="gelidus",terrain="icemount",info="",notes="",x=55,y=23,z=0,building=""}
M[#M+1] = {uid=18567,name="Snow Elf Hills",area="gelidus",terrain="icehills",info="",notes="",x=56,y=23,z=0,building=""}
M[#M+1] = {uid=18568,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=57,y=23,z=0,building=""}
M[#M+1] = {uid=18569,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=58,y=23,z=0,building=""}
M[#M+1] = {uid=18570,name="Elfin Bay",area="gelidus",terrain="ocean",info="",notes="",x=59,y=23,z=0,building=""}
M[#M+1] = {uid=18571,name="Ice Floe",area="gelidus",terrain="ocean",info="",notes="",x=0,y=24,z=0,building=""}
M[#M+1] = {uid=18572,name="Ice Floe",area="gelidus",terrain="ocean",info="",notes="",x=1,y=24,z=0,building=""}
M[#M+1] = {uid=18573,name="The Edge of Heavenstruck",area="gelidus",terrain="ice",info="",notes="",x=2,y=24,z=0,building=""}
M[#M+1] = {uid=18574,name="The Edge of Heavenstruck",area="gelidus",terrain="ice",info="",notes="",x=3,y=24,z=0,building=""}
M[#M+1] = {uid=18575,name="The Edge of Heavenstruck",area="gelidus",terrain="icehills",info="",notes="",x=4,y=24,z=0,building=""}
M[#M+1] = {uid=18576,name="The Edge of Heavenstruck",area="gelidus",terrain="ice",info="",notes="",x=5,y=24,z=0,building=""}
M[#M+1] = {uid=18577,name="Five Finger Mountains",area="gelidus",terrain="icemount",info="",notes="",x=6,y=24,z=0,building=""}
M[#M+1] = {uid=18578,name="Doomwhisper",area="gelidus",terrain="icemount",info="",notes="",x=7,y=24,z=0,building=""}
M[#M+1] = {uid=18579,name="Remorhaz Valley",area="gelidus",terrain="ice",info="",notes="",x=8,y=24,z=0,building=""}
M[#M+1] = {uid=18580,name="Remorhaz Valley",area="gelidus",terrain="icehills",info="",notes="",x=9,y=24,z=0,building=""}
M[#M+1] = {uid=18581,name="Arisha Skyreach",area="gelidus",terrain="icemount",info="",notes="",x=10,y=24,z=0,building=""}
M[#M+1] = {uid=18582,name="Unnoneq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=11,y=24,z=0,building=""}
M[#M+1] = {uid=18583,name="Unnoneq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=12,y=24,z=0,building=""}
M[#M+1] = {uid=18584,name="Unnoneq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=13,y=24,z=0,building=""}
M[#M+1] = {uid=18585,name="Unnoneq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=14,y=24,z=0,building=""}
M[#M+1] = {uid=18586,name="Edge of Megara",area="gelidus",terrain="icemount",info="",notes="",x=15,y=24,z=0,building=""}
M[#M+1] = {uid=18587,name="Darasesseq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=16,y=24,z=0,building=""}
M[#M+1] = {uid=18588,name="Darasesseq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=17,y=24,z=0,building=""}
M[#M+1] = {uid=18589,name="Icereach Mountains",area="gelidus",terrain="icemount",info="",notes="",x=18,y=24,z=0,building=""}
M[#M+1] = {uid=18590,name="Darasesseq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=19,y=24,z=0,building=""}
M[#M+1] = {uid=18591,name="Darasesseq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=20,y=24,z=0,building=""}
M[#M+1] = {uid=18592,name="Darasesseq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=21,y=24,z=0,building=""}
M[#M+1] = {uid=18593,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=22,y=24,z=0,building=""}
M[#M+1] = {uid=18594,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=23,y=24,z=0,building=""}
M[#M+1] = {uid=18595,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=24,y=24,z=0,building=""}
M[#M+1] = {uid=18596,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=25,y=24,z=0,building=""}
M[#M+1] = {uid=18597,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=26,y=24,z=0,building=""}
M[#M+1] = {uid=18598,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=27,y=24,z=0,building=""}
M[#M+1] = {uid=18599,name="Glaciers of Hypergelidus",area="gelidus",terrain="icehills",info="",notes="",x=28,y=24,z=0,building=""}
M[#M+1] = {uid=18600,name="Glaciers of Hypergelidus",area="gelidus",terrain="icehills",info="",notes="",x=29,y=24,z=0,building=""}
M[#M+1] = {uid=18601,name="Glaciers of Hypergelidus",area="gelidus",terrain="icehills",info="",notes="",x=30,y=24,z=0,building=""}
M[#M+1] = {uid=18602,name="A Very Odd Spot",area="gelidus",terrain="ice",info="",notes="",x=31,y=24,z=0,building=""}
M[#M+1] = {uid=18603,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=32,y=24,z=0,building=""}
M[#M+1] = {uid=18604,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=33,y=24,z=0,building=""}
M[#M+1] = {uid=18605,name="Glaciers of Hypergelidus",area="gelidus",terrain="icehills",info="",notes="",x=34,y=24,z=0,building=""}
M[#M+1] = {uid=18606,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=35,y=24,z=0,building=""}
M[#M+1] = {uid=18607,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=36,y=24,z=0,building=""}
M[#M+1] = {uid=18608,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=37,y=24,z=0,building=""}
M[#M+1] = {uid=18609,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=38,y=24,z=0,building=""}
M[#M+1] = {uid=18610,name="Gale",area="gelidus",terrain="icemount",info="",notes="",x=39,y=24,z=0,building=""}
M[#M+1] = {uid=18611,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=40,y=24,z=0,building=""}
M[#M+1] = {uid=18612,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=41,y=24,z=0,building=""}
M[#M+1] = {uid=18613,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=42,y=24,z=0,building=""}
M[#M+1] = {uid=18614,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=43,y=24,z=0,building=""}
M[#M+1] = {uid=18615,name="Esaaneq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=44,y=24,z=0,building=""}
M[#M+1] = {uid=18616,name="Esaaneq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=45,y=24,z=0,building=""}
M[#M+1] = {uid=18617,name="Esaaneq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=46,y=24,z=0,building=""}
M[#M+1] = {uid=18618,name="Esaaneq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=47,y=24,z=0,building=""}
M[#M+1] = {uid=18619,name="Esaaneq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=48,y=24,z=0,building=""}
M[#M+1] = {uid=18620,name="Foothills",area="gelidus",terrain="icehills",info="",notes="",x=49,y=24,z=0,building=""}
M[#M+1] = {uid=18621,name="Frosthaven",area="gelidus",terrain="ice",info="",notes="",x=50,y=24,z=0,building=""}
M[#M+1] = {uid=18622,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=51,y=24,z=0,building=""}
M[#M+1] = {uid=18623,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=52,y=24,z=0,building=""}
M[#M+1] = {uid=18624,name="Snow Elf Hills",area="gelidus",terrain="ice",info="",notes="",x=53,y=24,z=0,building=""}
M[#M+1] = {uid=18625,name="Snow Elf Hills",area="gelidus",terrain="ice",info="",notes="",x=54,y=24,z=0,building=""}
M[#M+1] = {uid=18626,name="Snow Elf Hills",area="gelidus",terrain="ice",info="",notes="",x=55,y=24,z=0,building=""}
M[#M+1] = {uid=18627,name="Snow Elf Hills",area="gelidus",terrain="ice",info="",notes="",x=56,y=24,z=0,building=""}
M[#M+1] = {uid=18628,name="Point Ealinn",area="gelidus",terrain="icehills",info="",notes="",x=57,y=24,z=0,building=""}
M[#M+1] = {uid=18629,name="Aurora Bay",area="gelidus",terrain="ocean",info="",notes="",x=58,y=24,z=0,building=""}
M[#M+1] = {uid=18630,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=59,y=24,z=0,building=""}
M[#M+1] = {uid=18631,name="Ice Floe",area="gelidus",terrain="ocean",info="",notes="",x=0,y=25,z=0,building=""}
M[#M+1] = {uid=18632,name="Ice Floe",area="gelidus",terrain="ocean",info="",notes="",x=1,y=25,z=0,building=""}
M[#M+1] = {uid=18633,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=2,y=25,z=0,building=""}
M[#M+1] = {uid=18634,name="The Edge of Heavenstruck",area="gelidus",terrain="ice",info="",notes="",x=3,y=25,z=0,building=""}
M[#M+1] = {uid=18635,name="The Edge of Heavenstruck",area="gelidus",terrain="icehills",info="",notes="",x=4,y=25,z=0,building=""}
M[#M+1] = {uid=18636,name="The Edge of Heavenstruck",area="gelidus",terrain="icehills",info="",notes="",x=5,y=25,z=0,building=""}
M[#M+1] = {uid=18637,name="The Edge of Heavenstruck",area="gelidus",terrain="icehills",info="",notes="",x=6,y=25,z=0,building=""}
M[#M+1] = {uid=18638,name="The Edge of Heavenstruck",area="gelidus",terrain="icehills",info="",notes="",x=7,y=25,z=0,building=""}
M[#M+1] = {uid=18639,name="Remorhaz Valley",area="gelidus",terrain="icehills",info="",notes="",x=8,y=25,z=0,building=""}
M[#M+1] = {uid=18640,name="Remorhaz Valley",area="gelidus",terrain="icehills",info="",notes="",x=9,y=25,z=0,building=""}
M[#M+1] = {uid=18641,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=10,y=25,z=0,building=""}
M[#M+1] = {uid=18642,name="Unnoneq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=11,y=25,z=0,building=""}
M[#M+1] = {uid=18643,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=12,y=25,z=0,building=""}
M[#M+1] = {uid=18644,name="Unnoneq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=13,y=25,z=0,building=""}
M[#M+1] = {uid=18645,name="Unnoneq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=14,y=25,z=0,building=""}
M[#M+1] = {uid=18646,name="Megara Divider",area="gelidus",terrain="icehills",info="",notes="",x=15,y=25,z=0,building=""}
M[#M+1] = {uid=18647,name="Darasesseq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=16,y=25,z=0,building=""}
M[#M+1] = {uid=18648,name="Darasesseq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=17,y=25,z=0,building=""}
M[#M+1] = {uid=18649,name="Darasesseq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=18,y=25,z=0,building=""}
M[#M+1] = {uid=18650,name="Darasesseq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=19,y=25,z=0,building=""}
M[#M+1] = {uid=18651,name="Darasesseq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=20,y=25,z=0,building=""}
M[#M+1] = {uid=18652,name="Darasesseq Kujalleq",area="gelidus",terrain="trail_ew",info="",notes="",x=21,y=25,z=0,building=""}
M[#M+1] = {uid=18653,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=22,y=25,z=0,building=""}
M[#M+1] = {uid=18654,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=23,y=25,z=0,building=""}
M[#M+1] = {uid=18655,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=24,y=25,z=0,building=""}
M[#M+1] = {uid=18656,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=25,y=25,z=0,building=""}
M[#M+1] = {uid=18657,name="Hypergelidus",area="gelidus",terrain="areaexit",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=18658,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=27,y=25,z=0,building=""}
M[#M+1] = {uid=18659,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=28,y=25,z=0,building=""}
M[#M+1] = {uid=18660,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=29,y=25,z=0,building=""}
M[#M+1] = {uid=18661,name="Hypergelidus",area="gelidus",terrain="snow",info="",notes="",x=30,y=25,z=0,building=""}
M[#M+1] = {uid=18662,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=31,y=25,z=0,building=""}
M[#M+1] = {uid=18663,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=32,y=25,z=0,building=""}
M[#M+1] = {uid=18664,name="Diamond Gorge",area="gelidus",terrain="snow",info="",notes="",x=33,y=25,z=0,building=""}
M[#M+1] = {uid=18665,name="Diamond Gorge",area="gelidus",terrain="snow",info="",notes="",x=34,y=25,z=0,building=""}
M[#M+1] = {uid=18666,name="Diamond Gorge",area="gelidus",terrain="snow",info="",notes="",x=35,y=25,z=0,building=""}
M[#M+1] = {uid=18667,name="Glaciers of Hypergelidus",area="gelidus",terrain="ice",info="",notes="",x=36,y=25,z=0,building=""}
M[#M+1] = {uid=18668,name="Valley of the Yeti",area="gelidus",terrain="snow",info="",notes="",x=37,y=25,z=0,building=""}
M[#M+1] = {uid=18669,name="Valley of the Yeti",area="gelidus",terrain="snow",info="",notes="",x=38,y=25,z=0,building=""}
M[#M+1] = {uid=18670,name="A Field of Jagged Ice",area="gelidus",terrain="ice",info="",notes="",x=39,y=25,z=0,building=""}
M[#M+1] = {uid=18671,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=40,y=25,z=0,building=""}
M[#M+1] = {uid=18672,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=41,y=25,z=0,building=""}
M[#M+1] = {uid=18673,name="Esaaneq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=42,y=25,z=0,building=""}
M[#M+1] = {uid=18674,name="Esaaneq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=43,y=25,z=0,building=""}
M[#M+1] = {uid=18675,name="Esaaneq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=44,y=25,z=0,building=""}
M[#M+1] = {uid=18676,name="Esaaneq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=45,y=25,z=0,building=""}
M[#M+1] = {uid=18677,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=46,y=25,z=0,building=""}
M[#M+1] = {uid=18678,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=47,y=25,z=0,building=""}
M[#M+1] = {uid=18679,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=48,y=25,z=0,building=""}
M[#M+1] = {uid=18680,name="Esaaneq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=49,y=25,z=0,building=""}
M[#M+1] = {uid=18681,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=50,y=25,z=0,building=""}
M[#M+1] = {uid=18682,name="Danameq Kujalleq",area="gelidus",terrain="ice",info="",notes="",x=51,y=25,z=0,building=""}
M[#M+1] = {uid=18683,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=52,y=25,z=0,building=""}
M[#M+1] = {uid=18684,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=53,y=25,z=0,building=""}
M[#M+1] = {uid=18685,name="Snow Elf Hollow",area="gelidus",terrain="snow",info="",notes="",x=54,y=25,z=0,building=""}
M[#M+1] = {uid=18686,name="Snow Elf Hills",area="gelidus",terrain="icehills",info="",notes="",x=55,y=25,z=0,building=""}
M[#M+1] = {uid=18687,name="Snow Elf Hills",area="gelidus",terrain="icehills",info="",notes="",x=56,y=25,z=0,building=""}
M[#M+1] = {uid=18688,name="Aurora Bay",area="gelidus",terrain="ocean",info="",notes="",x=57,y=25,z=0,building=""}
M[#M+1] = {uid=18689,name="Aurora Bay",area="gelidus",terrain="ocean",info="",notes="",x=58,y=25,z=0,building=""}
M[#M+1] = {uid=18690,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=59,y=25,z=0,building=""}
M[#M+1] = {uid=18691,name="Ice Floe",area="gelidus",terrain="ocean",info="",notes="",x=0,y=26,z=0,building=""}
M[#M+1] = {uid=18692,name="Ice Floe",area="gelidus",terrain="ocean",info="",notes="",x=1,y=26,z=0,building=""}
M[#M+1] = {uid=18693,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=2,y=26,z=0,building=""}
M[#M+1] = {uid=18694,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=3,y=26,z=0,building=""}
M[#M+1] = {uid=18695,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=4,y=26,z=0,building=""}
M[#M+1] = {uid=18696,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=5,y=26,z=0,building=""}
M[#M+1] = {uid=18697,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=6,y=26,z=0,building=""}
M[#M+1] = {uid=18698,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=7,y=26,z=0,building=""}
M[#M+1] = {uid=18699,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=8,y=26,z=0,building=""}
M[#M+1] = {uid=18700,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=9,y=26,z=0,building=""}
M[#M+1] = {uid=18701,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=10,y=26,z=0,building=""}
M[#M+1] = {uid=18702,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=11,y=26,z=0,building=""}
M[#M+1] = {uid=18703,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=12,y=26,z=0,building=""}
M[#M+1] = {uid=18704,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=13,y=26,z=0,building=""}
M[#M+1] = {uid=18705,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=14,y=26,z=0,building=""}
M[#M+1] = {uid=18706,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=15,y=26,z=0,building=""}
M[#M+1] = {uid=18707,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=16,y=26,z=0,building=""}
M[#M+1] = {uid=18708,name="Darasesseq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=17,y=26,z=0,building=""}
M[#M+1] = {uid=18709,name="Darasesseq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=18,y=26,z=0,building=""}
M[#M+1] = {uid=18710,name="Darasesseq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=19,y=26,z=0,building=""}
M[#M+1] = {uid=18711,name="Darasesseq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=20,y=26,z=0,building=""}
M[#M+1] = {uid=18712,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=21,y=26,z=0,building=""}
M[#M+1] = {uid=18713,name="Hypergelidus",area="gelidus",terrain="snow",info="",notes="",x=22,y=26,z=0,building=""}
M[#M+1] = {uid=18714,name="Hypergelidus",area="gelidus",terrain="snow",info="",notes="",x=23,y=26,z=0,building=""}
M[#M+1] = {uid=18715,name="Hypergelidus",area="gelidus",terrain="snow",info="",notes="",x=24,y=26,z=0,building=""}
M[#M+1] = {uid=18716,name="Hypergelidus",area="gelidus",terrain="snow",info="",notes="",x=25,y=26,z=0,building=""}
M[#M+1] = {uid=18717,name="Hypergelidus",area="gelidus",terrain="snow",info="",notes="",x=26,y=26,z=0,building=""}
M[#M+1] = {uid=18718,name="Hypergelidus",area="gelidus",terrain="snow",info="",notes="",x=27,y=26,z=0,building=""}
M[#M+1] = {uid=18719,name="Hypergelidus",area="gelidus",terrain="snow",info="",notes="",x=28,y=26,z=0,building=""}
M[#M+1] = {uid=18720,name="Hypergelidus",area="gelidus",terrain="snow",info="",notes="",x=29,y=26,z=0,building=""}
M[#M+1] = {uid=18721,name="Hypergelidus",area="gelidus",terrain="snow",info="",notes="",x=30,y=26,z=0,building=""}
M[#M+1] = {uid=18722,name="Hypergelidus",area="gelidus",terrain="snow",info="",notes="",x=31,y=26,z=0,building=""}
M[#M+1] = {uid=18723,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=32,y=26,z=0,building=""}
M[#M+1] = {uid=18724,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=33,y=26,z=0,building=""}
M[#M+1] = {uid=18725,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=34,y=26,z=0,building=""}
M[#M+1] = {uid=18726,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=35,y=26,z=0,building=""}
M[#M+1] = {uid=18727,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=36,y=26,z=0,building=""}
M[#M+1] = {uid=18728,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=37,y=26,z=0,building=""}
M[#M+1] = {uid=18729,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=38,y=26,z=0,building=""}
M[#M+1] = {uid=18730,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=39,y=26,z=0,building=""}
M[#M+1] = {uid=18731,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=40,y=26,z=0,building=""}
M[#M+1] = {uid=18732,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=41,y=26,z=0,building=""}
M[#M+1] = {uid=18733,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=42,y=26,z=0,building=""}
M[#M+1] = {uid=18734,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=43,y=26,z=0,building=""}
M[#M+1] = {uid=18735,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=44,y=26,z=0,building=""}
M[#M+1] = {uid=18736,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=45,y=26,z=0,building=""}
M[#M+1] = {uid=18737,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=46,y=26,z=0,building=""}
M[#M+1] = {uid=18738,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=47,y=26,z=0,building=""}
M[#M+1] = {uid=18739,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=48,y=26,z=0,building=""}
M[#M+1] = {uid=18740,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=49,y=26,z=0,building=""}
M[#M+1] = {uid=18741,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=50,y=26,z=0,building=""}
M[#M+1] = {uid=18742,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=51,y=26,z=0,building=""}
M[#M+1] = {uid=18743,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=52,y=26,z=0,building=""}
M[#M+1] = {uid=18744,name="Frost Coast",area="gelidus",terrain="snow",info="",notes="",x=53,y=26,z=0,building=""}
M[#M+1] = {uid=18745,name="Frost Coast",area="gelidus",terrain="snow",info="",notes="",x=54,y=26,z=0,building=""}
M[#M+1] = {uid=18746,name="Snow Elf Hills",area="gelidus",terrain="icehills",info="",notes="",x=55,y=26,z=0,building=""}
M[#M+1] = {uid=18747,name="Snow Elf Hills",area="gelidus",terrain="icehills",info="",notes="",x=56,y=26,z=0,building=""}
M[#M+1] = {uid=18748,name="Aurora Bay",area="gelidus",terrain="ocean",info="",notes="",x=57,y=26,z=0,building=""}
M[#M+1] = {uid=18749,name="Aurora Bay",area="gelidus",terrain="ocean",info="",notes="",x=58,y=26,z=0,building=""}
M[#M+1] = {uid=18750,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=59,y=26,z=0,building=""}
M[#M+1] = {uid=18751,name="Ice Floe",area="gelidus",terrain="ocean",info="",notes="",x=0,y=27,z=0,building=""}
M[#M+1] = {uid=18752,name="Heavenstruck Bay",area="gelidus",terrain="ocean",info="",notes="",x=1,y=27,z=0,building=""}
M[#M+1] = {uid=18753,name="Heavenstruck Bay",area="gelidus",terrain="ocean",info="",notes="",x=2,y=27,z=0,building=""}
M[#M+1] = {uid=18754,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=3,y=27,z=0,building=""}
M[#M+1] = {uid=18755,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=4,y=27,z=0,building=""}
M[#M+1] = {uid=18756,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=5,y=27,z=0,building=""}
M[#M+1] = {uid=18757,name="A Gigantic Crater",area="gelidus",terrain="snow",info="",notes="",x=6,y=27,z=0,building=""}
M[#M+1] = {uid=18758,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=7,y=27,z=0,building=""}
M[#M+1] = {uid=18759,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=8,y=27,z=0,building=""}
M[#M+1] = {uid=18760,name="Deshtar Peak",area="gelidus",terrain="icehills",info="",notes="",x=9,y=27,z=0,building=""}
M[#M+1] = {uid=18761,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=10,y=27,z=0,building=""}
M[#M+1] = {uid=18762,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=11,y=27,z=0,building=""}
M[#M+1] = {uid=18763,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=12,y=27,z=0,building=""}
M[#M+1] = {uid=18764,name="Icicle Mesa",area="gelidus",terrain="ice",info="",notes="",x=13,y=27,z=0,building=""}
M[#M+1] = {uid=18765,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=14,y=27,z=0,building=""}
M[#M+1] = {uid=18766,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=15,y=27,z=0,building=""}
M[#M+1] = {uid=18767,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=16,y=27,z=0,building=""}
M[#M+1] = {uid=18768,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=17,y=27,z=0,building=""}
M[#M+1] = {uid=18769,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=18,y=27,z=0,building=""}
M[#M+1] = {uid=18770,name="Darasesseq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=19,y=27,z=0,building=""}
M[#M+1] = {uid=18771,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=20,y=27,z=0,building=""}
M[#M+1] = {uid=18772,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=21,y=27,z=0,building=""}
M[#M+1] = {uid=18773,name="Hypergelidus",area="gelidus",terrain="snow",info="",notes="",x=22,y=27,z=0,building=""}
M[#M+1] = {uid=18774,name="Hypergelidus",area="gelidus",terrain="snow",info="",notes="",x=23,y=27,z=0,building=""}
M[#M+1] = {uid=18775,name="Hypergelidus",area="gelidus",terrain="snow",info="",notes="",x=24,y=27,z=0,building=""}
M[#M+1] = {uid=18776,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=25,y=27,z=0,building=""}
M[#M+1] = {uid=18777,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=26,y=27,z=0,building=""}
M[#M+1] = {uid=18778,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=27,y=27,z=0,building=""}
M[#M+1] = {uid=18779,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=28,y=27,z=0,building=""}
M[#M+1] = {uid=18780,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=29,y=27,z=0,building=""}
M[#M+1] = {uid=18781,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=30,y=27,z=0,building=""}
M[#M+1] = {uid=18782,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=31,y=27,z=0,building=""}
M[#M+1] = {uid=18783,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=32,y=27,z=0,building=""}
M[#M+1] = {uid=18784,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=33,y=27,z=0,building=""}
M[#M+1] = {uid=18785,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=34,y=27,z=0,building=""}
M[#M+1] = {uid=18786,name="Dread Fields",area="gelidus",terrain="snow",info="",notes="",x=35,y=27,z=0,building=""}
M[#M+1] = {uid=18787,name="Blackfields",area="gelidus",terrain="snow",info="",notes="",x=36,y=27,z=0,building=""}
M[#M+1] = {uid=18788,name="Blackfields",area="gelidus",terrain="snow",info="",notes="",x=37,y=27,z=0,building=""}
M[#M+1] = {uid=18789,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=38,y=27,z=0,building=""}
M[#M+1] = {uid=18790,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=39,y=27,z=0,building=""}
M[#M+1] = {uid=18791,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=40,y=27,z=0,building=""}
M[#M+1] = {uid=18792,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=41,y=27,z=0,building=""}
M[#M+1] = {uid=18793,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=42,y=27,z=0,building=""}
M[#M+1] = {uid=18794,name="Danameq Kujalleq",area="gelidus",terrain="areaexit",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=18795,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=44,y=27,z=0,building=""}
M[#M+1] = {uid=18796,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=45,y=27,z=0,building=""}
M[#M+1] = {uid=18797,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=46,y=27,z=0,building=""}
M[#M+1] = {uid=18798,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=47,y=27,z=0,building=""}
M[#M+1] = {uid=18799,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=48,y=27,z=0,building=""}
M[#M+1] = {uid=18800,name="Tunturia",area="gelidus",terrain="snow",info="",notes="",x=49,y=27,z=0,building=""}
M[#M+1] = {uid=18801,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=50,y=27,z=0,building=""}
M[#M+1] = {uid=18802,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=51,y=27,z=0,building=""}
M[#M+1] = {uid=18803,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=52,y=27,z=0,building=""}
M[#M+1] = {uid=18804,name="Frost Coast",area="gelidus",terrain="snow",info="",notes="",x=53,y=27,z=0,building=""}
M[#M+1] = {uid=18805,name="Frost Coast",area="gelidus",terrain="snow",info="",notes="",x=54,y=27,z=0,building=""}
M[#M+1] = {uid=18806,name="Aurora Bay",area="gelidus",terrain="ocean",info="",notes="",x=55,y=27,z=0,building=""}
M[#M+1] = {uid=18807,name="Aurora Bay",area="gelidus",terrain="ocean",info="",notes="",x=56,y=27,z=0,building=""}
M[#M+1] = {uid=18808,name="Aurora Bay",area="gelidus",terrain="ocean",info="",notes="",x=57,y=27,z=0,building=""}
M[#M+1] = {uid=18809,name="Aurora Bay",area="gelidus",terrain="ocean",info="",notes="",x=58,y=27,z=0,building=""}
M[#M+1] = {uid=18810,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=59,y=27,z=0,building=""}
M[#M+1] = {uid=18811,name="Ice Floe",area="gelidus",terrain="ocean",info="",notes="",x=0,y=28,z=0,building=""}
M[#M+1] = {uid=18812,name="Heavenstruck Bay",area="gelidus",terrain="ocean",info="",notes="",x=1,y=28,z=0,building=""}
M[#M+1] = {uid=18813,name="Heavenstruck Bay",area="gelidus",terrain="ocean",info="",notes="",x=2,y=28,z=0,building=""}
M[#M+1] = {uid=18814,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=3,y=28,z=0,building=""}
M[#M+1] = {uid=18815,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=4,y=28,z=0,building=""}
M[#M+1] = {uid=18816,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=5,y=28,z=0,building=""}
M[#M+1] = {uid=18817,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=6,y=28,z=0,building=""}
M[#M+1] = {uid=18818,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=7,y=28,z=0,building=""}
M[#M+1] = {uid=18819,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=8,y=28,z=0,building=""}
M[#M+1] = {uid=18820,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=9,y=28,z=0,building=""}
M[#M+1] = {uid=18821,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=10,y=28,z=0,building=""}
M[#M+1] = {uid=18822,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=11,y=28,z=0,building=""}
M[#M+1] = {uid=18823,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=12,y=28,z=0,building=""}
M[#M+1] = {uid=18824,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=13,y=28,z=0,building=""}
M[#M+1] = {uid=18825,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=14,y=28,z=0,building=""}
M[#M+1] = {uid=18826,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=15,y=28,z=0,building=""}
M[#M+1] = {uid=18827,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=16,y=28,z=0,building=""}
M[#M+1] = {uid=18828,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=17,y=28,z=0,building=""}
M[#M+1] = {uid=18829,name="Queen Angelina Land",area="gelidus",terrain="snow",info="",notes="",x=18,y=28,z=0,building=""}
M[#M+1] = {uid=18830,name="Darasesseq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=19,y=28,z=0,building=""}
M[#M+1] = {uid=18831,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=20,y=28,z=0,building=""}
M[#M+1] = {uid=18832,name="Carbonado Rockfields",area="gelidus",terrain="plain",info="",notes="",x=21,y=28,z=0,building=""}
M[#M+1] = {uid=18833,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=22,y=28,z=0,building=""}
M[#M+1] = {uid=18834,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=23,y=28,z=0,building=""}
M[#M+1] = {uid=18835,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=24,y=28,z=0,building=""}
M[#M+1] = {uid=18836,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=25,y=28,z=0,building=""}
M[#M+1] = {uid=18837,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=26,y=28,z=0,building=""}
M[#M+1] = {uid=18838,name="Carbonado Rockfields",area="gelidus",terrain="snow",info="",notes="",x=27,y=28,z=0,building=""}
M[#M+1] = {uid=18839,name="Dread Fields",area="gelidus",terrain="snow",info="",notes="",x=28,y=28,z=0,building=""}
M[#M+1] = {uid=18840,name="Dread Fields",area="gelidus",terrain="snow",info="",notes="",x=29,y=28,z=0,building=""}
M[#M+1] = {uid=18841,name="Dread Fields",area="gelidus",terrain="snow",info="",notes="",x=30,y=28,z=0,building=""}
M[#M+1] = {uid=18842,name="Dread Fields",area="gelidus",terrain="snow",info="",notes="",x=31,y=28,z=0,building=""}
M[#M+1] = {uid=18843,name="Dread Fields",area="gelidus",terrain="snow",info="",notes="",x=32,y=28,z=0,building=""}
M[#M+1] = {uid=18844,name="Dread Fields",area="gelidus",terrain="snow",info="",notes="",x=33,y=28,z=0,building=""}
M[#M+1] = {uid=18845,name="Dread Fields",area="gelidus",terrain="snow",info="",notes="",x=34,y=28,z=0,building=""}
M[#M+1] = {uid=18846,name="Dread Fields",area="gelidus",terrain="snow",info="",notes="",x=35,y=28,z=0,building=""}
M[#M+1] = {uid=18847,name="Blackfields",area="gelidus",terrain="snow",info="",notes="",x=36,y=28,z=0,building=""}
M[#M+1] = {uid=18848,name="Blackfields",area="gelidus",terrain="snow",info="",notes="",x=37,y=28,z=0,building=""}
M[#M+1] = {uid=18849,name="Blackfields",area="gelidus",terrain="snow",info="",notes="",x=38,y=28,z=0,building=""}
M[#M+1] = {uid=18850,name="Blackfields",area="gelidus",terrain="snow",info="",notes="",x=39,y=28,z=0,building=""}
M[#M+1] = {uid=18851,name="Blackfields",area="gelidus",terrain="snow",info="",notes="",x=40,y=28,z=0,building=""}
M[#M+1] = {uid=18852,name="Blackfields",area="gelidus",terrain="snow",info="",notes="",x=41,y=28,z=0,building=""}
M[#M+1] = {uid=18853,name="Blackfields",area="gelidus",terrain="snow",info="",notes="",x=42,y=28,z=0,building=""}
M[#M+1] = {uid=18854,name="Standing in front of the Winterlands",area="gelidus",terrain="castle",info="",notes="",x=43,y=28,z=0,building=""}
M[#M+1] = {uid=18855,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=44,y=28,z=0,building=""}
M[#M+1] = {uid=18856,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=45,y=28,z=0,building=""}
M[#M+1] = {uid=18857,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=46,y=28,z=0,building=""}
M[#M+1] = {uid=18858,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=47,y=28,z=0,building=""}
M[#M+1] = {uid=18859,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=48,y=28,z=0,building=""}
M[#M+1] = {uid=18860,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=49,y=28,z=0,building=""}
M[#M+1] = {uid=18861,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=50,y=28,z=0,building=""}
M[#M+1] = {uid=18862,name="Danameq Kujalleq",area="gelidus",terrain="icehills",info="",notes="",x=51,y=28,z=0,building=""}
M[#M+1] = {uid=18863,name="Frost Coast",area="gelidus",terrain="snow",info="",notes="",x=52,y=28,z=0,building=""}
M[#M+1] = {uid=18864,name="Frost Coast",area="gelidus",terrain="snow",info="",notes="",x=53,y=28,z=0,building=""}
M[#M+1] = {uid=18865,name="Aurora Harbor",area="gelidus",terrain="ocean",info="",notes="",x=54,y=28,z=0,building=""}
M[#M+1] = {uid=18866,name="Aurora Bay",area="gelidus",terrain="ocean",info="",notes="",x=55,y=28,z=0,building=""}
M[#M+1] = {uid=18867,name="Aurora Bay",area="gelidus",terrain="ocean",info="",notes="",x=56,y=28,z=0,building=""}
M[#M+1] = {uid=18868,name="Aurora Bay",area="gelidus",terrain="ocean",info="",notes="",x=57,y=28,z=0,building=""}
M[#M+1] = {uid=18869,name="Aurora Bay",area="gelidus",terrain="ocean",info="",notes="",x=58,y=28,z=0,building=""}
M[#M+1] = {uid=18870,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=59,y=28,z=0,building=""}
M[#M+1] = {uid=18871,name="Cape Nightfall",area="gelidus",terrain="plain",info="",notes="",x=0,y=29,z=0,building=""}
M[#M+1] = {uid=18872,name="Heavenstruck Bay",area="gelidus",terrain="ocean",info="",notes="",x=1,y=29,z=0,building=""}
M[#M+1] = {uid=18873,name="Heavenstruck Bay",area="gelidus",terrain="ocean",info="",notes="",x=2,y=29,z=0,building=""}
M[#M+1] = {uid=18874,name="Kyremaria",area="gelidus",terrain="plain",info="",notes="",x=3,y=29,z=0,building=""}
M[#M+1] = {uid=18875,name="Kyremaria",area="gelidus",terrain="plain",info="",notes="",x=4,y=29,z=0,building=""}
M[#M+1] = {uid=18876,name="Kyremaria",area="gelidus",terrain="plain",info="",notes="",x=5,y=29,z=0,building=""}
M[#M+1] = {uid=18877,name="Kyremaria",area="gelidus",terrain="plain",info="",notes="",x=6,y=29,z=0,building=""}
M[#M+1] = {uid=18878,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=7,y=29,z=0,building=""}
M[#M+1] = {uid=18879,name="Heavenstruck",area="gelidus",terrain="snow",info="",notes="",x=8,y=29,z=0,building=""}
M[#M+1] = {uid=18880,name="Demaria Plains",area="gelidus",terrain="plain",info="",notes="",x=9,y=29,z=0,building=""}
M[#M+1] = {uid=18881,name="Demaria Plains",area="gelidus",terrain="plain",info="",notes="",x=10,y=29,z=0,building=""}
M[#M+1] = {uid=18882,name="Demaria Plains",area="gelidus",terrain="plain",info="",notes="",x=11,y=29,z=0,building=""}
M[#M+1] = {uid=18883,name="Demaria Plains",area="gelidus",terrain="plain",info="",notes="",x=12,y=29,z=0,building=""}
M[#M+1] = {uid=18884,name="Demaria Plains",area="gelidus",terrain="plain",info="",notes="",x=13,y=29,z=0,building=""}
M[#M+1] = {uid=18885,name="Demaria Plains",area="gelidus",terrain="snow",info="",notes="",x=14,y=29,z=0,building=""}
M[#M+1] = {uid=18886,name="Demaria Plains",area="gelidus",terrain="snow",info="",notes="",x=15,y=29,z=0,building=""}
M[#M+1] = {uid=18887,name="Demaria Plains",area="gelidus",terrain="plain",info="",notes="",x=16,y=29,z=0,building=""}
M[#M+1] = {uid=18888,name="Demaria Plains",area="gelidus",terrain="plain",info="",notes="",x=17,y=29,z=0,building=""}
M[#M+1] = {uid=18889,name="Demaria Plains",area="gelidus",terrain="snow",info="",notes="",x=18,y=29,z=0,building=""}
M[#M+1] = {uid=18890,name="Demaria Plains",area="gelidus",terrain="snow",info="",notes="",x=19,y=29,z=0,building=""}
M[#M+1] = {uid=18891,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=20,y=29,z=0,building=""}
M[#M+1] = {uid=18892,name="Carbonado Rockfields",area="gelidus",terrain="plain",info="",notes="",x=21,y=29,z=0,building=""}
M[#M+1] = {uid=18893,name="Carbonado Rockfields",area="gelidus",terrain="plain",info="",notes="",x=22,y=29,z=0,building=""}
M[#M+1] = {uid=18894,name="Carbonado Rockfields",area="gelidus",terrain="plain",info="",notes="",x=23,y=29,z=0,building=""}
M[#M+1] = {uid=18895,name="Carbonado Rockfields",area="gelidus",terrain="snow",info="",notes="",x=24,y=29,z=0,building=""}
M[#M+1] = {uid=18896,name="Carbonado Rockfields",area="gelidus",terrain="snow",info="",notes="",x=25,y=29,z=0,building=""}
M[#M+1] = {uid=18897,name="Carbonado Rockfields",area="gelidus",terrain="plain",info="",notes="",x=26,y=29,z=0,building=""}
M[#M+1] = {uid=18898,name="Carbonado Rockfields",area="gelidus",terrain="plain",info="",notes="",x=27,y=29,z=0,building=""}
M[#M+1] = {uid=18899,name="Dread Fields",area="gelidus",terrain="snow",info="",notes="",x=28,y=29,z=0,building=""}
M[#M+1] = {uid=18900,name="Dread Fields",area="gelidus",terrain="plain",info="",notes="",x=29,y=29,z=0,building=""}
M[#M+1] = {uid=18901,name="Dread Fields",area="gelidus",terrain="plain",info="",notes="",x=30,y=29,z=0,building=""}
M[#M+1] = {uid=18902,name="Dread Fields",area="gelidus",terrain="plain",info="",notes="",x=31,y=29,z=0,building=""}
M[#M+1] = {uid=18903,name="Dread Fields",area="gelidus",terrain="plain",info="",notes="",x=32,y=29,z=0,building=""}
M[#M+1] = {uid=18904,name="A Grassy Spot",area="gelidus",terrain="field4",info="",notes="",x=33,y=29,z=0,building=""}
M[#M+1] = {uid=18905,name="Dread Fields",area="gelidus",terrain="plain",info="",notes="",x=34,y=29,z=0,building=""}
M[#M+1] = {uid=18906,name="Dread Fields",area="gelidus",terrain="plain",info="",notes="",x=35,y=29,z=0,building=""}
M[#M+1] = {uid=18907,name="Blackfields",area="gelidus",terrain="snow",info="",notes="",x=36,y=29,z=0,building=""}
M[#M+1] = {uid=18908,name="Blackfields",area="gelidus",terrain="snow",info="",notes="",x=37,y=29,z=0,building=""}
M[#M+1] = {uid=18909,name="Blackfields",area="gelidus",terrain="plain",info="",notes="",x=38,y=29,z=0,building=""}
M[#M+1] = {uid=18910,name="Blackfields",area="gelidus",terrain="plain",info="",notes="",x=39,y=29,z=0,building=""}
M[#M+1] = {uid=18911,name="Blackfields",area="gelidus",terrain="plain",info="",notes="",x=40,y=29,z=0,building=""}
M[#M+1] = {uid=18912,name="Blackfields",area="gelidus",terrain="plain",info="",notes="",x=41,y=29,z=0,building=""}
M[#M+1] = {uid=18913,name="Blackfields",area="gelidus",terrain="snow",info="",notes="",x=42,y=29,z=0,building=""}
M[#M+1] = {uid=18914,name="Blackfields",area="gelidus",terrain="plain",info="",notes="",x=43,y=29,z=0,building=""}
M[#M+1] = {uid=18915,name="Blackfields",area="gelidus",terrain="plain",info="",notes="",x=44,y=29,z=0,building=""}
M[#M+1] = {uid=18916,name="Blackfields",area="gelidus",terrain="plain",info="",notes="",x=45,y=29,z=0,building=""}
M[#M+1] = {uid=18917,name="Blackfields",area="gelidus",terrain="plain",info="",notes="",x=46,y=29,z=0,building=""}
M[#M+1] = {uid=18918,name="Upper Einskerr",area="gelidus",terrain="plain",info="",notes="",x=47,y=29,z=0,building=""}
M[#M+1] = {uid=18919,name="Upper Einskerr",area="gelidus",terrain="plain",info="",notes="",x=48,y=29,z=0,building=""}
M[#M+1] = {uid=18920,name="Upper Einskerr",area="gelidus",terrain="plain",info="",notes="",x=49,y=29,z=0,building=""}
M[#M+1] = {uid=18921,name="Upper Einskerr",area="gelidus",terrain="plain",info="",notes="",x=50,y=29,z=0,building=""}
M[#M+1] = {uid=18922,name="Upper Einskerr",area="gelidus",terrain="plain",info="",notes="",x=51,y=29,z=0,building=""}
M[#M+1] = {uid=18923,name="Upper Einskerr",area="gelidus",terrain="plain",info="",notes="",x=52,y=29,z=0,building=""}
return M
