-- generated by tools/import-mushmap.py — do not edit
-- rooms 12001..12750
local M = {}
M[#M+1] = {uid=17424,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=53,y=4,z=0,building=""}
M[#M+1] = {uid=17425,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=54,y=4,z=0,building=""}
M[#M+1] = {uid=17426,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=55,y=4,z=0,building=""}
M[#M+1] = {uid=17427,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=56,y=4,z=0,building=""}
M[#M+1] = {uid=17428,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=57,y=4,z=0,building=""}
M[#M+1] = {uid=17429,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=58,y=4,z=0,building=""}
M[#M+1] = {uid=17430,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=59,y=4,z=0,building=""}
M[#M+1] = {uid=17431,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=0,y=5,z=0,building=""}
M[#M+1] = {uid=17432,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=1,y=5,z=0,building=""}
M[#M+1] = {uid=17433,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=2,y=5,z=0,building=""}
M[#M+1] = {uid=17434,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=3,y=5,z=0,building=""}
M[#M+1] = {uid=17435,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=4,y=5,z=0,building=""}
M[#M+1] = {uid=17436,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=5,y=5,z=0,building=""}
M[#M+1] = {uid=17437,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=6,y=5,z=0,building=""}
M[#M+1] = {uid=17438,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=7,y=5,z=0,building=""}
M[#M+1] = {uid=17439,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=8,y=5,z=0,building=""}
M[#M+1] = {uid=17440,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=9,y=5,z=0,building=""}
M[#M+1] = {uid=17441,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=10,y=5,z=0,building=""}
M[#M+1] = {uid=17442,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=11,y=5,z=0,building=""}
M[#M+1] = {uid=17443,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=12,y=5,z=0,building=""}
M[#M+1] = {uid=17444,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=13,y=5,z=0,building=""}
M[#M+1] = {uid=17445,name="Gulf of Arnas",area="gelidus",terrain="ocean",info="",notes="",x=14,y=5,z=0,building=""}
M[#M+1] = {uid=17446,name="Gulf of Arnas",area="gelidus",terrain="ocean",info="",notes="",x=15,y=5,z=0,building=""}
M[#M+1] = {uid=17447,name="Gulf of Arnas",area="gelidus",terrain="ocean",info="",notes="",x=16,y=5,z=0,building=""}
M[#M+1] = {uid=17448,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=17,y=5,z=0,building=""}
M[#M+1] = {uid=17449,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=18,y=5,z=0,building=""}
M[#M+1] = {uid=17450,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=19,y=5,z=0,building=""}
M[#M+1] = {uid=17451,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=20,y=5,z=0,building=""}
M[#M+1] = {uid=17452,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=21,y=5,z=0,building=""}
M[#M+1] = {uid=17453,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=22,y=5,z=0,building=""}
M[#M+1] = {uid=17454,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=23,y=5,z=0,building=""}
M[#M+1] = {uid=17455,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=24,y=5,z=0,building=""}
M[#M+1] = {uid=17456,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=25,y=5,z=0,building=""}
M[#M+1] = {uid=17457,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=26,y=5,z=0,building=""}
M[#M+1] = {uid=17458,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=27,y=5,z=0,building=""}
M[#M+1] = {uid=17459,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=28,y=5,z=0,building=""}
M[#M+1] = {uid=17460,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=29,y=5,z=0,building=""}
M[#M+1] = {uid=17461,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=30,y=5,z=0,building=""}
M[#M+1] = {uid=17462,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=31,y=5,z=0,building=""}
M[#M+1] = {uid=17463,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=32,y=5,z=0,building=""}
M[#M+1] = {uid=17464,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=33,y=5,z=0,building=""}
M[#M+1] = {uid=17465,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=34,y=5,z=0,building=""}
M[#M+1] = {uid=17466,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=35,y=5,z=0,building=""}
M[#M+1] = {uid=17467,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=36,y=5,z=0,building=""}
M[#M+1] = {uid=17468,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=37,y=5,z=0,building=""}
M[#M+1] = {uid=17469,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=38,y=5,z=0,building=""}
M[#M+1] = {uid=17470,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=39,y=5,z=0,building=""}
M[#M+1] = {uid=17471,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=40,y=5,z=0,building=""}
M[#M+1] = {uid=17472,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=41,y=5,z=0,building=""}
M[#M+1] = {uid=17473,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=42,y=5,z=0,building=""}
M[#M+1] = {uid=17474,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=43,y=5,z=0,building=""}
M[#M+1] = {uid=17475,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=44,y=5,z=0,building=""}
M[#M+1] = {uid=17476,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=45,y=5,z=0,building=""}
M[#M+1] = {uid=17477,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=46,y=5,z=0,building=""}
M[#M+1] = {uid=17478,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=47,y=5,z=0,building=""}
M[#M+1] = {uid=17479,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=48,y=5,z=0,building=""}
M[#M+1] = {uid=17480,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=49,y=5,z=0,building=""}
M[#M+1] = {uid=17481,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=50,y=5,z=0,building=""}
M[#M+1] = {uid=17482,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=51,y=5,z=0,building=""}
M[#M+1] = {uid=17483,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=52,y=5,z=0,building=""}
M[#M+1] = {uid=17484,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=53,y=5,z=0,building=""}
M[#M+1] = {uid=17485,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=54,y=5,z=0,building=""}
M[#M+1] = {uid=17486,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=55,y=5,z=0,building=""}
M[#M+1] = {uid=17487,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=56,y=5,z=0,building=""}
M[#M+1] = {uid=17488,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=57,y=5,z=0,building=""}
M[#M+1] = {uid=17489,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=58,y=5,z=0,building=""}
M[#M+1] = {uid=17490,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=59,y=5,z=0,building=""}
M[#M+1] = {uid=17491,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=0,y=6,z=0,building=""}
M[#M+1] = {uid=17492,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=1,y=6,z=0,building=""}
M[#M+1] = {uid=17493,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=2,y=6,z=0,building=""}
M[#M+1] = {uid=17494,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=3,y=6,z=0,building=""}
M[#M+1] = {uid=17495,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=4,y=6,z=0,building=""}
M[#M+1] = {uid=17496,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=5,y=6,z=0,building=""}
M[#M+1] = {uid=17497,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=6,y=6,z=0,building=""}
M[#M+1] = {uid=17498,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=7,y=6,z=0,building=""}
M[#M+1] = {uid=17499,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=8,y=6,z=0,building=""}
M[#M+1] = {uid=17500,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=9,y=6,z=0,building=""}
M[#M+1] = {uid=17501,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=10,y=6,z=0,building=""}
M[#M+1] = {uid=17502,name="Androlinn",area="gelidus",terrain="field",info="",notes="",x=11,y=6,z=0,building=""}
M[#M+1] = {uid=17503,name="Androlinn",area="gelidus",terrain="field",info="",notes="",x=12,y=6,z=0,building=""}
M[#M+1] = {uid=17504,name="Androlinn",area="gelidus",terrain="field",info="",notes="",x=13,y=6,z=0,building=""}
M[#M+1] = {uid=17505,name="Port Androlinn",area="gelidus",terrain="field",info="",notes="",x=14,y=6,z=0,building=""}
M[#M+1] = {uid=17506,name="Gulf of Arnas",area="gelidus",terrain="ocean",info="",notes="",x=15,y=6,z=0,building=""}
M[#M+1] = {uid=17507,name="Kirnalinn Harbor",area="gelidus",terrain="field",info="",notes="",x=16,y=6,z=0,building=""}
M[#M+1] = {uid=17508,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=17,y=6,z=0,building=""}
M[#M+1] = {uid=17509,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=18,y=6,z=0,building=""}
M[#M+1] = {uid=17510,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=19,y=6,z=0,building=""}
M[#M+1] = {uid=17511,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=20,y=6,z=0,building=""}
M[#M+1] = {uid=17512,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=21,y=6,z=0,building=""}
M[#M+1] = {uid=17513,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=22,y=6,z=0,building=""}
M[#M+1] = {uid=17514,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=23,y=6,z=0,building=""}
M[#M+1] = {uid=17515,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=24,y=6,z=0,building=""}
M[#M+1] = {uid=17516,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=25,y=6,z=0,building=""}
M[#M+1] = {uid=17517,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=26,y=6,z=0,building=""}
M[#M+1] = {uid=17518,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=27,y=6,z=0,building=""}
M[#M+1] = {uid=17519,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=28,y=6,z=0,building=""}
M[#M+1] = {uid=17520,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=29,y=6,z=0,building=""}
M[#M+1] = {uid=17521,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=30,y=6,z=0,building=""}
M[#M+1] = {uid=17522,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=31,y=6,z=0,building=""}
M[#M+1] = {uid=17523,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=32,y=6,z=0,building=""}
M[#M+1] = {uid=17524,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=33,y=6,z=0,building=""}
M[#M+1] = {uid=17525,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=34,y=6,z=0,building=""}
M[#M+1] = {uid=17526,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=35,y=6,z=0,building=""}
M[#M+1] = {uid=17527,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=36,y=6,z=0,building=""}
M[#M+1] = {uid=17528,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=37,y=6,z=0,building=""}
M[#M+1] = {uid=17529,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=38,y=6,z=0,building=""}
M[#M+1] = {uid=17530,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=39,y=6,z=0,building=""}
M[#M+1] = {uid=17531,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=40,y=6,z=0,building=""}
M[#M+1] = {uid=17532,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=41,y=6,z=0,building=""}
M[#M+1] = {uid=17533,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=42,y=6,z=0,building=""}
M[#M+1] = {uid=17534,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=43,y=6,z=0,building=""}
M[#M+1] = {uid=17535,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=44,y=6,z=0,building=""}
M[#M+1] = {uid=17536,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=45,y=6,z=0,building=""}
M[#M+1] = {uid=17537,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=46,y=6,z=0,building=""}
M[#M+1] = {uid=17538,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=47,y=6,z=0,building=""}
M[#M+1] = {uid=17539,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=48,y=6,z=0,building=""}
M[#M+1] = {uid=17540,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=49,y=6,z=0,building=""}
M[#M+1] = {uid=17541,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=50,y=6,z=0,building=""}
M[#M+1] = {uid=17542,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=51,y=6,z=0,building=""}
M[#M+1] = {uid=17543,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=52,y=6,z=0,building=""}
M[#M+1] = {uid=17544,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=53,y=6,z=0,building=""}
M[#M+1] = {uid=17545,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=54,y=6,z=0,building=""}
M[#M+1] = {uid=17546,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=55,y=6,z=0,building=""}
M[#M+1] = {uid=17547,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=56,y=6,z=0,building=""}
M[#M+1] = {uid=17548,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=57,y=6,z=0,building=""}
M[#M+1] = {uid=17549,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=58,y=6,z=0,building=""}
M[#M+1] = {uid=17550,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=59,y=6,z=0,building=""}
M[#M+1] = {uid=17551,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=0,y=7,z=0,building=""}
M[#M+1] = {uid=17552,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=1,y=7,z=0,building=""}
M[#M+1] = {uid=17553,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=2,y=7,z=0,building=""}
M[#M+1] = {uid=17554,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=3,y=7,z=0,building=""}
M[#M+1] = {uid=17555,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=4,y=7,z=0,building=""}
M[#M+1] = {uid=17556,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=5,y=7,z=0,building=""}
M[#M+1] = {uid=17557,name="Forest of the Veil",area="gelidus",terrain="forest",info="",notes="",x=6,y=7,z=0,building=""}
M[#M+1] = {uid=17558,name="Forest of the Veil",area="gelidus",terrain="forest",info="",notes="",x=7,y=7,z=0,building=""}
M[#M+1] = {uid=17559,name="Forest of the Veil",area="gelidus",terrain="forest",info="",notes="",x=8,y=7,z=0,building=""}
M[#M+1] = {uid=17560,name="Androlinn",area="gelidus",terrain="field",info="",notes="",x=9,y=7,z=0,building=""}
M[#M+1] = {uid=17561,name="Androlinn",area="gelidus",terrain="field",info="",notes="",x=10,y=7,z=0,building=""}
M[#M+1] = {uid=17562,name="Androlinn",area="gelidus",terrain="field",info="",notes="",x=11,y=7,z=0,building=""}
M[#M+1] = {uid=17563,name="Androlinn",area="gelidus",terrain="field",info="",notes="",x=12,y=7,z=0,building=""}
M[#M+1] = {uid=17564,name="Androlinn",area="gelidus",terrain="field",info="",notes="",x=13,y=7,z=0,building=""}
M[#M+1] = {uid=17565,name="Androlinn",area="gelidus",terrain="field",info="",notes="",x=14,y=7,z=0,building=""}
M[#M+1] = {uid=17566,name="Gulf of Arnas",area="gelidus",terrain="ocean",info="",notes="",x=15,y=7,z=0,building=""}
M[#M+1] = {uid=17567,name="Kirnas Rapids",area="gelidus",terrain="shore",info="",notes="",x=16,y=7,z=0,building=""}
M[#M+1] = {uid=17568,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=17,y=7,z=0,building=""}
M[#M+1] = {uid=17569,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=18,y=7,z=0,building=""}
M[#M+1] = {uid=17570,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=19,y=7,z=0,building=""}
M[#M+1] = {uid=17571,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=20,y=7,z=0,building=""}
M[#M+1] = {uid=17572,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=21,y=7,z=0,building=""}
M[#M+1] = {uid=17573,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=22,y=7,z=0,building=""}
M[#M+1] = {uid=17574,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=23,y=7,z=0,building=""}
M[#M+1] = {uid=17575,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=24,y=7,z=0,building=""}
M[#M+1] = {uid=17576,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=25,y=7,z=0,building=""}
M[#M+1] = {uid=17577,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=26,y=7,z=0,building=""}
M[#M+1] = {uid=17578,name="Bluegrass Haven",area="gelidus",terrain="field",info="",notes="",x=27,y=7,z=0,building=""}
M[#M+1] = {uid=17579,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=28,y=7,z=0,building=""}
M[#M+1] = {uid=17580,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=29,y=7,z=0,building=""}
M[#M+1] = {uid=17581,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=30,y=7,z=0,building=""}
M[#M+1] = {uid=17582,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=31,y=7,z=0,building=""}
M[#M+1] = {uid=17583,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=32,y=7,z=0,building=""}
M[#M+1] = {uid=17584,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=33,y=7,z=0,building=""}
M[#M+1] = {uid=17585,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=34,y=7,z=0,building=""}
M[#M+1] = {uid=17586,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=35,y=7,z=0,building=""}
M[#M+1] = {uid=17587,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=36,y=7,z=0,building=""}
M[#M+1] = {uid=17588,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=37,y=7,z=0,building=""}
M[#M+1] = {uid=17589,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=38,y=7,z=0,building=""}
M[#M+1] = {uid=17590,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=39,y=7,z=0,building=""}
M[#M+1] = {uid=17591,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=40,y=7,z=0,building=""}
M[#M+1] = {uid=17592,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=41,y=7,z=0,building=""}
M[#M+1] = {uid=17593,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=42,y=7,z=0,building=""}
M[#M+1] = {uid=17594,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=43,y=7,z=0,building=""}
M[#M+1] = {uid=17595,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=44,y=7,z=0,building=""}
M[#M+1] = {uid=17596,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=45,y=7,z=0,building=""}
M[#M+1] = {uid=17597,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=46,y=7,z=0,building=""}
M[#M+1] = {uid=17598,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=47,y=7,z=0,building=""}
M[#M+1] = {uid=17599,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=48,y=7,z=0,building=""}
M[#M+1] = {uid=17600,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=49,y=7,z=0,building=""}
M[#M+1] = {uid=17601,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=50,y=7,z=0,building=""}
M[#M+1] = {uid=17602,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=51,y=7,z=0,building=""}
M[#M+1] = {uid=17603,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=52,y=7,z=0,building=""}
M[#M+1] = {uid=17604,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=53,y=7,z=0,building=""}
M[#M+1] = {uid=17605,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=54,y=7,z=0,building=""}
M[#M+1] = {uid=17606,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=55,y=7,z=0,building=""}
M[#M+1] = {uid=17607,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=56,y=7,z=0,building=""}
M[#M+1] = {uid=17608,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=57,y=7,z=0,building=""}
M[#M+1] = {uid=17609,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=58,y=7,z=0,building=""}
M[#M+1] = {uid=17610,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=59,y=7,z=0,building=""}
M[#M+1] = {uid=17611,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=0,y=8,z=0,building=""}
M[#M+1] = {uid=17612,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=1,y=8,z=0,building=""}
M[#M+1] = {uid=17613,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=2,y=8,z=0,building=""}
M[#M+1] = {uid=17614,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=3,y=8,z=0,building=""}
M[#M+1] = {uid=17615,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=4,y=8,z=0,building=""}
M[#M+1] = {uid=17616,name="Forest of the Veil",area="gelidus",terrain="forest",info="",notes="",x=5,y=8,z=0,building=""}
M[#M+1] = {uid=17617,name="Nemaja Lowlands",area="gelidus",terrain="field",info="",notes="",x=6,y=8,z=0,building=""}
M[#M+1] = {uid=17618,name="Nemaja Lowlands",area="gelidus",terrain="field",info="",notes="",x=7,y=8,z=0,building=""}
M[#M+1] = {uid=17619,name="Forest of the Veil",area="gelidus",terrain="forest",info="",notes="",x=8,y=8,z=0,building=""}
M[#M+1] = {uid=17620,name="Forest of the Veil",area="gelidus",terrain="forest",info="",notes="",x=9,y=8,z=0,building=""}
M[#M+1] = {uid=17621,name="Androlinn",area="gelidus",terrain="field",info="",notes="",x=10,y=8,z=0,building=""}
M[#M+1] = {uid=17622,name="Androlinn",area="gelidus",terrain="field",info="",notes="",x=11,y=8,z=0,building=""}
M[#M+1] = {uid=17623,name="Androlinn",area="gelidus",terrain="field",info="",notes="",x=12,y=8,z=0,building=""}
M[#M+1] = {uid=17624,name="Gulf of Arnas",area="gelidus",terrain="ocean",info="",notes="",x=13,y=8,z=0,building=""}
M[#M+1] = {uid=17625,name="Gulf of Arnas",area="gelidus",terrain="ocean",info="",notes="",x=14,y=8,z=0,building=""}
M[#M+1] = {uid=17626,name="Kindannyd Fawr",area="gelidus",terrain="field",info="",notes="",x=15,y=8,z=0,building=""}
M[#M+1] = {uid=17627,name="Kindannyd Fawr",area="gelidus",terrain="field",info="",notes="",x=16,y=8,z=0,building=""}
M[#M+1] = {uid=17628,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=17,y=8,z=0,building=""}
M[#M+1] = {uid=17629,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=18,y=8,z=0,building=""}
M[#M+1] = {uid=17630,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=19,y=8,z=0,building=""}
M[#M+1] = {uid=17631,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=20,y=8,z=0,building=""}
M[#M+1] = {uid=17632,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=21,y=8,z=0,building=""}
M[#M+1] = {uid=17633,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=22,y=8,z=0,building=""}
M[#M+1] = {uid=17634,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=23,y=8,z=0,building=""}
M[#M+1] = {uid=17635,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=24,y=8,z=0,building=""}
M[#M+1] = {uid=17636,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=25,y=8,z=0,building=""}
M[#M+1] = {uid=17637,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=26,y=8,z=0,building=""}
M[#M+1] = {uid=17638,name="Bluegrass Haven",area="gelidus",terrain="field",info="",notes="",x=27,y=8,z=0,building=""}
M[#M+1] = {uid=17639,name="Bluegrass Haven",area="gelidus",terrain="field",info="",notes="",x=28,y=8,z=0,building=""}
M[#M+1] = {uid=17640,name="Bluegrass Haven",area="gelidus",terrain="field",info="",notes="",x=29,y=8,z=0,building=""}
M[#M+1] = {uid=17641,name="Bluegrass Haven",area="gelidus",terrain="field",info="",notes="",x=30,y=8,z=0,building=""}
M[#M+1] = {uid=17642,name="A Flat Coastline",area="gelidus",terrain="field",info="",notes="",x=31,y=8,z=0,building=""}
M[#M+1] = {uid=17643,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=32,y=8,z=0,building=""}
M[#M+1] = {uid=17644,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=33,y=8,z=0,building=""}
M[#M+1] = {uid=17645,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=34,y=8,z=0,building=""}
M[#M+1] = {uid=17646,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=35,y=8,z=0,building=""}
M[#M+1] = {uid=17647,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=36,y=8,z=0,building=""}
M[#M+1] = {uid=17648,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=37,y=8,z=0,building=""}
M[#M+1] = {uid=17649,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=38,y=8,z=0,building=""}
M[#M+1] = {uid=17650,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=39,y=8,z=0,building=""}
M[#M+1] = {uid=17651,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=40,y=8,z=0,building=""}
M[#M+1] = {uid=17652,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=41,y=8,z=0,building=""}
M[#M+1] = {uid=17653,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=42,y=8,z=0,building=""}
M[#M+1] = {uid=17654,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=43,y=8,z=0,building=""}
M[#M+1] = {uid=17655,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=44,y=8,z=0,building=""}
M[#M+1] = {uid=17656,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=45,y=8,z=0,building=""}
M[#M+1] = {uid=17657,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=46,y=8,z=0,building=""}
M[#M+1] = {uid=17658,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=47,y=8,z=0,building=""}
M[#M+1] = {uid=17659,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=48,y=8,z=0,building=""}
M[#M+1] = {uid=17660,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=49,y=8,z=0,building=""}
M[#M+1] = {uid=17661,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=50,y=8,z=0,building=""}
M[#M+1] = {uid=17662,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=51,y=8,z=0,building=""}
M[#M+1] = {uid=17663,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=52,y=8,z=0,building=""}
M[#M+1] = {uid=17664,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=53,y=8,z=0,building=""}
M[#M+1] = {uid=17665,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=54,y=8,z=0,building=""}
M[#M+1] = {uid=17666,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=55,y=8,z=0,building=""}
M[#M+1] = {uid=17667,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=56,y=8,z=0,building=""}
M[#M+1] = {uid=17668,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=57,y=8,z=0,building=""}
M[#M+1] = {uid=17669,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=58,y=8,z=0,building=""}
M[#M+1] = {uid=17670,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=59,y=8,z=0,building=""}
M[#M+1] = {uid=17671,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=0,y=9,z=0,building=""}
M[#M+1] = {uid=17672,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=1,y=9,z=0,building=""}
M[#M+1] = {uid=17673,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=2,y=9,z=0,building=""}
M[#M+1] = {uid=17674,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=3,y=9,z=0,building=""}
M[#M+1] = {uid=17675,name="Forest of the Veil",area="gelidus",terrain="forest",info="",notes="",x=4,y=9,z=0,building=""}
M[#M+1] = {uid=17676,name="Nemaja Lowlands",area="gelidus",terrain="field",info="",notes="",x=5,y=9,z=0,building=""}
M[#M+1] = {uid=17677,name="Nemaja Lowlands",area="gelidus",terrain="field",info="",notes="",x=6,y=9,z=0,building=""}
M[#M+1] = {uid=17678,name="Nemaja Lowlands",area="gelidus",terrain="field",info="",notes="",x=7,y=9,z=0,building=""}
M[#M+1] = {uid=17679,name="Nemaja Lowlands",area="gelidus",terrain="field",info="",notes="",x=8,y=9,z=0,building=""}
M[#M+1] = {uid=17680,name="Forest of the Veil",area="gelidus",terrain="forest",info="",notes="",x=9,y=9,z=0,building=""}
M[#M+1] = {uid=17681,name="Gulf of Arnas",area="gelidus",terrain="ocean",info="",notes="",x=10,y=9,z=0,building=""}
M[#M+1] = {uid=17682,name="Gulf of Arnas",area="gelidus",terrain="ocean",info="",notes="",x=11,y=9,z=0,building=""}
M[#M+1] = {uid=17683,name="Gulf of Arnas",area="gelidus",terrain="ocean",info="",notes="",x=12,y=9,z=0,building=""}
M[#M+1] = {uid=17684,name="Gulf of Arnas",area="gelidus",terrain="ocean",info="",notes="",x=13,y=9,z=0,building=""}
M[#M+1] = {uid=17685,name="Gulf of Arnas",area="gelidus",terrain="ocean",info="",notes="",x=14,y=9,z=0,building=""}
M[#M+1] = {uid=17686,name="Kirnas Rapids",area="gelidus",terrain="shore",info="",notes="",x=15,y=9,z=0,building=""}
M[#M+1] = {uid=17687,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=16,y=9,z=0,building=""}
M[#M+1] = {uid=17688,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=17,y=9,z=0,building=""}
M[#M+1] = {uid=17689,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=18,y=9,z=0,building=""}
M[#M+1] = {uid=17690,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=19,y=9,z=0,building=""}
M[#M+1] = {uid=17691,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=20,y=9,z=0,building=""}
M[#M+1] = {uid=17692,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=21,y=9,z=0,building=""}
M[#M+1] = {uid=17693,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=22,y=9,z=0,building=""}
M[#M+1] = {uid=17694,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=23,y=9,z=0,building=""}
M[#M+1] = {uid=17695,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=24,y=9,z=0,building=""}
M[#M+1] = {uid=17696,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=25,y=9,z=0,building=""}
M[#M+1] = {uid=17697,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=26,y=9,z=0,building=""}
M[#M+1] = {uid=17698,name="Bluegrass Haven",area="gelidus",terrain="areaexit",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=17699,name="Bluegrass Haven",area="gelidus",terrain="field",info="",notes="",x=28,y=9,z=0,building=""}
M[#M+1] = {uid=17700,name="Bluegrass Haven",area="gelidus",terrain="field",info="",notes="",x=29,y=9,z=0,building=""}
M[#M+1] = {uid=17701,name="Bluegrass Haven",area="gelidus",terrain="field",info="",notes="",x=30,y=9,z=0,building=""}
M[#M+1] = {uid=17702,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=31,y=9,z=0,building=""}
M[#M+1] = {uid=17703,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=32,y=9,z=0,building=""}
M[#M+1] = {uid=17704,name="A Flat Coastline",area="gelidus",terrain="field",info="",notes="",x=33,y=9,z=0,building=""}
M[#M+1] = {uid=17705,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=34,y=9,z=0,building=""}
M[#M+1] = {uid=17706,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=35,y=9,z=0,building=""}
M[#M+1] = {uid=17707,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=36,y=9,z=0,building=""}
M[#M+1] = {uid=17708,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=37,y=9,z=0,building=""}
M[#M+1] = {uid=17709,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=38,y=9,z=0,building=""}
M[#M+1] = {uid=17710,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=39,y=9,z=0,building=""}
M[#M+1] = {uid=17711,name="Sandy Wastes",area="gelidus",terrain="beach",info="",notes="",x=40,y=9,z=0,building=""}
M[#M+1] = {uid=17712,name="Sandy Wastes",area="gelidus",terrain="beach",info="",notes="",x=41,y=9,z=0,building=""}
M[#M+1] = {uid=17713,name="Sandy Wastes",area="gelidus",terrain="beach",info="",notes="",x=42,y=9,z=0,building=""}
M[#M+1] = {uid=17714,name="Sandy Wastes",area="gelidus",terrain="beach",info="",notes="",x=43,y=9,z=0,building=""}
M[#M+1] = {uid=17715,name="Sandy Wastes",area="gelidus",terrain="beach",info="",notes="",x=44,y=9,z=0,building=""}
M[#M+1] = {uid=17716,name="Sandy Wastes",area="gelidus",terrain="beach",info="",notes="",x=45,y=9,z=0,building=""}
M[#M+1] = {uid=17717,name="Amber Bay",area="gelidus",terrain="ocean",info="",notes="",x=46,y=9,z=0,building=""}
M[#M+1] = {uid=17718,name="Amber Bay",area="gelidus",terrain="ocean",info="",notes="",x=47,y=9,z=0,building=""}
M[#M+1] = {uid=17719,name="Amber Bay",area="gelidus",terrain="ocean",info="",notes="",x=48,y=9,z=0,building=""}
M[#M+1] = {uid=17720,name="Amber Bay",area="gelidus",terrain="ocean",info="",notes="",x=49,y=9,z=0,building=""}
M[#M+1] = {uid=17721,name="Amber Bay",area="gelidus",terrain="ocean",info="",notes="",x=50,y=9,z=0,building=""}
M[#M+1] = {uid=17722,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=51,y=9,z=0,building=""}
M[#M+1] = {uid=17723,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=52,y=9,z=0,building=""}
M[#M+1] = {uid=17724,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=53,y=9,z=0,building=""}
M[#M+1] = {uid=17725,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=54,y=9,z=0,building=""}
M[#M+1] = {uid=17726,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=55,y=9,z=0,building=""}
M[#M+1] = {uid=17727,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=56,y=9,z=0,building=""}
M[#M+1] = {uid=17728,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=57,y=9,z=0,building=""}
M[#M+1] = {uid=17729,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=58,y=9,z=0,building=""}
M[#M+1] = {uid=17730,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=59,y=9,z=0,building=""}
M[#M+1] = {uid=17731,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=0,y=10,z=0,building=""}
M[#M+1] = {uid=17732,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=1,y=10,z=0,building=""}
M[#M+1] = {uid=17733,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=2,y=10,z=0,building=""}
M[#M+1] = {uid=17734,name="Forest of the Veil",area="gelidus",terrain="forest",info="",notes="",x=3,y=10,z=0,building=""}
M[#M+1] = {uid=17735,name="Nemaja Lowlands",area="gelidus",terrain="field",info="",notes="",x=4,y=10,z=0,building=""}
M[#M+1] = {uid=17736,name="Nemaja Lowlands",area="gelidus",terrain="field",info="",notes="",x=5,y=10,z=0,building=""}
M[#M+1] = {uid=17737,name="Murkwater",area="gelidus",terrain="river",info="",notes="",x=6,y=10,z=0,building=""}
M[#M+1] = {uid=17738,name="Nemaja Lowlands",area="gelidus",terrain="field",info="",notes="",x=7,y=10,z=0,building=""}
M[#M+1] = {uid=17739,name="A Large Hill",area="gelidus",terrain="field4",info="",notes="",x=8,y=10,z=0,building=""}
M[#M+1] = {uid=17740,name="Nemaja Lowlands",area="gelidus",terrain="field3",info="",notes="",x=9,y=10,z=0,building=""}
M[#M+1] = {uid=17741,name="Nemaja Lowlands",area="gelidus",terrain="field",info="",notes="",x=10,y=10,z=0,building=""}
M[#M+1] = {uid=17742,name="Gulf of Arnas",area="gelidus",terrain="ocean",info="",notes="",x=11,y=10,z=0,building=""}
M[#M+1] = {uid=17743,name="Carnach",area="gelidus",terrain="field3",info="",notes="",x=12,y=10,z=0,building=""}
M[#M+1] = {uid=17744,name="Carnach",area="gelidus",terrain="field",info="",notes="",x=13,y=10,z=0,building=""}
M[#M+1] = {uid=17745,name="Carnach",area="gelidus",terrain="field3",info="",notes="",x=14,y=10,z=0,building=""}
M[#M+1] = {uid=17746,name="Carnach",area="gelidus",terrain="field",info="",notes="",x=15,y=10,z=0,building=""}
M[#M+1] = {uid=17747,name="Carnach",area="gelidus",terrain="field3",info="",notes="",x=16,y=10,z=0,building=""}
M[#M+1] = {uid=17748,name="Carnach",area="gelidus",terrain="field",info="",notes="",x=17,y=10,z=0,building=""}
M[#M+1] = {uid=17749,name="Carnach",area="gelidus",terrain="field4",info="",notes="",x=18,y=10,z=0,building=""}
M[#M+1] = {uid=17750,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=19,y=10,z=0,building=""}
M[#M+1] = {uid=17751,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=20,y=10,z=0,building=""}
M[#M+1] = {uid=17752,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=21,y=10,z=0,building=""}
M[#M+1] = {uid=17753,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=22,y=10,z=0,building=""}
M[#M+1] = {uid=17754,name="Lake Kirnas",area="gelidus",terrain="ocean",info="",notes="",x=23,y=10,z=0,building=""}
M[#M+1] = {uid=17755,name="Kirnalinn Hills",area="gelidus",terrain="field4",info="",notes="",x=24,y=10,z=0,building=""}
M[#M+1] = {uid=17756,name="Kirnalinn Forest",area="gelidus",terrain="forest",info="",notes="",x=25,y=10,z=0,building=""}
M[#M+1] = {uid=17757,name="Kirnalinn Peninsula",area="gelidus",terrain="field",info="",notes="",x=26,y=10,z=0,building=""}
M[#M+1] = {uid=17758,name="Bluegrass Haven",area="gelidus",terrain="field4",info="",notes="",x=27,y=10,z=0,building=""}
M[#M+1] = {uid=17759,name="Bluegrass Haven",area="gelidus",terrain="field",info="",notes="",x=28,y=10,z=0,building=""}
M[#M+1] = {uid=17760,name="Bluegrass Haven",area="gelidus",terrain="field",info="",notes="",x=29,y=10,z=0,building=""}
M[#M+1] = {uid=17761,name="An Eternal Flame",area="gelidus",terrain="field4",info="",notes="",x=30,y=10,z=0,building=""}
M[#M+1] = {uid=17762,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=31,y=10,z=0,building=""}
M[#M+1] = {uid=17763,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=32,y=10,z=0,building=""}
M[#M+1] = {uid=17764,name="An Oak Grove",area="gelidus",terrain="forest",info="",notes="",x=33,y=10,z=0,building=""}
M[#M+1] = {uid=17765,name="A Flat Coastline",area="gelidus",terrain="field",info="",notes="",x=34,y=10,z=0,building=""}
M[#M+1] = {uid=17766,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=35,y=10,z=0,building=""}
M[#M+1] = {uid=17767,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=36,y=10,z=0,building=""}
M[#M+1] = {uid=17768,name="Coastal Hills",area="gelidus",terrain="field4",info="",notes="",x=37,y=10,z=0,building=""}
M[#M+1] = {uid=17769,name="Coastal Hills",area="gelidus",terrain="field4",info="",notes="",x=38,y=10,z=0,building=""}
M[#M+1] = {uid=17770,name="Sandy Wastes",area="gelidus",terrain="beach",info="",notes="",x=39,y=10,z=0,building=""}
M[#M+1] = {uid=17771,name="Sandy Wastes",area="gelidus",terrain="beach",info="",notes="",x=40,y=10,z=0,building=""}
M[#M+1] = {uid=17772,name="Sandspout Forest",area="gelidus",terrain="forest",info="",notes="",x=41,y=10,z=0,building=""}
M[#M+1] = {uid=17773,name="Sandy Wastes",area="gelidus",terrain="beach",info="",notes="",x=42,y=10,z=0,building=""}
M[#M+1] = {uid=17774,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=43,y=10,z=0,building=""}
M[#M+1] = {uid=17775,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=44,y=10,z=0,building=""}
M[#M+1] = {uid=17776,name="Amber Bay",area="gelidus",terrain="ocean",info="",notes="",x=45,y=10,z=0,building=""}
M[#M+1] = {uid=17777,name="Amber Bay",area="gelidus",terrain="ocean",info="",notes="",x=46,y=10,z=0,building=""}
M[#M+1] = {uid=17778,name="Amber Bay",area="gelidus",terrain="ocean",info="",notes="",x=47,y=10,z=0,building=""}
M[#M+1] = {uid=17779,name="Amber Bay",area="gelidus",terrain="ocean",info="",notes="",x=48,y=10,z=0,building=""}
M[#M+1] = {uid=17780,name="Amber Bay",area="gelidus",terrain="ocean",info="",notes="",x=49,y=10,z=0,building=""}
M[#M+1] = {uid=17781,name="Hillsfawdren",area="gelidus",terrain="field4",info="",notes="",x=50,y=10,z=0,building=""}
M[#M+1] = {uid=17782,name="Hillsfawdren",area="gelidus",terrain="field4",info="",notes="",x=51,y=10,z=0,building=""}
M[#M+1] = {uid=17783,name="Meander Bay",area="gelidus",terrain="ocean",info="",notes="",x=52,y=10,z=0,building=""}
M[#M+1] = {uid=17784,name="Meander Bay",area="gelidus",terrain="ocean",info="",notes="",x=53,y=10,z=0,building=""}
M[#M+1] = {uid=17785,name="Meander Bay",area="gelidus",terrain="ocean",info="",notes="",x=54,y=10,z=0,building=""}
M[#M+1] = {uid=17786,name="Sparkling Sands",area="gelidus",terrain="beach",info="",notes="",x=55,y=10,z=0,building=""}
M[#M+1] = {uid=17787,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=56,y=10,z=0,building=""}
M[#M+1] = {uid=17788,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=57,y=10,z=0,building=""}
M[#M+1] = {uid=17789,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=58,y=10,z=0,building=""}
M[#M+1] = {uid=17790,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=59,y=10,z=0,building=""}
M[#M+1] = {uid=17791,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=0,y=11,z=0,building=""}
M[#M+1] = {uid=17792,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=1,y=11,z=0,building=""}
M[#M+1] = {uid=17793,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=2,y=11,z=0,building=""}
M[#M+1] = {uid=17794,name="Nemaja Bay",area="gelidus",terrain="ocean",info="",notes="",x=3,y=11,z=0,building=""}
M[#M+1] = {uid=17795,name="Nemaja Lowlands",area="gelidus",terrain="field",info="",notes="",x=4,y=11,z=0,building=""}
M[#M+1] = {uid=17796,name="Nemaja Lowlands",area="gelidus",terrain="field3",info="",notes="",x=5,y=11,z=0,building=""}
M[#M+1] = {uid=17797,name="Murkwater",area="gelidus",terrain="river",info="",notes="",x=6,y=11,z=0,building=""}
M[#M+1] = {uid=17798,name="Murkwater",area="gelidus",terrain="river",info="",notes="",x=7,y=11,z=0,building=""}
M[#M+1] = {uid=17799,name="Nemaja Lowlands",area="gelidus",terrain="field3",info="",notes="",x=8,y=11,z=0,building=""}
M[#M+1] = {uid=17800,name="Nemaja Lowlands",area="gelidus",terrain="field3",info="",notes="",x=9,y=11,z=0,building=""}
M[#M+1] = {uid=17801,name="Nemaja Lowlands",area="gelidus",terrain="field",info="",notes="",x=10,y=11,z=0,building=""}
M[#M+1] = {uid=17802,name="Carnach",area="gelidus",terrain="field4",info="",notes="",x=11,y=11,z=0,building=""}
M[#M+1] = {uid=17803,name="Carnach Forest",area="gelidus",terrain="forest",info="",notes="",x=12,y=11,z=0,building=""}
M[#M+1] = {uid=17804,name="Carnach",area="gelidus",terrain="field",info="",notes="",x=13,y=11,z=0,building=""}
M[#M+1] = {uid=17805,name="Carnach",area="gelidus",terrain="field",info="",notes="",x=14,y=11,z=0,building=""}
M[#M+1] = {uid=17806,name="Carnach Forest",area="gelidus",terrain="forest",info="",notes="",x=15,y=11,z=0,building=""}
M[#M+1] = {uid=17807,name="Carnach",area="gelidus",terrain="field4",info="",notes="",x=16,y=11,z=0,building=""}
M[#M+1] = {uid=17808,name="Carnach",area="gelidus",terrain="field",info="",notes="",x=17,y=11,z=0,building=""}
M[#M+1] = {uid=17809,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=18,y=11,z=0,building=""}
M[#M+1] = {uid=17810,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=19,y=11,z=0,building=""}
M[#M+1] = {uid=17811,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=20,y=11,z=0,building=""}
M[#M+1] = {uid=17812,name="Krasnokhotsk Plains",area="gelidus",terrain="field4",info="",notes="",x=21,y=11,z=0,building=""}
M[#M+1] = {uid=17813,name="Krasnokhotsk Plains",area="gelidus",terrain="field4",info="",notes="",x=22,y=11,z=0,building=""}
M[#M+1] = {uid=17814,name="Itineris Draconii",area="gelidus",terrain="smallroad",info="",notes="",x=23,y=11,z=0,building=""}
M[#M+1] = {uid=17815,name="Gelidus",area="gelidus",terrain="areaexit",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=17816,name="Kirnalinn Forest",area="gelidus",terrain="forest",info="",notes="",x=25,y=11,z=0,building=""}
M[#M+1] = {uid=17817,name="Kirnalinn Forest",area="gelidus",terrain="forest",info="",notes="",x=26,y=11,z=0,building=""}
M[#M+1] = {uid=17818,name="Loch Neathle",area="gelidus",terrain="ocean",info="",notes="",x=27,y=11,z=0,building=""}
M[#M+1] = {uid=17819,name="Loch Neathle",area="gelidus",terrain="ocean",info="",notes="",x=28,y=11,z=0,building=""}
M[#M+1] = {uid=17820,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=29,y=11,z=0,building=""}
M[#M+1] = {uid=17821,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=30,y=11,z=0,building=""}
M[#M+1] = {uid=17822,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=31,y=11,z=0,building=""}
M[#M+1] = {uid=17823,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=32,y=11,z=0,building=""}
M[#M+1] = {uid=17824,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=33,y=11,z=0,building=""}
M[#M+1] = {uid=17825,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=34,y=11,z=0,building=""}
M[#M+1] = {uid=17826,name="Elmwood Bay",area="gelidus",terrain="ocean",info="",notes="",x=35,y=11,z=0,building=""}
M[#M+1] = {uid=17827,name="Elmwood Harbor",area="gelidus",terrain="forest",info="",notes="",x=36,y=11,z=0,building=""}
M[#M+1] = {uid=17828,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=37,y=11,z=0,building=""}
M[#M+1] = {uid=17829,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=38,y=11,z=0,building=""}
M[#M+1] = {uid=17830,name="Endless Grassfields",area="gelidus",terrain="field3",info="",notes="",x=39,y=11,z=0,building=""}
M[#M+1] = {uid=17831,name="Endless Grassfields",area="gelidus",terrain="field3",info="",notes="",x=40,y=11,z=0,building=""}
M[#M+1] = {uid=17832,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=41,y=11,z=0,building=""}
M[#M+1] = {uid=17833,name="Endless Grassfields",area="gelidus",terrain="field3",info="",notes="",x=42,y=11,z=0,building=""}
M[#M+1] = {uid=17834,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=43,y=11,z=0,building=""}
M[#M+1] = {uid=17835,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=44,y=11,z=0,building=""}
M[#M+1] = {uid=17836,name="Endless Grassfields",area="gelidus",terrain="field3",info="",notes="",x=45,y=11,z=0,building=""}
M[#M+1] = {uid=17837,name="Amber Bay",area="gelidus",terrain="ocean",info="",notes="",x=46,y=11,z=0,building=""}
M[#M+1] = {uid=17838,name="Amber Bay",area="gelidus",terrain="ocean",info="",notes="",x=47,y=11,z=0,building=""}
M[#M+1] = {uid=17839,name="Amber Bay",area="gelidus",terrain="ocean",info="",notes="",x=48,y=11,z=0,building=""}
M[#M+1] = {uid=17840,name="Amber Bay",area="gelidus",terrain="ocean",info="",notes="",x=49,y=11,z=0,building=""}
M[#M+1] = {uid=17841,name="Meander",area="gelidus",terrain="field3",info="",notes="",x=50,y=11,z=0,building=""}
M[#M+1] = {uid=17842,name="Meander",area="gelidus",terrain="field",info="",notes="",x=51,y=11,z=0,building=""}
M[#M+1] = {uid=17843,name="Meander",area="gelidus",terrain="field3",info="",notes="",x=52,y=11,z=0,building=""}
M[#M+1] = {uid=17844,name="Meander Port",area="gelidus",terrain="field4",info="",notes="",x=53,y=11,z=0,building=""}
M[#M+1] = {uid=17845,name="Meander",area="gelidus",terrain="field4",info="",notes="",x=54,y=11,z=0,building=""}
M[#M+1] = {uid=17846,name="Sparkling Sands",area="gelidus",terrain="beach",info="",notes="",x=55,y=11,z=0,building=""}
M[#M+1] = {uid=17847,name="Sparkling Sands",area="gelidus",terrain="beach",info="",notes="",x=56,y=11,z=0,building=""}
M[#M+1] = {uid=17848,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=57,y=11,z=0,building=""}
M[#M+1] = {uid=17849,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=58,y=11,z=0,building=""}
M[#M+1] = {uid=17850,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=59,y=11,z=0,building=""}
M[#M+1] = {uid=17851,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=0,y=12,z=0,building=""}
M[#M+1] = {uid=17852,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=1,y=12,z=0,building=""}
M[#M+1] = {uid=17853,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=2,y=12,z=0,building=""}
M[#M+1] = {uid=17854,name="Sinistra Delta",area="gelidus",terrain="forest",info="",notes="",x=3,y=12,z=0,building=""}
M[#M+1] = {uid=17855,name="Nemaja Lowlands",area="gelidus",terrain="field",info="",notes="",x=4,y=12,z=0,building=""}
M[#M+1] = {uid=17856,name="Murkwater",area="gelidus",terrain="river",info="",notes="",x=5,y=12,z=0,building=""}
M[#M+1] = {uid=17857,name="Gelidus",area="gelidus",terrain="areaexit",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=17858,name="Murkwater",area="gelidus",terrain="river",info="",notes="",x=7,y=12,z=0,building=""}
M[#M+1] = {uid=17859,name="Murkwater",area="gelidus",terrain="river",info="",notes="",x=8,y=12,z=0,building=""}
M[#M+1] = {uid=17860,name="Nemaja Lowlands",area="gelidus",terrain="field",info="",notes="",x=9,y=12,z=0,building=""}
M[#M+1] = {uid=17861,name="Nemaja Lowlands",area="gelidus",terrain="field",info="",notes="",x=10,y=12,z=0,building=""}
M[#M+1] = {uid=17862,name="Carnach",area="gelidus",terrain="field4",info="",notes="",x=11,y=12,z=0,building=""}
M[#M+1] = {uid=17863,name="Carnach",area="gelidus",terrain="field3",info="",notes="",x=12,y=12,z=0,building=""}
M[#M+1] = {uid=17864,name="Carnach Forest",area="gelidus",terrain="forest",info="",notes="",x=13,y=12,z=0,building=""}
M[#M+1] = {uid=17865,name="Carnach Forest",area="gelidus",terrain="forest",info="",notes="",x=14,y=12,z=0,building=""}
M[#M+1] = {uid=17866,name="Carnach",area="gelidus",terrain="field",info="",notes="",x=15,y=12,z=0,building=""}
M[#M+1] = {uid=17867,name="Carnach",area="gelidus",terrain="field3",info="",notes="",x=16,y=12,z=0,building=""}
M[#M+1] = {uid=17868,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=17,y=12,z=0,building=""}
M[#M+1] = {uid=17869,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=18,y=12,z=0,building=""}
M[#M+1] = {uid=17870,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=19,y=12,z=0,building=""}
M[#M+1] = {uid=17871,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=20,y=12,z=0,building=""}
M[#M+1] = {uid=17872,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=21,y=12,z=0,building=""}
M[#M+1] = {uid=17873,name="Krasnokhotsk Plains",area="gelidus",terrain="field4",info="",notes="",x=22,y=12,z=0,building=""}
M[#M+1] = {uid=17874,name="Itineris Draconii",area="gelidus",terrain="smallroad",info="",notes="",x=23,y=12,z=0,building=""}
M[#M+1] = {uid=17875,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=24,y=12,z=0,building=""}
M[#M+1] = {uid=17876,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=25,y=12,z=0,building=""}
M[#M+1] = {uid=17877,name="Loch Neathle",area="gelidus",terrain="ocean",info="",notes="",x=26,y=12,z=0,building=""}
M[#M+1] = {uid=17878,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=27,y=12,z=0,building=""}
M[#M+1] = {uid=17879,name="Juniper Hollow",area="gelidus",terrain="forest",info="",notes="",x=28,y=12,z=0,building=""}
M[#M+1] = {uid=17880,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=29,y=12,z=0,building=""}
M[#M+1] = {uid=17881,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=30,y=12,z=0,building=""}
M[#M+1] = {uid=17882,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=31,y=12,z=0,building=""}
M[#M+1] = {uid=17883,name="Endless Grassfields",area="gelidus",terrain="field3",info="",notes="",x=32,y=12,z=0,building=""}
M[#M+1] = {uid=17884,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=33,y=12,z=0,building=""}
M[#M+1] = {uid=17885,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=34,y=12,z=0,building=""}
M[#M+1] = {uid=17886,name="A Flat Coastline",area="gelidus",terrain="field3",info="",notes="",x=35,y=12,z=0,building=""}
M[#M+1] = {uid=17887,name="Endless Grassfields",area="gelidus",terrain="field3",info="",notes="",x=36,y=12,z=0,building=""}
M[#M+1] = {uid=17888,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=37,y=12,z=0,building=""}
M[#M+1] = {uid=17889,name="Endless Grassfields",area="gelidus",terrain="field3",info="",notes="",x=38,y=12,z=0,building=""}
M[#M+1] = {uid=17890,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=39,y=12,z=0,building=""}
M[#M+1] = {uid=17891,name="Endless Grassfields",area="gelidus",terrain="field3",info="",notes="",x=40,y=12,z=0,building=""}
M[#M+1] = {uid=17892,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=41,y=12,z=0,building=""}
M[#M+1] = {uid=17893,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=42,y=12,z=0,building=""}
M[#M+1] = {uid=17894,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=43,y=12,z=0,building=""}
M[#M+1] = {uid=17895,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=44,y=12,z=0,building=""}
M[#M+1] = {uid=17896,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=45,y=12,z=0,building=""}
M[#M+1] = {uid=17897,name="Ancient Ruins",area="gelidus",terrain="field4",info="",notes="",x=46,y=12,z=0,building=""}
M[#M+1] = {uid=17898,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=47,y=12,z=0,building=""}
M[#M+1] = {uid=17899,name="Meander",area="gelidus",terrain="field",info="",notes="",x=48,y=12,z=0,building=""}
M[#M+1] = {uid=17900,name="Meander",area="gelidus",terrain="field",info="",notes="",x=49,y=12,z=0,building=""}
M[#M+1] = {uid=17901,name="Meander",area="gelidus",terrain="field3",info="",notes="",x=50,y=12,z=0,building=""}
M[#M+1] = {uid=17902,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=51,y=12,z=0,building=""}
M[#M+1] = {uid=17903,name="Meander",area="gelidus",terrain="field3",info="",notes="",x=52,y=12,z=0,building=""}
M[#M+1] = {uid=17904,name="Meander",area="gelidus",terrain="field4",info="",notes="",x=53,y=12,z=0,building=""}
M[#M+1] = {uid=17905,name="Meander",area="gelidus",terrain="field",info="",notes="",x=54,y=12,z=0,building=""}
M[#M+1] = {uid=17906,name="Meander",area="gelidus",terrain="field4",info="",notes="",x=55,y=12,z=0,building=""}
M[#M+1] = {uid=17907,name="Meander",area="gelidus",terrain="field",info="",notes="",x=56,y=12,z=0,building=""}
M[#M+1] = {uid=17908,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=57,y=12,z=0,building=""}
M[#M+1] = {uid=17909,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=58,y=12,z=0,building=""}
M[#M+1] = {uid=17910,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=59,y=12,z=0,building=""}
M[#M+1] = {uid=17911,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=0,y=13,z=0,building=""}
M[#M+1] = {uid=17912,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=1,y=13,z=0,building=""}
M[#M+1] = {uid=17913,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=2,y=13,z=0,building=""}
M[#M+1] = {uid=17914,name="Sinistra Delta",area="gelidus",terrain="forest",info="",notes="",x=3,y=13,z=0,building=""}
M[#M+1] = {uid=17915,name="Sinistra Delta",area="gelidus",terrain="forest",info="",notes="",x=4,y=13,z=0,building=""}
M[#M+1] = {uid=17916,name="Plains of the Frozen Dead",area="gelidus",terrain="field3",info="",notes="",x=5,y=13,z=0,building=""}
M[#M+1] = {uid=17917,name="Murkwater",area="gelidus",terrain="river",info="",notes="",x=6,y=13,z=0,building=""}
M[#M+1] = {uid=17918,name="A Dangerous Waterspout",area="gelidus",terrain="river",info="",notes="",x=7,y=13,z=0,building=""}
M[#M+1] = {uid=17919,name="Murkwater",area="gelidus",terrain="river",info="",notes="",x=8,y=13,z=0,building=""}
M[#M+1] = {uid=17920,name="Huldra Forest",area="gelidus",terrain="forest",info="",notes="",x=9,y=13,z=0,building=""}
M[#M+1] = {uid=17921,name="At the Edge of Huldra Forest",area="gelidus",terrain="field4",info="",notes="",x=10,y=13,z=0,building=""}
M[#M+1] = {uid=17922,name="Carnach",area="gelidus",terrain="field",info="",notes="",x=11,y=13,z=0,building=""}
M[#M+1] = {uid=17923,name="Carnach",area="gelidus",terrain="field",info="",notes="",x=12,y=13,z=0,building=""}
M[#M+1] = {uid=17924,name="Carnach Forest",area="gelidus",terrain="forest",info="",notes="",x=13,y=13,z=0,building=""}
M[#M+1] = {uid=17925,name="Carnach",area="gelidus",terrain="field",info="",notes="",x=14,y=13,z=0,building=""}
M[#M+1] = {uid=17926,name="Carnach",area="gelidus",terrain="field3",info="",notes="",x=15,y=13,z=0,building=""}
M[#M+1] = {uid=17927,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=16,y=13,z=0,building=""}
M[#M+1] = {uid=17928,name="A Trail Through the Forest",area="gelidus",terrain="field4",info="",notes="",x=17,y=13,z=0,building=""}
M[#M+1] = {uid=17929,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=18,y=13,z=0,building=""}
M[#M+1] = {uid=17930,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=19,y=13,z=0,building=""}
M[#M+1] = {uid=17931,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=20,y=13,z=0,building=""}
M[#M+1] = {uid=17932,name="Krasnokhotsk Plains",area="gelidus",terrain="field4",info="",notes="",x=21,y=13,z=0,building=""}
M[#M+1] = {uid=17933,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=22,y=13,z=0,building=""}
M[#M+1] = {uid=17934,name="Itineris Draconii",area="gelidus",terrain="smallroad",info="",notes="",x=23,y=13,z=0,building=""}
M[#M+1] = {uid=17935,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=24,y=13,z=0,building=""}
M[#M+1] = {uid=17936,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=25,y=13,z=0,building=""}
M[#M+1] = {uid=17937,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=26,y=13,z=0,building=""}
M[#M+1] = {uid=17938,name="Krasnokhotsk Plains",area="gelidus",terrain="field4",info="",notes="",x=27,y=13,z=0,building=""}
M[#M+1] = {uid=17939,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=28,y=13,z=0,building=""}
M[#M+1] = {uid=17940,name="Krasnokhotsk Plains",area="gelidus",terrain="field4",info="",notes="",x=29,y=13,z=0,building=""}
M[#M+1] = {uid=17941,name="Krasnokhotsk Plains",area="gelidus",terrain="field4",info="",notes="",x=30,y=13,z=0,building=""}
M[#M+1] = {uid=17942,name="Endless Grassfields",area="gelidus",terrain="field3",info="",notes="",x=31,y=13,z=0,building=""}
M[#M+1] = {uid=17943,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=32,y=13,z=0,building=""}
M[#M+1] = {uid=17944,name="Gelidus",area="gelidus",terrain="areaexit",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=17945,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=34,y=13,z=0,building=""}
M[#M+1] = {uid=17946,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=35,y=13,z=0,building=""}
M[#M+1] = {uid=17947,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=36,y=13,z=0,building=""}
M[#M+1] = {uid=17948,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=37,y=13,z=0,building=""}
M[#M+1] = {uid=17949,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=38,y=13,z=0,building=""}
M[#M+1] = {uid=17950,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=39,y=13,z=0,building=""}
M[#M+1] = {uid=17951,name="Endless Grassfields",area="gelidus",terrain="field3",info="",notes="",x=40,y=13,z=0,building=""}
M[#M+1] = {uid=17952,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=41,y=13,z=0,building=""}
M[#M+1] = {uid=17953,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=42,y=13,z=0,building=""}
M[#M+1] = {uid=17954,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=43,y=13,z=0,building=""}
M[#M+1] = {uid=17955,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=44,y=13,z=0,building=""}
M[#M+1] = {uid=17956,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=45,y=13,z=0,building=""}
M[#M+1] = {uid=17957,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=46,y=13,z=0,building=""}
M[#M+1] = {uid=17958,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=47,y=13,z=0,building=""}
M[#M+1] = {uid=17959,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=48,y=13,z=0,building=""}
M[#M+1] = {uid=17960,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=49,y=13,z=0,building=""}
M[#M+1] = {uid=17961,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=50,y=13,z=0,building=""}
M[#M+1] = {uid=17962,name="Edge of Redwood",area="gelidus",terrain="plain",info="",notes="",x=51,y=13,z=0,building=""}
M[#M+1] = {uid=17963,name="Wyrmspoil Flats",area="gelidus",terrain="plain",info="",notes="",x=52,y=13,z=0,building=""}
M[#M+1] = {uid=17964,name="Wyrmspoil Flats",area="gelidus",terrain="plain",info="",notes="",x=53,y=13,z=0,building=""}
M[#M+1] = {uid=17965,name="Wyrmspoil Flats",area="gelidus",terrain="plain",info="",notes="",x=54,y=13,z=0,building=""}
M[#M+1] = {uid=17966,name="Meander",area="gelidus",terrain="field3",info="",notes="",x=55,y=13,z=0,building=""}
M[#M+1] = {uid=17967,name="Meander",area="gelidus",terrain="field3",info="",notes="",x=56,y=13,z=0,building=""}
M[#M+1] = {uid=17968,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=57,y=13,z=0,building=""}
M[#M+1] = {uid=17969,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=58,y=13,z=0,building=""}
M[#M+1] = {uid=17970,name="Gelidus Continental Shelf",area="gelidus",terrain="ocean",info="",notes="",x=59,y=13,z=0,building=""}
M[#M+1] = {uid=17971,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=0,y=14,z=0,building=""}
M[#M+1] = {uid=17972,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=1,y=14,z=0,building=""}
M[#M+1] = {uid=17973,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=2,y=14,z=0,building=""}
M[#M+1] = {uid=17974,name="Sinistra Delta",area="gelidus",terrain="forest",info="",notes="",x=3,y=14,z=0,building=""}
M[#M+1] = {uid=17975,name="Plains of the Frozen Dead",area="gelidus",terrain="field",info="",notes="",x=4,y=14,z=0,building=""}
M[#M+1] = {uid=17976,name="Plains of the Frozen Dead",area="gelidus",terrain="field4",info="",notes="",x=5,y=14,z=0,building=""}
M[#M+1] = {uid=17977,name="Black Juniper Trail",area="gelidus",terrain="forest",info="",notes="",x=6,y=14,z=0,building=""}
M[#M+1] = {uid=17978,name="Murkwater",area="gelidus",terrain="river",info="",notes="",x=7,y=14,z=0,building=""}
M[#M+1] = {uid=17979,name="The Screaming Plains",area="gelidus",terrain="field3",info="",notes="",x=8,y=14,z=0,building=""}
M[#M+1] = {uid=17980,name="Huldra Forest",area="gelidus",terrain="forest",info="",notes="",x=9,y=14,z=0,building=""}
M[#M+1] = {uid=17981,name="Huldra Forest",area="gelidus",terrain="forest",info="",notes="",x=10,y=14,z=0,building=""}
M[#M+1] = {uid=17982,name="Carnach",area="gelidus",terrain="field4",info="",notes="",x=11,y=14,z=0,building=""}
M[#M+1] = {uid=17983,name="Carnach",area="gelidus",terrain="field3",info="",notes="",x=12,y=14,z=0,building=""}
M[#M+1] = {uid=17984,name="Carnach Forest",area="gelidus",terrain="forest",info="",notes="",x=13,y=14,z=0,building=""}
M[#M+1] = {uid=17985,name="Carnach",area="gelidus",terrain="field",info="",notes="",x=14,y=14,z=0,building=""}
M[#M+1] = {uid=17986,name="Carnach",area="gelidus",terrain="field4",info="",notes="",x=15,y=14,z=0,building=""}
M[#M+1] = {uid=17987,name="A Trail Through the Forest",area="gelidus",terrain="field4",info="",notes="",x=16,y=14,z=0,building=""}
M[#M+1] = {uid=17988,name="A Trail Through the Forest",area="gelidus",terrain="field4",info="",notes="",x=17,y=14,z=0,building=""}
M[#M+1] = {uid=17989,name="A Huge Pasture",area="gelidus",terrain="field",info="",notes="",x=18,y=14,z=0,building=""}
M[#M+1] = {uid=17990,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=19,y=14,z=0,building=""}
M[#M+1] = {uid=17991,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=20,y=14,z=0,building=""}
M[#M+1] = {uid=17992,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=21,y=14,z=0,building=""}
M[#M+1] = {uid=17993,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=22,y=14,z=0,building=""}
M[#M+1] = {uid=17994,name="Itineris Draconii",area="gelidus",terrain="smallroad",info="",notes="",x=23,y=14,z=0,building=""}
M[#M+1] = {uid=17995,name="Krasnokhotsk Plains",area="gelidus",terrain="field4",info="",notes="",x=24,y=14,z=0,building=""}
M[#M+1] = {uid=17996,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=25,y=14,z=0,building=""}
M[#M+1] = {uid=17997,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=26,y=14,z=0,building=""}
M[#M+1] = {uid=17998,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=27,y=14,z=0,building=""}
M[#M+1] = {uid=17999,name="Krasnokhotsk Plains",area="gelidus",terrain="field4",info="",notes="",x=28,y=14,z=0,building=""}
M[#M+1] = {uid=18000,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=29,y=14,z=0,building=""}
M[#M+1] = {uid=18001,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=30,y=14,z=0,building=""}
M[#M+1] = {uid=18002,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=31,y=14,z=0,building=""}
M[#M+1] = {uid=18003,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=32,y=14,z=0,building=""}
M[#M+1] = {uid=18004,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=33,y=14,z=0,building=""}
M[#M+1] = {uid=18005,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=34,y=14,z=0,building=""}
M[#M+1] = {uid=18006,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=35,y=14,z=0,building=""}
M[#M+1] = {uid=18007,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=36,y=14,z=0,building=""}
M[#M+1] = {uid=18008,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=37,y=14,z=0,building=""}
M[#M+1] = {uid=18009,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=38,y=14,z=0,building=""}
M[#M+1] = {uid=18010,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=39,y=14,z=0,building=""}
M[#M+1] = {uid=18011,name="Endless Grassfields",area="gelidus",terrain="field3",info="",notes="",x=40,y=14,z=0,building=""}
M[#M+1] = {uid=18012,name="Endless Grassfields",area="gelidus",terrain="field3",info="",notes="",x=41,y=14,z=0,building=""}
M[#M+1] = {uid=18013,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=42,y=14,z=0,building=""}
M[#M+1] = {uid=18014,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=43,y=14,z=0,building=""}
M[#M+1] = {uid=18015,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=44,y=14,z=0,building=""}
M[#M+1] = {uid=18016,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=45,y=14,z=0,building=""}
M[#M+1] = {uid=18017,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=46,y=14,z=0,building=""}
M[#M+1] = {uid=18018,name="Cradle of Redwood",area="gelidus",terrain="forest",info="",notes="",x=47,y=14,z=0,building=""}
M[#M+1] = {uid=18019,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=48,y=14,z=0,building=""}
M[#M+1] = {uid=18020,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=49,y=14,z=0,building=""}
M[#M+1] = {uid=18021,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=50,y=14,z=0,building=""}
M[#M+1] = {uid=18022,name="Edge of Redwood",area="gelidus",terrain="plain",info="",notes="",x=51,y=14,z=0,building=""}
M[#M+1] = {uid=18023,name="Wyrmspoil Flats",area="gelidus",terrain="plain",info="",notes="",x=52,y=14,z=0,building=""}
M[#M+1] = {uid=18024,name="Wyrmspoil Flats",area="gelidus",terrain="plain",info="",notes="",x=53,y=14,z=0,building=""}
M[#M+1] = {uid=18025,name="Wyrmspoil Flats",area="gelidus",terrain="plain",info="",notes="",x=54,y=14,z=0,building=""}
M[#M+1] = {uid=18026,name="Wyrmspoil Flats",area="gelidus",terrain="plain",info="",notes="",x=55,y=14,z=0,building=""}
M[#M+1] = {uid=18027,name="Meander",area="gelidus",terrain="field",info="",notes="",x=56,y=14,z=0,building=""}
M[#M+1] = {uid=18028,name="Meander",area="gelidus",terrain="field",info="",notes="",x=57,y=14,z=0,building=""}
M[#M+1] = {uid=18029,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=58,y=14,z=0,building=""}
M[#M+1] = {uid=18030,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=59,y=14,z=0,building=""}
M[#M+1] = {uid=18031,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=0,y=15,z=0,building=""}
M[#M+1] = {uid=18032,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=1,y=15,z=0,building=""}
M[#M+1] = {uid=18033,name="Plains of the Frozen Dead",area="gelidus",terrain="field3",info="",notes="",x=2,y=15,z=0,building=""}
M[#M+1] = {uid=18034,name="Plains of the Frozen Dead",area="gelidus",terrain="field",info="",notes="",x=3,y=15,z=0,building=""}
M[#M+1] = {uid=18035,name="An Onyx Obelisk",area="gelidus",terrain="field4",info="",notes="",x=4,y=15,z=0,building=""}
M[#M+1] = {uid=18036,name="Plains of the Frozen Dead",area="gelidus",terrain="field3",info="",notes="",x=5,y=15,z=0,building=""}
M[#M+1] = {uid=18037,name="Black Juniper Trail",area="gelidus",terrain="forest",info="",notes="",x=6,y=15,z=0,building=""}
M[#M+1] = {uid=18038,name="The Screaming Plains",area="gelidus",terrain="field",info="",notes="",x=7,y=15,z=0,building=""}
M[#M+1] = {uid=18039,name="The Screaming Plains",area="gelidus",terrain="field3",info="",notes="",x=8,y=15,z=0,building=""}
M[#M+1] = {uid=18040,name="Huldra Forest",area="gelidus",terrain="forest",info="",notes="",x=9,y=15,z=0,building=""}
M[#M+1] = {uid=18041,name="Huldra Glade",area="gelidus",terrain="areaexit",info="",notes="",x=10,y=15,z=0,building=""}
M[#M+1] = {uid=18042,name="Huldra Forest",area="gelidus",terrain="forest",info="",notes="",x=11,y=15,z=0,building=""}
M[#M+1] = {uid=18043,name="Carnach",area="gelidus",terrain="field4",info="",notes="",x=12,y=15,z=0,building=""}
M[#M+1] = {uid=18044,name="Carnach",area="gelidus",terrain="field4",info="",notes="",x=13,y=15,z=0,building=""}
M[#M+1] = {uid=18045,name="Carnach",area="gelidus",terrain="field4",info="",notes="",x=14,y=15,z=0,building=""}
M[#M+1] = {uid=18046,name="Carnach",area="gelidus",terrain="field4",info="",notes="",x=15,y=15,z=0,building=""}
M[#M+1] = {uid=18047,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=16,y=15,z=0,building=""}
M[#M+1] = {uid=18048,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=17,y=15,z=0,building=""}
M[#M+1] = {uid=18049,name="A Trail Through the Forest",area="gelidus",terrain="field",info="",notes="",x=18,y=15,z=0,building=""}
M[#M+1] = {uid=18050,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=19,y=15,z=0,building=""}
M[#M+1] = {uid=18051,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=20,y=15,z=0,building=""}
M[#M+1] = {uid=18052,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=21,y=15,z=0,building=""}
M[#M+1] = {uid=18053,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=22,y=15,z=0,building=""}
M[#M+1] = {uid=18054,name="Krasnokhotsk Plains",area="gelidus",terrain="field2",info="",notes="",x=23,y=15,z=0,building=""}
M[#M+1] = {uid=18055,name="Krasnokhotsk Plains",area="gelidus",terrain="field4",info="",notes="",x=24,y=15,z=0,building=""}
M[#M+1] = {uid=18056,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=25,y=15,z=0,building=""}
M[#M+1] = {uid=18057,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=26,y=15,z=0,building=""}
M[#M+1] = {uid=18058,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=27,y=15,z=0,building=""}
M[#M+1] = {uid=18059,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=28,y=15,z=0,building=""}
M[#M+1] = {uid=18060,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=29,y=15,z=0,building=""}
M[#M+1] = {uid=18061,name="Kapralov Grove",area="gelidus",terrain="forest",info="",notes="",x=30,y=15,z=0,building=""}
M[#M+1] = {uid=18062,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=31,y=15,z=0,building=""}
M[#M+1] = {uid=18063,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=32,y=15,z=0,building=""}
M[#M+1] = {uid=18064,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=33,y=15,z=0,building=""}
M[#M+1] = {uid=18065,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=34,y=15,z=0,building=""}
M[#M+1] = {uid=18066,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=35,y=15,z=0,building=""}
M[#M+1] = {uid=18067,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=36,y=15,z=0,building=""}
M[#M+1] = {uid=18068,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=37,y=15,z=0,building=""}
M[#M+1] = {uid=18069,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=38,y=15,z=0,building=""}
M[#M+1] = {uid=18070,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=39,y=15,z=0,building=""}
M[#M+1] = {uid=18071,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=40,y=15,z=0,building=""}
M[#M+1] = {uid=18072,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=41,y=15,z=0,building=""}
M[#M+1] = {uid=18073,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=42,y=15,z=0,building=""}
M[#M+1] = {uid=18074,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=43,y=15,z=0,building=""}
M[#M+1] = {uid=18075,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=44,y=15,z=0,building=""}
M[#M+1] = {uid=18076,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=45,y=15,z=0,building=""}
M[#M+1] = {uid=18077,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=46,y=15,z=0,building=""}
M[#M+1] = {uid=18078,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=47,y=15,z=0,building=""}
M[#M+1] = {uid=18079,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=48,y=15,z=0,building=""}
M[#M+1] = {uid=18080,name="An Overgrown Cairn",area="gelidus",terrain="forest",info="",notes="",x=49,y=15,z=0,building=""}
M[#M+1] = {uid=18081,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=50,y=15,z=0,building=""}
M[#M+1] = {uid=18082,name="Nordaustlandet",area="gelidus",terrain="field3",info="",notes="",x=51,y=15,z=0,building=""}
M[#M+1] = {uid=18083,name="Wyrmspoil Flats",area="gelidus",terrain="plain",info="",notes="",x=52,y=15,z=0,building=""}
M[#M+1] = {uid=18084,name="Wyrmspoil Flats",area="gelidus",terrain="plain",info="",notes="",x=53,y=15,z=0,building=""}
M[#M+1] = {uid=18085,name="Wyrmspoil Flats",area="gelidus",terrain="plain",info="",notes="",x=54,y=15,z=0,building=""}
M[#M+1] = {uid=18086,name="Wyrmspoil Flats",area="gelidus",terrain="plain",info="",notes="",x=55,y=15,z=0,building=""}
M[#M+1] = {uid=18087,name="Wyrmspoil Flats",area="gelidus",terrain="plain",info="",notes="",x=56,y=15,z=0,building=""}
M[#M+1] = {uid=18088,name="Meander",area="gelidus",terrain="field3",info="",notes="",x=57,y=15,z=0,building=""}
M[#M+1] = {uid=18089,name="Meander",area="gelidus",terrain="field",info="",notes="",x=58,y=15,z=0,building=""}
M[#M+1] = {uid=18090,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=59,y=15,z=0,building=""}
M[#M+1] = {uid=18091,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=0,y=16,z=0,building=""}
M[#M+1] = {uid=18092,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=1,y=16,z=0,building=""}
M[#M+1] = {uid=18093,name="Sleeping Hollow",area="gelidus",terrain="forest",info="",notes="",x=2,y=16,z=0,building=""}
M[#M+1] = {uid=18094,name="Plains of the Frozen Dead",area="gelidus",terrain="field3",info="",notes="",x=3,y=16,z=0,building=""}
M[#M+1] = {uid=18095,name="Plains of the Frozen Dead",area="gelidus",terrain="field",info="",notes="",x=4,y=16,z=0,building=""}
M[#M+1] = {uid=18096,name="Plains of the Frozen Dead",area="gelidus",terrain="field",info="",notes="",x=5,y=16,z=0,building=""}
M[#M+1] = {uid=18097,name="Plains of the Frozen Dead",area="gelidus",terrain="field",info="",notes="",x=6,y=16,z=0,building=""}
M[#M+1] = {uid=18098,name="Black Juniper Trail",area="gelidus",terrain="forest",info="",notes="",x=7,y=16,z=0,building=""}
M[#M+1] = {uid=18099,name="The Screaming Plains",area="gelidus",terrain="field",info="",notes="",x=8,y=16,z=0,building=""}
M[#M+1] = {uid=18100,name="Huldra Forest",area="gelidus",terrain="forest",info="",notes="",x=9,y=16,z=0,building=""}
M[#M+1] = {uid=18101,name="Huldra Forest",area="gelidus",terrain="forest",info="",notes="",x=10,y=16,z=0,building=""}
M[#M+1] = {uid=18102,name="Huldra Forest",area="gelidus",terrain="forest",info="",notes="",x=11,y=16,z=0,building=""}
M[#M+1] = {uid=18103,name="Carnach",area="gelidus",terrain="field3",info="",notes="",x=12,y=16,z=0,building=""}
M[#M+1] = {uid=18104,name="Carnach",area="gelidus",terrain="field",info="",notes="",x=13,y=16,z=0,building=""}
M[#M+1] = {uid=18105,name="Carnach",area="gelidus",terrain="field",info="",notes="",x=14,y=16,z=0,building=""}
M[#M+1] = {uid=18106,name="Kentauria",area="gelidus",terrain="field3",info="",notes="",x=15,y=16,z=0,building=""}
M[#M+1] = {uid=18107,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=16,y=16,z=0,building=""}
M[#M+1] = {uid=18108,name="A Trail Through the Forest",area="gelidus",terrain="field4",info="",notes="",x=17,y=16,z=0,building=""}
M[#M+1] = {uid=18109,name="A Trail Through the Forest",area="gelidus",terrain="field",info="",notes="",x=18,y=16,z=0,building=""}
M[#M+1] = {uid=18110,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=19,y=16,z=0,building=""}
M[#M+1] = {uid=18111,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=20,y=16,z=0,building=""}
M[#M+1] = {uid=18112,name="Forest Argentum",area="gelidus",terrain="forest",info="",notes="",x=21,y=16,z=0,building=""}
M[#M+1] = {uid=18113,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=22,y=16,z=0,building=""}
M[#M+1] = {uid=18114,name="Krasnokhotsk Plains",area="gelidus",terrain="field4",info="",notes="",x=23,y=16,z=0,building=""}
M[#M+1] = {uid=18115,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=24,y=16,z=0,building=""}
M[#M+1] = {uid=18116,name="Krasnokhotsk Plains",area="gelidus",terrain="field",info="",notes="",x=25,y=16,z=0,building=""}
M[#M+1] = {uid=18117,name="Krasnokhotsk Plains",area="gelidus",terrain="field3",info="",notes="",x=26,y=16,z=0,building=""}
M[#M+1] = {uid=18118,name="Astarchia",area="gelidus",terrain="snow",info="",notes="",x=27,y=16,z=0,building=""}
M[#M+1] = {uid=18119,name="Astarchia",area="gelidus",terrain="snow",info="",notes="",x=28,y=16,z=0,building=""}
M[#M+1] = {uid=18120,name="Astarchia",area="gelidus",terrain="snow",info="",notes="",x=29,y=16,z=0,building=""}
M[#M+1] = {uid=18121,name="Krasnokhotsk Plains",area="gelidus",terrain="field4",info="",notes="",x=30,y=16,z=0,building=""}
M[#M+1] = {uid=18122,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=31,y=16,z=0,building=""}
M[#M+1] = {uid=18123,name="Endless Grassfields",area="gelidus",terrain="field3",info="",notes="",x=32,y=16,z=0,building=""}
M[#M+1] = {uid=18124,name="Snowfields",area="gelidus",terrain="snow",info="",notes="",x=33,y=16,z=0,building=""}
M[#M+1] = {uid=18125,name="Snowfields",area="gelidus",terrain="snow",info="",notes="",x=34,y=16,z=0,building=""}
M[#M+1] = {uid=18126,name="Snowfields",area="gelidus",terrain="snow",info="",notes="",x=35,y=16,z=0,building=""}
M[#M+1] = {uid=18127,name="Endless Grassfields",area="gelidus",terrain="field2",info="",notes="",x=36,y=16,z=0,building=""}
M[#M+1] = {uid=18128,name="Endless Grassfields",area="gelidus",terrain="field3",info="",notes="",x=37,y=16,z=0,building=""}
M[#M+1] = {uid=18129,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=38,y=16,z=0,building=""}
M[#M+1] = {uid=18130,name="Endless Grassfields",area="gelidus",terrain="field",info="",notes="",x=39,y=16,z=0,building=""}
M[#M+1] = {uid=18131,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=40,y=16,z=0,building=""}
M[#M+1] = {uid=18132,name="Endless Grassfields",area="gelidus",terrain="field3",info="",notes="",x=41,y=16,z=0,building=""}
M[#M+1] = {uid=18133,name="Endless Grassfields",area="gelidus",terrain="field4",info="",notes="",x=42,y=16,z=0,building=""}
M[#M+1] = {uid=18134,name="Nordaustlandet",area="gelidus",terrain="field3",info="",notes="",x=43,y=16,z=0,building=""}
M[#M+1] = {uid=18135,name="Nordaustlandet",area="gelidus",terrain="field4",info="",notes="",x=44,y=16,z=0,building=""}
M[#M+1] = {uid=18136,name="Nordaustlandet",area="gelidus",terrain="field",info="",notes="",x=45,y=16,z=0,building=""}
M[#M+1] = {uid=18137,name="Nordaustlandet",area="gelidus",terrain="field",info="",notes="",x=46,y=16,z=0,building=""}
M[#M+1] = {uid=18138,name="Nordaustlandet",area="gelidus",terrain="field",info="",notes="",x=47,y=16,z=0,building=""}
M[#M+1] = {uid=18139,name="Nordaustlandet",area="gelidus",terrain="field4",info="",notes="",x=48,y=16,z=0,building=""}
M[#M+1] = {uid=18140,name="Redwood",area="gelidus",terrain="forest",info="",notes="",x=49,y=16,z=0,building=""}
M[#M+1] = {uid=18141,name="Nordaustlandet",area="gelidus",terrain="field3",info="",notes="",x=50,y=16,z=0,building=""}
M[#M+1] = {uid=18142,name="Nordaustlandet",area="gelidus",terrain="field4",info="",notes="",x=51,y=16,z=0,building=""}
M[#M+1] = {uid=18143,name="Nordaustlandet",area="gelidus",terrain="field4",info="",notes="",x=52,y=16,z=0,building=""}
M[#M+1] = {uid=18144,name="Nordaustlandet",area="gelidus",terrain="field",info="",notes="",x=53,y=16,z=0,building=""}
M[#M+1] = {uid=18145,name="Nordaustlandet",area="gelidus",terrain="field3",info="",notes="",x=54,y=16,z=0,building=""}
M[#M+1] = {uid=18146,name="Wyrmspoil Flats",area="gelidus",terrain="plain",info="",notes="",x=55,y=16,z=0,building=""}
M[#M+1] = {uid=18147,name="Wyrmspoil Flats",area="gelidus",terrain="plain",info="",notes="",x=56,y=16,z=0,building=""}
M[#M+1] = {uid=18148,name="Wyrmspoil Flats",area="gelidus",terrain="plain",info="",notes="",x=57,y=16,z=0,building=""}
M[#M+1] = {uid=18149,name="Meander",area="gelidus",terrain="field",info="",notes="",x=58,y=16,z=0,building=""}
M[#M+1] = {uid=18150,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=59,y=16,z=0,building=""}
M[#M+1] = {uid=18151,name="Haloisi Ocean",area="gelidus",terrain="ocean",info="",notes="",x=0,y=17,z=0,building=""}
M[#M+1] = {uid=18152,name="Gelidus Coastal Water",area="gelidus",terrain="ocean",info="",notes="",x=1,y=17,z=0,building=""}
M[#M+1] = {uid=18153,name="Plains of the Frozen Dead",area="gelidus",terrain="field",info="",notes="",x=2,y=17,z=0,building=""}
M[#M+1] = {uid=18154,name="Plains of the Frozen Dead",area="gelidus",terrain="field",info="",notes="",x=3,y=17,z=0,building=""}
M[#M+1] = {uid=18155,name="Steinsvik Badlands",area="gelidus",terrain="snow",info="",notes="",x=4,y=17,z=0,building=""}
M[#M+1] = {uid=18156,name="Steinsvik Badlands",area="gelidus",terrain="snow",info="",notes="",x=5,y=17,z=0,building=""}
M[#M+1] = {uid=18157,name="Steinsvik Badlands",area="gelidus",terrain="snow",info="",notes="",x=6,y=17,z=0,building=""}
M[#M+1] = {uid=18158,name="The Screaming Plains",area="gelidus",terrain="field3",info="",notes="",x=7,y=17,z=0,building=""}
M[#M+1] = {uid=18159,name="The Screaming Plains",area="gelidus",terrain="field3",info="",notes="",x=8,y=17,z=0,building=""}
M[#M+1] = {uid=18160,name="Huldra Forest",area="gelidus",terrain="forest",info="",notes="",x=9,y=17,z=0,building=""}
M[#M+1] = {uid=18161,name="Megara Snowfields",area="gelidus",terrain="snow",info="",notes="",x=10,y=17,z=0,building=""}
M[#M+1] = {uid=18162,name="Megara Snowfields",area="gelidus",terrain="snow",info="",notes="",x=11,y=17,z=0,building=""}
M[#M+1] = {uid=18163,name="Megara Snowfields",area="gelidus",terrain="snow",info="",notes="",x=12,y=17,z=0,building=""}
M[#M+1] = {uid=18164,name="Megara Snowfields",area="gelidus",terrain="snow",info="",notes="",x=13,y=17,z=0,building=""}
M[#M+1] = {uid=18165,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=14,y=17,z=0,building=""}
M[#M+1] = {uid=18166,name="Kentauria",area="gelidus",terrain="field4",info="",notes="",x=15,y=17,z=0,building=""}
M[#M+1] = {uid=18167,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=16,y=17,z=0,building=""}
M[#M+1] = {uid=18168,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=17,y=17,z=0,building=""}
M[#M+1] = {uid=18169,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=18,y=17,z=0,building=""}
M[#M+1] = {uid=18170,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=19,y=17,z=0,building=""}
M[#M+1] = {uid=18171,name="Kentauria",area="gelidus",terrain="field",info="",notes="",x=20,y=17,z=0,building=""}
M[#M+1] = {uid=18172,name="Iceridge Snowfields",area="gelidus",terrain="snow",info="",notes="",x=21,y=17,z=0,building=""}
M[#M+1] = {uid=18173,name="Itineris Draconii",area="gelidus",terrain="trail_ew",info="",notes="",x=22,y=17,z=0,building=""}
return M
