-- generated by tools/import-mushmap.py — do not edit
-- rooms 751..1500
local M = {}
M[#M+1] = {uid=1619,name="A small hallway",area="slaughter",terrain="bloodyhall",info="",notes="",x=8,y=-3,z=0,building=""}
M[#M+1] = {uid=1620,name="The Hallway Ends",area="slaughter",terrain="bloodyhall",info="",notes="",x=7,y=-3,z=0,building=""}
M[#M+1] = {uid=1621,name="The Pit",area="slaughter",terrain="alley",info="",notes="",x=7,y=-2,z=0,building=""}
M[#M+1] = {uid=1622,name="Shrine",area="slaughter",terrain="bloodyroom",info="",notes="",x=10,y=-4,z=0,building=""}
M[#M+1] = {uid=1623,name="Second Floor Landing",area="slaughter",terrain="bloodyhall",info="",notes="",x=9,y=-5,z=1,building=""}
M[#M+1] = {uid=1624,name="The Hallway Continues",area="slaughter",terrain="bloodyhall",info="",notes="",x=9,y=-4,z=1,building=""}
M[#M+1] = {uid=1627,name="The Hallway",area="slaughter",terrain="bloodyhall",info="",notes="",x=9,y=-3,z=1,building=""}
M[#M+1] = {uid=1629,name="The Hallway",area="slaughter",terrain="bloodyhall",info="",notes="",x=9,y=-2,z=1,building=""}
M[#M+1] = {uid=1674,name="Inside a Crowded Hovel",area="hoard",terrain="inside",info="",notes="",x=10,y=21,z=0,building=""}
M[#M+1] = {uid=1675,name="The Human Refugee Camp",area="hoard",terrain="snow",info="",notes="",x=9,y=21,z=0,building=""}
M[#M+1] = {uid=1676,name="Inside a Crowded Shelter",area="hoard",terrain="inside",info="",notes="",x=9,y=22,z=0,building=""}
M[#M+1] = {uid=1677,name="Approaching the Camp",area="hoard",terrain="snow",info="",notes="",x=8,y=21,z=0,building=""}
M[#M+1] = {uid=1678,name="At the Foot of the Volcano",area="hoard",terrain="snow",info="",notes="",x=9,y=20,z=0,building=""}
M[#M+1] = {uid=1679,name="On a Snowbound Trail",area="hoard",terrain="icehills",info="",notes="",x=10,y=20,z=0,building=""}
M[#M+1] = {uid=1680,name="On a Bleak Trail",area="hoard",terrain="icehills",info="",notes="",x=11,y=20,z=0,building=""}
M[#M+1] = {uid=1681,name="On a Treacherous Trail",area="hoard",terrain="icehills",info="",notes="",x=11,y=20,z=1,building=""}
M[#M+1] = {uid=1682,name="On a Rugged Trail",area="hoard",terrain="icehills",info="",notes="",x=10,y=20,z=1,building=""}
M[#M+1] = {uid=1683,name="On a Rocky Trail",area="hoard",terrain="icehills",info="",notes="",x=9,y=20,z=1,building=""}
M[#M+1] = {uid=1684,name="On a Deadly Trail",area="hoard",terrain="icehills",info="",notes="",x=9,y=20,z=2,building=""}
M[#M+1] = {uid=1685,name="On a Windswept Trail",area="hoard",terrain="icehills",info="",notes="",x=10,y=20,z=2,building=""}
M[#M+1] = {uid=1686,name="At the Volcano's Summit",area="hoard",terrain="icehills",info="",notes="",x=10,y=20,z=3,building=""}
M[#M+1] = {uid=1687,name="The Rim of the Crater",area="hoard",terrain="snow",info="",notes="",x=10,y=19,z=3,building=""}
M[#M+1] = {uid=1688,name="Within the Crater",area="hoard",terrain="icehills",info="",notes="",x=10,y=19,z=2,building=""}
M[#M+1] = {uid=1689,name="Within the Crater",area="hoard",terrain="snow",info="",notes="",x=11,y=19,z=2,building=""}
M[#M+1] = {uid=1690,name="Within the Crater",area="hoard",terrain="snow",info="",notes="",x=10,y=20,z=2,building=""}
M[#M+1] = {uid=1691,name="Before the Massive Gates",area="hoard",terrain="snow",info="",notes="",x=11,y=20,z=2,building=""}
M[#M+1] = {uid=1692,name="Entryway to the City",area="hoard",terrain="city",info="",notes="",x=12,y=20,z=2,building=""}
M[#M+1] = {uid=1693,name="At Street's Beginning",area="hoard",terrain="city",info="",notes="",x=12,y=20,z=1,building=""}
M[#M+1] = {uid=1694,name="A Sober Street Corner",area="hoard",terrain="city",info="",notes="",x=12,y=19,z=1,building=""}
M[#M+1] = {uid=1695,name="In a Dwarven Residence",area="hoard",terrain="inside",info="",notes="",x=13,y=19,z=1,building=""}
M[#M+1] = {uid=1696,name="At a Grand Intersection",area="hoard",terrain="city",info="",notes="",x=11,y=19,z=1,building=""}
M[#M+1] = {uid=1697,name="A Dwarven Garrison",area="hoard",terrain="office",info="",notes="",x=11,y=18,z=1,building=""}
M[#M+1] = {uid=1698,name="The Palace Entrance",area="hoard",terrain="redcarpet",info="",notes="",x=11,y=20,z=1,building=""}
M[#M+1] = {uid=1699,name="A Striking Street Corner",area="hoard",terrain="city",info="",notes="",x=10,y=19,z=1,building=""}
M[#M+1] = {uid=1700,name="In a Dwarven Home",area="hoard",terrain="inside",info="",notes="",x=9,y=19,z=1,building=""}
M[#M+1] = {uid=1701,name="On a Gridlocked Street",area="hoard",terrain="city",info="",notes="",x=10,y=20,z=1,building=""}
M[#M+1] = {uid=1702,name="A Fungal Street Corner",area="hoard",terrain="city",info="",notes="",x=10,y=21,z=1,building=""}
M[#M+1] = {uid=1703,name="In a Dwarven Dwelling",area="hoard",terrain="inside",info="",notes="",x=9,y=21,z=1,building=""}
M[#M+1] = {uid=1704,name="On a Busy Street",area="hoard",terrain="city",info="",notes="",x=11,y=21,z=1,building=""}
M[#M+1] = {uid=1705,name="A General Store",area="hoard",terrain="hallway",info="safe,shop",notes="",x=11,y=22,z=1,building=""}
M[#M+1] = {uid=1706,name="A Sooty Street Corner",area="hoard",terrain="city",info="",notes="",x=12,y=21,z=1,building=""}
M[#M+1] = {uid=1707,name="A Makeshift Dwarven Home",area="hoard",terrain="inside",info="",notes="",x=13,y=21,z=1,building=""}
M[#M+1] = {uid=1708,name="On a Seedy Street",area="hoard",terrain="city",info="",notes="",x=12,y=20,z=1,building=""}
M[#M+1] = {uid=1709,name="A Spotless Street Corner",area="hoard",terrain="city",info="",notes="",x=12,y=19,z=1,building=""}
M[#M+1] = {uid=1710,name="The Home of Nanna Dwarf",area="hoard",terrain="inside",info="",notes="",x=13,y=19,z=1,building=""}
M[#M+1] = {uid=1711,name="On A Noisy Street",area="hoard",terrain="city",info="",notes="",x=11,y=19,z=1,building=""}
M[#M+1] = {uid=1712,name="A Smithy",area="hoard",terrain="hallway",info="safe,shop",notes="",x=11,y=18,z=1,building=""}
M[#M+1] = {uid=1713,name="A Neglected Street Corner",area="hoard",terrain="city",info="",notes="",x=10,y=19,z=1,building=""}
M[#M+1] = {uid=1714,name="A Sundered Dwarven Home",area="hoard",terrain="inside",info="",notes="",x=9,y=19,z=1,building=""}
M[#M+1] = {uid=1715,name="At Street's End",area="hoard",terrain="city",info="",notes="",x=10,y=20,z=1,building=""}
M[#M+1] = {uid=1716,name="In the Great Hall",area="hoard",terrain="redcarpet",info="",notes="",x=11,y=20,z=0,building=""}
M[#M+1] = {uid=1717,name="An Opulent Throne Room",area="hoard",terrain="palace_room",info="",notes="",x=11,y=21,z=0,building=""}
M[#M+1] = {uid=1718,name="The Entrance to the Gem Mines",area="hoard",terrain="underground",info="",notes="",x=10,y=21,z=1,building=""}
M[#M+1] = {uid=1719,name="An Endless Mine Shaft",area="hoard",terrain="underground",info="",notes="",x=10,y=21,z=0,building=""}
M[#M+1] = {uid=1720,name="The Bottom of the Mine Shaft",area="hoard",terrain="underground",info="",notes="",x=10,y=21,z=-1,building=""}
M[#M+1] = {uid=1721,name="A Narrow Tunnel",area="hoard",terrain="underground",info="",notes="",x=11,y=21,z=-1,building=""}
M[#M+1] = {uid=1722,name="A Precarious Ledge",area="hoard",terrain="underground",info="",notes="",x=12,y=21,z=-1,building=""}
M[#M+1] = {uid=1723,name="The Heart of the Volcano",area="hoard",terrain="underground",info="",notes="",x=12,y=22,z=-1,building=""}
M[#M+1] = {uid=1724,name="A Claustrophobic Space",area="hoard",terrain="underground",info="",notes="",x=10,y=22,z=-1,building=""}
M[#M+1] = {uid=1725,name="Before a Mine Collapse",area="hoard",terrain="underground",info="",notes="",x=10,y=23,z=-1,building=""}
M[#M+1] = {uid=1726,name="Pools of Lava",area="hoard",terrain="hellfountain",info="",notes="",x=9,y=23,z=-1,building=""}
M[#M+1] = {uid=1727,name="Inside a Magma Tube",area="hoard",terrain="hell1",info="",notes="",x=9,y=23,z=-2,building=""}
M[#M+1] = {uid=1728,name="The Burning Core",area="hoard",terrain="hellinside",info="",notes="",x=9,y=23,z=-3,building=""}
M[#M+1] = {uid=1767,name="Chamber of Darkness",area="deathtrap",terrain="inside",info="pk,shop",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=1772,name="Chamber of Chaos",area="deathtrap",terrain="underground",info="pk",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=1773,name="Tower of the Magi",area="deathtrap",terrain="inside",info="maze",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=1774,name="Tower of the Magi",area="deathtrap",terrain="inside",info="maze",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=1775,name="Tower of the Magi",area="deathtrap",terrain="inside",info="maze",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=1776,name="Tower of the Magi",area="deathtrap",terrain="inside",info="maze",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=1785,name="Sanctuary of the Clerics",area="deathtrap",terrain="inside",info="maze",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=1789,name="Back-Alley of the Thieves",area="deathtrap",terrain="city",info="maze",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=1790,name="Back-Alley of the Thieves",area="deathtrap",terrain="city",info="maze",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=1791,name="Back-Alley of the Thieves",area="deathtrap",terrain="city",info="maze",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=1792,name="Back-Alley of the Thieves",area="deathtrap",terrain="city",info="maze",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=1799,name="A dungeon hallway",area="deathtrap",terrain="inside",info="pk",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=1800,name="A dungeon hallway",area="deathtrap",terrain="inside",info="pk",notes="",x=48,y=0,z=0,building=""}
M[#M+1] = {uid=1801,name="A dungeon hallway",area="deathtrap",terrain="inside",info="pk",notes="",x=48,y=-1,z=0,building=""}
M[#M+1] = {uid=1808,name="Before the guards",area="deathtrap",terrain="inside",info="pk",notes="",x=48,y=-1,z=1,building=""}
M[#M+1] = {uid=1966,name="The Storm Cruiser, Tempest",area="lemdagor",terrain="inside",info="",notes="",x=26,y=28,z=0,building=""}
M[#M+1] = {uid=1967,name="A Shiny Hallway",area="lemdagor",terrain="hallway",info="",notes="",x=27,y=28,z=0,building=""}
M[#M+1] = {uid=1968,name="The Imaginarium",area="lemdagor",terrain="inside",info="",notes="",x=28,y=28,z=0,building=""}
M[#M+1] = {uid=1969,name="A Shiny Hallway",area="lemdagor",terrain="hallway",info="",notes="",x=27,y=29,z=0,building=""}
M[#M+1] = {uid=1970,name="The Main Engineer Room",area="lemdagor",terrain="inside",info="",notes="",x=28,y=29,z=0,building=""}
M[#M+1] = {uid=1971,name="The Sick Bay",area="lemdagor",terrain="inside",info="",notes="",x=26,y=29,z=0,building=""}
M[#M+1] = {uid=1972,name="A Shiny Hallway",area="lemdagor",terrain="hallway",info="",notes="",x=27,y=30,z=0,building=""}
M[#M+1] = {uid=1973,name="A Shiny Hallway",area="lemdagor",terrain="hallway",info="",notes="",x=26,y=30,z=0,building=""}
M[#M+1] = {uid=1974,name="A Shiny Hallway",area="lemdagor",terrain="hallway",info="",notes="",x=26,y=31,z=0,building=""}
M[#M+1] = {uid=1975,name="A Shiny Hallway",area="lemdagor",terrain="hallway",info="",notes="",x=27,y=27,z=0,building=""}
M[#M+1] = {uid=1976,name="The Stairwell",area="lemdagor",terrain="inside",info="",notes="",x=26,y=27,z=0,building=""}
M[#M+1] = {uid=1977,name="A Stairwell",area="lemdagor",terrain="inside",info="",notes="",x=26,y=27,z=1,building=""}
M[#M+1] = {uid=1978,name="The Stairwell",area="lemdagor",terrain="inside",info="",notes="",x=26,y=27,z=2,building=""}
M[#M+1] = {uid=1979,name="A Shiny hallway",area="lemdagor",terrain="hallway",info="",notes="",x=25,y=27,z=2,building=""}
M[#M+1] = {uid=1980,name="A Shiny hallway",area="lemdagor",terrain="hallway",info="pk",notes="",x=25,y=28,z=2,building=""}
M[#M+1] = {uid=1981,name="The Entrance of the Bridge",area="lemdagor",terrain="inside",info="",notes="",x=27,y=27,z=1,building=""}
M[#M+1] = {uid=1982,name="The Battle System",area="lemdagor",terrain="inside",info="",notes="",x=28,y=27,z=1,building=""}
M[#M+1] = {uid=1983,name="The Cristallium",area="lemdagor",terrain="inside",info="",notes="",x=29,y=27,z=1,building=""}
M[#M+1] = {uid=1984,name="The West Side of the Bridge",area="lemdagor",terrain="inside",info="",notes="",x=27,y=26,z=1,building=""}
M[#M+1] = {uid=1985,name="The Centre of the Bridge",area="lemdagor",terrain="inside",info="",notes="",x=28,y=26,z=1,building=""}
M[#M+1] = {uid=1986,name="The East Side of the Bridge",area="lemdagor",terrain="inside",info="",notes="",x=29,y=26,z=1,building=""}
M[#M+1] = {uid=1987,name="Before the Captain's Quarters",area="lemdagor",terrain="inside",info="",notes="",x=27,y=25,z=1,building=""}
M[#M+1] = {uid=1988,name="At the Window",area="lemdagor",terrain="inside",info="",notes="",x=28,y=25,z=1,building=""}
M[#M+1] = {uid=1989,name="The Navigation System",area="lemdagor",terrain="inside",info="",notes="",x=29,y=25,z=1,building=""}
M[#M+1] = {uid=1990,name="The Captain's Quarters",area="lemdagor",terrain="inside",info="",notes="",x=26,y=25,z=1,building=""}
M[#M+1] = {uid=1991,name="The Stairwell",area="lemdagor",terrain="inside",info="",notes="",x=26,y=27,z=-1,building=""}
M[#M+1] = {uid=1992,name="A Shiny Hallway",area="lemdagor",terrain="hallway",info="",notes="",x=27,y=27,z=-1,building=""}
M[#M+1] = {uid=1993,name="Kaleb's Quarters",area="lemdagor",terrain="inside",info="",notes="",x=28,y=27,z=-1,building=""}
M[#M+1] = {uid=1994,name="A Shiny Hallway",area="lemdagor",terrain="hallway",info="",notes="",x=27,y=28,z=-1,building=""}
M[#M+1] = {uid=1995,name="Miranda's Quarters",area="lemdagor",terrain="inside",info="",notes="",x=26,y=28,z=-1,building=""}
M[#M+1] = {uid=1996,name="The Guest Chamber",area="lemdagor",terrain="inside",info="",notes="",x=27,y=29,z=-1,building=""}
M[#M+1] = {uid=1999,name="The chamber of Taelen",area="lemdagor",terrain="inside",info="",notes="",x=28,y=28,z=-1,building=""}
M[#M+1] = {uid=2000,name="A Shiny Hallway",area="lemdagor",terrain="hallway",info="",notes="",x=26,y=30,z=0,building=""}
M[#M+1] = {uid=2001,name="Tigi's Bar",area="lemdagor",terrain="inside",info="shop",notes="",x=28,y=27,z=0,building=""}
M[#M+1] = {uid=2002,name="The Wind Turbine Room",area="lemdagor",terrain="inside",info="",notes="",x=29,y=29,z=0,building=""}
M[#M+1] = {uid=2003,name="A Shiny Hallway",area="lemdagor",terrain="hallway",info="",notes="",x=27,y=30,z=0,building=""}
M[#M+1] = {uid=2004,name="A Shiny Hallway",area="lemdagor",terrain="hallway",info="",notes="",x=27,y=29,z=0,building=""}
M[#M+1] = {uid=2005,name="The Sick Bay",area="lemdagor",terrain="inside",info="",notes="",x=26,y=29,z=0,building=""}
M[#M+1] = {uid=2006,name="The Wind Turbines",area="lemdagor",terrain="inside",info="",notes="",x=29,y=29,z=0,building=""}
M[#M+1] = {uid=2007,name="The Eye of the Storm",area="lemdagor",terrain="air",info="",notes="",x=28,y=27,z=1,building=""}
M[#M+1] = {uid=2008,name="A Shiny Hallway",area="lemdagor",terrain="hallway",info="",notes="",x=27,y=28,z=0,building=""}
M[#M+1] = {uid=2009,name="The Storm Cruiser, Tempest",area="lemdagor",terrain="inside",info="",notes="",x=26,y=28,z=0,building=""}
M[#M+1] = {uid=2010,name="The Imaginarium",area="lemdagor",terrain="inside",info="",notes="",x=28,y=28,z=0,building=""}
M[#M+1] = {uid=2011,name="A Shiny Hallway",area="lemdagor",terrain="hallway",info="",notes="",x=27,y=27,z=0,building=""}
M[#M+1] = {uid=2012,name="Tigi's Bar",area="lemdagor",terrain="inside",info="",notes="",x=28,y=27,z=0,building=""}
M[#M+1] = {uid=2013,name="Stuck in a broken stairwell.",area="lemdagor",terrain="inside",info="",notes="",x=26,y=27,z=0,building=""}
M[#M+1] = {uid=2014,name="Hanging by a thread",area="lemdagor",terrain="air",info="",notes="",x=26,y=27,z=-1,building=""}
M[#M+1] = {uid=2015,name="A Shiny Hallway",area="lemdagor",terrain="hallway",info="",notes="",x=27,y=27,z=-1,building=""}
M[#M+1] = {uid=2016,name="Kaleb's Quarters",area="lemdagor",terrain="inside",info="",notes="",x=28,y=27,z=-1,building=""}
M[#M+1] = {uid=2017,name="A Shiny Hallway",area="lemdagor",terrain="hallway",info="",notes="",x=27,y=28,z=-1,building=""}
M[#M+1] = {uid=2018,name="Miranda's Quarters",area="lemdagor",terrain="inside",info="",notes="",x=26,y=28,z=-1,building=""}
M[#M+1] = {uid=2019,name="Gonzalo Taelen's Quarters",area="lemdagor",terrain="inside",info="",notes="",x=28,y=28,z=-1,building=""}
M[#M+1] = {uid=2021,name="On a broad landing",area="lemdagor",terrain="inside",info="",notes="",x=26,y=27,z=1,building=""}
M[#M+1] = {uid=2022,name="The Entrance of the Bridge",area="lemdagor",terrain="inside",info="",notes="",x=27,y=27,z=1,building=""}
M[#M+1] = {uid=2023,name="The Battle System",area="lemdagor",terrain="inside",info="",notes="",x=28,y=27,z=1,building=""}
M[#M+1] = {uid=2024,name="At the Cristallium",area="lemdagor",terrain="inside",info="",notes="",x=29,y=27,z=1,building=""}
M[#M+1] = {uid=2025,name="The West Side of the Bridge",area="lemdagor",terrain="inside",info="",notes="",x=27,y=26,z=1,building=""}
M[#M+1] = {uid=2026,name="The Centre of the Bridge",area="lemdagor",terrain="inside",info="",notes="",x=28,y=26,z=1,building=""}
M[#M+1] = {uid=2027,name="The East Side of the Bridge",area="lemdagor",terrain="inside",info="",notes="",x=29,y=26,z=1,building=""}
M[#M+1] = {uid=2028,name="Before the Captain's Quarters",area="lemdagor",terrain="inside",info="",notes="",x=27,y=25,z=1,building=""}
M[#M+1] = {uid=2029,name="At the Window",area="lemdagor",terrain="inside",info="",notes="",x=28,y=25,z=1,building=""}
M[#M+1] = {uid=2030,name="The Navigation System",area="lemdagor",terrain="inside",info="",notes="",x=29,y=25,z=1,building=""}
M[#M+1] = {uid=2031,name="The Captain's Quarters",area="lemdagor",terrain="inside",info="",notes="",x=26,y=25,z=1,building=""}
M[#M+1] = {uid=2038,name="Main Engineer Room",area="lemdagor",terrain="inside",info="",notes="",x=28,y=29,z=0,building=""}
M[#M+1] = {uid=2039,name="The Starboard Side of the Wave Runner",area="lemdagor",terrain="inside",info="",notes="",x=26,y=28,z=0,building=""}
M[#M+1] = {uid=2040,name="The Captain's Quarters",area="lemdagor",terrain="inside",info="",notes="",x=26,y=27,z=0,building=""}
M[#M+1] = {uid=2041,name="Inside a Cage",area="lemdagor",terrain="inside",info="",notes="",x=25,y=28,z=0,building=""}
M[#M+1] = {uid=2042,name="The East Wing of the Wave Runner",area="lemdagor",terrain="inside",info="",notes="",x=28,y=28,z=0,building=""}
M[#M+1] = {uid=2043,name="First Mate's Quarters",area="lemdagor",terrain="inside",info="",notes="",x=28,y=27,z=0,building=""}
M[#M+1] = {uid=2044,name="The Dining Hall",area="lemdagor",terrain="inside",info="",notes="",x=29,y=28,z=0,building=""}
M[#M+1] = {uid=2048,name="Spinning in the Storm",area="lemdagor",terrain="air",info="",notes="",x=28,y=27,z=2,building=""}
M[#M+1] = {uid=2049,name="Hanging alongside the Pirate Ship",area="lemdagor",terrain="air",info="",notes="",x=28,y=27,z=3,building=""}
M[#M+1] = {uid=2050,name="In the Lem-Dagor Pirateship",area="lemdagor",terrain="inside",info="",notes="",x=28,y=27,z=4,building=""}
M[#M+1] = {uid=2051,name="A very Peaceful Room......Yet!!!",area="lemdagor",terrain="inside",info="",notes="",x=28,y=26,z=4,building=""}
M[#M+1] = {uid=2052,name="The Bridge of the Pirateship",area="lemdagor",terrain="inside",info="",notes="",x=28,y=25,z=4,building=""}
M[#M+1] = {uid=2054,name="The Bridge of the Wave Runner",area="lemdagor",terrain="inside",info="",notes="",x=27,y=26,z=0,building=""}
M[#M+1] = {uid=2055,name="The Room of Conspiracy",area="lemdagor",terrain="inside",info="",notes="",x=27,y=27,z=0,building=""}
M[#M+1] = {uid=2056,name="The End of the Ventilation System",area="lemdagor",terrain="inside",info="",notes="",x=27,y=27,z=1,building=""}
M[#M+1] = {uid=2057,name="Before Two Locked Doors",area="lemdagor",terrain="inside",info="",notes="",x=27,y=28,z=0,building=""}
M[#M+1] = {uid=2058,name="The Ventilation System getting narrow",area="lemdagor",terrain="inside",info="",notes="",x=27,y=28,z=1,building=""}
M[#M+1] = {uid=2059,name="Ventilation System",area="lemdagor",terrain="inside",info="",notes="",x=27,y=29,z=1,building=""}
M[#M+1] = {uid=2060,name="Guest Room of the Wave Runner",area="lemdagor",terrain="inside",info="",notes="",x=27,y=29,z=0,building=""}
M[#M+1] = {uid=2061,name="The Bridge of the Typhoon",area="lemdagor",terrain="inside",info="",notes="",x=26,y=28,z=0,building=""}
M[#M+1] = {uid=2062,name="The Cargo Bay",area="lemdagor",terrain="inside",info="",notes="",x=26,y=29,z=0,building=""}
M[#M+1] = {uid=2064,name="Inside the trader, Typhoon",area="lemdagor",terrain="inside",info="",notes="",x=26,y=30,z=0,building=""}
M[#M+1] = {uid=2067,name="Entry way to the city of Athens",area="greece",terrain="city",info="",notes="",x=20,y=5,z=0,building=""}
M[#M+1] = {uid=2068,name="Before the portcullis",area="greece",terrain="city",info="",notes="",x=20,y=4,z=0,building=""}
M[#M+1] = {uid=2069,name="Eastern Guardhouse",area="greece",terrain="city",info="",notes="",x=21,y=4,z=0,building=""}
M[#M+1] = {uid=2070,name="Western Guardhouse",area="greece",terrain="city",info="",notes="",x=19,y=4,z=0,building=""}
M[#M+1] = {uid=2071,name="Market square",area="greece",terrain="city",info="",notes="",x=20,y=3,z=0,building=""}
M[#M+1] = {uid=2072,name="Eastern crossroads",area="greece",terrain="city",info="",notes="",x=21,y=3,z=0,building=""}
M[#M+1] = {uid=2073,name="Northeastern barracks",area="greece",terrain="hut",info="",notes="",x=21,y=2,z=0,building=""}
M[#M+1] = {uid=2074,name="Southeastern barracks",area="greece",terrain="hut",info="",notes="",x=21,y=4,z=0,building=""}
M[#M+1] = {uid=2075,name="Eastern officer barracks",area="greece",terrain="hut",info="",notes="",x=22,y=3,z=0,building=""}
M[#M+1] = {uid=2076,name="Road to Temple",area="greece",terrain="city",info="",notes="",x=23,y=1,z=0,building=""}
M[#M+1] = {uid=2077,name="Athenian temple ",area="greece",terrain="temple",info="",notes="",x=23,y=0,z=0,building=""}
M[#M+1] = {uid=2078,name="Priest Quarters",area="greece",terrain="hut",info="",notes="",x=23,y=2,z=0,building=""}
M[#M+1] = {uid=2079,name="Western crossroads",area="greece",terrain="city",info="",notes="",x=19,y=3,z=0,building=""}
M[#M+1] = {uid=2080,name="Southwestern barracks",area="greece",terrain="hut",info="",notes="",x=19,y=4,z=0,building=""}
M[#M+1] = {uid=2081,name="Northwestern Barracks",area="greece",terrain="hut",info="",notes="",x=19,y=2,z=0,building=""}
M[#M+1] = {uid=2082,name="Residential street",area="greece",terrain="city",info="",notes="",x=20,y=2,z=0,building=""}
M[#M+1] = {uid=2083,name="T-intersection",area="greece",terrain="city",info="",notes="",x=20,y=1,z=0,building=""}
M[#M+1] = {uid=2084,name="Draco Street",area="greece",terrain="city",info="",notes="",x=21,y=1,z=0,building=""}
M[#M+1] = {uid=2085,name="Eastern end of Draco street",area="greece",terrain="city",info="",notes="",x=22,y=1,z=0,building=""}
M[#M+1] = {uid=2086,name="Western end of Draco street",area="greece",terrain="city",info="",notes="",x=19,y=1,z=0,building=""}
M[#M+1] = {uid=2087,name="Stone path",area="greece",terrain="field",info="",notes="",x=20,y=6,z=0,building=""}
M[#M+1] = {uid=2088,name="Stone path",area="greece",terrain="field",info="",notes="",x=21,y=6,z=0,building=""}
M[#M+1] = {uid=2089,name="Bend in stone path",area="greece",terrain="field",info="",notes="",x=22,y=6,z=0,building=""}
M[#M+1] = {uid=2090,name="Stone path",area="greece",terrain="field",info="",notes="",x=22,y=7,z=0,building=""}
M[#M+1] = {uid=2091,name="Stone path",area="greece",terrain="field",info="",notes="",x=22,y=8,z=0,building=""}
M[#M+1] = {uid=2092,name="Forest path",area="greece",terrain="forest",info="",notes="",x=23,y=8,z=0,building=""}
M[#M+1] = {uid=2093,name="Forest path",area="greece",terrain="forest",info="",notes="",x=24,y=8,z=0,building=""}
M[#M+1] = {uid=2094,name="Forest path",area="greece",terrain="forest",info="",notes="",x=24,y=7,z=0,building=""}
M[#M+1] = {uid=2095,name="Forest path",area="greece",terrain="forest",info="",notes="",x=25,y=7,z=0,building=""}
M[#M+1] = {uid=2096,name="Entrance to Forest camp",area="greece",terrain="forest",info="",notes="",x=25,y=8,z=0,building=""}
M[#M+1] = {uid=2097,name="Bend in stone path",area="greece",terrain="field",info="",notes="",x=22,y=9,z=0,building=""}
M[#M+1] = {uid=2098,name="Corner of stone path",area="greece",terrain="field",info="",notes="",x=23,y=9,z=0,building=""}
M[#M+1] = {uid=2099,name="Entrance to the City of Sparta",area="greece",terrain="city",info="",notes="",x=23,y=10,z=0,building=""}
M[#M+1] = {uid=2100,name="Main path",area="greece",terrain="forest",info="",notes="",x=25,y=9,z=0,building=""}
M[#M+1] = {uid=2101,name="Main path",area="greece",terrain="forest",info="",notes="",x=25,y=10,z=0,building=""}
M[#M+1] = {uid=2102,name="Intersection",area="greece",terrain="forest",info="",notes="",x=25,y=11,z=0,building=""}
M[#M+1] = {uid=2103,name="Leader's Hut",area="greece",terrain="hut",info="",notes="",x=25,y=12,z=0,building=""}
M[#M+1] = {uid=2104,name="Road in front of Bandit jail",area="greece",terrain="forest",info="",notes="",x=26,y=11,z=0,building=""}
M[#M+1] = {uid=2105,name="Road in front of weaponry",area="greece",terrain="forest",info="",notes="",x=24,y=11,z=0,building=""}
M[#M+1] = {uid=2106,name="Path",area="greece",terrain="forest",info="",notes="",x=26,y=9,z=0,building=""}
M[#M+1] = {uid=2107,name="Bandit's home",area="greece",terrain="forest",info="",notes="",x=27,y=9,z=0,building=""}
M[#M+1] = {uid=2108,name="Weaponry",area="greece",terrain="forest",info="shop",notes="",x=24,y=12,z=0,building=""}
M[#M+1] = {uid=2109,name="Jail",area="greece",terrain="forest",info="",notes="",x=26,y=12,z=0,building=""}
M[#M+1] = {uid=2110,name="Entrance to Senate",area="greece",terrain="city",info="",notes="",x=19,y=0,z=0,building=""}
M[#M+1] = {uid=2111,name="Senate Floor",area="greece",terrain="inside",info="",notes="",x=19,y=-1,z=0,building=""}
M[#M+1] = {uid=2112,name="Chamber of Klisthenes",area="greece",terrain="inside",info="",notes="",x=20,y=-1,z=0,building=""}
M[#M+1] = {uid=2113,name="Chamber of Pericles",area="greece",terrain="inside",info="",notes="",x=19,y=-2,z=0,building=""}
M[#M+1] = {uid=2114,name="The Chamber of Thucydides",area="greece",terrain="inside",info="",notes="",x=18,y=-1,z=0,building=""}
M[#M+1] = {uid=2115,name="Uphill Path to Acropolis",area="greece",terrain="city",info="",notes="",x=21,y=0,z=0,building=""}
M[#M+1] = {uid=2116,name="Uphill Path ",area="greece",terrain="city",info="",notes="",x=21,y=-1,z=0,building=""}
M[#M+1] = {uid=2117,name="Middle of Acropolis",area="greece",terrain="temple",info="",notes="",x=21,y=-2,z=0,building=""}
M[#M+1] = {uid=2118,name="Temple of Athena",area="greece",terrain="temple",info="",notes="",x=22,y=-2,z=0,building=""}
M[#M+1] = {uid=2119,name="Parthenon",area="greece",terrain="temple",info="",notes="",x=21,y=-3,z=0,building=""}
M[#M+1] = {uid=2120,name="Temple of Poseidon",area="greece",terrain="temple",info="",notes="",x=20,y=-2,z=0,building=""}
M[#M+1] = {uid=2121,name="Gate House",area="greece",terrain="city",info="",notes="",x=23,y=11,z=0,building=""}
M[#M+1] = {uid=2122,name="Junction Main and Perimeter C",area="greece",terrain="city",info="",notes="",x=23,y=12,z=0,building=""}
M[#M+1] = {uid=2123,name="Main road before Armory",area="greece",terrain="city",info="",notes="",x=23,y=13,z=0,building=""}
M[#M+1] = {uid=2124,name="Intersection Main and Halfway",area="greece",terrain="city",info="",notes="",x=23,y=14,z=0,building=""}
M[#M+1] = {uid=2125,name="Main before Tax office",area="greece",terrain="city",info="",notes="",x=23,y=15,z=0,building=""}
M[#M+1] = {uid=2126,name="Main in front of Residential House",area="greece",terrain="city",info="",notes="",x=23,y=16,z=0,building=""}
M[#M+1] = {uid=2127,name="Junction Main and Perimeter A",area="greece",terrain="city",info="",notes="",x=23,y=17,z=0,building=""}
M[#M+1] = {uid=2129,name="Perimeter A in front of Generals office",area="greece",terrain="city",info="",notes="",x=22,y=17,z=0,building=""}
M[#M+1] = {uid=2130,name="Corner Perimeter A and Perimeter B",area="greece",terrain="city",info="",notes="",x=21,y=17,z=0,building=""}
M[#M+1] = {uid=2131,name="Perimeter B at Police",area="greece",terrain="city",info="",notes="",x=21,y=16,z=0,building=""}
M[#M+1] = {uid=2132,name="Perimeter B in front of Executioner",area="greece",terrain="city",info="",notes="",x=21,y=15,z=0,building=""}
M[#M+1] = {uid=2133,name="Junction Perimeter B and Halfway",area="greece",terrain="city",info="",notes="",x=21,y=14,z=0,building=""}
M[#M+1] = {uid=2134,name="Halfway before Jail",area="greece",terrain="city",info="",notes="",x=22,y=14,z=0,building=""}
M[#M+1] = {uid=2135,name="Ninety degree turn in stone path",area="greece",terrain="field",info="",notes="",x=23,y=6,z=0,building=""}
M[#M+1] = {uid=2136,name="Long stretch in stone path",area="greece",terrain="field",info="",notes="",x=23,y=5,z=0,building=""}
M[#M+1] = {uid=2137,name="Bend in stone path",area="greece",terrain="field",info="",notes="",x=23,y=4,z=0,building=""}
M[#M+1] = {uid=2138,name="Sharp turn in stone path",area="greece",terrain="field",info="",notes="",x=24,y=4,z=0,building=""}
M[#M+1] = {uid=2139,name="Entrance to city of Thebes",area="greece",terrain="city",info="",notes="",x=24,y=3,z=0,building=""}
M[#M+1] = {uid=2140,name="Square of the Sphinx",area="greece",terrain="city",info="",notes="",x=24,y=2,z=0,building=""}
M[#M+1] = {uid=2141,name="Main Street",area="greece",terrain="city",info="",notes="",x=24,y=1,z=0,building=""}
M[#M+1] = {uid=2142,name="Main Street",area="greece",terrain="city",info="",notes="",x=24,y=0,z=0,building=""}
M[#M+1] = {uid=2143,name="Main Street",area="greece",terrain="city",info="",notes="",x=24,y=-1,z=0,building=""}
M[#M+1] = {uid=2144,name="Northern End of Main Street",area="greece",terrain="city",info="",notes="",x=24,y=-2,z=0,building=""}
M[#M+1] = {uid=2145,name="Path to Ebony Way",area="greece",terrain="city",info="",notes="",x=25,y=1,z=0,building=""}
M[#M+1] = {uid=2146,name="Ebony Way",area="greece",terrain="city",info="",notes="",x=25,y=2,z=0,building=""}
M[#M+1] = {uid=2147,name="Ebony Way",area="greece",terrain="city",info="",notes="",x=26,y=2,z=0,building=""}
M[#M+1] = {uid=2148,name="Corner Ebony Way and Ivory Pass",area="greece",terrain="city",info="",notes="",x=27,y=2,z=0,building=""}
M[#M+1] = {uid=2149,name="Ivory Pass",area="greece",terrain="city",info="",notes="",x=27,y=1,z=0,building=""}
M[#M+1] = {uid=2150,name="Ivory Pass",area="greece",terrain="city",info="",notes="",x=27,y=0,z=0,building=""}
M[#M+1] = {uid=2151,name="Ivory Pass",area="greece",terrain="city",info="",notes="",x=27,y=-1,z=0,building=""}
M[#M+1] = {uid=2152,name="Northern End of Ivory Pass",area="greece",terrain="city",info="",notes="",x=27,y=-2,z=0,building=""}
M[#M+1] = {uid=2153,name="Ivory Side Street",area="greece",terrain="city",info="",notes="",x=26,y=-2,z=0,building=""}
M[#M+1] = {uid=2154,name="Ivory Side Street",area="greece",terrain="city",info="",notes="",x=26,y=-1,z=0,building=""}
M[#M+1] = {uid=2155,name="Dead End Road",area="greece",terrain="city",info="",notes="",x=25,y=-1,z=0,building=""}
M[#M+1] = {uid=2156,name="Ivory Side Street",area="greece",terrain="city",info="",notes="",x=26,y=0,z=0,building=""}
M[#M+1] = {uid=2157,name="Weird End of Road",area="greece",terrain="city",info="",notes="",x=25,y=0,z=0,building=""}
M[#M+1] = {uid=2158,name="Perimeter A: Residential",area="greece",terrain="city",info="",notes="",x=24,y=17,z=0,building=""}
M[#M+1] = {uid=2159,name="Perimeter A: Residential",area="greece",terrain="city",info="",notes="",x=25,y=17,z=0,building=""}
M[#M+1] = {uid=2160,name="Corner Perimeter A and Perimeter D",area="greece",terrain="city",info="",notes="",x=26,y=17,z=0,building=""}
M[#M+1] = {uid=2161,name="Entryway to the land of togas",area="greece",terrain="field",info="",notes="",x=22,y=5,z=0,building=""}
M[#M+1] = {uid=2162,name="Perimeter D: Residential",area="greece",terrain="city",info="",notes="",x=26,y=16,z=0,building=""}
M[#M+1] = {uid=2163,name="Perimeter D: Residential",area="greece",terrain="city",info="",notes="",x=26,y=15,z=0,building=""}
M[#M+1] = {uid=2164,name="Perimeter D and Halfway",area="greece",terrain="city",info="",notes="",x=26,y=14,z=0,building=""}
M[#M+1] = {uid=2165,name="Halfway: Residential",area="greece",terrain="city",info="",notes="",x=25,y=14,z=0,building=""}
M[#M+1] = {uid=2166,name="Halfway: Residential",area="greece",terrain="city",info="",notes="",x=24,y=14,z=0,building=""}
M[#M+1] = {uid=2167,name="Perimeter D in front of School",area="greece",terrain="city",info="",notes="",x=26,y=14,z=0,building=""}
M[#M+1] = {uid=2168,name="Perimeter D",area="greece",terrain="city",info="",notes="",x=26,y=13,z=0,building=""}
M[#M+1] = {uid=2169,name="Corner Perimeter D and Perimeter C",area="greece",terrain="city",info="",notes="",x=26,y=12,z=0,building=""}
M[#M+1] = {uid=2170,name="Perimeter C in front of the Agra",area="greece",terrain="city",info="",notes="",x=25,y=12,z=0,building=""}
M[#M+1] = {uid=2171,name="Perimeter C in front of the bakery",area="greece",terrain="city",info="",notes="",x=24,y=12,z=0,building=""}
M[#M+1] = {uid=2172,name="Perimeter C entrance to Training Ground",area="greece",terrain="city",info="",notes="",x=22,y=12,z=0,building=""}
M[#M+1] = {uid=2173,name="Perimeter C",area="greece",terrain="city",info="",notes="",x=21,y=12,z=0,building=""}
M[#M+1] = {uid=2174,name="Corner Perimeter C and Perimeter B",area="greece",terrain="city",info="",notes="",x=20,y=12,z=0,building=""}
M[#M+1] = {uid=2175,name="Perimeter B",area="greece",terrain="city",info="",notes="",x=20,y=13,z=0,building=""}
M[#M+1] = {uid=2176,name="Training Grounds",area="greece",terrain="hellinside",info="",notes="",x=22,y=11,z=0,building=""}
M[#M+1] = {uid=2177,name="Watch Tower",area="greece",terrain="hellinside",info="",notes="",x=23,y=11,z=0,building=""}
M[#M+1] = {uid=2178,name="Watch Tower",area="greece",terrain="hellinside",info="",notes="",x=22,y=10,z=0,building=""}
M[#M+1] = {uid=2179,name="Watch Tower",area="greece",terrain="hellinside",info="",notes="",x=21,y=11,z=0,building=""}
M[#M+1] = {uid=2180,name="Bakery",area="greece",terrain="shop",info="shop",notes="",x=24,y=13,z=0,building=""}
M[#M+1] = {uid=2181,name="Agra",area="greece",terrain="city",info="",notes="",x=25,y=13,z=0,building=""}
M[#M+1] = {uid=2182,name="School",area="greece",terrain="hut",info="",notes="",x=25,y=14,z=0,building=""}
M[#M+1] = {uid=2183,name="Citizen Home",area="greece",terrain="hut",info="",notes="",x=25,y=15,z=0,building=""}
M[#M+1] = {uid=2184,name="Citizen House",area="greece",terrain="hut",info="",notes="",x=24,y=15,z=0,building=""}
M[#M+1] = {uid=2185,name="Jail",area="greece",terrain="hut",info="",notes="",x=22,y=15,z=0,building=""}
M[#M+1] = {uid=2186,name="Executioner's room",area="greece",terrain="inside",info="",notes="",x=22,y=15,z=0,building=""}
M[#M+1] = {uid=2187,name="Police",area="greece",terrain="inside",info="",notes="",x=22,y=16,z=0,building=""}
M[#M+1] = {uid=2188,name="General's Office",area="greece",terrain="hut",info="",notes="",x=22,y=16,z=0,building=""}
M[#M+1] = {uid=2189,name="Citizen home",area="greece",terrain="hut",info="",notes="",x=24,y=16,z=0,building=""}
M[#M+1] = {uid=2190,name="Citizen home",area="greece",terrain="hut",info="",notes="",x=25,y=16,z=0,building=""}
M[#M+1] = {uid=2191,name="Citizen home",area="greece",terrain="hut",info="",notes="",x=25,y=16,z=0,building=""}
M[#M+1] = {uid=2192,name="Citizen house",area="greece",terrain="hut",info="",notes="",x=25,y=15,z=0,building=""}
M[#M+1] = {uid=2193,name="Armory",area="greece",terrain="shop",info="shop",notes="",x=24,y=13,z=0,building=""}
M[#M+1] = {uid=2194,name="Tax office",area="greece",terrain="hut",info="",notes="",x=22,y=15,z=0,building=""}
M[#M+1] = {uid=2195,name="Citizen home",area="greece",terrain="hut",info="",notes="",x=24,y=16,z=0,building=""}
M[#M+1] = {uid=2196,name="Meeting Area",area="greece",terrain="field",info="",notes="",x=25,y=16,z=0,building=""}
M[#M+1] = {uid=2197,name="Entrance to catacombs",area="greece",terrain="underground",info="",notes="",x=25,y=16,z=-1,building=""}
M[#M+1] = {uid=2198,name="Passage in Catacombs",area="greece",terrain="underground",info="",notes="",x=25,y=15,z=-1,building=""}
M[#M+1] = {uid=2199,name="Passage in catacombs",area="greece",terrain="underground",info="",notes="",x=25,y=13,z=-1,building=""}
M[#M+1] = {uid=2200,name="Passage in Catacombs",area="greece",terrain="underground",info="",notes="",x=25,y=14,z=-1,building=""}
M[#M+1] = {uid=2201,name="Large opening",area="greece",terrain="underground",info="",notes="",x=25,y=12,z=-1,building=""}
M[#M+1] = {uid=2202,name="Burial area",area="greece",terrain="crypt",info="",notes="",x=26,y=16,z=-1,building=""}
M[#M+1] = {uid=2203,name="Burial area",area="greece",terrain="crypt",info="",notes="",x=24,y=16,z=-1,building=""}
M[#M+1] = {uid=2204,name="Burial area",area="greece",terrain="crypt",info="",notes="",x=26,y=14,z=-1,building=""}
M[#M+1] = {uid=2205,name="Burial Area",area="greece",terrain="crypt",info="",notes="",x=24,y=14,z=-1,building=""}
M[#M+1] = {uid=2206,name="Kumquat Road",area="greece",terrain="city",info="",notes="",x=23,y=-1,z=0,building=""}
M[#M+1] = {uid=2207,name="Kumquat Road",area="greece",terrain="city",info="",notes="",x=22,y=-1,z=0,building=""}
M[#M+1] = {uid=2208,name="Long and Winding Lane",area="greece",terrain="city",info="",notes="",x=22,y=-2,z=0,building=""}
M[#M+1] = {uid=2209,name="Long and Winding Lane",area="greece",terrain="city",info="",notes="",x=21,y=-2,z=0,building=""}
M[#M+1] = {uid=2210,name="Long and Winding Lane",area="greece",terrain="city",info="",notes="",x=21,y=-1,z=0,building=""}
M[#M+1] = {uid=2211,name="Long and Winding Lane",area="greece",terrain="city",info="",notes="",x=21,y=0,z=0,building=""}
M[#M+1] = {uid=2212,name="Long and Winding Lane",area="greece",terrain="city",info="",notes="",x=19,y=0,z=0,building=""}
M[#M+1] = {uid=2213,name="Junction of Kumquat and Long",area="greece",terrain="city",info="",notes="",x=19,y=-1,z=0,building=""}
M[#M+1] = {uid=2214,name="Another Dead End",area="greece",terrain="city",info="",notes="",x=19,y=-2,z=0,building=""}
M[#M+1] = {uid=2215,name="Kumquat Road",area="greece",terrain="city",info="",notes="",x=20,y=-1,z=0,building=""}
M[#M+1] = {uid=2216,name="Kumquat Road",area="greece",terrain="city",info="",notes="",x=21,y=-1,z=0,building=""}
M[#M+1] = {uid=2224,name="Center of the Frozen Lake",area="greece",terrain="ice",info="",notes="",x=23,y=6,z=0,building=""}
M[#M+1] = {uid=2225,name="Frozen Lake",area="greece",terrain="ice",info="",notes="",x=23,y=7,z=0,building=""}
M[#M+1] = {uid=2226,name="Frozen Lake",area="greece",terrain="ice",info="",notes="",x=24,y=7,z=0,building=""}
M[#M+1] = {uid=2227,name="Frozen Lake",area="greece",terrain="ice",info="",notes="",x=24,y=8,z=0,building=""}
M[#M+1] = {uid=2228,name="Frozen Lake",area="greece",terrain="ice",info="",notes="",x=23,y=8,z=0,building=""}
M[#M+1] = {uid=2229,name="Opening to area of Compound Fraud",area="greece",terrain="ashen_field",info="",notes="",x=23,y=9,z=0,building=""}
M[#M+1] = {uid=2230,name="Gates to the Final Circle",area="greece",terrain="ashen_field",info="",notes="",x=23,y=10,z=0,building=""}
M[#M+1] = {uid=2231,name="Valley of the Giants",area="greece",terrain="ashen_field",info="",notes="",x=23,y=11,z=0,building=""}
M[#M+1] = {uid=2232,name="Valley of the Giants",area="greece",terrain="ashen_field",info="",notes="",x=21,y=11,z=0,building=""}
M[#M+1] = {uid=2233,name="Valley of the Giants",area="greece",terrain="ashen_field",info="",notes="",x=22,y=11,z=0,building=""}
M[#M+1] = {uid=2234,name="Plain of the Giants",area="greece",terrain="field",info="",notes="",x=22,y=10,z=0,building=""}
M[#M+1] = {uid=2346,name="Path along the River's Shore",area="mudwog",terrain="waterswim",info="",notes="",x=41,y=25,z=0,building=""}
M[#M+1] = {uid=2347,name="Path near the Swamp",area="mudwog",terrain="waterswim",info="",notes="",x=41,y=26,z=0,building=""}
M[#M+1] = {uid=2348,name="At the edge of a Murky Swamp",area="mudwog",terrain="waterswim",info="",notes="",x=40,y=26,z=0,building=""}
M[#M+1] = {uid=2349,name="The Banks of a Slow-moving River",area="mudwog",terrain="waterswim",info="",notes="",x=41,y=24,z=0,building=""}
M[#M+1] = {uid=2350,name="Mudwog's Swamp",area="mudwog",terrain="swamp",info="",notes="",x=41,y=25,z=0,building=""}
M[#M+1] = {uid=2351,name="Mudwog's Swamp",area="mudwog",terrain="swamp",info="",notes="",x=41,y=24,z=0,building=""}
M[#M+1] = {uid=2352,name="Mudwog's Swamp",area="mudwog",terrain="swamp",info="",notes="",x=42,y=25,z=0,building=""}
M[#M+1] = {uid=2353,name="Mudwog's Swamp",area="mudwog",terrain="swamp",info="",notes="",x=42,y=24,z=0,building=""}
M[#M+1] = {uid=2354,name="Mudwog's Swamp",area="mudwog",terrain="swamp",info="",notes="",x=43,y=25,z=0,building=""}
M[#M+1] = {uid=2355,name="Mudwog's Swamp",area="mudwog",terrain="swamp",info="",notes="",x=43,y=24,z=0,building=""}
M[#M+1] = {uid=2356,name="Mudwog's Swamp",area="mudwog",terrain="swamp",info="",notes="",x=44,y=25,z=0,building=""}
M[#M+1] = {uid=2357,name="Wading into the Swamp",area="mudwog",terrain="swamp",info="",notes="",x=44,y=24,z=0,building=""}
M[#M+1] = {uid=2358,name="A Mudslide",area="mudwog",terrain="swamp",info="",notes="",x=45,y=25,z=0,building=""}
M[#M+1] = {uid=2359,name="Sliding Through the Mud",area="mudwog",terrain="swamp",info="",notes="",x=41,y=25,z=0,building=""}
M[#M+1] = {uid=2360,name="Sliding Through the Mud",area="mudwog",terrain="swamp",info="",notes="",x=41,y=26,z=0,building=""}
M[#M+1] = {uid=2361,name="Sliding Through the Mud",area="mudwog",terrain="swamp",info="",notes="",x=41,y=25,z=0,building=""}
M[#M+1] = {uid=2362,name="Deeper into Mudwog's Swamp",area="mudwog",terrain="swamp",info="",notes="",x=41,y=26,z=0,building=""}
M[#M+1] = {uid=2363,name="The Bog",area="mudwog",terrain="swamp",info="",notes="",x=40,y=26,z=0,building=""}
M[#M+1] = {uid=2364,name="The Bog",area="mudwog",terrain="swamp",info="",notes="",x=40,y=27,z=0,building=""}
M[#M+1] = {uid=2365,name="The Bog",area="mudwog",terrain="swamp",info="",notes="",x=39,y=27,z=0,building=""}
M[#M+1] = {uid=2366,name="The Bog",area="mudwog",terrain="swamp",info="",notes="",x=39,y=26,z=0,building=""}
M[#M+1] = {uid=2367,name="A Path through the Bog",area="mudwog",terrain="swamp",info="",notes="",x=38,y=26,z=0,building=""}
M[#M+1] = {uid=2368,name="An Island in the Bog",area="mudwog",terrain="swamp",info="",notes="",x=37,y=26,z=0,building=""}
M[#M+1] = {uid=2369,name="An Island in the Bog",area="mudwog",terrain="swamp",info="",notes="",x=37,y=25,z=0,building=""}
M[#M+1] = {uid=2370,name="An Island in the Bog",area="mudwog",terrain="swamp",info="",notes="",x=36,y=26,z=0,building=""}
M[#M+1] = {uid=2371,name="An Island in the Bog",area="mudwog",terrain="swamp",info="",notes="",x=36,y=25,z=0,building=""}
M[#M+1] = {uid=2372,name="A Path through the Swamp",area="mudwog",terrain="swamp",info="",notes="",x=35,y=25,z=0,building=""}
M[#M+1] = {uid=2373,name="A Path through the Swamp",area="mudwog",terrain="swamp",info="",notes="",x=35,y=24,z=0,building=""}
M[#M+1] = {uid=2374,name="A Path through the Swamp",area="mudwog",terrain="swamp",info="",notes="",x=35,y=23,z=0,building=""}
M[#M+1] = {uid=2375,name="Sucked into the Mud",area="mudwog",terrain="underwater",info="",notes="",x=41,y=25,z=0,building=""}
M[#M+1] = {uid=2376,name="Sucked into the Mud",area="mudwog",terrain="underwater",info="",notes="",x=41,y=25,z=-1,building=""}
M[#M+1] = {uid=2377,name="A Pocket of Air",area="mudwog",terrain="waterswim",info="",notes="",x=41,y=26,z=-1,building=""}
M[#M+1] = {uid=2378,name="Sucked into the Mud",area="mudwog",terrain="waterswim",info="",notes="",x=41,y=26,z=-2,building=""}
M[#M+1] = {uid=2379,name="Mudwog's Domain",area="mudwog",terrain="cave",info="",notes="",x=41,y=26,z=-3,building=""}
M[#M+1] = {uid=2380,name="Mudwog's First Wife",area="mudwog",terrain="waternoswim",info="",notes="",x=41,y=25,z=-3,building=""}
M[#M+1] = {uid=2381,name="Mudwog's Domain",area="mudwog",terrain="cave",info="",notes="",x=41,y=27,z=-3,building=""}
M[#M+1] = {uid=2382,name="Mudwog's Second Wife",area="mudwog",terrain="beach",info="",notes="",x=42,y=25,z=-3,building=""}
M[#M+1] = {uid=2383,name="Mudwog's Hatchery",area="mudwog",terrain="cave",info="",notes="",x=40,y=26,z=-3,building=""}
M[#M+1] = {uid=2384,name="Mudwog's Hatchery",area="mudwog",terrain="cave",info="",notes="",x=40,y=27,z=-3,building=""}
M[#M+1] = {uid=2385,name="Mudwog's Hatchery",area="mudwog",terrain="cave",info="",notes="",x=39,y=26,z=-3,building=""}
M[#M+1] = {uid=2386,name="Mudwog's Hatchery",area="mudwog",terrain="cave",info="",notes="",x=39,y=27,z=-3,building=""}
M[#M+1] = {uid=2387,name="Slimy Trail to Mudwog",area="mudwog",terrain="underwater",info="",notes="",x=42,y=26,z=-3,building=""}
M[#M+1] = {uid=2388,name="Slimy Trail to Mudwog",area="mudwog",terrain="underwater",info="",notes="",x=43,y=26,z=-3,building=""}
M[#M+1] = {uid=2389,name="Mudwog's Favorite Wife",area="mudwog",terrain="underwater",info="",notes="",x=43,y=25,z=-3,building=""}
M[#M+1] = {uid=2390,name="Slimy Trail to Mudwog",area="mudwog",terrain="underwater",info="",notes="",x=44,y=26,z=-3,building=""}
M[#M+1] = {uid=2391,name="Slimy Trail to Mudwog",area="mudwog",terrain="underwater",info="",notes="",x=44,y=25,z=-3,building=""}
M[#M+1] = {uid=2392,name="Slimy Trail to Mudwog",area="mudwog",terrain="underwater",info="",notes="",x=45,y=25,z=-3,building=""}
M[#M+1] = {uid=2393,name="Slimy Trail to Mudwog",area="mudwog",terrain="underwater",info="",notes="",x=46,y=25,z=-3,building=""}
M[#M+1] = {uid=2394,name="Mudwog's Nest",area="mudwog",terrain="underwater",info="",notes="",x=47,y=25,z=-3,building=""}
M[#M+1] = {uid=2395,name="Climbing a cold mountain trail",area="andarin",terrain="road",info="",notes="",x=21,y=0,z=0,building=""}
M[#M+1] = {uid=2396,name="The hazardous path",area="andarin",terrain="road",info="",notes="",x=21,y=0,z=1,building=""}
M[#M+1] = {uid=2397,name="Climbing the snowy mountain",area="andarin",terrain="road",info="",notes="",x=21,y=-1,z=1,building=""}
M[#M+1] = {uid=2398,name="Following the icy trail",area="andarin",terrain="road",info="",notes="",x=21,y=-1,z=2,building=""}
M[#M+1] = {uid=2399,name="A turn in the path",area="andarin",terrain="road",info="",notes="",x=21,y=-2,z=2,building=""}
M[#M+1] = {uid=2400,name="Climbing up the frozen rocks",area="andarin",terrain="road",info="",notes="",x=22,y=-2,z=2,building=""}
M[#M+1] = {uid=2401,name="An isolated igloo",area="andarin",terrain="ice",info="",notes="",x=27,y=0,z=4,building=""}
M[#M+1] = {uid=2402,name="A large igloo",area="andarin",terrain="ice",info="",notes="",x=28,y=0,z=4,building=""}
M[#M+1] = {uid=2403,name="An igloo",area="andarin",terrain="ice",info="",notes="",x=29,y=0,z=4,building=""}
M[#M+1] = {uid=2404,name="A collapsed igloo",area="andarin",terrain="ice",info="",notes="",x=28,y=-2,z=4,building=""}
M[#M+1] = {uid=2405,name="A puddle of water",area="andarin",terrain="ice",info="",notes="",x=29,y=-2,z=4,building=""}
M[#M+1] = {uid=2406,name="On top of the cliffs",area="andarin",terrain="mountain",info="",notes="",x=27,y=-1,z=4,building=""}
M[#M+1] = {uid=2407,name="A colorful igloo",area="andarin",terrain="ice",info="",notes="",x=28,y=-1,z=4,building=""}
M[#M+1] = {uid=2408,name="Standing before a huge sundial",area="andarin",terrain="pillar",info="",notes="",x=29,y=-1,z=4,building=""}
M[#M+1] = {uid=2409,name="A small igloo",area="andarin",terrain="ice",info="",notes="",x=28,y=-3,z=4,building=""}
M[#M+1] = {uid=2410,name="An igloo",area="andarin",terrain="mountain",info="",notes="",x=29,y=-3,z=4,building=""}
M[#M+1] = {uid=2411,name="Icy plains",area="andarin",terrain="snow",info="",notes="",x=23,y=-1,z=3,building=""}
M[#M+1] = {uid=2412,name="A snow covered wasteland",area="andarin",terrain="snow",info="",notes="",x=24,y=-1,z=3,building=""}
M[#M+1] = {uid=2413,name="The Dead of Winter",area="andarin",terrain="snow",info="",notes="",x=25,y=-1,z=3,building=""}
M[#M+1] = {uid=2414,name="The twin pines",area="andarin",terrain="snow",info="",notes="",x=26,y=-1,z=3,building=""}
M[#M+1] = {uid=2415,name="Underneath the Cliffs of Valhan",area="andarin",terrain="snow",info="",notes="",x=27,y=-1,z=3,building=""}
M[#M+1] = {uid=2416,name="A frozen expanse",area="andarin",terrain="snow",info="",notes="",x=23,y=-2,z=3,building=""}
M[#M+1] = {uid=2417,name="An icy plain",area="andarin",terrain="snow",info="",notes="",x=24,y=-2,z=3,building=""}
M[#M+1] = {uid=2418,name="A vast expanse",area="andarin",terrain="snow",info="",notes="",x=25,y=-2,z=3,building=""}
M[#M+1] = {uid=2419,name="Between the twin pines",area="andarin",terrain="snow",info="safe",notes="",x=26,y=-2,z=3,building=""}
M[#M+1] = {uid=2420,name="In the shadows of the cliffs",area="andarin",terrain="snow",info="",notes="",x=27,y=-2,z=3,building=""}
M[#M+1] = {uid=2421,name="The frozen tundra",area="andarin",terrain="snow",info="",notes="",x=23,y=-3,z=3,building=""}
M[#M+1] = {uid=2422,name="The icy plains",area="andarin",terrain="snow",info="",notes="",x=24,y=-3,z=3,building=""}
M[#M+1] = {uid=2423,name="A damp tundra",area="andarin",terrain="snow",info="",notes="",x=25,y=-3,z=3,building=""}
M[#M+1] = {uid=2424,name="The twin pines",area="andarin",terrain="snow",info="",notes="",x=26,y=-3,z=3,building=""}
M[#M+1] = {uid=2425,name="In the shadows of the cliffs",area="andarin",terrain="snow",info="",notes="",x=27,y=-3,z=3,building=""}
M[#M+1] = {uid=2426,name="The frozen tundra",area="andarin",terrain="snow",info="",notes="",x=23,y=-4,z=3,building=""}
M[#M+1] = {uid=2427,name="An arctic expanse",area="andarin",terrain="snow",info="",notes="",x=24,y=-4,z=3,building=""}
M[#M+1] = {uid=2428,name="Beneath the Tree of Sodrus",area="andarin",terrain="snow",info="",notes="",x=25,y=-4,z=3,building=""}
M[#M+1] = {uid=2429,name="A persistent cold",area="andarin",terrain="snow",info="",notes="",x=26,y=-4,z=3,building=""}
M[#M+1] = {uid=2430,name="In the shadows of the cliffs",area="andarin",terrain="snow",info="",notes="",x=27,y=-4,z=3,building=""}
M[#M+1] = {uid=2431,name="A deep snow drift",area="andarin",terrain="snow",info="",notes="",x=23,y=-5,z=3,building=""}
M[#M+1] = {uid=2432,name="A wintry plain",area="andarin",terrain="snow",info="",notes="",x=24,y=-5,z=3,building=""}
M[#M+1] = {uid=2433,name="A frozen wasteland",area="andarin",terrain="snow",info="",notes="",x=25,y=-5,z=3,building=""}
M[#M+1] = {uid=2434,name="A bleak winter",area="andarin",terrain="snow",info="",notes="",x=26,y=-5,z=3,building=""}
M[#M+1] = {uid=2435,name="In the shadows of the cliffs",area="andarin",terrain="snow",info="",notes="",x=27,y=-5,z=3,building=""}
M[#M+1] = {uid=2436,name="The ice-covered tundra",area="andarin",terrain="snow",info="",notes="",x=23,y=-6,z=3,building=""}
M[#M+1] = {uid=2437,name="The frigid plains",area="andarin",terrain="snow",info="",notes="",x=24,y=-6,z=3,building=""}
M[#M+1] = {uid=2438,name="A barren tundra",area="andarin",terrain="snow",info="",notes="",x=25,y=-6,z=3,building=""}
M[#M+1] = {uid=2439,name="An everlasting cold",area="andarin",terrain="snow",info="",notes="",x=26,y=-6,z=3,building=""}
M[#M+1] = {uid=2440,name="In the shadows of the cliffs",area="andarin",terrain="snow",info="",notes="",x=27,y=-6,z=3,building=""}
M[#M+1] = {uid=2441,name="The icy champaign",area="andarin",terrain="snow",info="",notes="",x=24,y=-7,z=3,building=""}
M[#M+1] = {uid=2442,name="Before an underground cavern",area="andarin",terrain="snow",info="",notes="",x=22,y=-6,z=3,building=""}
M[#M+1] = {uid=2443,name="A glacial plain",area="andarin",terrain="snow",info="",notes="",x=26,y=-7,z=3,building=""}
M[#M+1] = {uid=2444,name="Standing in the snow",area="andarin",terrain="snow",info="",notes="",x=24,y=-8,z=3,building=""}
M[#M+1] = {uid=2445,name="Snowy plains",area="andarin",terrain="snow",info="",notes="",x=23,y=-7,z=3,building=""}
M[#M+1] = {uid=2446,name="The frosty plains",area="andarin",terrain="snow",info="",notes="",x=25,y=-7,z=3,building=""}
M[#M+1] = {uid=2447,name="The dead calm",area="andarin",terrain="snow",info="",notes="",x=22,y=-2,z=3,building=""}
M[#M+1] = {uid=2462,name="The sapphire tunnel",area="andarin",terrain="underground",info="",notes="",x=26,y=-1,z=2,building=""}
M[#M+1] = {uid=2463,name="A large tunnel",area="andarin",terrain="underground",info="",notes="",x=27,y=-1,z=2,building=""}
M[#M+1] = {uid=2464,name="The amber chamber",area="andarin",terrain="underground",info="",notes="",x=27,y=-3,z=2,building=""}
M[#M+1] = {uid=2465,name="The sapphire tunnel",area="andarin",terrain="underground",info="",notes="",x=26,y=0,z=2,building=""}
M[#M+1] = {uid=2466,name="The sapphire chamber",area="andarin",terrain="underground",info="",notes="",x=26,y=1,z=2,building=""}
M[#M+1] = {uid=2467,name="The amber tunnel",area="andarin",terrain="underground",info="",notes="",x=27,y=-2,z=2,building=""}
M[#M+1] = {uid=2471,name="The lower branches",area="andarin",terrain="forest",info="",notes="",x=24,y=-4,z=4,building=""}
M[#M+1] = {uid=2472,name="Climbing the Tree of Sodrus",area="andarin",terrain="forest",info="",notes="",x=25,y=-4,z=4,building=""}
M[#M+1] = {uid=2473,name="The lower branches",area="andarin",terrain="forest",info="",notes="",x=26,y=-4,z=4,building=""}
M[#M+1] = {uid=2474,name="The upper branches",area="andarin",terrain="forest",info="",notes="",x=24,y=-4,z=5,building=""}
M[#M+1] = {uid=2475,name="Further up the Tree of Sodrus",area="andarin",terrain="forest",info="",notes="",x=25,y=-4,z=5,building=""}
M[#M+1] = {uid=2476,name="The upper branches",area="andarin",terrain="mountain",info="",notes="",x=26,y=-4,z=5,building=""}
M[#M+1] = {uid=2477,name="A crow's nest",area="andarin",terrain="forest",info="",notes="",x=25,y=-4,z=6,building=""}
M[#M+1] = {uid=2478,name="A warm mountain cabin",area="andarin",terrain="shop",info="shop",notes="",x=20,y=-2,z=2,building=""}
M[#M+1] = {uid=2479,name="Inside the cave",area="andarin",terrain="cave",info="pk",notes="",x=23,y=-8,z=3,building=""}
M[#M+1] = {uid=2492,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=2493,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=1,y=0,z=0,building=""}
M[#M+1] = {uid=2494,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=2,y=0,z=0,building=""}
M[#M+1] = {uid=2495,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=3,y=0,z=0,building=""}
M[#M+1] = {uid=2496,name="Ghostly Sands",area="alagh",terrain="beach",info="",notes="",x=4,y=0,z=0,building=""}
M[#M+1] = {uid=2497,name="Bay of Death",area="alagh",terrain="ocean",info="",notes="",x=5,y=0,z=0,building=""}
M[#M+1] = {uid=2498,name="Bay of Death",area="alagh",terrain="ocean",info="",notes="",x=6,y=0,z=0,building=""}
M[#M+1] = {uid=2499,name="Bay of Death",area="alagh",terrain="ocean",info="",notes="",x=7,y=0,z=0,building=""}
M[#M+1] = {uid=2500,name="Oninochi",area="alagh",terrain="hell2",info="",notes="",x=8,y=0,z=0,building=""}
M[#M+1] = {uid=2501,name="Oninochi",area="alagh",terrain="hell3",info="",notes="",x=9,y=0,z=0,building=""}
M[#M+1] = {uid=2502,name="Oni Bay",area="alagh",terrain="ocean",info="",notes="",x=10,y=0,z=0,building=""}
M[#M+1] = {uid=2503,name="Oni Bay",area="alagh",terrain="ocean",info="",notes="",x=11,y=0,z=0,building=""}
M[#M+1] = {uid=2504,name="Oni Bay",area="alagh",terrain="ocean",info="",notes="",x=12,y=0,z=0,building=""}
M[#M+1] = {uid=2505,name="Oni Bay",area="alagh",terrain="ocean",info="",notes="",x=13,y=0,z=0,building=""}
M[#M+1] = {uid=2506,name="Oni Bay",area="alagh",terrain="ocean",info="",notes="",x=14,y=0,z=0,building=""}
M[#M+1] = {uid=2507,name="Oninochi",area="alagh",terrain="hell2",info="",notes="",x=15,y=0,z=0,building=""}
M[#M+1] = {uid=2508,name="Oninochi",area="alagh",terrain="hell2",info="",notes="",x=16,y=0,z=0,building=""}
M[#M+1] = {uid=2509,name="Mistwater",area="alagh",terrain="ocean",info="",notes="",x=17,y=0,z=0,building=""}
M[#M+1] = {uid=2510,name="Mistridge Forest",area="alagh",terrain="forest",info="",notes="",x=18,y=0,z=0,building=""}
M[#M+1] = {uid=2511,name="Mistwater",area="alagh",terrain="ocean",info="",notes="",x=19,y=0,z=0,building=""}
M[#M+1] = {uid=2512,name="Mistwater",area="alagh",terrain="ocean",info="",notes="",x=20,y=0,z=0,building=""}
M[#M+1] = {uid=2513,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=21,y=0,z=0,building=""}
M[#M+1] = {uid=2514,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=22,y=0,z=0,building=""}
M[#M+1] = {uid=2515,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=23,y=0,z=0,building=""}
M[#M+1] = {uid=2516,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=24,y=0,z=0,building=""}
M[#M+1] = {uid=2517,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=25,y=0,z=0,building=""}
M[#M+1] = {uid=2518,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=26,y=0,z=0,building=""}
M[#M+1] = {uid=2519,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=27,y=0,z=0,building=""}
M[#M+1] = {uid=2520,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=28,y=0,z=0,building=""}
M[#M+1] = {uid=2521,name="The Forbidden Waters",area="alagh",terrain="ocean",info="",notes="",x=29,y=0,z=0,building=""}
M[#M+1] = {uid=2522,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=0,y=1,z=0,building=""}
M[#M+1] = {uid=2523,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=1,y=1,z=0,building=""}
M[#M+1] = {uid=2524,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=2,y=1,z=0,building=""}
M[#M+1] = {uid=2525,name="Ghostly Sands",area="alagh",terrain="beach",info="",notes="",x=3,y=1,z=0,building=""}
M[#M+1] = {uid=2526,name="Ghostly Sands",area="alagh",terrain="beach",info="",notes="",x=4,y=1,z=0,building=""}
M[#M+1] = {uid=2527,name="Ghostly Sands",area="alagh",terrain="beach",info="",notes="",x=5,y=1,z=0,building=""}
M[#M+1] = {uid=2528,name="Bay of Death",area="alagh",terrain="ocean",info="",notes="",x=6,y=1,z=0,building=""}
M[#M+1] = {uid=2529,name="Ghostly Sands",area="alagh",terrain="beach",info="",notes="",x=7,y=1,z=0,building=""}
M[#M+1] = {uid=2530,name="Oninochi",area="alagh",terrain="hell2",info="",notes="",x=8,y=1,z=0,building=""}
M[#M+1] = {uid=2531,name="Oninochi",area="alagh",terrain="hell2",info="",notes="",x=9,y=1,z=0,building=""}
M[#M+1] = {uid=2532,name="Oni Bay",area="alagh",terrain="ocean",info="",notes="",x=10,y=1,z=0,building=""}
M[#M+1] = {uid=2533,name="Oninochi",area="alagh",terrain="hell1",info="",notes="",x=11,y=1,z=0,building=""}
M[#M+1] = {uid=2534,name="Oninochi",area="alagh",terrain="hell1",info="",notes="",x=12,y=1,z=0,building=""}
M[#M+1] = {uid=2535,name="Oninochi",area="alagh",terrain="hell2",info="",notes="",x=13,y=1,z=0,building=""}
M[#M+1] = {uid=2536,name="Oninochi",area="alagh",terrain="hell2",info="",notes="",x=14,y=1,z=0,building=""}
M[#M+1] = {uid=2537,name="Oninochi",area="alagh",terrain="hell2",info="",notes="",x=15,y=1,z=0,building=""}
M[#M+1] = {uid=2538,name="Oninochi",area="alagh",terrain="hell1",info="",notes="",x=16,y=1,z=0,building=""}
M[#M+1] = {uid=2539,name="Mistridge Forest",area="alagh",terrain="forest",info="",notes="",x=17,y=1,z=0,building=""}
M[#M+1] = {uid=2540,name="Mistridge Forest",area="alagh",terrain="forest",info="",notes="",x=18,y=1,z=0,building=""}
M[#M+1] = {uid=2541,name="Mistridge Forest",area="alagh",terrain="areaexit",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=2542,name="Mistwater",area="alagh",terrain="ocean",info="",notes="",x=20,y=1,z=0,building=""}
M[#M+1] = {uid=2543,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=21,y=1,z=0,building=""}
M[#M+1] = {uid=2544,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=22,y=1,z=0,building=""}
M[#M+1] = {uid=2545,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=23,y=1,z=0,building=""}
M[#M+1] = {uid=2546,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=24,y=1,z=0,building=""}
M[#M+1] = {uid=2547,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=25,y=1,z=0,building=""}
M[#M+1] = {uid=2548,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=26,y=1,z=0,building=""}
M[#M+1] = {uid=2549,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=27,y=1,z=0,building=""}
M[#M+1] = {uid=2550,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=28,y=1,z=0,building=""}
M[#M+1] = {uid=2551,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=29,y=1,z=0,building=""}
M[#M+1] = {uid=2552,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=0,y=2,z=0,building=""}
M[#M+1] = {uid=2553,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=1,y=2,z=0,building=""}
M[#M+1] = {uid=2554,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=2,y=2,z=0,building=""}
M[#M+1] = {uid=2555,name="Ghostly Sands",area="alagh",terrain="beach",info="",notes="",x=3,y=2,z=0,building=""}
M[#M+1] = {uid=2556,name="Mercury Lake",area="alagh",terrain="ocean",info="",notes="",x=4,y=2,z=0,building=""}
M[#M+1] = {uid=2557,name="Ghostly Sands",area="alagh",terrain="beach",info="",notes="",x=5,y=2,z=0,building=""}
M[#M+1] = {uid=2558,name="Ghostly Sands",area="alagh",terrain="beach",info="",notes="",x=6,y=2,z=0,building=""}
M[#M+1] = {uid=2559,name="Ghostly Sands",area="alagh",terrain="beach",info="",notes="",x=7,y=2,z=0,building=""}
M[#M+1] = {uid=2560,name="Oninochi",area="alagh",terrain="hell3",info="",notes="",x=8,y=2,z=0,building=""}
M[#M+1] = {uid=2561,name="Oninochi",area="alagh",terrain="hell2",info="",notes="",x=9,y=2,z=0,building=""}
M[#M+1] = {uid=2562,name="Oninochi",area="alagh",terrain="hell2",info="",notes="",x=10,y=2,z=0,building=""}
M[#M+1] = {uid=2563,name="Oninochi",area="alagh",terrain="hell1",info="",notes="",x=11,y=2,z=0,building=""}
M[#M+1] = {uid=2564,name="Oninochi",area="alagh",terrain="hell2",info="",notes="",x=12,y=2,z=0,building=""}
M[#M+1] = {uid=2565,name="Oninochi",area="alagh",terrain="hell1",info="",notes="",x=13,y=2,z=0,building=""}
M[#M+1] = {uid=2566,name="Oninochi",area="alagh",terrain="hell3",info="",notes="",x=14,y=2,z=0,building=""}
M[#M+1] = {uid=2567,name="Oninochi",area="alagh",terrain="hell3",info="",notes="",x=15,y=2,z=0,building=""}
M[#M+1] = {uid=2568,name="Mistridge Forest",area="alagh",terrain="forest",info="",notes="",x=16,y=2,z=0,building=""}
M[#M+1] = {uid=2569,name="Mistridge Forest",area="alagh",terrain="forest",info="",notes="",x=17,y=2,z=0,building=""}
M[#M+1] = {uid=2570,name="Alagh, the Blood Lands",area="alagh",terrain="areaexit",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=2571,name="The Stream of Wolf",area="alagh",terrain="ocean",info="",notes="",x=19,y=2,z=0,building=""}
M[#M+1] = {uid=2572,name="Mistwater",area="alagh",terrain="ocean",info="",notes="",x=20,y=2,z=0,building=""}
M[#M+1] = {uid=2573,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=21,y=2,z=0,building=""}
M[#M+1] = {uid=2574,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=22,y=2,z=0,building=""}
M[#M+1] = {uid=2575,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=23,y=2,z=0,building=""}
M[#M+1] = {uid=2576,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=24,y=2,z=0,building=""}
M[#M+1] = {uid=2577,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=25,y=2,z=0,building=""}
M[#M+1] = {uid=2578,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=26,y=2,z=0,building=""}
M[#M+1] = {uid=2579,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=27,y=2,z=0,building=""}
M[#M+1] = {uid=2580,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=28,y=2,z=0,building=""}
M[#M+1] = {uid=2581,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=29,y=2,z=0,building=""}
M[#M+1] = {uid=2582,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=0,y=3,z=0,building=""}
M[#M+1] = {uid=2583,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=1,y=3,z=0,building=""}
M[#M+1] = {uid=2584,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=2,y=3,z=0,building=""}
M[#M+1] = {uid=2585,name="Ghostly Sands",area="alagh",terrain="beach",info="",notes="",x=3,y=3,z=0,building=""}
M[#M+1] = {uid=2586,name="Ghostly Sands",area="alagh",terrain="beach",info="",notes="",x=4,y=3,z=0,building=""}
M[#M+1] = {uid=2587,name="Ghostly Sands",area="alagh",terrain="beach",info="",notes="",x=5,y=3,z=0,building=""}
M[#M+1] = {uid=2588,name="Desolate Hills",area="alagh",terrain="hell3",info="",notes="",x=6,y=3,z=0,building=""}
M[#M+1] = {uid=2589,name="Desolate Hills",area="alagh",terrain="hell2",info="",notes="",x=7,y=3,z=0,building=""}
M[#M+1] = {uid=2590,name="Oninochi",area="alagh",terrain="hell1",info="",notes="",x=8,y=3,z=0,building=""}
M[#M+1] = {uid=2591,name="Oninochi",area="alagh",terrain="hell2",info="",notes="",x=9,y=3,z=0,building=""}
M[#M+1] = {uid=2592,name="Oninochi",area="alagh",terrain="hell3",info="",notes="",x=10,y=3,z=0,building=""}
M[#M+1] = {uid=2593,name="Oninochi",area="alagh",terrain="hell1",info="",notes="",x=11,y=3,z=0,building=""}
M[#M+1] = {uid=2594,name="The Edge of an Ancient Battlefield",area="alagh",terrain="plain",info="",notes="",x=12,y=3,z=0,building=""}
M[#M+1] = {uid=2595,name="Outside the Walls of Takeda's Warcamp",area="alagh",terrain="plain",info="",notes="",x=13,y=3,z=0,building=""}
M[#M+1] = {uid=2596,name="The Blood plains of Battle",area="alagh",terrain="areaexit",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=2597,name="Oninochi",area="alagh",terrain="hell3",info="",notes="",x=15,y=3,z=0,building=""}
M[#M+1] = {uid=2598,name="Oninochi",area="alagh",terrain="hell1",info="",notes="",x=16,y=3,z=0,building=""}
M[#M+1] = {uid=2599,name="Mistridge Forest",area="alagh",terrain="forest",info="",notes="",x=17,y=3,z=0,building=""}
M[#M+1] = {uid=2600,name="Mistridge Forest",area="alagh",terrain="forest",info="",notes="",x=18,y=3,z=0,building=""}
M[#M+1] = {uid=2601,name="Fainacen",area="alagh",terrain="hell1",info="",notes="",x=19,y=3,z=0,building=""}
M[#M+1] = {uid=2602,name="The Radiant Coast",area="alagh",terrain="ocean",info="",notes="",x=20,y=3,z=0,building=""}
M[#M+1] = {uid=2603,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=21,y=3,z=0,building=""}
M[#M+1] = {uid=2604,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=22,y=3,z=0,building=""}
M[#M+1] = {uid=2605,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=23,y=3,z=0,building=""}
M[#M+1] = {uid=2606,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=24,y=3,z=0,building=""}
M[#M+1] = {uid=2607,name="Morlergar Island",area="alagh",terrain="hell1",info="",notes="",x=25,y=3,z=0,building=""}
M[#M+1] = {uid=2608,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=26,y=3,z=0,building=""}
M[#M+1] = {uid=2609,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=27,y=3,z=0,building=""}
M[#M+1] = {uid=2610,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=28,y=3,z=0,building=""}
M[#M+1] = {uid=2611,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=29,y=3,z=0,building=""}
M[#M+1] = {uid=2612,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=0,y=4,z=0,building=""}
M[#M+1] = {uid=2613,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=1,y=4,z=0,building=""}
M[#M+1] = {uid=2614,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=2,y=4,z=0,building=""}
M[#M+1] = {uid=2615,name="Channel of Vapours",area="alagh",terrain="ocean",info="",notes="",x=3,y=4,z=0,building=""}
M[#M+1] = {uid=2616,name="Channel of Vapours",area="alagh",terrain="ocean",info="",notes="",x=4,y=4,z=0,building=""}
M[#M+1] = {uid=2617,name="Ghostly Sands",area="alagh",terrain="beach",info="",notes="",x=5,y=4,z=0,building=""}
M[#M+1] = {uid=2618,name="Desolate Hills",area="alagh",terrain="hell3",info="",notes="",x=6,y=4,z=0,building=""}
M[#M+1] = {uid=2619,name="Desolate Hills",area="alagh",terrain="hell3",info="",notes="",x=7,y=4,z=0,building=""}
M[#M+1] = {uid=2620,name="Entering a Forgotten Battlefield",area="alagh",terrain="plain",info="",notes="",x=8,y=4,z=0,building=""}
M[#M+1] = {uid=2621,name="Beside Jerrin S'reedith's House",area="alagh",terrain="plain",info="",notes="",x=9,y=4,z=0,building=""}
M[#M+1] = {uid=2622,name="The Blood plains of Battle",area="alagh",terrain="areaexit",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=2623,name="Next to a Small House",area="alagh",terrain="plain",info="",notes="",x=11,y=4,z=0,building=""}
M[#M+1] = {uid=2624,name="The Grave of Merriv D'kratos",area="alagh",terrain="plain",info="",notes="",x=12,y=4,z=0,building=""}
M[#M+1] = {uid=2625,name="Amidst Gigantic Craters",area="alagh",terrain="plain",info="",notes="",x=13,y=4,z=0,building=""}
M[#M+1] = {uid=2626,name="Before Lord Takeda's Gates",area="alagh",terrain="plain",info="",notes="",x=14,y=4,z=0,building=""}
M[#M+1] = {uid=2627,name="Oninochi",area="alagh",terrain="hell3",info="",notes="",x=15,y=4,z=0,building=""}
M[#M+1] = {uid=2628,name="Oninochi",area="alagh",terrain="hell3",info="",notes="",x=16,y=4,z=0,building=""}
M[#M+1] = {uid=2629,name="Fainacen",area="alagh",terrain="hell3",info="",notes="",x=17,y=4,z=0,building=""}
M[#M+1] = {uid=2630,name="Fainacen",area="alagh",terrain="hell1",info="",notes="",x=18,y=4,z=0,building=""}
M[#M+1] = {uid=2631,name="Fainacen",area="alagh",terrain="hell3",info="",notes="",x=19,y=4,z=0,building=""}
M[#M+1] = {uid=2632,name="The Radiant Coast",area="alagh",terrain="ocean",info="",notes="",x=20,y=4,z=0,building=""}
M[#M+1] = {uid=2633,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=21,y=4,z=0,building=""}
M[#M+1] = {uid=2634,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=22,y=4,z=0,building=""}
M[#M+1] = {uid=2635,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=23,y=4,z=0,building=""}
M[#M+1] = {uid=2636,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=24,y=4,z=0,building=""}
M[#M+1] = {uid=2637,name="Misty Channel",area="alagh",terrain="ocean",info="",notes="",x=25,y=4,z=0,building=""}
M[#M+1] = {uid=2638,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=26,y=4,z=0,building=""}
M[#M+1] = {uid=2639,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=27,y=4,z=0,building=""}
M[#M+1] = {uid=2640,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=28,y=4,z=0,building=""}
M[#M+1] = {uid=2641,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=29,y=4,z=0,building=""}
M[#M+1] = {uid=2642,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=0,y=5,z=0,building=""}
M[#M+1] = {uid=2643,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=1,y=5,z=0,building=""}
M[#M+1] = {uid=2644,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=2,y=5,z=0,building=""}
M[#M+1] = {uid=2645,name="Colossal Golem",area="alagh",terrain="hell2",info="",notes="",x=3,y=5,z=0,building=""}
M[#M+1] = {uid=2646,name="The Unliving Coast",area="alagh",terrain="beach",info="",notes="",x=4,y=5,z=0,building=""}
M[#M+1] = {uid=2647,name="The Unliving Coast",area="alagh",terrain="beach",info="",notes="",x=5,y=5,z=0,building=""}
M[#M+1] = {uid=2648,name="The Unliving Lands",area="alagh",terrain="hell3",info="",notes="",x=6,y=5,z=0,building=""}
M[#M+1] = {uid=2649,name="The Unliving Lands",area="alagh",terrain="hell2",info="",notes="",x=7,y=5,z=0,building=""}
M[#M+1] = {uid=2650,name="The Edge of an Ancient Battlefield",area="alagh",terrain="plain",info="",notes="",x=8,y=5,z=0,building=""}
M[#M+1] = {uid=2651,name="Amongst a Patch of Thorny Bushes",area="alagh",terrain="plain",info="",notes="",x=9,y=5,z=0,building=""}
M[#M+1] = {uid=2652,name="Jerrin S'reedith's Front Yard",area="alagh",terrain="plain",info="",notes="",x=10,y=5,z=0,building=""}
M[#M+1] = {uid=2653,name="A Barren Spot on the Plains",area="alagh",terrain="plain",info="",notes="",x=11,y=5,z=0,building=""}
M[#M+1] = {uid=2654,name="Haunted Grounds",area="alagh",terrain="plain",info="",notes="",x=12,y=5,z=0,building=""}
M[#M+1] = {uid=2655,name="Blasted Fields",area="alagh",terrain="plain",info="",notes="",x=13,y=5,z=0,building=""}
M[#M+1] = {uid=2656,name="The Living Statues",area="alagh",terrain="plain",info="",notes="",x=14,y=5,z=0,building=""}
M[#M+1] = {uid=2657,name="Snowy Fields",area="alagh",terrain="plain",info="",notes="",x=15,y=5,z=0,building=""}
M[#M+1] = {uid=2658,name="Frozen Ground",area="alagh",terrain="plain",info="",notes="",x=16,y=5,z=0,building=""}
M[#M+1] = {uid=2659,name="Fainacen",area="alagh",terrain="hell3",info="",notes="",x=17,y=5,z=0,building=""}
M[#M+1] = {uid=2660,name="Fainacen",area="alagh",terrain="hell3",info="",notes="",x=18,y=5,z=0,building=""}
M[#M+1] = {uid=2661,name="Fainacen",area="alagh",terrain="hell2",info="",notes="",x=19,y=5,z=0,building=""}
M[#M+1] = {uid=2662,name="Fainacen",area="alagh",terrain="hell3",info="",notes="",x=20,y=5,z=0,building=""}
M[#M+1] = {uid=2663,name="The Radiant Coast",area="alagh",terrain="ocean",info="",notes="",x=21,y=5,z=0,building=""}
M[#M+1] = {uid=2664,name="The Radiant Coast",area="alagh",terrain="ocean",info="",notes="",x=22,y=5,z=0,building=""}
M[#M+1] = {uid=2665,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=23,y=5,z=0,building=""}
M[#M+1] = {uid=2666,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=24,y=5,z=0,building=""}
M[#M+1] = {uid=2667,name="Eikharterikh Island",area="alagh",terrain="hell1",info="",notes="",x=25,y=5,z=0,building=""}
M[#M+1] = {uid=2668,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=26,y=5,z=0,building=""}
M[#M+1] = {uid=2669,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=27,y=5,z=0,building=""}
M[#M+1] = {uid=2670,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=28,y=5,z=0,building=""}
M[#M+1] = {uid=2671,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=29,y=5,z=0,building=""}
M[#M+1] = {uid=2672,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=0,y=6,z=0,building=""}
M[#M+1] = {uid=2673,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=1,y=6,z=0,building=""}
M[#M+1] = {uid=2674,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=2,y=6,z=0,building=""}
M[#M+1] = {uid=2675,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=3,y=6,z=0,building=""}
M[#M+1] = {uid=2676,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=4,y=6,z=0,building=""}
M[#M+1] = {uid=2677,name="The Unliving Coast",area="alagh",terrain="beach",info="",notes="",x=5,y=6,z=0,building=""}
M[#M+1] = {uid=2678,name="The Unliving Lands",area="alagh",terrain="hell1",info="",notes="",x=6,y=6,z=0,building=""}
M[#M+1] = {uid=2679,name="Stepping onto an Old Battleground",area="alagh",terrain="plain",info="",notes="",x=7,y=6,z=0,building=""}
M[#M+1] = {uid=2680,name="An Unmarked Grave",area="alagh",terrain="plain",info="",notes="",x=8,y=6,z=0,building=""}
M[#M+1] = {uid=2681,name="Peaceful Planes",area="alagh",terrain="plain",info="",notes="",x=9,y=6,z=0,building=""}
M[#M+1] = {uid=2682,name="The Beginning of a Gorge",area="alagh",terrain="plain",info="",notes="",x=10,y=6,z=0,building=""}
M[#M+1] = {uid=2683,name="Continuing Along the Fissure",area="alagh",terrain="plain",info="",notes="",x=11,y=6,z=0,building=""}
M[#M+1] = {uid=2684,name="A Deep Scar in the Earth",area="alagh",terrain="plain",info="",notes="",x=12,y=6,z=0,building=""}
M[#M+1] = {uid=2685,name="Continuing Along the Fissure",area="alagh",terrain="plain",info="",notes="",x=13,y=6,z=0,building=""}
M[#M+1] = {uid=2686,name="The End of a Deep Gorge",area="alagh",terrain="plain",info="",notes="",x=14,y=6,z=0,building=""}
M[#M+1] = {uid=2687,name="Atop the Permafrost",area="alagh",terrain="plain",info="",notes="",x=15,y=6,z=0,building=""}
M[#M+1] = {uid=2688,name="Bitterly Cold Plains",area="alagh",terrain="plain",info="",notes="",x=16,y=6,z=0,building=""}
M[#M+1] = {uid=2689,name="A Thawing Battlefield",area="alagh",terrain="plain",info="",notes="",x=17,y=6,z=0,building=""}
M[#M+1] = {uid=2690,name="Fainacen",area="alagh",terrain="hell2",info="",notes="",x=18,y=6,z=0,building=""}
M[#M+1] = {uid=2691,name="Fainacen",area="alagh",terrain="hell1",info="",notes="",x=19,y=6,z=0,building=""}
M[#M+1] = {uid=2692,name="Fainacen",area="alagh",terrain="hell3",info="",notes="",x=20,y=6,z=0,building=""}
M[#M+1] = {uid=2693,name="Fainacen",area="alagh",terrain="hell1",info="",notes="",x=21,y=6,z=0,building=""}
M[#M+1] = {uid=2694,name="The Radiant Coast",area="alagh",terrain="ocean",info="",notes="",x=22,y=6,z=0,building=""}
M[#M+1] = {uid=2695,name="The Radiant Coast",area="alagh",terrain="ocean",info="",notes="",x=23,y=6,z=0,building=""}
M[#M+1] = {uid=2696,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=24,y=6,z=0,building=""}
M[#M+1] = {uid=2697,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=25,y=6,z=0,building=""}
M[#M+1] = {uid=2698,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=26,y=6,z=0,building=""}
M[#M+1] = {uid=2699,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=27,y=6,z=0,building=""}
M[#M+1] = {uid=2700,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=28,y=6,z=0,building=""}
M[#M+1] = {uid=2701,name="Northern Lem-Dagor",area="alagh",terrain="ocean",info="",notes="",x=29,y=6,z=0,building=""}
M[#M+1] = {uid=2702,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=0,y=7,z=0,building=""}
M[#M+1] = {uid=2703,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=1,y=7,z=0,building=""}
M[#M+1] = {uid=2704,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=2,y=7,z=0,building=""}
M[#M+1] = {uid=2705,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=3,y=7,z=0,building=""}
M[#M+1] = {uid=2706,name="The Unliving Coast",area="alagh",terrain="beach",info="",notes="",x=4,y=7,z=0,building=""}
M[#M+1] = {uid=2707,name="The Unliving Coast",area="alagh",terrain="beach",info="",notes="",x=5,y=7,z=0,building=""}
M[#M+1] = {uid=2708,name="The Unliving Lands",area="alagh",terrain="hell3",info="",notes="",x=6,y=7,z=0,building=""}
M[#M+1] = {uid=2709,name="Entering Sangu'ter",area="alagh",terrain="plain",info="",notes="",x=7,y=7,z=0,building=""}
M[#M+1] = {uid=2710,name="Standing upon Sangu'ter",area="alagh",terrain="plain",info="",notes="",x=8,y=7,z=0,building=""}
M[#M+1] = {uid=2711,name="A Badly Burned Field",area="alagh",terrain="plain",info="",notes="",x=9,y=7,z=0,building=""}
M[#M+1] = {uid=2712,name="North of the Giant Dune",area="alagh",terrain="plain",info="",notes="",x=10,y=7,z=0,building=""}
M[#M+1] = {uid=2713,name="Wind Swept Sands",area="alagh",terrain="plain",info="",notes="",x=11,y=7,z=0,building=""}
M[#M+1] = {uid=2714,name="A Burnt Field",area="alagh",terrain="plain",info="",notes="",x=12,y=7,z=0,building=""}
M[#M+1] = {uid=2715,name="A Soothing Place",area="alagh",terrain="plain",info="",notes="",x=13,y=7,z=0,building=""}
M[#M+1] = {uid=2716,name="Surrounded by Rusting Relics",area="alagh",terrain="plain",info="",notes="",x=14,y=7,z=0,building=""}
M[#M+1] = {uid=2717,name="An Eternally Raging Blizzard",area="alagh",terrain="plain",info="",notes="",x=15,y=7,z=0,building=""}
M[#M+1] = {uid=2718,name="Desolate Earth",area="alagh",terrain="plain",info="",notes="",x=16,y=7,z=0,building=""}
M[#M+1] = {uid=2719,name="A Sanguine Stream",area="alagh",terrain="plain",info="",notes="",x=17,y=7,z=0,building=""}
M[#M+1] = {uid=2720,name="Surrounded by Red Sands",area="alagh",terrain="plain",info="",notes="",x=18,y=7,z=0,building=""}
M[#M+1] = {uid=2721,name="Fainacen",area="alagh",terrain="hell2",info="",notes="",x=19,y=7,z=0,building=""}
M[#M+1] = {uid=2722,name="Fainacen",area="alagh",terrain="hell2",info="",notes="",x=20,y=7,z=0,building=""}
M[#M+1] = {uid=2723,name="Fainacen",area="alagh",terrain="hell3",info="",notes="",x=21,y=7,z=0,building=""}
M[#M+1] = {uid=2724,name="Fainacen Lighthouse",area="alagh",terrain="hell2",info="",notes="",x=22,y=7,z=0,building=""}
M[#M+1] = {uid=2725,name="The Radiant Coast",area="alagh",terrain="ocean",info="",notes="",x=23,y=7,z=0,building=""}
M[#M+1] = {uid=2726,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=24,y=7,z=0,building=""}
M[#M+1] = {uid=2727,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=25,y=7,z=0,building=""}
M[#M+1] = {uid=2728,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=26,y=7,z=0,building=""}
M[#M+1] = {uid=2729,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=27,y=7,z=0,building=""}
M[#M+1] = {uid=2730,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=28,y=7,z=0,building=""}
M[#M+1] = {uid=2731,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=29,y=7,z=0,building=""}
M[#M+1] = {uid=2732,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=0,y=8,z=0,building=""}
M[#M+1] = {uid=2733,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=1,y=8,z=0,building=""}
M[#M+1] = {uid=2734,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=2,y=8,z=0,building=""}
M[#M+1] = {uid=2735,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=3,y=8,z=0,building=""}
M[#M+1] = {uid=2736,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=4,y=8,z=0,building=""}
M[#M+1] = {uid=2737,name="The Unliving Coast",area="alagh",terrain="beach",info="",notes="",x=5,y=8,z=0,building=""}
M[#M+1] = {uid=2738,name="The Unliving Lands",area="alagh",terrain="hell1",info="",notes="",x=6,y=8,z=0,building=""}
M[#M+1] = {uid=2739,name="A Windy Steppe",area="alagh",terrain="plain",info="",notes="",x=7,y=8,z=0,building=""}
M[#M+1] = {uid=2740,name="Gettor'ak Arch",area="alagh",terrain="plain",info="",notes="",x=8,y=8,z=0,building=""}
M[#M+1] = {uid=2741,name="West of the Giant Dune",area="alagh",terrain="plain",info="",notes="",x=9,y=8,z=0,building=""}
M[#M+1] = {uid=2742,name="The Foot of a Giant Dune",area="alagh",terrain="plain",info="",notes="",x=10,y=8,z=0,building=""}
M[#M+1] = {uid=2743,name="East of the Giant Dune",area="alagh",terrain="plain",info="",notes="",x=11,y=8,z=0,building=""}
M[#M+1] = {uid=2744,name="Underneath a Tattered Flag",area="alagh",terrain="plain",info="",notes="",x=12,y=8,z=0,building=""}
M[#M+1] = {uid=2745,name="The Remains of a War Machine",area="alagh",terrain="plain",info="",notes="",x=13,y=8,z=0,building=""}
M[#M+1] = {uid=2746,name="The Buried Relics of Sangu'ter",area="alagh",terrain="plain",info="",notes="",x=14,y=8,z=0,building=""}
M[#M+1] = {uid=2747,name="Fields of Rot and Decay",area="alagh",terrain="plain",info="",notes="",x=15,y=8,z=0,building=""}
M[#M+1] = {uid=2748,name="Encircled by Rusted Remnants",area="alagh",terrain="plain",info="",notes="",x=16,y=8,z=0,building=""}
M[#M+1] = {uid=2749,name="The Outskirts of a Battlefield",area="alagh",terrain="plain",info="",notes="",x=17,y=8,z=0,building=""}
M[#M+1] = {uid=2750,name="Fainacen",area="alagh",terrain="hell2",info="",notes="",x=18,y=8,z=0,building=""}
M[#M+1] = {uid=2751,name="Fainacen",area="alagh",terrain="hell2",info="",notes="",x=19,y=8,z=0,building=""}
M[#M+1] = {uid=2752,name="Fainacen",area="alagh",terrain="hell3",info="",notes="",x=20,y=8,z=0,building=""}
M[#M+1] = {uid=2753,name="Fainacen",area="alagh",terrain="hell2",info="",notes="",x=21,y=8,z=0,building=""}
M[#M+1] = {uid=2754,name="Cape Fainacen",area="alagh",terrain="hell1",info="",notes="",x=22,y=8,z=0,building=""}
M[#M+1] = {uid=2755,name="The Radiant Coast",area="alagh",terrain="ocean",info="",notes="",x=23,y=8,z=0,building=""}
M[#M+1] = {uid=2756,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=24,y=8,z=0,building=""}
M[#M+1] = {uid=2757,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=25,y=8,z=0,building=""}
M[#M+1] = {uid=2758,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=26,y=8,z=0,building=""}
M[#M+1] = {uid=2759,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=27,y=8,z=0,building=""}
M[#M+1] = {uid=2760,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=28,y=8,z=0,building=""}
M[#M+1] = {uid=2761,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=29,y=8,z=0,building=""}
M[#M+1] = {uid=2762,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=0,y=9,z=0,building=""}
M[#M+1] = {uid=2763,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=1,y=9,z=0,building=""}
M[#M+1] = {uid=2764,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=2,y=9,z=0,building=""}
M[#M+1] = {uid=2765,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=3,y=9,z=0,building=""}
M[#M+1] = {uid=2766,name="The Unliving Coast",area="alagh",terrain="beach",info="",notes="",x=4,y=9,z=0,building=""}
M[#M+1] = {uid=2767,name="The Unliving Coast",area="alagh",terrain="beach",info="",notes="",x=5,y=9,z=0,building=""}
M[#M+1] = {uid=2768,name="The Unliving Lands",area="alagh",terrain="hell3",info="",notes="",x=6,y=9,z=0,building=""}
M[#M+1] = {uid=2769,name="The Unliving Lands",area="alagh",terrain="hell2",info="",notes="",x=7,y=9,z=0,building=""}
M[#M+1] = {uid=2770,name="A Path to Aphasia",area="alagh",terrain="plain",info="",notes="",x=8,y=9,z=0,building=""}
M[#M+1] = {uid=2771,name="Approaching a Sandy Dune",area="alagh",terrain="plain",info="",notes="",x=9,y=9,z=0,building=""}
M[#M+1] = {uid=2772,name="South of the Giant Dune",area="alagh",terrain="plain",info="",notes="",x=10,y=9,z=0,building=""}
M[#M+1] = {uid=2773,name="In the Shadow of a Giant Monolith",area="alagh",terrain="plain",info="",notes="",x=11,y=9,z=0,building=""}
M[#M+1] = {uid=2774,name="Awestruck by a Massive Monolith",area="alagh",terrain="plain",info="",notes="",x=12,y=9,z=0,building=""}
M[#M+1] = {uid=2775,name="A Bare Spot on the Plains",area="alagh",terrain="plain",info="",notes="",x=13,y=9,z=0,building=""}
M[#M+1] = {uid=2776,name="Slow Growing Foliage",area="alagh",terrain="plain",info="",notes="",x=14,y=9,z=0,building=""}
M[#M+1] = {uid=2777,name="Wind Stripped Ground",area="alagh",terrain="plain",info="",notes="",x=15,y=9,z=0,building=""}
M[#M+1] = {uid=2778,name="On the Edge of the Battlegrounds",area="alagh",terrain="plain",info="",notes="",x=16,y=9,z=0,building=""}
M[#M+1] = {uid=2779,name="Evilstar Coast",area="alagh",terrain="hell3",info="",notes="",x=17,y=9,z=0,building=""}
M[#M+1] = {uid=2780,name="Evilstar Coast",area="alagh",terrain="hell2",info="",notes="",x=18,y=9,z=0,building=""}
M[#M+1] = {uid=2781,name="Eahdroma Bay",area="alagh",terrain="ocean",info="",notes="",x=19,y=9,z=0,building=""}
M[#M+1] = {uid=2782,name="Horn Bay",area="alagh",terrain="ocean",info="",notes="",x=20,y=9,z=0,building=""}
M[#M+1] = {uid=2783,name="Horn Bay",area="alagh",terrain="ocean",info="",notes="",x=21,y=9,z=0,building=""}
M[#M+1] = {uid=2784,name="Horn Bay",area="alagh",terrain="ocean",info="",notes="",x=22,y=9,z=0,building=""}
M[#M+1] = {uid=2785,name="Horn Bay",area="alagh",terrain="ocean",info="",notes="",x=23,y=9,z=0,building=""}
M[#M+1] = {uid=2786,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=24,y=9,z=0,building=""}
M[#M+1] = {uid=2787,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=25,y=9,z=0,building=""}
M[#M+1] = {uid=2788,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=26,y=9,z=0,building=""}
M[#M+1] = {uid=2789,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=27,y=9,z=0,building=""}
M[#M+1] = {uid=2790,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=28,y=9,z=0,building=""}
M[#M+1] = {uid=2791,name="Sea of the Horn",area="alagh",terrain="ocean",info="",notes="",x=29,y=9,z=0,building=""}
M[#M+1] = {uid=2792,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=0,y=10,z=0,building=""}
M[#M+1] = {uid=2793,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=1,y=10,z=0,building=""}
M[#M+1] = {uid=2794,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=2,y=10,z=0,building=""}
M[#M+1] = {uid=2795,name="Aphasia",area="alagh",terrain="ocean",info="",notes="",x=3,y=10,z=0,building=""}
M[#M+1] = {uid=2796,name="The Unliving Coast",area="alagh",terrain="beach",info="",notes="",x=4,y=10,z=0,building=""}
M[#M+1] = {uid=2797,name="The Unliving Lands",area="alagh",terrain="hell2",info="",notes="",x=5,y=10,z=0,building=""}
M[#M+1] = {uid=2798,name="The Unliving Lands",area="alagh",terrain="hell1",info="",notes="",x=6,y=10,z=0,building=""}
M[#M+1] = {uid=2799,name="The Unliving Lands",area="alagh",terrain="hell2",info="",notes="",x=7,y=10,z=0,building=""}
M[#M+1] = {uid=2800,name="An Old Battlefield",area="alagh",terrain="plain",info="",notes="",x=8,y=10,z=0,building=""}
M[#M+1] = {uid=2801,name="An Elaborate Grave",area="alagh",terrain="plain",info="",notes="",x=9,y=10,z=0,building=""}
return M
