-- generated by tools/import-mushmap.py — do not edit
-- rooms 22501..22946
local M = {}
M[#M+1] = {uid=41996,name="Cyclops Lair",area="uprising",terrain="inside",info="",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=41997,name="A Widening Expanse",area="uprising",terrain="inside",info="",notes="",x=47,y=1,z=0,building=""}
M[#M+1] = {uid=41998,name="Nearing a Large Hole",area="uprising",terrain="inside",info="",notes="",x=46,y=1,z=0,building=""}
M[#M+1] = {uid=41999,name="Walking Around a Hole",area="uprising",terrain="inside",info="",notes="",x=46,y=0,z=0,building=""}
M[#M+1] = {uid=42135,name="Skirting Around a Hole",area="uprising",terrain="inside",info="",notes="",x=46,y=-1,z=0,building=""}
M[#M+1] = {uid=42136,name="Along the Northern Wall",area="uprising",terrain="inside",info="",notes="",x=45,y=-1,z=0,building=""}
M[#M+1] = {uid=42137,name="A Narrow Ledge",area="uprising",terrain="inside",info="",notes="",x=44,y=-1,z=0,building=""}
M[#M+1] = {uid=42138,name="A Lip over the Hole",area="uprising",terrain="inside",info="",notes="",x=44,y=0,z=0,building=""}
M[#M+1] = {uid=42139,name="Approaching the Lip",area="uprising",terrain="inside",info="",notes="",x=44,y=1,z=0,building=""}
M[#M+1] = {uid=42140,name="Nearing a Corridor",area="uprising",terrain="inside",info="",notes="",x=45,y=1,z=0,building=""}
M[#M+1] = {uid=42141,name="A Cleaned Corridor",area="uprising",terrain="inside",info="",notes="",x=45,y=2,z=0,building=""}
M[#M+1] = {uid=42142,name="An Opening in the Corridor",area="uprising",terrain="inside",info="",notes="",x=45,y=3,z=0,building=""}
M[#M+1] = {uid=42143,name="Before a Large Room",area="uprising",terrain="inside",info="",notes="",x=45,y=4,z=0,building=""}
M[#M+1] = {uid=42144,name="A Sleeping Dormitory",area="uprising",terrain="inside",info="",notes="",x=46,y=6,z=0,building=""}
M[#M+1] = {uid=42145,name="A Sleeping Dormitory",area="uprising",terrain="inside",info="",notes="",x=46,y=5,z=0,building=""}
M[#M+1] = {uid=42146,name="A Sleeping Dormitory",area="uprising",terrain="inside",info="",notes="",x=45,y=5,z=0,building=""}
M[#M+1] = {uid=42147,name="A Sleeping Dormitory",area="uprising",terrain="inside",info="",notes="",x=45,y=6,z=0,building=""}
M[#M+1] = {uid=42148,name="An Enchanter's Room",area="uprising",terrain="inside",info="",notes="",x=46,y=3,z=0,building=""}
M[#M+1] = {uid=42149,name="A Small Forge",area="uprising",terrain="inside",info="",notes="",x=44,y=3,z=0,building=""}
M[#M+1] = {uid=42150,name="A Cyclops Pit",area="uprising",terrain="cave",info="pk",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=42151,name="Entering the City Proper",area="uprising",terrain="ruins",info="",notes="",x=48,y=8,z=0,building=""}
M[#M+1] = {uid=42152,name="Southern Temple Road",area="uprising",terrain="city",info="",notes="",x=48,y=7,z=0,building=""}
M[#M+1] = {uid=42153,name="Southwestern Temple Road",area="uprising",terrain="city",info="",notes="",x=47,y=7,z=0,building=""}
M[#M+1] = {uid=42154,name="Northwestern Temple Road",area="uprising",terrain="city",info="",notes="",x=47,y=5,z=0,building=""}
M[#M+1] = {uid=42155,name="Northeastern Temple Road",area="uprising",terrain="city",info="",notes="",x=49,y=5,z=0,building=""}
M[#M+1] = {uid=42156,name="Entrance to the Temple of the Night",area="uprising",terrain="city",info="",notes="",x=49,y=6,z=0,building=""}
M[#M+1] = {uid=42157,name="Southeastern Temple Road",area="uprising",terrain="city",info="",notes="",x=49,y=7,z=0,building=""}
M[#M+1] = {uid=42158,name="A Burned-out Road",area="uprising",terrain="city",info="",notes="",x=50,y=7,z=0,building=""}
M[#M+1] = {uid=42370,name="An Impressive Hallway",area="terramire",terrain="inside",info="",notes="",x=47,y=3,z=1,building=""}
M[#M+1] = {uid=42371,name="Master Bedroom",area="terramire",terrain="inside",info="shop",notes="",x=47,y=2,z=1,building=""}
M[#M+1] = {uid=42372,name="A Kit's Bedroom",area="terramire",terrain="inside",info="",notes="",x=49,y=3,z=1,building=""}
M[#M+1] = {uid=42373,name="An Impressive Hallway",area="terramire",terrain="inside",info="",notes="",x=48,y=3,z=1,building=""}
M[#M+1] = {uid=42374,name="The Living Area",area="terramire",terrain="inside",info="",notes="",x=47,y=2,z=0,building=""}
M[#M+1] = {uid=43150,name="A room with a view! (Atop the platform)",area="ascent",terrain="areaexit",info="safe,shop",notes="",x=30,y=20,z=0,building=""}
M[#M+1] = {uid=43151,name="Dark and forgotten",area="ascent",terrain="inside",info="",notes="",x=30,y=20,z=1,building=""}
M[#M+1] = {uid=43152,name="A focusing lens glows with enormous arcane power",area="ascent",terrain="inside",info="",notes="",x=30,y=20,z=2,building=""}
M[#M+1] = {uid=43153,name="Port side power conversion room",area="ascent",terrain="inside",info="",notes="",x=30,y=19,z=2,building=""}
M[#M+1] = {uid=43155,name="A complex reduction gear",area="ascent",terrain="inside",info="",notes="",x=31,y=19,z=2,building=""}
M[#M+1] = {uid=43157,name="The shaft",area="ascent",terrain="inside",info="",notes="",x=31,y=19,z=3,building=""}
M[#M+1] = {uid=43158,name="A long sterile passageway ends here",area="ascent",terrain="inside",info="",notes="",x=32,y=22,z=3,building=""}
M[#M+1] = {uid=43159,name="A long sterile passageway continues",area="ascent",terrain="inside",info="",notes="",x=32,y=21,z=3,building=""}
M[#M+1] = {uid=43160,name="A long sterile passageway with access to the catwalk",area="ascent",terrain="inside",info="",notes="",x=32,y=20,z=3,building=""}
M[#M+1] = {uid=43161,name="Control station",area="ascent",terrain="inside",info="",notes="",x=32,y=19,z=3,building=""}
M[#M+1] = {uid=43162,name="A long sterile passageway",area="ascent",terrain="inside",info="",notes="",x=32,y=18,z=3,building=""}
M[#M+1] = {uid=43163,name="A long sterile passageway with access to the catwalk",area="ascent",terrain="inside",info="",notes="",x=32,y=17,z=3,building=""}
M[#M+1] = {uid=43164,name="A long sterile passageway continues",area="ascent",terrain="inside",info="",notes="",x=32,y=16,z=3,building=""}
M[#M+1] = {uid=43165,name="A long sterile passageway ends here",area="ascent",terrain="inside",info="",notes="",x=32,y=15,z=3,building=""}
M[#M+1] = {uid=43166,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=34,y=21,z=3,building=""}
M[#M+1] = {uid=43167,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=34,y=20,z=3,building=""}
M[#M+1] = {uid=43168,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=34,y=19,z=3,building=""}
M[#M+1] = {uid=43169,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=34,y=18,z=3,building=""}
M[#M+1] = {uid=43170,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=34,y=17,z=3,building=""}
M[#M+1] = {uid=43171,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=34,y=16,z=3,building=""}
M[#M+1] = {uid=43172,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=35,y=16,z=3,building=""}
M[#M+1] = {uid=43173,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=36,y=16,z=3,building=""}
M[#M+1] = {uid=43174,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=37,y=16,z=3,building=""}
M[#M+1] = {uid=43175,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=37,y=17,z=3,building=""}
M[#M+1] = {uid=43176,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=37,y=18,z=3,building=""}
M[#M+1] = {uid=43177,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=37,y=19,z=3,building=""}
M[#M+1] = {uid=43178,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=37,y=20,z=3,building=""}
M[#M+1] = {uid=43179,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=37,y=21,z=3,building=""}
M[#M+1] = {uid=43180,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=36,y=21,z=3,building=""}
M[#M+1] = {uid=43181,name="A catwalk overlooking the exercise yard",area="ascent",terrain="inside",info="",notes="",x=35,y=21,z=3,building=""}
M[#M+1] = {uid=43182,name="Basketball Court",area="ascent",terrain="inside",info="",notes="",x=34,y=20,z=2,building=""}
M[#M+1] = {uid=43183,name="The Weight Room (West side)",area="ascent",terrain="inside",info="",notes="",x=34,y=18,z=2,building=""}
M[#M+1] = {uid=43184,name="The Combat Ring (Magic allowed)",area="ascent",terrain="inside",info="pk",notes="",x=34,y=17,z=2,building=""}
M[#M+1] = {uid=43185,name="The Combat Ring (NO Magic Allowed)",area="ascent",terrain="inside",info="pk",notes="",x=35,y=17,z=2,building=""}
M[#M+1] = {uid=43186,name="The Weight Room (East side)",area="ascent",terrain="inside",info="",notes="",x=35,y=18,z=2,building=""}
M[#M+1] = {uid=43187,name="Arts and Crafts - Bludgeons",area="ascent",terrain="inside",info="",notes="",x=35,y=19,z=2,building=""}
M[#M+1] = {uid=43188,name="Basketball Court",area="ascent",terrain="inside",info="",notes="",x=35,y=20,z=2,building=""}
M[#M+1] = {uid=43189,name="A bridge to the catwalk",area="ascent",terrain="inside",info="",notes="",x=33,y=20,z=3,building=""}
M[#M+1] = {uid=43190,name="A bridge to the catwalk",area="ascent",terrain="inside",info="",notes="",x=33,y=17,z=3,building=""}
M[#M+1] = {uid=43191,name="Arts and Crafts - Shivs",area="ascent",terrain="inside",info="",notes="",x=34,y=19,z=2,building=""}
M[#M+1] = {uid=43192,name="The top of the stairs",area="ascent",terrain="inside",info="",notes="",x=32,y=22,z=4,building=""}
M[#M+1] = {uid=43193,name="A branching corridor",area="ascent",terrain="inside",info="",notes="",x=32,y=21,z=4,building=""}
M[#M+1] = {uid=43194,name="A stretch of echoing corridor",area="ascent",terrain="inside",info="",notes="",x=32,y=20,z=4,building=""}
M[#M+1] = {uid=43195,name="An intersection",area="ascent",terrain="inside",info="",notes="",x=32,y=19,z=4,building=""}
M[#M+1] = {uid=43196,name="A room beside the elevator room",area="ascent",terrain="inside",info="",notes="",x=32,y=18,z=4,building=""}
M[#M+1] = {uid=43197,name="The elevator room",area="ascent",terrain="inside",info="",notes="",x=32,y=17,z=4,building=""}
M[#M+1] = {uid=43198,name="A room beside the elevator room",area="ascent",terrain="inside",info="",notes="",x=32,y=18,z=4,building=""}
M[#M+1] = {uid=43199,name="Gateway to the cell blocks",area="ascent",terrain="inside",info="",notes="",x=32,y=17,z=4,building=""}
M[#M+1] = {uid=43200,name="The back of the prison",area="ascent",terrain="inside",info="",notes="",x=32,y=16,z=4,building=""}
M[#M+1] = {uid=43201,name="The top of the stairs at the back of the prison",area="ascent",terrain="inside",info="",notes="",x=32,y=15,z=4,building=""}
M[#M+1] = {uid=43202,name="Cell block A",area="ascent",terrain="inside",info="",notes="",x=31,y=17,z=4,building=""}
M[#M+1] = {uid=43211,name="Cell Block B",area="ascent",terrain="inside",info="",notes="",x=30,y=17,z=4,building=""}
M[#M+1] = {uid=43219,name="Trustee lounge",area="ascent",terrain="inside",info="pk",notes="",x=28,y=17,z=4,building=""}
M[#M+1] = {uid=43220,name="Cell block C (Front)",area="ascent",terrain="inside",info="",notes="",x=29,y=17,z=4,building=""}
M[#M+1] = {uid=43221,name="Cell block C (Back) TRUSTEES ONLY",area="ascent",terrain="inside",info="",notes="",x=27,y=17,z=4,building=""}
M[#M+1] = {uid=43222,name="Cell C2B",area="ascent",terrain="inside",info="",notes="",x=27,y=18,z=4,building=""}
M[#M+1] = {uid=43223,name="Cell C1B",area="ascent",terrain="inside",info="",notes="",x=27,y=16,z=4,building=""}
M[#M+1] = {uid=43224,name="Cell C1F",area="ascent",terrain="inside",info="",notes="",x=29,y=16,z=4,building=""}
M[#M+1] = {uid=43225,name="Cell C2F",area="ascent",terrain="inside",info="",notes="",x=29,y=18,z=4,building=""}
M[#M+1] = {uid=43233,name="Entrance to the bull pen",area="ascent",terrain="inside",info="",notes="",x=31,y=19,z=4,building=""}
M[#M+1] = {uid=43234,name="A corner in the bull pen",area="ascent",terrain="inside",info="",notes="",x=29,y=18,z=4,building=""}
M[#M+1] = {uid=43235,name="The South side of the bull pen",area="ascent",terrain="inside",info="",notes="",x=30,y=19,z=4,building=""}
M[#M+1] = {uid=43236,name="The North side of the bull pen",area="ascent",terrain="inside",info="",notes="",x=30,y=18,z=4,building=""}
M[#M+1] = {uid=43237,name="Near the center of the bull pen",area="ascent",terrain="inside",info="",notes="",x=29,y=19,z=4,building=""}
M[#M+1] = {uid=43238,name="A corner in the bull pen",area="ascent",terrain="inside",info="",notes="",x=29,y=20,z=4,building=""}
M[#M+1] = {uid=43239,name="A stubby wooden diving board",area="ascent",terrain="waterswim",info="",notes="",x=36,y=20,z=4,building=""}
M[#M+1] = {uid=43240,name="The shallow end of the pool",area="ascent",terrain="waterswim",info="pk",notes="",x=33,y=21,z=4,building=""}
M[#M+1] = {uid=43241,name="The middle of the pool",area="ascent",terrain="waterswim",info="",notes="",x=34,y=20,z=4,building=""}
M[#M+1] = {uid=43242,name="The middle of the pool",area="ascent",terrain="waterswim",info="",notes="",x=34,y=21,z=4,building=""}
M[#M+1] = {uid=43243,name="The deep end of the pool",area="ascent",terrain="waterswim",info="",notes="",x=35,y=20,z=4,building=""}
M[#M+1] = {uid=43244,name="The deep end of the pool",area="ascent",terrain="waterswim",info="",notes="",x=35,y=21,z=4,building=""}
M[#M+1] = {uid=43245,name="A cell in maximum security",area="ascent",terrain="inside",info="",notes="",x=32,y=17,z=5,building=""}
M[#M+1] = {uid=43246,name="A cell in maximum security",area="ascent",terrain="inside",info="",notes="",x=32,y=17,z=6,building=""}
M[#M+1] = {uid=43247,name="A cell in maximum security",area="ascent",terrain="inside",info="",notes="",x=32,y=17,z=7,building=""}
M[#M+1] = {uid=43248,name="A cell in maximum security",area="ascent",terrain="inside",info="",notes="",x=32,y=17,z=8,building=""}
M[#M+1] = {uid=43249,name="Maximum confinement",area="ascent",terrain="inside",info="",notes="",x=32,y=18,z=8,building=""}
M[#M+1] = {uid=43250,name="A dark forest",area="siege",terrain="forest",info="",notes="",x=10,y=15,z=0,building=""}
M[#M+1] = {uid=43251,name="A dark forest",area="siege",terrain="forest",info="",notes="",x=10,y=14,z=0,building=""}
M[#M+1] = {uid=43252,name="A dark forest",area="siege",terrain="forest",info="",notes="",x=10,y=13,z=0,building=""}
M[#M+1] = {uid=43253,name="A dark forest",area="siege",terrain="forest",info="",notes="",x=10,y=12,z=0,building=""}
M[#M+1] = {uid=43254,name="A dark forest",area="siege",terrain="forest",info="",notes="",x=9,y=13,z=0,building=""}
M[#M+1] = {uid=43255,name="A dark forest",area="siege",terrain="forest",info="",notes="",x=10,y=16,z=0,building=""}
M[#M+1] = {uid=43256,name="A dark intersection",area="siege",terrain="forest",info="",notes="",x=10,y=17,z=0,building=""}
M[#M+1] = {uid=43257,name="A dark forest",area="siege",terrain="forest",info="",notes="",x=9,y=17,z=0,building=""}
M[#M+1] = {uid=43258,name="A dark forest",area="siege",terrain="forest",info="",notes="",x=10,y=18,z=0,building=""}
M[#M+1] = {uid=43259,name="A dark forest",area="siege",terrain="forest",info="",notes="",x=11,y=18,z=0,building=""}
M[#M+1] = {uid=43260,name="A dark forest",area="siege",terrain="forest",info="",notes="",x=11,y=17,z=0,building=""}
M[#M+1] = {uid=43261,name="A dark forest",area="siege",terrain="forest",info="",notes="",x=11,y=13,z=0,building=""}
M[#M+1] = {uid=43262,name="The top of a tall tree",area="siege",terrain="forest",info="",notes="",x=10,y=15,z=0,building=""}
M[#M+1] = {uid=43263,name="A dark forest",area="siege",terrain="forest",info="",notes="",x=8,y=13,z=0,building=""}
M[#M+1] = {uid=43264,name="A dark forest",area="siege",terrain="forest",info="",notes="",x=8,y=17,z=0,building=""}
M[#M+1] = {uid=43265,name="A bright path",area="siege",terrain="forest",info="",notes="",x=11,y=15,z=0,building=""}
M[#M+1] = {uid=43267,name="Entrance to the Warcamp",area="siege",terrain="trail_ew",info="",notes="",x=12,y=15,z=0,building=""}
M[#M+1] = {uid=43268,name="A path through the camp",area="siege",terrain="trail_ew",info="",notes="",x=12,y=16,z=0,building=""}
M[#M+1] = {uid=43269,name="A path through the camp",area="siege",terrain="trail_ew",info="",notes="",x=12,y=17,z=0,building=""}
M[#M+1] = {uid=43270,name="A path through the camp",area="siege",terrain="trail_ew",info="",notes="",x=12,y=18,z=0,building=""}
M[#M+1] = {uid=43271,name="The end of the path",area="siege",terrain="trail_ew",info="",notes="",x=12,y=19,z=0,building=""}
M[#M+1] = {uid=43272,name="A path through the camp",area="siege",terrain="trail_ew",info="",notes="",x=12,y=14,z=0,building=""}
M[#M+1] = {uid=43273,name="Mann's tent",area="siege",terrain="hut",info="",notes="",x=12,y=13,z=0,building=""}
M[#M+1] = {uid=43274,name="A large purple tent",area="siege",terrain="hut",info="",notes="",x=11,y=14,z=0,building=""}
M[#M+1] = {uid=43275,name="A small clay building",area="siege",terrain="hut",info="",notes="",x=11,y=16,z=0,building=""}
M[#M+1] = {uid=43276,name="The yellow tent",area="siege",terrain="hut",info="",notes="",x=11,y=19,z=0,building=""}
M[#M+1] = {uid=43277,name="The General's tent",area="siege",terrain="hut",info="",notes="",x=12,y=20,z=0,building=""}
M[#M+1] = {uid=43278,name="The battle path around the castle",area="siege",terrain="smallroad",info="",notes="",x=15,y=16,z=0,building=""}
M[#M+1] = {uid=43279,name="The battle path around the castle",area="siege",terrain="smallroad",info="",notes="",x=15,y=15,z=0,building=""}
M[#M+1] = {uid=43280,name="At the corner of the castle",area="siege",terrain="smallroad",info="",notes="",x=15,y=14,z=0,building=""}
M[#M+1] = {uid=43281,name="At the corner of the castle",area="siege",terrain="crossroad_se",info="",notes="",x=15,y=13,z=0,building=""}
M[#M+1] = {uid=43282,name="At the corner of the castle",area="siege",terrain="smallroad_ew",info="",notes="",x=16,y=13,z=0,building=""}
M[#M+1] = {uid=43283,name="The battle path around the castle",area="siege",terrain="smallroad_ew",info="",notes="",x=17,y=13,z=0,building=""}
M[#M+1] = {uid=43284,name="At the corner of the castle",area="siege",terrain="smallroad_ew",info="",notes="",x=18,y=13,z=0,building=""}
M[#M+1] = {uid=43285,name="At the corner of the castle",area="siege",terrain="crossroad_nw",info="pk",notes="",x=19,y=13,z=0,building=""}
M[#M+1] = {uid=43286,name="At the corner of the castle",area="siege",terrain="smallroad",info="",notes="",x=19,y=14,z=0,building=""}
M[#M+1] = {uid=43287,name="The castle doors",area="siege",terrain="smallroad",info="",notes="",x=19,y=15,z=0,building=""}
M[#M+1] = {uid=43288,name="The castle doors",area="siege",terrain="smallroad",info="",notes="",x=19,y=16,z=0,building=""}
M[#M+1] = {uid=43289,name="At the corner of the castle",area="siege",terrain="smallroad",info="",notes="",x=19,y=17,z=0,building=""}
M[#M+1] = {uid=43290,name="At the corner of the castle",area="siege",terrain="crossroad_nw",info="",notes="",x=19,y=18,z=0,building=""}
M[#M+1] = {uid=43291,name="At the corner of the castle",area="siege",terrain="smallroad_ew",info="",notes="",x=18,y=18,z=0,building=""}
M[#M+1] = {uid=43292,name="The battle path around the castle",area="siege",terrain="smallroad_ew",info="",notes="",x=17,y=18,z=0,building=""}
M[#M+1] = {uid=43293,name="At the corner of the castle",area="siege",terrain="smallroad_ew",info="",notes="",x=16,y=18,z=0,building=""}
M[#M+1] = {uid=43294,name="At the corner of the castle",area="siege",terrain="crossroad_se",info="",notes="",x=15,y=18,z=0,building=""}
M[#M+1] = {uid=43295,name="At the corner of the castle",area="siege",terrain="smallroad",info="",notes="",x=15,y=17,z=0,building=""}
M[#M+1] = {uid=43296,name="A tunnel",area="siege",terrain="rocks",info="",notes="",x=10,y=15,z=0,building=""}
M[#M+1] = {uid=43297,name="A dead end",area="siege",terrain="rocks",info="",notes="",x=11,y=15,z=0,building=""}
M[#M+1] = {uid=43298,name="A dead end",area="siege",terrain="tunnel",info="",notes="",x=12,y=15,z=0,building=""}
M[#M+1] = {uid=43299,name="An endless tunnel",area="siege",terrain="rocks",info="",notes="",x=10,y=17,z=0,building=""}
M[#M+1] = {uid=43300,name="A dead end",area="siege",terrain="tunnel",info="",notes="",x=8,y=15,z=0,building=""}
M[#M+1] = {uid=43301,name="A wet tunnel",area="siege",terrain="tunnel",info="",notes="",x=8,y=16,z=0,building=""}
M[#M+1] = {uid=43302,name="In a tunnel",area="siege",terrain="tunnel",info="",notes="",x=9,y=17,z=0,building=""}
M[#M+1] = {uid=43303,name="A turn in the tunnel",area="siege",terrain="tunnel",info="",notes="",x=8,y=17,z=0,building=""}
M[#M+1] = {uid=43304,name="A dead end",area="siege",terrain="rocks",info="",notes="",x=11,y=16,z=0,building=""}
M[#M+1] = {uid=43305,name="Entrance to a tunnel",area="siege",terrain="tunnel",info="",notes="",x=11,y=17,z=0,building=""}
M[#M+1] = {uid=43306,name="A dark tunnel",area="siege",terrain="tunnel",info="",notes="",x=12,y=16,z=0,building=""}
M[#M+1] = {uid=43307,name="A dead end",area="siege",terrain="tunnel",info="",notes="",x=13,y=17,z=0,building=""}
M[#M+1] = {uid=43308,name="A small tunnel",area="siege",terrain="tunnel",info="",notes="",x=12,y=17,z=0,building=""}
M[#M+1] = {uid=43309,name="A dark tunnel",area="siege",terrain="rocks",info="",notes="",x=10,y=16,z=0,building=""}
M[#M+1] = {uid=43313,name="The combat arena",area="siege",terrain="bloodyroom",info="pk",notes="",x=13,y=19,z=0,building=""}
M[#M+1] = {uid=43314,name="The end of the path",area="siege",terrain="trail_ew",info="",notes="",x=13,y=18,z=0,building=""}
M[#M+1] = {uid=43315,name="The barracks",area="siege",terrain="hut",info="",notes="",x=13,y=17,z=0,building=""}
M[#M+1] = {uid=43316,name="The campfire",area="siege",terrain="hellfountain",info="",notes="",x=13,y=15,z=0,building=""}
M[#M+1] = {uid=43317,name="The end of the path",area="siege",terrain="trail_ew",info="",notes="",x=13,y=14,z=0,building=""}
M[#M+1] = {uid=43319,name="The stinky paddock",area="siege",terrain="plain",info="pk",notes="",x=13,y=13,z=0,building=""}
M[#M+1] = {uid=43320,name="A maroon tent",area="siege",terrain="hut",info="",notes="",x=14,y=14,z=0,building=""}
M[#M+1] = {uid=43321,name="Siege camp gates",area="siege",terrain="trail_ew",info="",notes="",x=13,y=16,z=0,building=""}
M[#M+1] = {uid=43322,name="A massive construction site",area="siege",terrain="trail_ew",info="",notes="",x=11,y=17,z=0,building=""}
M[#M+1] = {uid=43324,name="Next to the camp",area="siege",terrain="field",info="",notes="",x=13,y=15,z=0,building=""}
M[#M+1] = {uid=43325,name="A dried creek bed",area="siege",terrain="field",info="",notes="",x=13,y=14,z=0,building=""}
M[#M+1] = {uid=43326,name="Next to the camp",area="siege",terrain="hills",info="",notes="",x=13,y=13,z=0,building=""}
M[#M+1] = {uid=43327,name="The corner of the field",area="siege",terrain="field",info="",notes="",x=13,y=12,z=0,building=""}
M[#M+1] = {uid=43328,name="A dried creek bed",area="siege",terrain="hills",info="",notes="",x=14,y=12,z=0,building=""}
M[#M+1] = {uid=43329,name="A dried creek bed",area="siege",terrain="field",info="",notes="",x=14,y=13,z=0,building=""}
M[#M+1] = {uid=43330,name="A dried creek bed",area="siege",terrain="field",info="",notes="",x=14,y=14,z=0,building=""}
M[#M+1] = {uid=43331,name="A deforested field",area="siege",terrain="field",info="",notes="",x=14,y=15,z=0,building=""}
M[#M+1] = {uid=43332,name="A deforested field",area="siege",terrain="hills",info="",notes="",x=14,y=16,z=0,building=""}
M[#M+1] = {uid=43333,name="A deforested field",area="siege",terrain="field",info="",notes="",x=14,y=17,z=0,building=""}
M[#M+1] = {uid=43334,name="Next to the camp",area="siege",terrain="field",info="",notes="",x=13,y=17,z=0,building=""}
M[#M+1] = {uid=43335,name="Next to the camp",area="siege",terrain="hills",info="",notes="",x=13,y=18,z=0,building=""}
M[#M+1] = {uid=43336,name="A duck pond?!",area="siege",terrain="waterswim",info="pk",notes="",x=13,y=19,z=0,building=""}
M[#M+1] = {uid=43337,name="A deforested field",area="siege",terrain="field",info="",notes="",x=14,y=19,z=0,building=""}
M[#M+1] = {uid=43338,name="A deforested field",area="siege",terrain="field",info="",notes="",x=14,y=18,z=0,building=""}
M[#M+1] = {uid=43339,name="The corner of the field",area="siege",terrain="field",info="",notes="",x=15,y=19,z=0,building=""}
M[#M+1] = {uid=43340,name="A secluded corner",area="siege",terrain="field",info="",notes="",x=15,y=12,z=0,building=""}
M[#M+1] = {uid=43341,name="The barracks",area="siege",terrain="hut",info="",notes="",x=14,y=17,z=0,building=""}
M[#M+1] = {uid=43342,name="The latrine",area="siege",terrain="hut",info="",notes="",x=13,y=16,z=0,building=""}
M[#M+1] = {uid=43343,name="The barracks",area="siege",terrain="hut",info="",notes="",x=14,y=16,z=0,building=""}
M[#M+1] = {uid=43345,name="Castle Ramparts",area="siege",terrain="smallroad_ew",info="",notes="",x=10,y=15,z=0,building=""}
M[#M+1] = {uid=43346,name="Flying high above the forest",area="siege",terrain="air",info="",notes="",x=10,y=15,z=0,building=""}
M[#M+1] = {uid=43350,name="A rarely used path",area="siege",terrain="trail_ew",info="",notes="",x=10,y=17,z=0,building=""}
M[#M+1] = {uid=43351,name="Jailor's tent",area="siege",terrain="hut",info="",notes="",x=10,y=18,z=0,building=""}
M[#M+1] = {uid=43352,name="A dangling cage",area="siege",terrain="cabin",info="",notes="",x=10,y=16,z=0,building=""}
M[#M+1] = {uid=43353,name="A dangling cage",area="siege",terrain="cabin",info="",notes="",x=9,y=17,z=0,building=""}
M[#M+1] = {uid=43782,name="A Collapsed Section of the City Wall",area="uprising",terrain="ruins",info="",notes="",x=51,y=7,z=0,building=""}
M[#M+1] = {uid=43785,name="A Collapsed Roadway",area="uprising",terrain="ruins",info="",notes="",x=50,y=5,z=0,building=""}
M[#M+1] = {uid=43786,name="A Burned-Out Forge",area="uprising",terrain="ruins",info="",notes="",x=49,y=4,z=0,building=""}
M[#M+1] = {uid=43787,name="A Residential Road",area="uprising",terrain="city",info="",notes="",x=46,y=5,z=0,building=""}
M[#M+1] = {uid=43788,name="A Residential Road",area="uprising",terrain="city",info="",notes="",x=45,y=5,z=0,building=""}
M[#M+1] = {uid=43789,name="A Burned Out House",area="uprising",terrain="ruins",info="",notes="",x=45,y=4,z=0,building=""}
M[#M+1] = {uid=43790,name="A Burned Out House",area="uprising",terrain="ruins",info="",notes="",x=45,y=6,z=0,building=""}
M[#M+1] = {uid=43791,name="Northern Edge of the Dais",area="uprising",terrain="temple",info="",notes="",x=46,y=5,z=0,building=""}
M[#M+1] = {uid=43792,name="Approaching the Dais",area="uprising",terrain="temple",info="",notes="",x=47,y=5,z=0,building=""}
M[#M+1] = {uid=43793,name="A Hallway in the Temple",area="uprising",terrain="temple",info="",notes="",x=48,y=5,z=0,building=""}
M[#M+1] = {uid=43794,name="At the Pulpit",area="uprising",terrain="temple",info="",notes="",x=46,y=6,z=0,building=""}
M[#M+1] = {uid=43795,name="Inside the Temple of the Night",area="uprising",terrain="bloodyroom",info="",notes="",x=48,y=6,z=0,building=""}
M[#M+1] = {uid=43796,name="Southern Edge of the Dais",area="uprising",terrain="temple",info="",notes="",x=46,y=7,z=0,building=""}
M[#M+1] = {uid=43797,name="Approaching the Dais",area="uprising",terrain="temple",info="",notes="",x=47,y=7,z=0,building=""}
M[#M+1] = {uid=43798,name="A Hallway in the Temple",area="uprising",terrain="temple",info="",notes="",x=48,y=7,z=0,building=""}
M[#M+1] = {uid=44255,name="A Flower Patch",area="bliss",terrain="flowers1",info="",notes="",x=22,y=25,z=0,building=""}
M[#M+1] = {uid=44256,name="At the top of a giant tree",area="solan",terrain="forest",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=44257,name="In the high branches of a mulberry tree",area="solan",terrain="forest",info="",notes="",x=4,y=-9,z=1,building=""}
M[#M+1] = {uid=44258,name="End of Cinder Way",area="solan",terrain="city",info="",notes="",x=5,y=-3,z=0,building=""}
M[#M+1] = {uid=44259,name="Center Avenue at the town park",area="solan",terrain="city",info="",notes="",x=1,y=-3,z=0,building=""}
M[#M+1] = {uid=44260,name="A Flower Patch",area="bliss",terrain="flowers1",info="",notes="",x=23,y=25,z=0,building=""}
M[#M+1] = {uid=44261,name="A Flower Patch",area="bliss",terrain="flowers1",info="",notes="",x=21,y=25,z=0,building=""}
M[#M+1] = {uid=44262,name="A Flower Patch",area="bliss",terrain="flowers1",info="",notes="",x=20,y=25,z=0,building=""}
M[#M+1] = {uid=44263,name="A Flower Patch",area="bliss",terrain="flowers1",info="",notes="",x=20,y=26,z=0,building=""}
M[#M+1] = {uid=44264,name="A Flower Patch",area="bliss",terrain="flowers1",info="",notes="",x=20,y=27,z=0,building=""}
M[#M+1] = {uid=44265,name="A Flower Patch",area="bliss",terrain="flowers1",info="",notes="",x=20,y=28,z=0,building=""}
M[#M+1] = {uid=44266,name="A Flower Patch",area="bliss",terrain="flowers1",info="",notes="",x=20,y=29,z=0,building=""}
M[#M+1] = {uid=44267,name="A Flower Patch",area="bliss",terrain="flowers1",info="",notes="",x=21,y=29,z=0,building=""}
M[#M+1] = {uid=44268,name="A Flower Patch",area="bliss",terrain="flowers1",info="",notes="",x=22,y=29,z=0,building=""}
M[#M+1] = {uid=44269,name="A Flower Patch",area="bliss",terrain="flowers1",info="",notes="",x=23,y=29,z=0,building=""}
M[#M+1] = {uid=44270,name="Ul'te Plains",area="manorville",terrain="field",info="",notes="",x=49,y=21,z=0,building=""}
M[#M+1] = {uid=44271,name="Ul'te Plains",area="manorville",terrain="field",info="",notes="",x=49,y=20,z=0,building=""}
M[#M+1] = {uid=44272,name="Ul'te Plains",area="manorville",terrain="field",info="",notes="",x=49,y=19,z=0,building=""}
M[#M+1] = {uid=44273,name="Ul'te Plains",area="manorville",terrain="field",info="",notes="",x=49,y=18,z=0,building=""}
M[#M+1] = {uid=44281,name="End of Autumn Trail",area="solan",terrain="city",info="",notes="",x=-3,y=-3,z=0,building=""}
M[#M+1] = {uid=44288,name="The Root Cellar",area="slaughter",terrain="bloodyroom",info="pk",notes="",x=9,y=-4,z=-1,building=""}
M[#M+1] = {uid=44290,name="Corner of the Root Cellar",area="slaughter",terrain="bloodyroom",info="pk",notes="",x=10,y=-4,z=-1,building=""}
M[#M+1] = {uid=44525,name="Approaching the City",area="uprising",terrain="cave",info="",notes="",x=49,y=9,z=0,building=""}
M[#M+1] = {uid=44526,name="Before the Gates",area="uprising",terrain="cave",info="",notes="",x=48,y=9,z=0,building=""}
M[#M+1] = {uid=44527,name="Approaching the City",area="uprising",terrain="cave",info="",notes="",x=47,y=9,z=0,building=""}
M[#M+1] = {uid=44528,name="Approaching the City",area="uprising",terrain="cave",info="",notes="",x=47,y=8,z=0,building=""}
M[#M+1] = {uid=44529,name="Approaching the City",area="uprising",terrain="cave",info="",notes="",x=47,y=7,z=0,building=""}
M[#M+1] = {uid=44530,name="A Sharp Corner",area="uprising",terrain="cave",info="",notes="",x=47,y=6,z=0,building=""}
M[#M+1] = {uid=44567,name="A Well-Carved Tunnel",area="uprising",terrain="cave",info="",notes="",x=46,y=6,z=0,building=""}
M[#M+1] = {uid=44568,name="A Gentle Turn in the Tunnel",area="uprising",terrain="cave",info="",notes="",x=45,y=6,z=0,building=""}
M[#M+1] = {uid=44569,name="Approaching a Bend",area="uprising",terrain="cave",info="",notes="",x=45,y=5,z=0,building=""}
M[#M+1] = {uid=44570,name="A Widening Tunnel",area="uprising",terrain="cave",info="",notes="",x=45,y=4,z=0,building=""}
M[#M+1] = {uid=44571,name="A Sharp Corner",area="uprising",terrain="cave",info="",notes="",x=45,y=3,z=0,building=""}
M[#M+1] = {uid=44572,name="A Widening Tunnel",area="uprising",terrain="cave",info="",notes="",x=46,y=3,z=0,building=""}
M[#M+1] = {uid=44573,name="A Slight Turn in the Cave",area="uprising",terrain="cave",info="bank",notes="",x=47,y=3,z=0,building=""}
M[#M+1] = {uid=44574,name="A Cramped Corner",area="uprising",terrain="cave",info="",notes="",x=47,y=2,z=0,building=""}
M[#M+1] = {uid=45176,name="The Aylorian Morgue",area="aylor",terrain="inside",info="safe",notes="",x=30,y=16,z=-1,building=""}
M[#M+1] = {uid=45544,name="The Memorial Garden",area="aylor",terrain="flowers1",info="safe",notes="",x=30,y=14,z=0,building=""}
M[#M+1] = {uid=45545,name="free",area="aylor",terrain="inside",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=47013,name="Approaching some ruins",area="songpalace",terrain="forest",info="",notes="",x=40,y=36,z=0,building=""}
M[#M+1] = {uid=47014,name="Nearing the ruins",area="songpalace",terrain="forest",info="",notes="",x=40,y=35,z=0,building=""}
M[#M+1] = {uid=47015,name="Under a crumbled archway",area="songpalace",terrain="forest",info="",notes="",x=41,y=35,z=0,building=""}
M[#M+1] = {uid=47016,name="Among the ruins",area="songpalace",terrain="city",info="",notes="",x=41,y=34,z=0,building=""}
M[#M+1] = {uid=47017,name="A stone platform",area="songpalace",terrain="pillar",info="",notes="",x=41,y=33,z=0,building=""}
M[#M+1] = {uid=47018,name="Beginning of marble path",area="songpalace",terrain="road",info="",notes="",x=40,y=36,z=0,building=""}
M[#M+1] = {uid=47019,name="A quiet grove",area="songpalace",terrain="field2",info="",notes="",x=40,y=34,z=0,building=""}
M[#M+1] = {uid=47020,name="Path through the gardens",area="songpalace",terrain="road",info="",notes="",x=40,y=35,z=0,building=""}
M[#M+1] = {uid=47021,name="Nearing the palace",area="songpalace",terrain="road",info="",notes="",x=40,y=34,z=0,building=""}
M[#M+1] = {uid=47022,name="Garden of Princess Amepsmamptra",area="songpalace",terrain="flowers1",info="",notes="",x=39,y=34,z=0,building=""}
M[#M+1] = {uid=47023,name="Garden of Prince Amepsmamptrer",area="songpalace",terrain="flowers2",info="",notes="",x=41,y=34,z=0,building=""}
M[#M+1] = {uid=47024,name="Garden of Duke Nhoukym",area="songpalace",terrain="field2",info="",notes="",x=39,y=35,z=0,building=""}
M[#M+1] = {uid=47025,name="Garden of Lady Maltesa",area="songpalace",terrain="field2",info="",notes="",x=41,y=35,z=0,building=""}
M[#M+1] = {uid=47026,name="Foot of the steps",area="songpalace",terrain="road",info="",notes="",x=40,y=33,z=0,building=""}
M[#M+1] = {uid=47027,name="Top of the steps",area="songpalace",terrain="city",info="",notes="",x=40,y=33,z=1,building=""}
M[#M+1] = {uid=47028,name="Atrium of the Palace of Song",area="songpalace",terrain="castle",info="",notes="",x=40,y=32,z=1,building=""}
M[#M+1] = {uid=47029,name="Clouds",area="songpalace",terrain="cloud2",info="pk",notes="",x=39,y=33,z=1,building=""}
M[#M+1] = {uid=47030,name="Southwest Atrium",area="songpalace",terrain="pillar",info="safe,shop",notes="",x=39,y=32,z=1,building=""}
M[#M+1] = {uid=47031,name="Southeast Atrium",area="songpalace",terrain="pillar",info="",notes="",x=41,y=32,z=1,building=""}
M[#M+1] = {uid=47032,name="Northwest Atrium",area="songpalace",terrain="pillar",info="",notes="",x=39,y=31,z=1,building=""}
M[#M+1] = {uid=47033,name="Northeast Atrium",area="songpalace",terrain="pillar",info="",notes="",x=41,y=31,z=1,building=""}
M[#M+1] = {uid=47034,name="North Atrium",area="songpalace",terrain="castle",info="",notes="",x=40,y=31,z=1,building=""}
M[#M+1] = {uid=47035,name="Western staircase",area="songpalace",terrain="stairs",info="",notes="",x=38,y=32,z=1,building=""}
M[#M+1] = {uid=47036,name="Eastern staircase",area="songpalace",terrain="stairs",info="",notes="",x=42,y=32,z=1,building=""}
M[#M+1] = {uid=47037,name="Upper Atrium",area="songpalace",terrain="pillar",info="",notes="",x=38,y=32,z=2,building=""}
M[#M+1] = {uid=47038,name="Upper Atrium",area="songpalace",terrain="pillar",info="",notes="",x=42,y=32,z=2,building=""}
M[#M+1] = {uid=47039,name="Upper Atrium",area="songpalace",terrain="castle",info="",notes="",x=39,y=32,z=2,building=""}
M[#M+1] = {uid=47040,name="An endless stream",area="songpalace",terrain="river",info="",notes="",x=41,y=36,z=0,building=""}
M[#M+1] = {uid=47041,name="An endless stream",area="songpalace",terrain="river",info="",notes="",x=39,y=36,z=0,building=""}
M[#M+1] = {uid=47042,name="Back Orchestra",area="songpalace",terrain="inside",info="",notes="",x=40,y=30,z=1,building=""}
M[#M+1] = {uid=47043,name="Back Orchestra",area="songpalace",terrain="inside",info="",notes="",x=39,y=30,z=1,building=""}
M[#M+1] = {uid=47044,name="Back Orchestra",area="songpalace",terrain="inside",info="",notes="",x=41,y=30,z=1,building=""}
M[#M+1] = {uid=47045,name="Mid Orchestra",area="songpalace",terrain="inside",info="",notes="",x=41,y=29,z=1,building=""}
M[#M+1] = {uid=47046,name="Mid Orchestra",area="songpalace",terrain="inside",info="",notes="",x=40,y=29,z=1,building=""}
M[#M+1] = {uid=47047,name="Mid Orchestra",area="songpalace",terrain="inside",info="",notes="",x=39,y=29,z=1,building=""}
M[#M+1] = {uid=47048,name="Front Row",area="songpalace",terrain="inside",info="",notes="",x=41,y=28,z=1,building=""}
M[#M+1] = {uid=47049,name="Front Row",area="songpalace",terrain="inside",info="",notes="",x=40,y=28,z=1,building=""}
M[#M+1] = {uid=47050,name="Front Row",area="songpalace",terrain="inside",info="",notes="",x=39,y=28,z=1,building=""}
M[#M+1] = {uid=47051,name="Downstage Centre",area="songpalace",terrain="city",info="",notes="",x=40,y=28,z=2,building=""}
M[#M+1] = {uid=47052,name="Downstage Left",area="songpalace",terrain="flowers1",info="",notes="",x=41,y=28,z=2,building=""}
M[#M+1] = {uid=47053,name="Downstage Right",area="songpalace",terrain="field2",info="",notes="",x=39,y=28,z=2,building=""}
M[#M+1] = {uid=47054,name="Upstage Centre",area="songpalace",terrain="river",info="",notes="",x=40,y=27,z=2,building=""}
M[#M+1] = {uid=47055,name="Upstage Left",area="songpalace",terrain="flowers2",info="",notes="",x=41,y=27,z=2,building=""}
M[#M+1] = {uid=47056,name="Upstage Right",area="songpalace",terrain="river",info="",notes="",x=39,y=27,z=2,building=""}
M[#M+1] = {uid=47057,name="Backstage",area="songpalace",terrain="inside",info="",notes="",x=39,y=26,z=2,building=""}
M[#M+1] = {uid=47058,name="Backstage",area="songpalace",terrain="inside",info="",notes="",x=40,y=26,z=2,building=""}
M[#M+1] = {uid=47059,name="Backstage",area="songpalace",terrain="inside",info="",notes="",x=41,y=26,z=2,building=""}
M[#M+1] = {uid=47060,name="Ensemble Dressing Room",area="songpalace",terrain="inside",info="",notes="",x=41,y=25,z=2,building=""}
M[#M+1] = {uid=47061,name="Star Dressing Room",area="songpalace",terrain="palace_room",info="",notes="",x=39,y=25,z=2,building=""}
M[#M+1] = {uid=47062,name="In the Pit",area="songpalace",terrain="hellinside",info="",notes="",x=40,y=27,z=1,building=""}
M[#M+1] = {uid=47063,name="In the flies",area="songpalace",terrain="air",info="",notes="",x=39,y=27,z=3,building=""}
M[#M+1] = {uid=47068,name="Mezzanine",area="songpalace",terrain="inside",info="",notes="",x=38,y=31,z=2,building=""}
M[#M+1] = {uid=47069,name="Mezzanine",area="songpalace",terrain="inside",info="",notes="",x=39,y=31,z=2,building=""}
M[#M+1] = {uid=47070,name="Mezzanine",area="songpalace",terrain="inside",info="",notes="",x=42,y=31,z=2,building=""}
M[#M+1] = {uid=47071,name="West Box",area="songpalace",terrain="inside",info="",notes="",x=38,y=30,z=2,building=""}
M[#M+1] = {uid=47072,name="Royal Dress Circle",area="songpalace",terrain="inside",info="",notes="",x=39,y=30,z=2,building=""}
M[#M+1] = {uid=47073,name="East Box",area="songpalace",terrain="inside",info="",notes="",x=42,y=30,z=2,building=""}
M[#M+1] = {uid=47106,name="The Mysterious Arch",area="manorsea",terrain="inside",info="shop",notes="",x=24,y=2,z=0,building=""}
M[#M+1] = {uid=47187,name="Little Attic",area="crusaders",terrain="inside",info="bank,safe,shop",notes="",x=32,y=23,z=1,building=""}
M[#M+1] = {uid=47195,name="The Common Room",area="bootcamp",terrain="city",info="bank,safe,questor",notes="",x=-1,y=-1,z=0,building=""}
M[#M+1] = {uid=47196,name="A Bed of Corpses",area="bootcamp",terrain="city",info="bank,safe",notes="",x=-2,y=-1,z=-1,building=""}
M[#M+1] = {uid=47200,name="The Skybridge",area="bootcamp",terrain="city",info="bank,safe,trainer",notes="",x=0,y=-1,z=0,building=""}
M[#M+1] = {uid=47210,name="The Dumping Ground",area="bootcamp",terrain="city",info="safe",notes="",x=0,y=-1,z=-1,building=""}
M[#M+1] = {uid=47218,name="Every Vote Counts",area="bootcamp",terrain="city",info="bank,safe",notes="",x=-1,y=-2,z=0,building=""}
M[#M+1] = {uid=47220,name="Branching Possibilities",area="bootcamp",terrain="city",info="bank,safe",notes="",x=-1,y=-1,z=1,building=""}
M[#M+1] = {uid=47276,name="Four Winds Outpost",area="desolation",terrain="inside",info="",notes="",x=8,y=17,z=0,building=""}
M[#M+1] = {uid=47509,name="Aardington Estate",area="aardington",terrain="trail_ew",info="",notes="",x=38,y=25,z=0,building=""}
M[#M+1] = {uid=47510,name="A path through the estate",area="aardington",terrain="trail_ew",info="",notes="",x=38,y=24,z=0,building=""}
M[#M+1] = {uid=47511,name="Before the manor",area="aardington",terrain="trail_ew",info="",notes="",x=38,y=23,z=0,building=""}
M[#M+1] = {uid=47512,name="Path around the manor",area="aardington",terrain="trail_ew",info="",notes="",x=37,y=23,z=0,building=""}
M[#M+1] = {uid=47515,name="Path around the manor",area="aardington",terrain="trail_ew",info="",notes="",x=36,y=23,z=0,building=""}
M[#M+1] = {uid=47516,name="Path around the manor",area="aardington",terrain="trail_ew",info="pk",notes="",x=36,y=22,z=0,building=""}
M[#M+1] = {uid=47517,name="Path around the manor",area="aardington",terrain="trail_ew",info="",notes="",x=36,y=21,z=0,building=""}
M[#M+1] = {uid=47518,name="Path around the manor",area="aardington",terrain="trail_ew",info="",notes="",x=36,y=20,z=0,building=""}
M[#M+1] = {uid=47519,name="Path around the manor",area="aardington",terrain="trail_ew",info="",notes="",x=37,y=20,z=0,building=""}
M[#M+1] = {uid=47520,name="Behind the manor",area="aardington",terrain="trail_ew",info="",notes="",x=38,y=18,z=0,building=""}
M[#M+1] = {uid=47521,name="Path around the manor",area="aardington",terrain="trail_ew",info="",notes="",x=39,y=18,z=0,building=""}
M[#M+1] = {uid=47522,name="Path around the manor",area="aardington",terrain="trail_ew",info="",notes="",x=40,y=20,z=0,building=""}
M[#M+1] = {uid=47523,name="Path around the manor",area="aardington",terrain="trail_ew",info="",notes="",x=40,y=21,z=0,building=""}
M[#M+1] = {uid=47524,name="Path around the manor",area="aardington",terrain="trail_ew",info="",notes="",x=40,y=22,z=0,building=""}
M[#M+1] = {uid=47525,name="Path around the manor",area="aardington",terrain="trail_ew",info="",notes="",x=40,y=23,z=0,building=""}
M[#M+1] = {uid=47526,name="Path around the manor",area="aardington",terrain="trail_ew",info="",notes="",x=39,y=23,z=0,building=""}
M[#M+1] = {uid=47527,name="Aardington manor",area="aardington",terrain="redcarpet",info="",notes="",x=38,y=22,z=0,building=""}
M[#M+1] = {uid=47528,name="Grand staircase",area="aardington",terrain="redcarpet",info="",notes="",x=38,y=21,z=0,building=""}
M[#M+1] = {uid=47529,name="Grand hall",area="aardington",terrain="redcarpet",info="",notes="",x=38,y=20,z=0,building=""}
M[#M+1] = {uid=47530,name="West wing",area="aardington",terrain="inside",info="",notes="",x=37,y=20,z=0,building=""}
M[#M+1] = {uid=47531,name="Library",area="aardington",terrain="bookshelves_ns",info="",notes="",x=37,y=21,z=0,building=""}
M[#M+1] = {uid=47532,name="Parlour",area="aardington",terrain="inside",info="",notes="",x=36,y=20,z=0,building=""}
M[#M+1] = {uid=47533,name="The Earl's den",area="aardington",terrain="inside",info="",notes="",x=37,y=19,z=0,building=""}
M[#M+1] = {uid=47534,name="Kitchen",area="aardington",terrain="inside",info="",notes="",x=38,y=19,z=0,building=""}
M[#M+1] = {uid=47535,name="Dining room",area="aardington",terrain="inside",info="",notes="",x=39,y=19,z=0,building=""}
M[#M+1] = {uid=47536,name="Ballroom",area="aardington",terrain="inside",info="",notes="",x=40,y=20,z=0,building=""}
M[#M+1] = {uid=47537,name="Trophy room",area="aardington",terrain="inside",info="",notes="",x=39,y=21,z=0,building=""}
M[#M+1] = {uid=47538,name="East wing",area="aardington",terrain="inside",info="",notes="",x=39,y=20,z=0,building=""}
M[#M+1] = {uid=47539,name="Grand staircase",area="aardington",terrain="inside",info="",notes="",x=38,y=21,z=1,building=""}
M[#M+1] = {uid=47540,name="East wing",area="aardington",terrain="inside",info="",notes="",x=39,y=21,z=1,building=""}
M[#M+1] = {uid=47541,name="Bedroom",area="aardington",terrain="inside",info="",notes="",x=39,y=20,z=1,building=""}
M[#M+1] = {uid=47542,name="Master bedroom",area="aardington",terrain="inside",info="",notes="",x=40,y=21,z=1,building=""}
M[#M+1] = {uid=47543,name="Bedroom",area="aardington",terrain="inside",info="",notes="",x=39,y=22,z=1,building=""}
M[#M+1] = {uid=47544,name="Nursery",area="aardington",terrain="inside",info="",notes="",x=38,y=22,z=1,building=""}
M[#M+1] = {uid=47545,name="Play room",area="aardington",terrain="inside",info="",notes="",x=37,y=22,z=1,building=""}
M[#M+1] = {uid=47546,name="West wing",area="aardington",terrain="inside",info="",notes="",x=37,y=21,z=1,building=""}
M[#M+1] = {uid=47547,name="Store room",area="aardington",terrain="inside",info="",notes="",x=36,y=21,z=1,building=""}
M[#M+1] = {uid=47548,name="Guest room",area="aardington",terrain="inside",info="",notes="",x=37,y=20,z=1,building=""}
M[#M+1] = {uid=47549,name="Bathroom",area="aardington",terrain="inside",info="",notes="",x=38,y=20,z=1,building=""}
M[#M+1] = {uid=47550,name="Attic",area="aardington",terrain="inside",info="",notes="",x=36,y=21,z=2,building=""}
M[#M+1] = {uid=47551,name="Attic",area="aardington",terrain="inside",info="",notes="",x=37,y=21,z=2,building=""}
M[#M+1] = {uid=47552,name="Mezzanine",area="aardington",terrain="inside",info="",notes="",x=37,y=21,z=3,building=""}
M[#M+1] = {uid=47553,name="Wine cellar",area="aardington",terrain="underground",info="",notes="",x=38,y=19,z=-1,building=""}
M[#M+1] = {uid=47554,name="Wine cellar",area="aardington",terrain="underground",info="",notes="",x=37,y=19,z=-1,building=""}
M[#M+1] = {uid=47555,name="Wine cellar",area="aardington",terrain="underground",info="",notes="",x=37,y=18,z=-1,building=""}
M[#M+1] = {uid=47556,name="A path through the estate",area="aardington",terrain="trail_ew",info="pk",notes="",x=38,y=17,z=0,building=""}
M[#M+1] = {uid=47557,name="Green lawns",area="aardington",terrain="field",info="",notes="",x=38,y=16,z=0,building=""}
M[#M+1] = {uid=47558,name="Green lawns",area="aardington",terrain="field",info="",notes="",x=39,y=16,z=0,building=""}
M[#M+1] = {uid=47559,name="A quiet lake",area="aardington",terrain="waterswim",info="",notes="",x=39,y=18,z=0,building=""}
M[#M+1] = {uid=47560,name="Approaching a dark wood",area="aardington",terrain="field",info="",notes="",x=40,y=18,z=0,building=""}
M[#M+1] = {uid=47561,name="A path through the estate",area="aardington",terrain="trail_ew",info="",notes="",x=40,y=19,z=0,building=""}
M[#M+1] = {uid=47562,name="A dark wood",area="aardington",terrain="forest",info="",notes="",x=40,y=17,z=0,building=""}
M[#M+1] = {uid=47563,name="A dark wood",area="aardington",terrain="forest",info="pk",notes="",x=40,y=16,z=0,building=""}
M[#M+1] = {uid=47564,name="A dark wood",area="aardington",terrain="forest",info="",notes="",x=39,y=17,z=0,building=""}
M[#M+1] = {uid=47565,name="A dark wood",area="aardington",terrain="forest",info="",notes="",x=41,y=17,z=0,building=""}
M[#M+1] = {uid=47566,name="A secluded cabin",area="aardington",terrain="cabin",info="",notes="",x=40,y=17,z=0,building=""}
M[#M+1] = {uid=47575,name="A path through the estate",area="aardington",terrain="trail_ew",info="",notes="",x=35,y=21,z=0,building=""}
M[#M+1] = {uid=47576,name="A path through the estate",area="aardington",terrain="trail_ew",info="",notes="",x=34,y=21,z=0,building=""}
M[#M+1] = {uid=47577,name="The stables",area="aardington",terrain="cabin",info="",notes="",x=34,y=20,z=0,building=""}
M[#M+1] = {uid=47578,name="The hayloft",area="aardington",terrain="cabin",info="",notes="",x=34,y=20,z=1,building=""}
M[#M+1] = {uid=47579,name="The carriage house",area="aardington",terrain="cabin",info="pk",notes="",x=33,y=21,z=0,building=""}
M[#M+1] = {uid=47580,name="A corral",area="aardington",terrain="field",info="",notes="",x=34,y=22,z=0,building=""}
M[#M+1] = {uid=47581,name="A path through the estate",area="aardington",terrain="trail_ew",info="pk",notes="",x=41,y=22,z=0,building=""}
M[#M+1] = {uid=47582,name="Before a temple",area="aardington",terrain="trail_ew",info="",notes="",x=42,y=22,z=0,building=""}
M[#M+1] = {uid=47583,name="A beautiful garden",area="aardington",terrain="flowers1",info="",notes="",x=42,y=21,z=0,building=""}
M[#M+1] = {uid=47584,name="A beautiful garden",area="aardington",terrain="flowers1",info="",notes="",x=43,y=21,z=0,building=""}
M[#M+1] = {uid=47585,name="A beautiful garden",area="aardington",terrain="flowers1",info="",notes="",x=42,y=23,z=0,building=""}
M[#M+1] = {uid=47586,name="A beautiful garden",area="aardington",terrain="flowers1",info="",notes="",x=43,y=23,z=0,building=""}
M[#M+1] = {uid=47587,name="Temple foyer",area="aardington",terrain="temple",info="healer",notes="",x=43,y=22,z=0,building=""}
M[#M+1] = {uid=47588,name="Wooden pews",area="aardington",terrain="temple",info="",notes="",x=44,y=22,z=0,building=""}
M[#M+1] = {uid=47589,name="Wooden pews",area="aardington",terrain="temple",info="",notes="",x=45,y=22,z=0,building=""}
M[#M+1] = {uid=47590,name="A confessional",area="aardington",terrain="temple",info="",notes="",x=45,y=21,z=0,building=""}
M[#M+1] = {uid=47591,name="The dais",area="aardington",terrain="temple",info="",notes="",x=46,y=22,z=0,building=""}
M[#M+1] = {uid=47592,name="A memorial alcove",area="aardington",terrain="temple",info="",notes="",x=45,y=23,z=0,building=""}
M[#M+1] = {uid=47593,name="Entrance to the catacombs",area="aardington",terrain="underground",info="",notes="",x=45,y=23,z=-1,building=""}
M[#M+1] = {uid=47594,name="Catacombs",area="aardington",terrain="crypt",info="pk",notes="",x=45,y=24,z=-1,building=""}
M[#M+1] = {uid=47595,name="Catacombs",area="aardington",terrain="crypt",info="",notes="",x=46,y=24,z=-1,building=""}
M[#M+1] = {uid=47596,name="Catacombs",area="aardington",terrain="crypt",info="",notes="",x=46,y=25,z=-1,building=""}
M[#M+1] = {uid=47597,name="Catacombs",area="aardington",terrain="crypt",info="pk",notes="",x=46,y=26,z=-1,building=""}
M[#M+1] = {uid=47598,name="Catacombs",area="aardington",terrain="crypt",info="",notes="",x=45,y=26,z=-1,building=""}
M[#M+1] = {uid=47599,name="Catacombs",area="aardington",terrain="crypt",info="pk",notes="",x=44,y=26,z=-1,building=""}
M[#M+1] = {uid=47600,name="Catacombs",area="aardington",terrain="crypt",info="",notes="",x=44,y=25,z=-1,building=""}
M[#M+1] = {uid=47601,name="Catacombs",area="aardington",terrain="crypt",info="",notes="",x=44,y=24,z=-1,building=""}
M[#M+1] = {uid=49217,name="The Crusader Forge",area="crusaders",terrain="inside",info="bank,safe,shop",notes="",x=32,y=23,z=-1,building=""}
M[#M+1] = {uid=49256,name="The Boot Lyceum",area="bootcamp",terrain="shop",info="bank,safe,shop",notes="",x=2,y=-1,z=0,building=""}
M[#M+1] = {uid=49260,name="Rest and Relaxation",area="bootcamp",terrain="city",info="bank,safe,healer",notes="",x=-2,y=-1,z=0,building=""}
M[#M+1] = {uid=49320,name="The Bell Tower",area="crusaders",terrain="inside",info="safe",notes="",x=30,y=20,z=1,building=""}
M[#M+1] = {uid=49335,name="The GaardBucks Get Wired Cafe",area="gaardian",terrain="shop",info="bank,safe,shop",notes="",x=30,y=22,z=0,building=""}
M[#M+1] = {uid=49345,name="Electrifying Lessons in Magic",area="bootcamp",terrain="city",info="bank,safe,trainer",notes="",x=1,y=1,z=0,building=""}
M[#M+1] = {uid=49373,name="Fizzbough's Herbal Shop",area="tao",terrain="shop",info="bank,safe,shop",notes="",x=31,y=18,z=0,building=""}
M[#M+1] = {uid=49391,name="Stealthy Lessons in Thievery",area="bootcamp",terrain="city",info="bank,safe,trainer",notes="",x=3,y=1,z=0,building=""}
M[#M+1] = {uid=49392,name="All You Can Drink Potions",area="bootcamp",terrain="shop",info="bank,safe,shop",notes="",x=1,y=-1,z=0,building=""}
M[#M+1] = {uid=49393,name="Getting to Know You",area="bootcamp",terrain="city",info="safe",notes="",x=-1,y=0,z=0,building=""}
M[#M+1] = {uid=50099,name="Approaching Attendance",area="bootcamp",terrain="city",info="bank,safe",notes="",x=2,y=1,z=0,building=""}
M[#M+1] = {uid=50100,name="Continued Education",area="bootcamp",terrain="city",info="bank,safe",notes="",x=2,y=2,z=0,building=""}
M[#M+1] = {uid=50101,name="An End of Higher Learning",area="bootcamp",terrain="city",info="bank,safe",notes="",x=2,y=3,z=0,building=""}
M[#M+1] = {uid=50102,name="Barely Managing",area="bootcamp",terrain="shop",info="bank,safe,shop",notes="",x=3,y=-1,z=0,building=""}
M[#M+1] = {uid=50103,name="Sharp Pointy Things",area="bootcamp",terrain="shop",info="bank,safe,shop",notes="",x=2,y=0,z=0,building=""}
M[#M+1] = {uid=50123,name="Senior Explorers Hut",area="touchstone",terrain="shop",info="safe,shop",notes="",x=29,y=21,z=0,building=""}
M[#M+1] = {uid=50146,name="The Eastern Cavern",area="touchstone",terrain="inside",info="safe",notes="",x=31,y=20,z=0,building=""}
M[#M+1] = {uid=50152,name="Martial Expedition Hut",area="touchstone",terrain="shop",info="safe,shop",notes="",x=31,y=19,z=0,building=""}
M[#M+1] = {uid=50290,name="Mique's Porch",area="manorwoods",terrain="inside",info="shop",notes="",x=19,y=1,z=0,building=""}
M[#M+1] = {uid=50534,name="A Snaky Corner",area="uprising",terrain="cave",info="",notes="",x=49,y=3,z=0,building=""}
M[#M+1] = {uid=50635,name="Western Temple Road",area="uprising",terrain="city",info="",notes="",x=47,y=6,z=0,building=""}
M[#M+1] = {uid=50636,name="Northern Temple Road",area="uprising",terrain="city",info="",notes="",x=48,y=5,z=0,building=""}
M[#M+1] = {uid=52118,name="A Tight Cubby",area="uprising",terrain="cave",info="",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=52182,name="Urru's Porch",area="manorville",terrain="inside",info="",notes="",x=50,y=20,z=0,building=""}
M[#M+1] = {uid=52198,name="Hassan's Ready Room ",area="emerald",terrain="inside",info="safe",notes="",x=30,y=21,z=0,building=""}
M[#M+1] = {uid=52223,name="Kelderek's Porch",area="manorville",terrain="inside",info="",notes="",x=48,y=20,z=0,building=""}
M[#M+1] = {uid=52579,name="West Nest",area="manorville",terrain="inside",info="",notes="",x=48,y=19,z=0,building=""}
M[#M+1] = {uid=52673,name="A menacing mansion",area="manorville",terrain="inside",info="shop",notes="",x=50,y=19,z=0,building=""}
M[#M+1] = {uid=52871,name="Pile of rocks at the bottom of the cave.",area="manorville",terrain="inside",info="shop",notes="",x=48,y=18,z=0,building=""}
M[#M+1] = {uid=55236,name="An Overgrown Temple",area="amazonclan",terrain="forest",info="safe",notes="",x=28,y=20,z=0,building=""}
M[#M+1] = {uid=55237,name="Chamber of Darkness",area="amazonclan",terrain="forest",info="bank,safe",notes="",x=29,y=20,z=0,building=""}
M[#M+1] = {uid=55238,name="Amazon Tribunal",area="amazonclan",terrain="inside",info="safe",notes="",x=27,y=20,z=1,building=""}
M[#M+1] = {uid=55239,name="The Locus of a Bespoiled Temple",area="amazonclan",terrain="forest",info="safe,shop",notes="",x=28,y=20,z=1,building=""}
M[#M+1] = {uid=55240,name="Viscera Encrusted Canopy",area="amazonclan",terrain="forest",info="safe,questor",notes="",x=28,y=20,z=2,building=""}
M[#M+1] = {uid=55761,name="Honorable Lessons In Knighting",area="bootcamp",terrain="city",info="bank,safe,questor",notes="",x=1,y=2,z=0,building=""}
M[#M+1] = {uid=55762,name="Strong Lessons In War",area="bootcamp",terrain="city",info="bank,safe,trainer",notes="",x=3,y=2,z=0,building=""}
M[#M+1] = {uid=55763,name="Pure Lessons in Ministering",area="bootcamp",terrain="city",info="bank,safe,trainer",notes="",x=1,y=3,z=0,building=""}
M[#M+1] = {uid=55764,name="Mindful Lessons In Mysticism",area="bootcamp",terrain="city",info="bank,safe,trainer",notes="",x=3,y=3,z=0,building=""}
M[#M+1] = {uid=55765,name="Survival Lessons In Rangering",area="bootcamp",terrain="city",info="bank,safe,trainer",notes="",x=2,y=4,z=0,building=""}
M[#M+1] = {uid=55766,name="Training Beneath The Great Trees",area="bootcamp",terrain="city",info="",notes="",x=2,y=3,z=-1,building=""}
return M
