-- generated by tools/import-mushmap.py — do not edit
-- rooms 21001..21750
local M = {}
M[#M+1] = {uid=34157,name="Bottom of the Stairs",area="shouggoth",terrain="inside",info="",notes="",x=22,y=30,z=-6,building=""}
M[#M+1] = {uid=34158,name="Cavern of Summoning",area="shouggoth",terrain="inside",info="",notes="",x=23,y=30,z=-6,building=""}
M[#M+1] = {uid=34159,name="Cavern of Summoning",area="shouggoth",terrain="inside",info="",notes="",x=23,y=29,z=-6,building=""}
M[#M+1] = {uid=34160,name="Cavern of Summoning",area="shouggoth",terrain="inside",info="",notes="",x=24,y=29,z=-6,building=""}
M[#M+1] = {uid=34161,name="Cavern of Summoning",area="shouggoth",terrain="inside",info="",notes="",x=25,y=29,z=-6,building=""}
M[#M+1] = {uid=34162,name="Cavern of Summoning",area="shouggoth",terrain="inside",info="",notes="",x=25,y=30,z=-6,building=""}
M[#M+1] = {uid=34163,name="Cavern of Summoning",area="shouggoth",terrain="inside",info="",notes="",x=25,y=31,z=-6,building=""}
M[#M+1] = {uid=34164,name="Cavern of Summoning",area="shouggoth",terrain="inside",info="",notes="",x=24,y=31,z=-6,building=""}
M[#M+1] = {uid=34165,name="Cavern of Summoning",area="shouggoth",terrain="inside",info="",notes="",x=23,y=31,z=-6,building=""}
M[#M+1] = {uid=34166,name="Inside the Pentagram!",area="shouggoth",terrain="inside",info="",notes="",x=24,y=30,z=-6,building=""}
M[#M+1] = {uid=34174,name="Past the Northern Gate",area="amazonclan",terrain="forest",info="bank,safe,questor",notes="",x=30,y=20,z=0,building=""}
M[#M+1] = {uid=34176,name="A Tranquil, Sylvan Glade",area="amazonclan",terrain="forest",info="bank,safe,healer",notes="",x=31,y=20,z=0,building=""}
M[#M+1] = {uid=34179,name="The Training Circle",area="amazonclan",terrain="inside",info="safe,trainer",notes="",x=30,y=21,z=0,building=""}
M[#M+1] = {uid=34193,name="The Kayapos Trading Grounds",area="amazonclan",terrain="inside",info="safe,shop",notes="",x=29,y=21,z=0,building=""}
M[#M+1] = {uid=34210,name="Shop Above the Canopy",area="amazonclan",terrain="forest",info="safe,shop",notes="",x=29,y=20,z=1,building=""}
M[#M+1] = {uid=34211,name="Hall of Ancestral Evocation",area="amazonclan",terrain="inside",info="safe",notes="",x=27,y=20,z=0,building=""}
M[#M+1] = {uid=34212,name="Approaching a Vast Complex of Ruins",area="amazonclan",terrain="forest",info="safe,trainer",notes="",x=28,y=21,z=0,building=""}
M[#M+1] = {uid=34315,name="Gnomalin National Bank",area="gnomalin",terrain="inside",info="bank",notes="",x=38,y=37,z=0,building=""}
M[#M+1] = {uid=34316,name="Bank Counter",area="gnomalin",terrain="inside",info="",notes="",x=37,y=37,z=0,building=""}
M[#M+1] = {uid=34317,name="North Wing",area="gnomalin",terrain="inside",info="",notes="",x=37,y=36,z=0,building=""}
M[#M+1] = {uid=34318,name="The VIP Lounge",area="gnomalin",terrain="inside",info="",notes="",x=37,y=38,z=0,building=""}
M[#M+1] = {uid=34319,name="Staff's Lounge",area="gnomalin",terrain="inside",info="",notes="",x=36,y=36,z=0,building=""}
M[#M+1] = {uid=34320,name="Manager's Office",area="gnomalin",terrain="inside",info="",notes="",x=36,y=38,z=0,building=""}
M[#M+1] = {uid=34321,name="A Dark Tunnel",area="gnomalin",terrain="inside",info="",notes="",x=36,y=37,z=0,building=""}
M[#M+1] = {uid=34330,name="Entrance to the Operations building",area="gnomalin",terrain="inside",info="",notes="",x=40,y=39,z=0,building=""}
M[#M+1] = {uid=34345,name="Stratus Street",area="gnomalin",terrain="city",info="",notes="",x=40,y=35,z=0,building=""}
M[#M+1] = {uid=34349,name="Stratus Street",area="gnomalin",terrain="city",info="",notes="",x=40,y=34,z=0,building=""}
M[#M+1] = {uid=34350,name="Large Cloud House",area="gnomalin",terrain="city",info="",notes="",x=41,y=34,z=0,building=""}
M[#M+1] = {uid=34375,name="Gnomalin Square, North West End",area="gnomalin",terrain="city",info="",notes="",x=39,y=36,z=0,building=""}
M[#M+1] = {uid=34376,name="Gnomalin Square, North End",area="gnomalin",terrain="city",info="",notes="",x=40,y=36,z=0,building=""}
M[#M+1] = {uid=34379,name="Gnomalin Square, South East End",area="gnomalin",terrain="city",info="",notes="",x=41,y=38,z=0,building=""}
M[#M+1] = {uid=34380,name="Gnomalin Square, South End",area="gnomalin",terrain="city",info="",notes="",x=40,y=38,z=0,building=""}
M[#M+1] = {uid=34381,name="Gnomalin Square, South West End",area="gnomalin",terrain="city",info="",notes="",x=39,y=38,z=0,building=""}
M[#M+1] = {uid=34382,name="Gnomalin Square, West End",area="gnomalin",terrain="city",info="",notes="",x=39,y=37,z=0,building=""}
M[#M+1] = {uid=34395,name="Fields",area="gnomalin",terrain="field",info="",notes="",x=38,y=37,z=0,building=""}
M[#M+1] = {uid=34396,name="Fields",area="gnomalin",terrain="field",info="",notes="",x=38,y=38,z=0,building=""}
M[#M+1] = {uid=34397,name="Standing before an airship",area="gnomalin",terrain="field",info="",notes="",x=37,y=38,z=0,building=""}
M[#M+1] = {uid=34398,name="Fields",area="gnomalin",terrain="field",info="",notes="",x=37,y=37,z=0,building=""}
M[#M+1] = {uid=34399,name="Landing Bay for Visitors",area="gnomalin",terrain="field",info="",notes="",x=41,y=39,z=0,building=""}
M[#M+1] = {uid=34400,name="Entrance to a Forest",area="adaldar",terrain="field",info="pk",notes="",x=52,y=4,z=0,building=""}
M[#M+1] = {uid=34401,name="Path through the forest",area="adaldar",terrain="field",info="",notes="",x=52,y=4,z=0,building=""}
M[#M+1] = {uid=34402,name="Opening to the battlefield",area="adaldar",terrain="field",info="",notes="",x=52,y=3,z=0,building=""}
M[#M+1] = {uid=34405,name="Southern edge of the battlefield",area="adaldar",terrain="field",info="",notes="",x=52,y=2,z=0,building=""}
M[#M+1] = {uid=34408,name="Western edge of the battlefield",area="adaldar",terrain="field",info="",notes="",x=50,y=1,z=0,building=""}
M[#M+1] = {uid=34409,name="On the battlefield",area="adaldar",terrain="field",info="",notes="",x=51,y=1,z=0,building=""}
M[#M+1] = {uid=34410,name="On the battlefield",area="adaldar",terrain="field",info="",notes="",x=52,y=1,z=0,building=""}
M[#M+1] = {uid=34451,name="Stone Archway",area="bazaar",terrain="underground",info="",notes="",x=48,y=1,z=0,building=""}
M[#M+1] = {uid=34452,name="Inside the Archway",area="bazaar",terrain="underground",info="",notes="",x=47,y=1,z=0,building=""}
M[#M+1] = {uid=34453,name="Descending into the Forlorn Cavern",area="bazaar",terrain="cave",info="",notes="",x=47,y=1,z=-1,building=""}
M[#M+1] = {uid=34454,name="A Widening Passage",area="bazaar",terrain="cave",info="",notes="",x=46,y=1,z=-1,building=""}
M[#M+1] = {uid=34455,name="Entrance to the Bazaar",area="bazaar",terrain="cave",info="",notes="",x=45,y=1,z=-1,building=""}
M[#M+1] = {uid=34456,name="Path through the Market",area="bazaar",terrain="city_underground",info="",notes="",x=44,y=1,z=-1,building=""}
M[#M+1] = {uid=34457,name="A Well Worn Path",area="bazaar",terrain="city_underground",info="",notes="",x=43,y=1,z=-1,building=""}
M[#M+1] = {uid=34458,name="Walkway Through the Market",area="bazaar",terrain="city_underground",info="shop",notes="",x=42,y=1,z=-1,building=""}
M[#M+1] = {uid=34459,name="The Way Below",area="bazaar",terrain="city_underground",info="",notes="",x=41,y=1,z=-1,building=""}
M[#M+1] = {uid=34460,name="The Dairy",area="bazaar",terrain="city_underground",info="",notes="",x=40,y=1,z=-1,building=""}
M[#M+1] = {uid=34461,name="The Bakery",area="bazaar",terrain="city_underground",info="shop",notes="",x=40,y=0,z=-1,building=""}
M[#M+1] = {uid=34462,name="Butcher Shop",area="bazaar",terrain="city_underground",info="shop",notes="",x=41,y=0,z=-1,building=""}
M[#M+1] = {uid=34463,name="Beverage Center",area="bazaar",terrain="city_underground",info="",notes="",x=42,y=0,z=-1,building=""}
M[#M+1] = {uid=34464,name="Spice Shop",area="bazaar",terrain="city_underground",info="",notes="",x=43,y=0,z=-1,building=""}
M[#M+1] = {uid=34465,name="A Feast",area="bazaar",terrain="city_underground",info="",notes="",x=44,y=0,z=-1,building=""}
M[#M+1] = {uid=34466,name="Fresh Honey Stand",area="bazaar",terrain="city_underground",info="shop",notes="",x=45,y=0,z=-1,building=""}
M[#M+1] = {uid=34468,name="A Dank Corner of a Musty Cavern",area="bazaar",terrain="underground",info="",notes="",x=47,y=0,z=0,building=""}
M[#M+1] = {uid=34469,name="The Traders' Encampment",area="bazaar",terrain="cave",info="",notes="",x=47,y=2,z=-1,building=""}
M[#M+1] = {uid=34470,name="The Head Trader's Encampment",area="bazaar",terrain="cave",info="",notes="",x=48,y=2,z=-1,building=""}
M[#M+1] = {uid=34471,name="Dark Stairway",area="bazaar",terrain="cave",info="",notes="",x=41,y=1,z=-2,building=""}
M[#M+1] = {uid=34472,name="Vegetable Shop",area="bazaar",terrain="city_underground",info="shop",notes="",x=41,y=2,z=-1,building=""}
M[#M+1] = {uid=34473,name="Playground",area="bazaar",terrain="city_underground",info="",notes="",x=42,y=2,z=-1,building=""}
M[#M+1] = {uid=34474,name="Playground",area="bazaar",terrain="city_underground",info="",notes="",x=43,y=2,z=-1,building=""}
M[#M+1] = {uid=34475,name="Well Lit Alley",area="bazaar",terrain="city_underground",info="",notes="",x=44,y=2,z=-1,building=""}
M[#M+1] = {uid=34476,name="Path to the Traders' Encampment",area="bazaar",terrain="cave",info="",notes="",x=45,y=2,z=-1,building=""}
M[#M+1] = {uid=34477,name="Path to the Traders' Encampment",area="bazaar",terrain="cave",info="",notes="",x=45,y=3,z=-1,building=""}
M[#M+1] = {uid=34478,name="Path to the Traders' Encampment",area="bazaar",terrain="cave",info="",notes="",x=46,y=3,z=-1,building=""}
M[#M+1] = {uid=34479,name="The Traders' Encampment",area="bazaar",terrain="cave",info="",notes="",x=47,y=3,z=-1,building=""}
M[#M+1] = {uid=34480,name="The Traders' Encampment",area="bazaar",terrain="cave",info="",notes="",x=48,y=3,z=-1,building=""}
M[#M+1] = {uid=34481,name="The Guard Station",area="bazaar",terrain="cave",info="",notes="",x=41,y=1,z=-3,building=""}
M[#M+1] = {uid=34482,name="Edge of the Crowd",area="bazaar",terrain="underground",info="",notes="",x=42,y=1,z=-3,building=""}
M[#M+1] = {uid=34483,name="On a Secondary Stage",area="bazaar",terrain="underground",info="",notes="",x=43,y=1,z=-3,building=""}
M[#M+1] = {uid=34484,name="Crowded Seats",area="bazaar",terrain="underground",info="",notes="",x=44,y=1,z=-3,building=""}
M[#M+1] = {uid=34485,name="A Crowded Bar Room",area="bazaar",terrain="underground",info="",notes="",x=45,y=1,z=-3,building=""}
M[#M+1] = {uid=34486,name="A Less Crowded Corner of the Club",area="bazaar",terrain="underground",info="",notes="",x=46,y=1,z=-3,building=""}
M[#M+1] = {uid=34487,name="Secondary Stage",area="bazaar",terrain="underground",info="",notes="",x=45,y=-1,z=-3,building=""}
M[#M+1] = {uid=34488,name="A Classy Seating Place",area="bazaar",terrain="underground",info="",notes="",x=46,y=-1,z=-3,building=""}
M[#M+1] = {uid=34489,name="Guards",area="bazaar",terrain="underground",info="",notes="",x=47,y=-1,z=-3,building=""}
M[#M+1] = {uid=34491,name="Gamblers' Den",area="bazaar",terrain="inside",info="",notes="",x=48,y=-2,z=-4,building=""}
M[#M+1] = {uid=34492,name="Pushing through the Crowd",area="bazaar",terrain="underground",info="",notes="",x=42,y=2,z=-3,building=""}
M[#M+1] = {uid=34493,name="In Front of the Stage",area="bazaar",terrain="underground",info="",notes="",x=43,y=2,z=-3,building=""}
M[#M+1] = {uid=34494,name="Splitting of the Crowd",area="bazaar",terrain="underground",info="",notes="",x=44,y=2,z=-3,building=""}
M[#M+1] = {uid=34495,name="Main Stage",area="bazaar",terrain="underground",info="",notes="",x=45,y=2,z=-3,building=""}
M[#M+1] = {uid=34496,name="A Very Hectic Room",area="bazaar",terrain="underground",info="",notes="",x=44,y=0,z=-3,building=""}
M[#M+1] = {uid=34497,name="In Front of a Secondary Stage",area="bazaar",terrain="underground",info="",notes="",x=45,y=0,z=-3,building=""}
M[#M+1] = {uid=34498,name="A Sitting Room",area="bazaar",terrain="underground",info="",notes="",x=46,y=0,z=-3,building=""}
M[#M+1] = {uid=34499,name="Alternate Forms of Entertainment",area="bazaar",terrain="underground",info="",notes="",x=47,y=0,z=-3,building=""}
M[#M+1] = {uid=34500,name="A Dusty Stairwell",area="bazaar",terrain="underground",info="",notes="",x=47,y=-1,z=-4,building=""}
M[#M+1] = {uid=34501,name="Private show",area="bazaar",terrain="inside",info="",notes="",x=48,y=-1,z=-4,building=""}
M[#M+1] = {uid=34502,name="Stone Arch",area="bazaar",terrain="underground",info="",notes="",x=43,y=2,z=-4,building=""}
M[#M+1] = {uid=34503,name="A Choice",area="bazaar",terrain="underground",info="",notes="",x=44,y=2,z=-4,building=""}
M[#M+1] = {uid=34504,name="Stolen Moments",area="bazaar",terrain="underground",info="",notes="",x=45,y=2,z=-4,building=""}
M[#M+1] = {uid=34505,name="Illicit Drawings",area="bazaar",terrain="underground",info="",notes="",x=41,y=0,z=-4,building=""}
M[#M+1] = {uid=34506,name="Unknown Realms",area="bazaar",terrain="underground",info="",notes="",x=42,y=0,z=-4,building=""}
M[#M+1] = {uid=34507,name="Flagellates",area="bazaar",terrain="underground",info="",notes="",x=43,y=0,z=-4,building=""}
M[#M+1] = {uid=34508,name="The Alkaloids",area="bazaar",terrain="underground",info="",notes="",x=44,y=0,z=-4,building=""}
M[#M+1] = {uid=34509,name="Pharmacy",area="bazaar",terrain="underground",info="",notes="",x=45,y=0,z=-4,building=""}
M[#M+1] = {uid=34510,name="Black Magiks",area="bazaar",terrain="underground",info="",notes="",x=46,y=0,z=-4,building=""}
M[#M+1] = {uid=34511,name="Dark Guard Chamber",area="bazaar",terrain="underground",info="",notes="",x=47,y=0,z=-4,building=""}
M[#M+1] = {uid=34512,name="Pit Overseer's Office",area="bazaar",terrain="underground",info="",notes="",x=43,y=3,z=-4,building=""}
M[#M+1] = {uid=34513,name="A Pit in the Dark",area="bazaar",terrain="underground",info="pk",notes="",x=46,y=4,z=-6,building=""}
M[#M+1] = {uid=34514,name="Stolen Treasures",area="bazaar",terrain="underground",info="",notes="",x=40,y=1,z=-4,building=""}
M[#M+1] = {uid=34515,name="Seals",area="bazaar",terrain="underground",info="",notes="",x=41,y=1,z=-4,building=""}
M[#M+1] = {uid=34516,name="Weaponry",area="bazaar",terrain="underground",info="",notes="",x=42,y=1,z=-4,building=""}
M[#M+1] = {uid=34517,name="Breastplates",area="bazaar",terrain="underground",info="shop",notes="",x=43,y=1,z=-4,building=""}
M[#M+1] = {uid=34518,name="Mirrors and Madness",area="bazaar",terrain="underground",info="",notes="",x=47,y=2,z=-4,building=""}
M[#M+1] = {uid=34519,name="Staves",area="bazaar",terrain="underground",info="",notes="",x=45,y=1,z=-4,building=""}
M[#M+1] = {uid=34520,name="Wandz",area="bazaar",terrain="underground",info="shop",notes="",x=46,y=1,z=-4,building=""}
M[#M+1] = {uid=34521,name="Walls of Painted Stone",area="bazaar",terrain="underground",info="",notes="",x=47,y=1,z=-4,building=""}
M[#M+1] = {uid=34522,name="Dimly lit corridor",area="bazaar",terrain="underground",info="",notes="",x=41,y=2,z=-5,building=""}
M[#M+1] = {uid=34523,name="The Boss's Corner",area="bazaar",terrain="underground",info="",notes="",x=43,y=2,z=-5,building=""}
M[#M+1] = {uid=34524,name="Fully Armored",area="bazaar",terrain="underground",info="",notes="",x=43,y=4,z=-5,building=""}
M[#M+1] = {uid=34525,name="Last Stance",area="bazaar",terrain="underground",info="",notes="",x=44,y=4,z=-5,building=""}
M[#M+1] = {uid=34526,name="Arena",area="bazaar",terrain="underground",info="pk",notes="",x=45,y=3,z=-6,building=""}
M[#M+1] = {uid=34527,name="Pit of Fists",area="bazaar",terrain="underground",info="pk",notes="",x=44,y=5,z=-6,building=""}
M[#M+1] = {uid=34528,name="Sparkling corner",area="bazaar",terrain="underground",info="",notes="",x=45,y=4,z=-5,building=""}
M[#M+1] = {uid=34529,name="Testing area",area="bazaar",terrain="underground",info="",notes="",x=46,y=4,z=-5,building=""}
M[#M+1] = {uid=34530,name="Survival",area="bazaar",terrain="underground",info="",notes="",x=47,y=4,z=-5,building=""}
M[#M+1] = {uid=34531,name="Sideway to the pits",area="bazaar",terrain="underground",info="",notes="",x=41,y=3,z=-5,building=""}
M[#M+1] = {uid=34532,name="Open area",area="bazaar",terrain="underground",info="",notes="",x=42,y=3,z=-5,building=""}
M[#M+1] = {uid=34533,name="A Warning",area="bazaar",terrain="underground",info="",notes="",x=43,y=3,z=-5,building=""}
M[#M+1] = {uid=34534,name="Whistling Swords, Clashing Axes",area="bazaar",terrain="underground",info="",notes="",x=43,y=5,z=-5,building=""}
M[#M+1] = {uid=34535,name="Blades of Darkness",area="bazaar",terrain="underground",info="",notes="",x=44,y=5,z=-5,building=""}
M[#M+1] = {uid=34536,name="Brutal Arenas",area="bazaar",terrain="underground",info="pk",notes="",x=45,y=4,z=-6,building=""}
M[#M+1] = {uid=34537,name="Brutal Madness",area="bazaar",terrain="underground",info="",notes="",x=45,y=3,z=-5,building=""}
M[#M+1] = {uid=34538,name="Shifting air currents",area="bazaar",terrain="underground",info="",notes="",x=45,y=5,z=-5,building=""}
M[#M+1] = {uid=34539,name="Surging energies",area="bazaar",terrain="underground",info="",notes="",x=46,y=5,z=-5,building=""}
M[#M+1] = {uid=34540,name="Gilded hallway",area="bazaar",terrain="underground",info="",notes="",x=47,y=5,z=-5,building=""}
M[#M+1] = {uid=34541,name="Office of the Five Families",area="bazaar",terrain="hallway",info="",notes="",x=38,y=6,z=-5,building=""}
M[#M+1] = {uid=34542,name="Office of the Five Families",area="bazaar",terrain="hallway",info="",notes="",x=39,y=6,z=-5,building=""}
M[#M+1] = {uid=34543,name="Office of the Five Families",area="bazaar",terrain="hallway",info="",notes="",x=39,y=5,z=-5,building=""}
M[#M+1] = {uid=34544,name="Office of the Five Families",area="bazaar",terrain="hallway",info="",notes="",x=38,y=5,z=-5,building=""}
M[#M+1] = {uid=34545,name="Waiting Room",area="bazaar",terrain="hallway",info="",notes="",x=42,y=6,z=-5,building=""}
M[#M+1] = {uid=34546,name="Waiting",area="bazaar",terrain="hallway",info="",notes="",x=43,y=6,z=-5,building=""}
M[#M+1] = {uid=34548,name="Turn in the hallway",area="bazaar",terrain="hallway",info="",notes="",x=45,y=6,z=-5,building=""}
M[#M+1] = {uid=34549,name="Associates' Hallway",area="bazaar",terrain="hallway",info="",notes="",x=46,y=6,z=-5,building=""}
M[#M+1] = {uid=34550,name="Pricey Selections",area="bazaar",terrain="underground",info="",notes="",x=47,y=6,z=-5,building=""}
M[#M+1] = {uid=34551,name="Corridor of Lies",area="bazaar",terrain="hallway",info="",notes="",x=38,y=7,z=-5,building=""}
M[#M+1] = {uid=34552,name="Corridor of Lies",area="bazaar",terrain="hallway",info="",notes="",x=39,y=7,z=-5,building=""}
M[#M+1] = {uid=34553,name="Corridor of Lies",area="bazaar",terrain="hallway",info="",notes="",x=40,y=7,z=-5,building=""}
M[#M+1] = {uid=34554,name="Corridor of Lies",area="bazaar",terrain="hallway",info="",notes="",x=41,y=7,z=-5,building=""}
M[#M+1] = {uid=34555,name="Corridor of Lies",area="bazaar",terrain="hallway",info="",notes="",x=42,y=7,z=-5,building=""}
M[#M+1] = {uid=34556,name="A Corridor of Decisions",area="bazaar",terrain="hallway",info="",notes="",x=43,y=7,z=-5,building=""}
M[#M+1] = {uid=34557,name="End of Associates' Hallway",area="bazaar",terrain="hallway",info="",notes="",x=44,y=7,z=-5,building=""}
M[#M+1] = {uid=34558,name="Second turn",area="bazaar",terrain="hallway",info="",notes="",x=45,y=7,z=-5,building=""}
M[#M+1] = {uid=34560,name="A Dimly Lit Passageway",area="bazaar",terrain="underground",info="",notes="",x=47,y=7,z=-5,building=""}
M[#M+1] = {uid=34561,name="Outside the Boss's Office",area="bazaar",terrain="office",info="",notes="",x=41,y=6,z=-5,building=""}
M[#M+1] = {uid=34562,name="Shark Lounge",area="bazaar",terrain="hallway",info="",notes="",x=39,y=8,z=-5,building=""}
M[#M+1] = {uid=34563,name="Office of Debt Collections",area="bazaar",terrain="hallway",info="",notes="",x=40,y=8,z=-5,building=""}
M[#M+1] = {uid=34564,name="Alcove in a Back Alley",area="bazaar",terrain="underground",info="shop",notes="",x=41,y=8,z=-5,building=""}
M[#M+1] = {uid=34565,name="Entrance to a small tunnel",area="bazaar",terrain="underground",info="",notes="",x=42,y=8,z=-5,building=""}
M[#M+1] = {uid=34566,name="Side passage",area="bazaar",terrain="hallway",info="",notes="",x=43,y=8,z=-5,building=""}
M[#M+1] = {uid=34567,name="Final Tortures",area="bazaar",terrain="cave",info="",notes="",x=44,y=8,z=-5,building=""}
M[#M+1] = {uid=34569,name="A Lit Passageway",area="bazaar",terrain="underground",info="",notes="",x=46,y=8,z=-5,building=""}
M[#M+1] = {uid=34570,name="A Dimly Lit Passageway",area="bazaar",terrain="underground",info="",notes="",x=47,y=8,z=-5,building=""}
M[#M+1] = {uid=34571,name="Boss's Personal Chamber",area="bazaar",terrain="office",info="",notes="",x=41,y=5,z=-5,building=""}
M[#M+1] = {uid=34572,name="Entrance to Unknown Treasures",area="bazaar",terrain="cave",info="",notes="",x=39,y=8,z=-6,building=""}
M[#M+1] = {uid=34573,name="Unknown Treasures",area="bazaar",terrain="cave",info="",notes="",x=40,y=8,z=-6,building=""}
M[#M+1] = {uid=34575,name="Cramped crawlway",area="bazaar",terrain="underground",info="",notes="",x=42,y=9,z=-5,building=""}
M[#M+1] = {uid=34578,name="Half-Griffon Slaves' Quarters",area="bazaar",terrain="underground",info="",notes="",x=43,y=8,z=-5,building=""}
M[#M+1] = {uid=34579,name="Slaves' Caverns",area="bazaar",terrain="underground",info="",notes="",x=44,y=8,z=-5,building=""}
M[#M+1] = {uid=34580,name="Kobold Slave Quarters",area="bazaar",terrain="underground",info="",notes="",x=45,y=8,z=-5,building=""}
M[#M+1] = {uid=34581,name="Jewels and Timepieces",area="bazaar",terrain="cave",info="",notes="",x=38,y=9,z=-6,building=""}
M[#M+1] = {uid=34582,name="Split in the cave",area="bazaar",terrain="cave",info="",notes="",x=39,y=9,z=-6,building=""}
M[#M+1] = {uid=34583,name="Rear corner of the Treasures",area="bazaar",terrain="cave",info="",notes="",x=40,y=9,z=-6,building=""}
M[#M+1] = {uid=34584,name="Difficult passage",area="bazaar",terrain="underground",info="",notes="",x=44,y=9,z=-5,building=""}
M[#M+1] = {uid=34585,name="Wriggle room",area="bazaar",terrain="underground",info="",notes="",x=43,y=9,z=-5,building=""}
M[#M+1] = {uid=34588,name="Slave Master's Room",area="bazaar",terrain="underground",info="",notes="",x=43,y=9,z=-5,building=""}
M[#M+1] = {uid=34589,name="Dwarven Slaves' Quarters",area="bazaar",terrain="underground",info="",notes="",x=44,y=9,z=-5,building=""}
M[#M+1] = {uid=34590,name="Elven Slaves' Quarters",area="bazaar",terrain="underground",info="",notes="",x=45,y=9,z=-5,building=""}
M[#M+1] = {uid=34591,name="Widening cavern",area="bazaar",terrain="underground",info="",notes="",x=42,y=2,z=-5,building=""}
M[#M+1] = {uid=34592,name="Turbulent Sea",area="sahuagin",terrain="ocean",info="",notes="",x=7,y=32,z=0,building=""}
M[#M+1] = {uid=34593,name="Deeper into the Abyss",area="sahuagin",terrain="underwater",info="",notes="",x=7,y=32,z=-1,building=""}
M[#M+1] = {uid=34594,name="Deeper into the Abyss",area="sahuagin",terrain="underwater",info="",notes="",x=7,y=31,z=-1,building=""}
M[#M+1] = {uid=34595,name="Deeper into the Abyss",area="sahuagin",terrain="underwater",info="",notes="",x=8,y=32,z=-1,building=""}
M[#M+1] = {uid=34596,name="Deeper into the Abyss",area="sahuagin",terrain="underwater",info="",notes="",x=6,y=32,z=-1,building=""}
M[#M+1] = {uid=34597,name="Deeper into the Abyss",area="sahuagin",terrain="underwater",info="",notes="",x=8,y=33,z=-1,building=""}
M[#M+1] = {uid=34598,name="Deeper into the Abyss",area="sahuagin",terrain="underwater",info="",notes="",x=6,y=33,z=-1,building=""}
M[#M+1] = {uid=34599,name="Behind a Cluster of Seaweed",area="sahuagin",terrain="underwater",info="",notes="",x=8,y=33,z=-2,building=""}
M[#M+1] = {uid=34602,name="Alcove below Stronghold of Kutrok",area="sahuagin",terrain="underwater",info="pk,maze",notes="",x=7,y=32,z=0,building=""}
M[#M+1] = {uid=34604,name="Alcove below Stronghold of Azhirlur",area="sahuagin",terrain="underwater",info="pk,maze",notes="",x=7,y=32,z=0,building=""}
M[#M+1] = {uid=34606,name="Subaqueous Caverns",area="sahuagin",terrain="underwater",info="pk,maze",notes="",x=7,y=32,z=0,building=""}
M[#M+1] = {uid=34607,name="Subaqueous Caverns",area="sahuagin",terrain="underwater",info="pk,maze",notes="",x=7,y=32,z=0,building=""}
M[#M+1] = {uid=34608,name="Subaqueous Caverns",area="sahuagin",terrain="underwater",info="pk,maze",notes="",x=7,y=32,z=0,building=""}
M[#M+1] = {uid=34609,name="Subaqueous Caverns",area="sahuagin",terrain="underwater",info="pk,maze",notes="",x=7,y=32,z=0,building=""}
M[#M+1] = {uid=34611,name="Crudely Carved Passage",area="sahuagin",terrain="underwater",info="",notes="",x=7,y=32,z=0,building=""}
M[#M+1] = {uid=34613,name="Crudely Carved Passage",area="sahuagin",terrain="underwater",info="",notes="",x=7,y=32,z=0,building=""}
M[#M+1] = {uid=34629,name="Dim Stronghold Passage",area="sahuagin",terrain="underwater",info="",notes="",x=7,y=33,z=0,building=""}
M[#M+1] = {uid=34630,name="Shark-filled Passage",area="sahuagin",terrain="underwater",info="",notes="",x=8,y=33,z=0,building=""}
M[#M+1] = {uid=34631,name="Treasure Strongroom",area="sahuagin",terrain="underwater",info="",notes="",x=9,y=33,z=0,building=""}
M[#M+1] = {uid=34643,name="A Vast Prairie",area="hatchling",terrain="field",info="",notes="",x=10,y=26,z=-1,building=""}
M[#M+1] = {uid=34644,name="A Vast Prairie",area="hatchling",terrain="field",info="",notes="",x=11,y=29,z=-1,building=""}
M[#M+1] = {uid=34645,name="A Vast Prairie",area="hatchling",terrain="field",info="",notes="",x=12,y=26,z=-1,building=""}
M[#M+1] = {uid=34646,name="A Vast Prairie",area="hatchling",terrain="field",info="",notes="",x=10,y=28,z=-1,building=""}
M[#M+1] = {uid=34647,name="A Vast Prairie",area="hatchling",terrain="field",info="",notes="",x=11,y=28,z=-1,building=""}
M[#M+1] = {uid=34648,name="A Vast Prairie",area="hatchling",terrain="field",info="",notes="",x=12,y=28,z=-1,building=""}
M[#M+1] = {uid=34649,name="A Forest At The Foot Of The Mountains",area="hatchling",terrain="forest",info="",notes="",x=10,y=27,z=-1,building=""}
M[#M+1] = {uid=34650,name="Sacred Mountains Of The Dragon",area="hatchling",terrain="mountain",info="",notes="",x=11,y=27,z=-1,building=""}
M[#M+1] = {uid=34651,name="A Forest At The Foot Of The Mountains",area="hatchling",terrain="forest",info="",notes="",x=12,y=27,z=-1,building=""}
M[#M+1] = {uid=34652,name="Before A Vast Prairie",area="hatchling",terrain="field",info="",notes="",x=11,y=30,z=-1,building=""}
M[#M+1] = {uid=34653,name="At A Corner",area="hatchling",terrain="cave",info="",notes="",x=8,y=27,z=-3,building=""}
M[#M+1] = {uid=34654,name="The Path Continues",area="hatchling",terrain="cave",info="",notes="",x=8,y=28,z=-3,building=""}
M[#M+1] = {uid=34655,name="The Nest",area="hatchling",terrain="cave",info="",notes="",x=9,y=28,z=-3,building=""}
M[#M+1] = {uid=34656,name="The Path Continues",area="hatchling",terrain="cave",info="",notes="",x=8,y=29,z=-3,building=""}
M[#M+1] = {uid=34657,name="Almost There",area="hatchling",terrain="cave",info="",notes="",x=9,y=29,z=-3,building=""}
M[#M+1] = {uid=34658,name="Along The Path",area="hatchling",terrain="cave",info="",notes="",x=9,y=30,z=-3,building=""}
M[#M+1] = {uid=34659,name="A Bend In The Path",area="hatchling",terrain="cave",info="",notes="",x=8,y=30,z=-3,building=""}
M[#M+1] = {uid=34660,name="Entering An Underground Cavern",area="hatchling",terrain="cave",info="",notes="",x=10,y=30,z=-3,building=""}
M[#M+1] = {uid=34661,name="Nearing The Top Of The Pathway",area="hatchling",terrain="cave",info="",notes="",x=10,y=29,z=-3,building=""}
M[#M+1] = {uid=34662,name="Nearing The Top Of The Pathway",area="hatchling",terrain="cave",info="",notes="",x=10,y=28,z=-3,building=""}
M[#M+1] = {uid=34663,name="Pathway To The Eggs",area="hatchling",terrain="cave",info="",notes="",x=10,y=27,z=-3,building=""}
M[#M+1] = {uid=34664,name="Pathway To The Eggs",area="hatchling",terrain="cave",info="",notes="",x=9,y=27,z=-3,building=""}
M[#M+1] = {uid=34665,name="Into The Murky Depths",area="hatchling",terrain="volcano",info="",notes="",x=11,y=27,z=-3,building=""}
M[#M+1] = {uid=34666,name="Nearing The End Of A Lava Tube",area="hatchling",terrain="volcano",info="",notes="",x=11,y=29,z=-3,building=""}
M[#M+1] = {uid=34667,name="Along A Lava Tube",area="hatchling",terrain="volcano",info="",notes="",x=11,y=28,z=-3,building=""}
M[#M+1] = {uid=34668,name="A Dark Tunnel",area="hatchling",terrain="underground",info="",notes="",x=11,y=27,z=-2,building=""}
M[#M+1] = {uid=34669,name="The End Of A Lava Tube",area="hatchling",terrain="volcano",info="",notes="",x=11,y=30,z=-3,building=""}
M[#M+1] = {uid=34670,name="Egg dropoff point",area="hatchling",terrain="underground",info="",notes="",x=11,y=27,z=0,building=""}
M[#M+1] = {uid=34671,name="Broad underground tunnel",area="hatchling",terrain="underground",info="",notes="",x=11,y=26,z=0,building=""}
M[#M+1] = {uid=34672,name="Egg incubation room 1",area="hatchling",terrain="city",info="",notes="",x=12,y=26,z=0,building=""}
M[#M+1] = {uid=34673,name="Egg incubation room 2",area="hatchling",terrain="field",info="",notes="",x=10,y=26,z=0,building=""}
M[#M+1] = {uid=34674,name="Freshly hatched dragons",area="hatchling",terrain="field",info="",notes="",x=11,y=25,z=0,building=""}
M[#M+1] = {uid=34675,name="Egg incubation room 3",area="hatchling",terrain="underground",info="",notes="",x=12,y=25,z=0,building=""}
M[#M+1] = {uid=34676,name="Egg incubation room 4",area="hatchling",terrain="underground",info="",notes="",x=10,y=25,z=0,building=""}
M[#M+1] = {uid=34677,name="Dragon nursery",area="hatchling",terrain="underground",info="",notes="",x=11,y=24,z=0,building=""}
M[#M+1] = {uid=34678,name="Piles of hatchlings",area="hatchling",terrain="underground",info="",notes="",x=12,y=24,z=0,building=""}
M[#M+1] = {uid=34679,name="Feeding time",area="hatchling",terrain="underground",info="",notes="",x=12,y=23,z=0,building=""}
M[#M+1] = {uid=34680,name="Centre of the nursery",area="hatchling",terrain="underground",info="",notes="",x=11,y=23,z=0,building=""}
M[#M+1] = {uid=34681,name="A small opening",area="hatchling",terrain="underground",info="",notes="",x=10,y=24,z=0,building=""}
M[#M+1] = {uid=34682,name="Stalagmites and stalactites",area="hatchling",terrain="field",info="",notes="",x=10,y=23,z=0,building=""}
M[#M+1] = {uid=34683,name="An anarchic corner of the cave",area="hatchling",terrain="field",info="",notes="",x=10,y=22,z=0,building=""}
M[#M+1] = {uid=34684,name="A cave opening",area="hatchling",terrain="field",info="",notes="",x=11,y=22,z=0,building=""}
M[#M+1] = {uid=34685,name="Naptime",area="hatchling",terrain="field",info="",notes="",x=12,y=22,z=0,building=""}
M[#M+1] = {uid=34686,name="Overlooking a kindergarten",area="hatchling",terrain="field",info="",notes="",x=11,y=21,z=0,building=""}
M[#M+1] = {uid=34687,name="Rocky pathway through the cavern",area="hatchling",terrain="inside",info="",notes="",x=9,y=21,z=0,building=""}
M[#M+1] = {uid=34688,name="Pathway before the rocky outcrop",area="hatchling",terrain="inside",info="",notes="",x=8,y=21,z=0,building=""}
M[#M+1] = {uid=34689,name="Rocky outcrop",area="hatchling",terrain="inside",info="",notes="",x=7,y=21,z=0,building=""}
M[#M+1] = {uid=34690,name="Pathway before the rocky outcrop",area="hatchling",terrain="inside",info="",notes="",x=6,y=21,z=0,building=""}
M[#M+1] = {uid=34691,name="Pathway through the cavern",area="hatchling",terrain="inside",info="",notes="",x=5,y=21,z=0,building=""}
M[#M+1] = {uid=34692,name="Glittering Room",area="hatchling",terrain="inside",info="",notes="",x=9,y=20,z=0,building=""}
M[#M+1] = {uid=34693,name="Magic Room",area="hatchling",terrain="inside",info="",notes="",x=8,y=20,z=0,building=""}
M[#M+1] = {uid=34694,name="Proving Ground",area="hatchling",terrain="inside",info="",notes="",x=7,y=20,z=0,building=""}
M[#M+1] = {uid=34695,name="Feeding Room",area="hatchling",terrain="inside",info="",notes="",x=6,y=20,z=0,building=""}
M[#M+1] = {uid=34696,name="Plotting.. er Rest Room",area="hatchling",terrain="inside",info="",notes="",x=5,y=20,z=0,building=""}
M[#M+1] = {uid=34697,name="Nesting Room",area="hatchling",terrain="inside",info="",notes="",x=9,y=22,z=0,building=""}
M[#M+1] = {uid=34698,name="Feeding Grounds",area="hatchling",terrain="inside",info="",notes="",x=8,y=22,z=0,building=""}
M[#M+1] = {uid=34699,name="Proving Ground",area="hatchling",terrain="inside",info="",notes="",x=7,y=22,z=0,building=""}
M[#M+1] = {uid=34700,name="Magic room",area="hatchling",terrain="inside",info="",notes="",x=6,y=22,z=0,building=""}
M[#M+1] = {uid=34701,name="Glittering Room",area="hatchling",terrain="inside",info="",notes="",x=5,y=22,z=0,building=""}
M[#M+1] = {uid=34702,name="Westerly exit to the large cavern",area="hatchling",terrain="inside",info="",notes="",x=4,y=21,z=0,building=""}
M[#M+1] = {uid=34703,name="Entry to a vast cavern",area="hatchling",terrain="inside",info="",notes="",x=10,y=21,z=0,building=""}
M[#M+1] = {uid=34704,name="Pick your battle!",area="hatchling",terrain="bloodyroom",info="",notes="",x=3,y=21,z=0,building=""}
M[#M+1] = {uid=34705,name="Evening",area="hatchling",terrain="air",info="",notes="",x=3,y=20,z=0,building=""}
M[#M+1] = {uid=34706,name="Sunset",area="hatchling",terrain="air",info="",notes="",x=3,y=19,z=0,building=""}
M[#M+1] = {uid=34707,name="Twilight",area="hatchling",terrain="air",info="",notes="",x=3,y=18,z=0,building=""}
M[#M+1] = {uid=34708,name="Dusk",area="hatchling",terrain="air",info="",notes="",x=3,y=17,z=0,building=""}
M[#M+1] = {uid=34709,name="Moon rise",area="hatchling",terrain="air",info="",notes="",x=3,y=16,z=0,building=""}
M[#M+1] = {uid=34710,name="Hopeless...",area="hatchling",terrain="hellinside",info="",notes="",x=2,y=21,z=3,building=""}
M[#M+1] = {uid=34711,name="Predawn",area="hatchling",terrain="air",info="",notes="",x=3,y=21,z=-1,building=""}
M[#M+1] = {uid=34712,name="Sunrise",area="hatchling",terrain="mountain",info="",notes="",x=3,y=21,z=-2,building=""}
M[#M+1] = {uid=34713,name="Morning",area="hatchling",terrain="mountain",info="",notes="",x=3,y=20,z=-2,building=""}
M[#M+1] = {uid=34714,name="A Fine Spring Day",area="hatchling",terrain="mountain",info="",notes="",x=3,y=19,z=-2,building=""}
M[#M+1] = {uid=34715,name="Warm Sunshine",area="hatchling",terrain="mountain",info="",notes="",x=2,y=19,z=-2,building=""}
M[#M+1] = {uid=34716,name="Blistering Heat",area="hatchling",terrain="air",info="",notes="",x=2,y=18,z=-2,building=""}
M[#M+1] = {uid=34717,name="Flying at night",area="hatchling",terrain="air",info="",notes="",x=3,y=21,z=1,building=""}
M[#M+1] = {uid=34718,name="Utter darkness",area="hatchling",terrain="hellinside",info="",notes="",x=3,y=20,z=1,building=""}
M[#M+1] = {uid=34719,name="Total eclipse",area="hatchling",terrain="hellinside",info="",notes="",x=3,y=20,z=2,building=""}
M[#M+1] = {uid=34720,name="Thick blackness",area="hatchling",terrain="hellinside",info="",notes="",x=3,y=21,z=2,building=""}
M[#M+1] = {uid=34721,name="Flying in circles! Lost!",area="hatchling",terrain="hellinside",info="",notes="",x=3,y=22,z=2,building=""}
M[#M+1] = {uid=34722,name="The ravening night",area="hatchling",terrain="hellinside",info="",notes="",x=2,y=21,z=2,building=""}
M[#M+1] = {uid=34723,name="Battle's End",area="hatchling",terrain="temple",info="",notes="",x=3,y=15,z=0,building=""}
M[#M+1] = {uid=34724,name="Up a lava tube",area="hatchling",terrain="underground",info="",notes="",x=7,y=21,z=1,building=""}
M[#M+1] = {uid=34725,name="Approaching the heart of the mountain",area="hatchling",terrain="inside",info="",notes="",x=3,y=11,z=0,building=""}
M[#M+1] = {uid=34726,name="Almost at the heart",area="hatchling",terrain="inside",info="pk",notes="",x=3,y=10,z=0,building=""}
M[#M+1] = {uid=34727,name="Nearing the peak",area="hatchling",terrain="underground",info="",notes="",x=7,y=21,z=2,building=""}
M[#M+1] = {uid=34728,name="The peak of the mountain",area="hatchling",terrain="mountain_cyan",info="",notes="",x=7,y=21,z=3,building=""}
M[#M+1] = {uid=34729,name="Closer to the heart",area="hatchling",terrain="inside",info="",notes="",x=3,y=12,z=0,building=""}
M[#M+1] = {uid=34730,name="Flight School",area="hatchling",terrain="mist",info="",notes="",x=8,y=21,z=3,building=""}
M[#M+1] = {uid=34731,name="Learning to fly",area="hatchling",terrain="air",info="maze",notes="",x=8,y=21,z=4,building=""}
M[#M+1] = {uid=34732,name="Learning to fly",area="hatchling",terrain="air",info="maze",notes="",x=10,y=23,z=0,building=""}
M[#M+1] = {uid=34733,name="Learning to fly",area="hatchling",terrain="air",info="maze",notes="",x=10,y=23,z=0,building=""}
M[#M+1] = {uid=34734,name="Learning to fly",area="hatchling",terrain="air",info="maze",notes="",x=10,y=23,z=0,building=""}
M[#M+1] = {uid=34735,name="Learning to fly",area="hatchling",terrain="air",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=34736,name="Learning to fly",area="hatchling",terrain="air",info="",notes="",x=-1,y=0,z=0,building=""}
M[#M+1] = {uid=34737,name="Learning to fly",area="hatchling",terrain="air",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=34738,name="Before the heart",area="hatchling",terrain="inside",info="",notes="",x=3,y=14,z=0,building=""}
M[#M+1] = {uid=34739,name="A tunnel to the heart of the mountain",area="hatchling",terrain="inside",info="",notes="",x=3,y=13,z=0,building=""}
M[#M+1] = {uid=34740,name="At the heart of the mountain",area="hatchling",terrain="inside",info="pk",notes="",x=3,y=9,z=0,building=""}
M[#M+1] = {uid=34741,name="Behind the Western Pillar",area="beer",terrain="inside",info="",notes="",x=-4,y=3,z=0,building=""}
M[#M+1] = {uid=34800,name="The Outskirts",area="spyreknow",terrain="underground",info="",notes="",x=36,y=7,z=0,building=""}
M[#M+1] = {uid=34801,name="A Rock Fissure",area="spyreknow",terrain="underground",info="",notes="",x=36,y=6,z=0,building=""}
M[#M+1] = {uid=34802,name="Underground Crawlway",area="spyreknow",terrain="underground",info="",notes="",x=36,y=5,z=0,building=""}
M[#M+1] = {uid=34803,name="Rock Face",area="spyreknow",terrain="underground",info="",notes="",x=36,y=3,z=0,building=""}
M[#M+1] = {uid=34804,name="Stalactite Cavern",area="spyreknow",terrain="underground",info="",notes="",x=36,y=4,z=0,building=""}
M[#M+1] = {uid=34805,name="Air Shaft",area="spyreknow",terrain="underground",info="",notes="",x=37,y=3,z=0,building=""}
M[#M+1] = {uid=34806,name="Miner's Storage Shed",area="spyreknow",terrain="underground",info="",notes="",x=37,y=4,z=0,building=""}
M[#M+1] = {uid=34807,name="Emerging into the Light",area="spyreknow",terrain="inside",info="",notes="",x=37,y=3,z=1,building=""}
M[#M+1] = {uid=34808,name="Cleric's Sacrificial Altar",area="spyreknow",terrain="temple",info="",notes="",x=38,y=3,z=1,building=""}
M[#M+1] = {uid=34809,name="Temple Square",area="spyreknow",terrain="temple",info="",notes="",x=37,y=2,z=1,building=""}
M[#M+1] = {uid=34810,name="Temple Foyer",area="spyreknow",terrain="temple",info="",notes="",x=37,y=1,z=1,building=""}
M[#M+1] = {uid=34811,name="Cleric's Inner Sanctum",area="spyreknow",terrain="temple",info="",notes="",x=38,y=1,z=1,building=""}
M[#M+1] = {uid=34812,name="Ascending Into Confusion",area="spyreknow",terrain="inside",info="",notes="",x=38,y=1,z=2,building=""}
M[#M+1] = {uid=34813,name="Twisting Corridor",area="spyreknow",terrain="mountain",info="",notes="",x=39,y=1,z=2,building=""}
M[#M+1] = {uid=34814,name="Hidden Alcove",area="spyreknow",terrain="mountain",info="",notes="",x=40,y=1,z=2,building=""}
M[#M+1] = {uid=34815,name="Shadowy Passage",area="spyreknow",terrain="mountain",info="",notes="",x=39,y=2,z=2,building=""}
M[#M+1] = {uid=34816,name="Shadowy Passage",area="spyreknow",terrain="mountain",info="",notes="",x=39,y=3,z=2,building=""}
M[#M+1] = {uid=34817,name="Meadow Rise",area="spyreknow",terrain="inside",info="",notes="",x=39,y=3,z=3,building=""}
M[#M+1] = {uid=34818,name="Meadow",area="spyreknow",terrain="field",info="",notes="",x=39,y=2,z=3,building=""}
M[#M+1] = {uid=34819,name="Meadow",area="spyreknow",terrain="field",info="",notes="",x=39,y=1,z=3,building=""}
M[#M+1] = {uid=34820,name="Meadow",area="spyreknow",terrain="field",info="",notes="",x=40,y=1,z=3,building=""}
M[#M+1] = {uid=34821,name="Waterfall",area="spyreknow",terrain="field",info="",notes="",x=40,y=2,z=3,building=""}
M[#M+1] = {uid=34822,name="Treeline",area="spyreknow",terrain="inside",info="",notes="",x=40,y=2,z=4,building=""}
M[#M+1] = {uid=34823,name="Rain Forest",area="spyreknow",terrain="forest",info="",notes="",x=40,y=1,z=4,building=""}
M[#M+1] = {uid=34824,name="Vine Covered Path",area="spyreknow",terrain="forest",info="",notes="",x=40,y=0,z=4,building=""}
M[#M+1] = {uid=34825,name="Giant Tree",area="spyreknow",terrain="forest",info="",notes="",x=41,y=0,z=4,building=""}
M[#M+1] = {uid=34826,name="Rain Forest",area="spyreknow",terrain="forest",info="",notes="",x=41,y=1,z=4,building=""}
M[#M+1] = {uid=34827,name="Pit Trap",area="spyreknow",terrain="forest",info="",notes="",x=41,y=1,z=3,building=""}
M[#M+1] = {uid=34828,name="Frosted Treetop",area="spyreknow",terrain="inside",info="",notes="",x=41,y=0,z=5,building=""}
M[#M+1] = {uid=34829,name="Snowy Trail",area="spyreknow",terrain="ice",info="",notes="",x=41,y=-1,z=5,building=""}
M[#M+1] = {uid=34830,name="Snowy Trail",area="spyreknow",terrain="ice",info="",notes="",x=41,y=-2,z=5,building=""}
M[#M+1] = {uid=34831,name="Glacial Summit",area="spyreknow",terrain="ice",info="",notes="",x=42,y=-2,z=5,building=""}
M[#M+1] = {uid=34832,name="Icy Precipice",area="spyreknow",terrain="ice",info="",notes="",x=42,y=-1,z=5,building=""}
M[#M+1] = {uid=34833,name="Pillar in the Clouds",area="spyreknow",terrain="inside",info="",notes="",x=42,y=-2,z=6,building=""}
M[#M+1] = {uid=34834,name="Great Pillar",area="spyreknow",terrain="air",info="",notes="",x=42,y=-3,z=6,building=""}
M[#M+1] = {uid=34835,name="Pocket In The Clouds",area="spyreknow",terrain="air",info="",notes="",x=42,y=-4,z=6,building=""}
M[#M+1] = {uid=34836,name="In the Great Pillar",area="spyreknow",terrain="air",info="",notes="",x=42,y=-3,z=5,building=""}
M[#M+1] = {uid=34837,name="Above The Clouds",area="spyreknow",terrain="air",info="",notes="",x=42,y=-3,z=7,building=""}
M[#M+1] = {uid=34840,name="The Outskirts",area="spyreknow",terrain="underground",info="",notes="",x=35,y=7,z=0,building=""}
M[#M+1] = {uid=34841,name="The Outskirts",area="spyreknow",terrain="underground",info="",notes="",x=37,y=7,z=0,building=""}
M[#M+1] = {uid=34842,name="In Spyre's Shadow",area="spyreknow",terrain="underground",info="",notes="",x=35,y=6,z=0,building=""}
M[#M+1] = {uid=34843,name="In Spyre's Shadow",area="spyreknow",terrain="underground",info="",notes="",x=37,y=6,z=0,building=""}
M[#M+1] = {uid=34844,name="Stalagmite Cavern",area="spyreknow",terrain="underground",info="",notes="",x=35,y=4,z=0,building=""}
M[#M+1] = {uid=34845,name="Stalactite Cavern",area="spyreknow",terrain="underground",info="",notes="",x=34,y=4,z=0,building=""}
M[#M+1] = {uid=34846,name="Rock Face",area="spyreknow",terrain="underground",info="",notes="",x=35,y=3,z=0,building=""}
M[#M+1] = {uid=34847,name="Rock Face",area="spyreknow",terrain="underground",info="",notes="",x=34,y=3,z=0,building=""}
M[#M+1] = {uid=34848,name="Animal Pen",area="spyreknow",terrain="city",info="",notes="",x=39,y=3,z=1,building=""}
M[#M+1] = {uid=34849,name="Small House",area="spyreknow",terrain="city",info="",notes="",x=38,y=2,z=1,building=""}
M[#M+1] = {uid=34850,name="Caretaker's Hovel",area="spyreknow",terrain="inside",info="",notes="",x=36,y=2,z=1,building=""}
M[#M+1] = {uid=34851,name="Cellar",area="spyreknow",terrain="city",info="",notes="",x=36,y=2,z=0,building=""}
M[#M+1] = {uid=34852,name="Confessional",area="spyreknow",terrain="temple",info="",notes="",x=36,y=1,z=1,building=""}
M[#M+1] = {uid=34853,name="Rectory Hallway",area="spyreknow",terrain="temple",info="",notes="",x=37,y=0,z=1,building=""}
M[#M+1] = {uid=34854,name="Rectory Hallway",area="spyreknow",terrain="temple",info="",notes="",x=37,y=-1,z=1,building=""}
M[#M+1] = {uid=34855,name="Priest's Cell",area="spyreknow",terrain="temple",info="",notes="",x=36,y=-1,z=1,building=""}
M[#M+1] = {uid=34856,name="Priest's Cell",area="spyreknow",terrain="temple",info="",notes="",x=38,y=-1,z=1,building=""}
M[#M+1] = {uid=34857,name="Shadowy Passage",area="spyreknow",terrain="mountain",info="",notes="",x=39,y=0,z=2,building=""}
M[#M+1] = {uid=34858,name="Shadowy Passage",area="spyreknow",terrain="mountain",info="",notes="",x=39,y=-1,z=2,building=""}
M[#M+1] = {uid=34862,name="Dark Hallway",area="spyreknow",terrain="mountain",info="",notes="",x=39,y=-1,z=3,building=""}
M[#M+1] = {uid=34863,name="Dark Hallway",area="spyreknow",terrain="mountain",info="",notes="",x=40,y=-1,z=3,building=""}
M[#M+1] = {uid=34864,name="Dark Hallway",area="spyreknow",terrain="mountain",info="",notes="",x=40,y=0,z=3,building=""}
M[#M+1] = {uid=34865,name="Meadow Rise",area="spyreknow",terrain="field",info="",notes="",x=38,y=3,z=3,building=""}
M[#M+1] = {uid=34866,name="Picnic Area",area="spyreknow",terrain="field",info="",notes="",x=38,y=2,z=3,building=""}
M[#M+1] = {uid=34867,name="Hill Top",area="spyreknow",terrain="field",info="",notes="",x=37,y=2,z=3,building=""}
M[#M+1] = {uid=34868,name="Picnic Area",area="spyreknow",terrain="field",info="",notes="",x=38,y=1,z=3,building=""}
M[#M+1] = {uid=34869,name="Ant Colony",area="spyreknow",terrain="field",info="",notes="",x=37,y=1,z=3,building=""}
M[#M+1] = {uid=34875,name="Witchdoctor's Hut",area="spyreknow",terrain="forest",info="",notes="",x=39,y=2,z=4,building=""}
M[#M+1] = {uid=34876,name="Cannibal Village",area="spyreknow",terrain="forest",info="",notes="",x=39,y=1,z=4,building=""}
M[#M+1] = {uid=34877,name="Vine Covered Path",area="spyreknow",terrain="forest",info="",notes="",x=40,y=-1,z=4,building=""}
M[#M+1] = {uid=34878,name="Vine Covered Path",area="spyreknow",terrain="forest",info="",notes="",x=39,y=-1,z=4,building=""}
M[#M+1] = {uid=34879,name="Nesting Cliff",area="spyreknow",terrain="forest",info="",notes="",x=39,y=-2,z=4,building=""}
M[#M+1] = {uid=34880,name="Climbing the Vines",area="spyreknow",terrain="forest",info="",notes="",x=40,y=-1,z=5,building=""}
M[#M+1] = {uid=34881,name="Swinging Through the Trees",area="spyreknow",terrain="forest",info="",notes="",x=40,y=0,z=5,building=""}
M[#M+1] = {uid=34882,name="Swinging Through the Trees",area="spyreknow",terrain="forest",info="",notes="",x=41,y=0,z=5,building=""}
M[#M+1] = {uid=34883,name="Icy Path",area="spyreknow",terrain="ice",info="",notes="",x=41,y=-3,z=5,building=""}
M[#M+1] = {uid=34884,name="Icy Path",area="spyreknow",terrain="ice",info="",notes="",x=42,y=-3,z=5,building=""}
M[#M+1] = {uid=34885,name="Icy Path",area="spyreknow",terrain="ice",info="",notes="",x=43,y=-3,z=5,building=""}
M[#M+1] = {uid=34886,name="Blowing Winds",area="spyreknow",terrain="ice",info="",notes="",x=42,y=-4,z=5,building=""}
M[#M+1] = {uid=34887,name="A Blizzard",area="spyreknow",terrain="ice",info="",notes="",x=42,y=-5,z=5,building=""}
M[#M+1] = {uid=34888,name="A Blizzard",area="spyreknow",terrain="ice",info="",notes="",x=41,y=-5,z=5,building=""}
M[#M+1] = {uid=34889,name="Ice Cave",area="spyreknow",terrain="ice",info="",notes="",x=41,y=-4,z=5,building=""}
M[#M+1] = {uid=34890,name="Ice Cave",area="spyreknow",terrain="ice",info="",notes="",x=40,y=-4,z=5,building=""}
M[#M+1] = {uid=34891,name="Ice Cave",area="spyreknow",terrain="ice",info="",notes="",x=40,y=-3,z=5,building=""}
M[#M+1] = {uid=34892,name="Light as a Feather",area="spyreknow",terrain="air",info="",notes="",x=42,y=-1,z=6,building=""}
M[#M+1] = {uid=34893,name="Light as a Feather",area="spyreknow",terrain="air",info="",notes="",x=43,y=-2,z=6,building=""}
M[#M+1] = {uid=34894,name="Cloud City",area="spyreknow",terrain="air",info="",notes="",x=41,y=-3,z=6,building=""}
M[#M+1] = {uid=34895,name="Cloud City",area="spyreknow",terrain="air",info="",notes="",x=41,y=-2,z=6,building=""}
M[#M+1] = {uid=34896,name="Cloud City",area="spyreknow",terrain="air",info="",notes="",x=41,y=-4,z=6,building=""}
M[#M+1] = {uid=34897,name="Pocket In The Clouds",area="spyreknow",terrain="air",info="",notes="",x=43,y=-3,z=7,building=""}
M[#M+1] = {uid=35004,name="Ul'te Plains",area="manorville",terrain="field",info="",notes="",x=49,y=22,z=0,building=""}
M[#M+1] = {uid=35005,name="Through the Clearing",area="deneria",terrain="forest",info="",notes="",x=45,y=33,z=0,building=""}
M[#M+1] = {uid=35006,name="Within Deneria",area="deneria",terrain="forest",info="",notes="",x=45,y=32,z=0,building=""}
M[#M+1] = {uid=35007,name="Before the Tower of Nuril",area="deneria",terrain="forest",info="",notes="",x=45,y=31,z=0,building=""}
M[#M+1] = {uid=35008,name="At the Crossroads",area="deneria",terrain="forest",info="",notes="",x=44,y=31,z=0,building=""}
M[#M+1] = {uid=35009,name="At a Small Lake",area="deneria",terrain="forest",info="",notes="",x=43,y=31,z=0,building=""}
M[#M+1] = {uid=35010,name="An Overgrown Path",area="deneria",terrain="forest",info="",notes="",x=43,y=32,z=0,building=""}
M[#M+1] = {uid=35011,name="Before the Castle Kaleon",area="deneria",terrain="forest",info="",notes="",x=44,y=32,z=0,building=""}
M[#M+1] = {uid=35012,name="Deep Within the Forest",area="deneria",terrain="forest",info="",notes="",x=43,y=33,z=0,building=""}
M[#M+1] = {uid=35013,name="Before the Gates of Castle Kaleon",area="deneria",terrain="forest",info="",notes="",x=44,y=31,z=0,building=""}
M[#M+1] = {uid=35014,name="Before the Church of Miad'Bir",area="deneria",terrain="inside",info="",notes="",x=44,y=30,z=0,building=""}
M[#M+1] = {uid=35015,name="A cave",area="deneria",terrain="cave",info="",notes="",x=45,y=32,z=-1,building=""}
M[#M+1] = {uid=35016,name="A cave",area="deneria",terrain="cave",info="",notes="",x=45,y=33,z=-1,building=""}
M[#M+1] = {uid=35017,name="A cave",area="deneria",terrain="cave",info="",notes="",x=46,y=33,z=-1,building=""}
M[#M+1] = {uid=35018,name="A cave",area="deneria",terrain="cave",info="",notes="",x=46,y=34,z=-1,building=""}
M[#M+1] = {uid=35019,name="A Crystalline Room",area="deneria",terrain="cave",info="",notes="",x=47,y=34,z=-1,building=""}
M[#M+1] = {uid=35020,name="Within the Tower of Nuril",area="deneria",terrain="inside",info="",notes="",x=46,y=31,z=0,building=""}
M[#M+1] = {uid=35021,name="Within the Tower",area="deneria",terrain="inside",info="",notes="",x=46,y=31,z=1,building=""}
M[#M+1] = {uid=35022,name="Abjurer's Room",area="deneria",terrain="inside",info="",notes="",x=46,y=32,z=1,building=""}
M[#M+1] = {uid=35023,name="Evoker's Room",area="deneria",terrain="inside",info="",notes="",x=47,y=31,z=1,building=""}
M[#M+1] = {uid=35024,name="Conjurer's Room",area="deneria",terrain="inside",info="",notes="",x=46,y=30,z=1,building=""}
M[#M+1] = {uid=35025,name="High Mage's Room",area="deneria",terrain="inside",info="",notes="",x=45,y=31,z=1,building=""}
M[#M+1] = {uid=35026,name="At the Back of the Church",area="deneria",terrain="temple",info="",notes="",x=44,y=29,z=0,building=""}
M[#M+1] = {uid=35027,name="Within the Church",area="deneria",terrain="temple",info="",notes="",x=44,y=28,z=0,building=""}
M[#M+1] = {uid=35028,name="Confessional",area="deneria",terrain="temple",info="",notes="",x=45,y=28,z=0,building=""}
M[#M+1] = {uid=35029,name="Within the Pews",area="deneria",terrain="temple",info="",notes="",x=43,y=28,z=0,building=""}
M[#M+1] = {uid=35030,name="At the Altar",area="deneria",terrain="temple",info="",notes="",x=44,y=27,z=0,building=""}
M[#M+1] = {uid=35031,name="Under the Lake",area="deneria",terrain="waternoswim",info="",notes="",x=43,y=31,z=-1,building=""}
M[#M+1] = {uid=35032,name="Under the Lake",area="deneria",terrain="underwater",info="",notes="",x=44,y=31,z=-1,building=""}
M[#M+1] = {uid=35033,name="Under the Lake",area="deneria",terrain="underwater",info="",notes="",x=43,y=32,z=-1,building=""}
M[#M+1] = {uid=35034,name="Under the Lake",area="deneria",terrain="underwater",info="",notes="",x=44,y=32,z=-1,building=""}
M[#M+1] = {uid=35035,name="Within Kraken's Cave",area="deneria",terrain="underwater",info="",notes="",x=44,y=32,z=-2,building=""}
M[#M+1] = {uid=35041,name="In the Gates",area="deneria",terrain="field",info="",notes="",x=44,y=30,z=0,building=""}
M[#M+1] = {uid=35042,name="Lobby",area="deneria",terrain="palace_room",info="",notes="",x=44,y=29,z=0,building=""}
M[#M+1] = {uid=35043,name="Throne Room",area="deneria",terrain="palace_room",info="safe",notes="",x=44,y=28,z=0,building=""}
M[#M+1] = {uid=35200,name="Outside the Aylorian Academy",area="academy",terrain="city",info="safe",notes="",x=30,y=20,z=0,building=""}
M[#M+1] = {uid=35201,name="Before the Academy Courtyard",area="academy",terrain="inside",info="safe",notes="",x=30,y=19,z=0,building=""}
M[#M+1] = {uid=35202,name="Inside the Academy Foyer",area="academy",terrain="inside",info="safe",notes="",x=30,y=14,z=0,building=""}
M[#M+1] = {uid=35203,name="Basic Training",area="academy",terrain="inside",info="safe,trainer",notes="",x=29,y=14,z=0,building=""}
M[#M+1] = {uid=35204,name="Skills training",area="academy",terrain="bloodyhall",info="safe,trainer",notes="",x=31,y=14,z=0,building=""}
M[#M+1] = {uid=35205,name="Practice Dummy Storage",area="academy",terrain="inside",info="",notes="",x=31,y=12,z=-2,building=""}
M[#M+1] = {uid=35206,name="Hallway in the Academy",area="academy",terrain="inside",info="",notes="",x=30,y=13,z=0,building=""}
M[#M+1] = {uid=35207,name="Hallway in the Academy",area="academy",terrain="inside",info="",notes="",x=30,y=12,z=0,building=""}
M[#M+1] = {uid=35208,name="Combat Training Room",area="academy",terrain="inside",info="trainer",notes="",x=29,y=12,z=0,building=""}
M[#M+1] = {uid=35209,name="The Academy Clinic",area="academy",terrain="inside",info="safe,healer",notes="",x=31,y=12,z=0,building=""}
M[#M+1] = {uid=35210,name="Academy Clinic Recovery Room",area="academy",terrain="temple",info="safe",notes="",x=31,y=11,z=0,building=""}
M[#M+1] = {uid=35211,name="The Armory",area="academy",terrain="inside",info="trainer",notes="",x=29,y=10,z=0,building=""}
M[#M+1] = {uid=35212,name="The Academy Treasury",area="academy",terrain="inside",info="bank,shop,trainer",notes="",x=31,y=10,z=0,building=""}
M[#M+1] = {uid=35213,name="Academy Hallway",area="academy",terrain="inside",info="",notes="",x=30,y=9,z=0,building=""}
M[#M+1] = {uid=35214,name="End of the hallway",area="academy",terrain="inside",info="",notes="",x=30,y=8,z=0,building=""}
M[#M+1] = {uid=35215,name="Communications Room",area="academy",terrain="office",info="trainer",notes="",x=29,y=8,z=0,building=""}
M[#M+1] = {uid=35216,name="Geography Training",area="academy",terrain="forest",info="trainer",notes="",x=31,y=8,z=0,building=""}
M[#M+1] = {uid=35217,name="Academy Stairway",area="academy",terrain="inside",info="",notes="",x=30,y=8,z=1,building=""}
M[#M+1] = {uid=35218,name="Top of Academy Staircase",area="academy",terrain="inside",info="",notes="",x=30,y=8,z=2,building=""}
M[#M+1] = {uid=35219,name="Social Studies Classroom",area="academy",terrain="fountain",info="trainer",notes="",x=29,y=8,z=2,building=""}
M[#M+1] = {uid=35220,name="Career Training",area="academy",terrain="inside",info="trainer,questor",notes="",x=31,y=8,z=2,building=""}
M[#M+1] = {uid=35221,name="Second Floor Hallway",area="academy",terrain="hallway",info="",notes="",x=30,y=9,z=2,building=""}
M[#M+1] = {uid=35222,name="Second Floor Hallway",area="academy",terrain="hallway",info="",notes="",x=30,y=10,z=2,building=""}
M[#M+1] = {uid=35223,name="Personal Development",area="academy",terrain="hellinside",info="trainer,questor",notes="",x=29,y=10,z=2,building=""}
M[#M+1] = {uid=35224,name="An Empty Classroom",area="academy",terrain="office",info="",notes="",x=31,y=10,z=2,building=""}
M[#M+1] = {uid=35225,name="A long hallway",area="academy",terrain="inside",info="",notes="",x=30,y=11,z=2,building=""}
M[#M+1] = {uid=35226,name="A long hallway",area="academy",terrain="inside",info="",notes="",x=30,y=12,z=2,building=""}
M[#M+1] = {uid=35227,name="A long hallway",area="academy",terrain="inside",info="",notes="",x=30,y=13,z=2,building=""}
M[#M+1] = {uid=35228,name="Office of the Arch Mage",area="academy",terrain="inside",info="",notes="",x=30,y=14,z=2,building=""}
M[#M+1] = {uid=35229,name="Academy Courtyard",area="academy",terrain="city",info="",notes="",x=30,y=18,z=0,building=""}
M[#M+1] = {uid=35230,name="Academy Main Entrance",area="academy",terrain="inside",info="",notes="",x=30,y=15,z=0,building=""}
M[#M+1] = {uid=35231,name="Academy Courtyard",area="academy",terrain="city",info="",notes="",x=31,y=18,z=0,building=""}
M[#M+1] = {uid=35232,name="Academy Courtyard",area="academy",terrain="city",info="",notes="",x=29,y=18,z=0,building=""}
M[#M+1] = {uid=35233,name="Academy Courtyard Fountain",area="academy",terrain="afountain",info="",notes="",x=30,y=17,z=0,building=""}
M[#M+1] = {uid=35234,name="Academy Courtyard",area="academy",terrain="city",info="",notes="",x=29,y=17,z=0,building=""}
M[#M+1] = {uid=35235,name="Academy Courtyard",area="academy",terrain="city",info="",notes="",x=31,y=17,z=0,building=""}
M[#M+1] = {uid=35236,name="Basement Staircase",area="academy",terrain="inside",info="",notes="",x=31,y=14,z=-1,building=""}
M[#M+1] = {uid=35237,name="A Darker Section of the Basement",area="academy",terrain="Mudschool",info="",notes="",x=23,y=5,z=-2,building=""}
M[#M+1] = {uid=35238,name="A Basement Hallway",area="academy",terrain="city_underground",info="",notes="",x=29,y=8,z=-2,building=""}
M[#M+1] = {uid=35239,name="Academy Basement Hallway",area="academy",terrain="city_underground",info="",notes="",x=29,y=9,z=-2,building=""}
M[#M+1] = {uid=35240,name="A Darker Section of the Basement",area="academy",terrain="Mudschool",info="",notes="",x=22,y=5,z=-2,building=""}
M[#M+1] = {uid=35241,name="A Darker Section of the Basement",area="academy",terrain="Mudschool",info="",notes="",x=24,y=5,z=-2,building=""}
M[#M+1] = {uid=35242,name="A Darker Section of the Basement",area="academy",terrain="underground",info="",notes="",x=24,y=4,z=-2,building=""}
M[#M+1] = {uid=35243,name="A Darker Section of the Basement",area="academy",terrain="underground",info="",notes="",x=22,y=4,z=-2,building=""}
M[#M+1] = {uid=35244,name="A Darker Section of the Basement",area="academy",terrain="underground",info="",notes="",x=22,y=6,z=-2,building=""}
M[#M+1] = {uid=35245,name="A Darker Section of the Basement",area="academy",terrain="underground",info="",notes="",x=24,y=6,z=-2,building=""}
M[#M+1] = {uid=35246,name="The Academy Basement",area="academy",terrain="underground",info="",notes="",x=24,y=7,z=-2,building=""}
M[#M+1] = {uid=35247,name="A Darker Section of the Basement",area="academy",terrain="underground",info="",notes="",x=23,y=7,z=-2,building=""}
M[#M+1] = {uid=35248,name="The Academy Basement",area="academy",terrain="underground",info="",notes="",x=22,y=7,z=-2,building=""}
M[#M+1] = {uid=35249,name="A Darker Section of the Basement",area="academy",terrain="underground",info="",notes="",x=24,y=3,z=-2,building=""}
M[#M+1] = {uid=35250,name="A Darker Section of the Basement",area="academy",terrain="underground",info="",notes="",x=23,y=3,z=-2,building=""}
M[#M+1] = {uid=35251,name="A Darker Section of the Basement",area="academy",terrain="underground",info="",notes="",x=22,y=3,z=-2,building=""}
M[#M+1] = {uid=35252,name="Academy Basement Hallway",area="academy",terrain="underground",info="",notes="",x=29,y=10,z=-2,building=""}
M[#M+1] = {uid=35253,name="A Basement Hallway",area="academy",terrain="underground",info="",notes="",x=25,y=5,z=-2,building=""}
M[#M+1] = {uid=35254,name="Basement Practice Area",area="academy",terrain="underground",info="",notes="",x=29,y=11,z=-2,building=""}
M[#M+1] = {uid=35255,name="Basement Practice Area",area="academy",terrain="underground",info="",notes="",x=30,y=11,z=-2,building=""}
M[#M+1] = {uid=35256,name="A Dark Alcove in the Basement",area="academy",terrain="underground",info="",notes="",x=21,y=5,z=-2,building=""}
M[#M+1] = {uid=35257,name="Basement Practice Area",area="academy",terrain="underground",info="",notes="",x=28,y=11,z=-2,building=""}
M[#M+1] = {uid=35258,name="Basement Practice Area",area="academy",terrain="underground",info="",notes="",x=28,y=12,z=-2,building=""}
M[#M+1] = {uid=35259,name="A Warm Hallway in the Basement",area="academy",terrain="inside",info="",notes="",x=26,y=5,z=-2,building=""}
M[#M+1] = {uid=35260,name="Basement Practice Area",area="academy",terrain="underground",info="",notes="",x=28,y=13,z=-2,building=""}
M[#M+1] = {uid=35261,name="Basement Practice Area",area="academy",terrain="underground",info="",notes="",x=28,y=14,z=-2,building=""}
M[#M+1] = {uid=35262,name="A Warm Basement Alcove",area="academy",terrain="city_underground",info="",notes="",x=31,y=5,z=-2,building=""}
M[#M+1] = {uid=35263,name="Basement First Aid Station",area="academy",terrain="underground",info="safe",notes="",x=28,y=15,z=-2,building=""}
M[#M+1] = {uid=35264,name="The Academy Furnace",area="academy",terrain="hell1",info="",notes="",x=30,y=4,z=-2,building=""}
M[#M+1] = {uid=35265,name="The Academy Furnace",area="academy",terrain="city_underground",info="",notes="",x=30,y=5,z=-2,building=""}
M[#M+1] = {uid=35266,name="The Academy Furnace",area="academy",terrain="city_underground",info="",notes="",x=30,y=6,z=-2,building=""}
M[#M+1] = {uid=35267,name="The Basement Furnace",area="academy",terrain="hell3",info="",notes="",x=30,y=3,z=-2,building=""}
M[#M+1] = {uid=35268,name="The Basement Furnace Room",area="academy",terrain="city_underground",info="",notes="",x=30,y=7,z=-2,building=""}
M[#M+1] = {uid=35269,name="The Basement Furnace",area="academy",terrain="city_underground",info="",notes="",x=29,y=7,z=-2,building=""}
M[#M+1] = {uid=35270,name="Basement Practice Area",area="academy",terrain="underground",info="",notes="",x=29,y=15,z=-2,building=""}
M[#M+1] = {uid=35271,name="Behind the Basement Furnace",area="academy",terrain="city_underground",info="",notes="",x=29,y=5,z=-2,building=""}
M[#M+1] = {uid=35272,name="Basement Practice Area",area="academy",terrain="underground",info="",notes="",x=30,y=15,z=-2,building=""}
M[#M+1] = {uid=35273,name="The Basement Furnace",area="academy",terrain="hell4",info="",notes="",x=29,y=3,z=-2,building=""}
M[#M+1] = {uid=35274,name="The Basement Furnace",area="academy",terrain="hell3",info="",notes="",x=28,y=3,z=-2,building=""}
M[#M+1] = {uid=35275,name="The Basement Furnace",area="academy",terrain="hell2",info="",notes="",x=28,y=4,z=-2,building=""}
M[#M+1] = {uid=35276,name="The Basement Furnace",area="academy",terrain="city_underground",info="",notes="",x=28,y=5,z=-2,building=""}
M[#M+1] = {uid=35277,name="The Basement Furnace",area="academy",terrain="city_underground",info="",notes="",x=28,y=6,z=-2,building=""}
M[#M+1] = {uid=35278,name="The Basement Furnace",area="academy",terrain="city_underground",info="",notes="",x=28,y=7,z=-2,building=""}
M[#M+1] = {uid=35279,name="Basement Practice Area",area="academy",terrain="underground",info="",notes="",x=30,y=14,z=-2,building=""}
M[#M+1] = {uid=35280,name="A Warm Hallway in the Basement",area="academy",terrain="city_underground",info="",notes="",x=27,y=5,z=-2,building=""}
M[#M+1] = {uid=35281,name="Basement Practice Area",area="academy",terrain="underground",info="",notes="",x=30,y=13,z=-2,building=""}
M[#M+1] = {uid=35282,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=32,y=17,z=0,building=""}
M[#M+1] = {uid=35283,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=33,y=17,z=0,building=""}
M[#M+1] = {uid=35284,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=34,y=17,z=0,building=""}
M[#M+1] = {uid=35285,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=34,y=16,z=0,building=""}
M[#M+1] = {uid=35286,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=34,y=15,z=0,building=""}
M[#M+1] = {uid=35287,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=34,y=14,z=0,building=""}
M[#M+1] = {uid=35288,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=34,y=13,z=0,building=""}
M[#M+1] = {uid=35289,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=34,y=12,z=0,building=""}
M[#M+1] = {uid=35290,name="A garden path",area="academy",terrain="field",info="",notes="",x=34,y=11,z=0,building=""}
M[#M+1] = {uid=35291,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=34,y=10,z=0,building=""}
M[#M+1] = {uid=35292,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=33,y=10,z=0,building=""}
M[#M+1] = {uid=35293,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=32,y=10,z=0,building=""}
M[#M+1] = {uid=35294,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=27,y=10,z=0,building=""}
M[#M+1] = {uid=35295,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=26,y=10,z=0,building=""}
M[#M+1] = {uid=35296,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=25,y=10,z=0,building=""}
M[#M+1] = {uid=35297,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=25,y=11,z=0,building=""}
M[#M+1] = {uid=35298,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=25,y=12,z=0,building=""}
M[#M+1] = {uid=35299,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=25,y=13,z=0,building=""}
M[#M+1] = {uid=35300,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=25,y=14,z=0,building=""}
M[#M+1] = {uid=35301,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=25,y=15,z=0,building=""}
M[#M+1] = {uid=35302,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=25,y=16,z=0,building=""}
M[#M+1] = {uid=35303,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=25,y=17,z=0,building=""}
M[#M+1] = {uid=35304,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=26,y=17,z=0,building=""}
M[#M+1] = {uid=35305,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=27,y=17,z=0,building=""}
M[#M+1] = {uid=35306,name="Pathway around the academy",area="academy",terrain="field",info="",notes="",x=28,y=17,z=0,building=""}
M[#M+1] = {uid=35307,name="Academy Courtyard",area="academy",terrain="city",info="",notes="",x=29,y=16,z=0,building=""}
M[#M+1] = {uid=35308,name="Before the Main Entrance",area="academy",terrain="city",info="",notes="",x=30,y=16,z=0,building=""}
M[#M+1] = {uid=35309,name="Academy Courtyard",area="academy",terrain="city",info="",notes="",x=31,y=16,z=0,building=""}
M[#M+1] = {uid=35310,name="Academy Gardens",area="academy",terrain="field",info="",notes="",x=24,y=15,z=0,building=""}
M[#M+1] = {uid=35311,name="Academy Gardens",area="academy",terrain="field",info="",notes="",x=23,y=15,z=0,building=""}
M[#M+1] = {uid=35312,name="Academy Flower Beds",area="academy",terrain="flowers1",info="",notes="",x=23,y=14,z=0,building=""}
M[#M+1] = {uid=35313,name="Academy Flower Beds",area="academy",terrain="flowers1",info="",notes="",x=24,y=14,z=0,building=""}
M[#M+1] = {uid=35314,name="Academy Flower Beds",area="academy",terrain="flowers2",info="",notes="",x=23,y=13,z=0,building=""}
M[#M+1] = {uid=35315,name="Academy Flower Beds",area="academy",terrain="flowers1",info="",notes="",x=24,y=13,z=0,building=""}
M[#M+1] = {uid=35316,name="Academy Gardens",area="academy",terrain="field",info="",notes="",x=23,y=12,z=0,building=""}
M[#M+1] = {uid=35317,name="Academy Gardens",area="academy",terrain="field",info="",notes="",x=24,y=12,z=0,building=""}
M[#M+1] = {uid=35318,name="Academy Gardens",area="academy",terrain="field",info="",notes="",x=22,y=12,z=0,building=""}
M[#M+1] = {uid=35319,name="Academy Flower Beds",area="academy",terrain="flowers1",info="",notes="",x=22,y=13,z=0,building=""}
M[#M+1] = {uid=35320,name="Academy Flower Beds",area="academy",terrain="flowers2",info="",notes="",x=22,y=14,z=0,building=""}
M[#M+1] = {uid=35321,name="Academy Gardens",area="academy",terrain="field",info="",notes="",x=22,y=15,z=0,building=""}
M[#M+1] = {uid=35322,name="Academy Gardens",area="academy",terrain="field",info="",notes="",x=21,y=15,z=0,building=""}
M[#M+1] = {uid=35323,name="Academy Gardens",area="academy",terrain="field",info="",notes="",x=21,y=14,z=0,building=""}
M[#M+1] = {uid=35324,name="Academy Gardens",area="academy",terrain="field",info="",notes="",x=21,y=13,z=0,building=""}
M[#M+1] = {uid=35325,name="Academy Gardens",area="academy",terrain="field",info="",notes="",x=21,y=12,z=0,building=""}
M[#M+1] = {uid=35326,name="A small gazebo",area="academy",terrain="inside",info="",notes="",x=27,y=9,z=0,building=""}
M[#M+1] = {uid=35327,name="A small gazebo",area="academy",terrain="inside",info="",notes="",x=32,y=9,z=0,building=""}
M[#M+1] = {uid=35328,name="A small gazebo",area="academy",terrain="inside",info="",notes="",x=27,y=8,z=0,building=""}
M[#M+1] = {uid=35329,name="A small pond",area="academy",terrain="well",info="",notes="",x=32,y=8,z=0,building=""}
M[#M+1] = {uid=35330,name="Academy Practice Fields",area="academy",terrain="forest",info="",notes="",x=35,y=12,z=0,building=""}
M[#M+1] = {uid=35331,name="Academy Practice Fields",area="academy",terrain="forest",info="",notes="",x=36,y=12,z=0,building=""}
M[#M+1] = {uid=35332,name="Academy Practice Fields",area="academy",terrain="forest",info="",notes="",x=37,y=12,z=0,building=""}
M[#M+1] = {uid=35333,name="Academy Practice Fields",area="academy",terrain="forest",info="",notes="",x=38,y=12,z=0,building=""}
M[#M+1] = {uid=35334,name="Academy Practice Fields",area="academy",terrain="forest",info="",notes="",x=38,y=13,z=0,building=""}
M[#M+1] = {uid=35335,name="Small Pond",area="academy",terrain="waterswim",info="",notes="",x=37,y=13,z=0,building=""}
M[#M+1] = {uid=35336,name="Small Pond",area="academy",terrain="waterswim",info="",notes="",x=36,y=13,z=0,building=""}
M[#M+1] = {uid=35337,name="Academy Practice Fields",area="academy",terrain="forest",info="",notes="",x=35,y=13,z=0,building=""}
M[#M+1] = {uid=35338,name="Academy Practice Fields",area="academy",terrain="forest",info="",notes="",x=35,y=14,z=0,building=""}
M[#M+1] = {uid=35339,name="A Small Pond",area="academy",terrain="waterswim",info="",notes="",x=36,y=14,z=0,building=""}
M[#M+1] = {uid=35340,name="A Small Pond",area="academy",terrain="waterswim",info="",notes="",x=37,y=14,z=0,building=""}
M[#M+1] = {uid=35341,name="Academy Practice Fields",area="academy",terrain="forest",info="",notes="",x=38,y=14,z=0,building=""}
M[#M+1] = {uid=35342,name="Damp undergrowth",area="academy",terrain="forest",info="",notes="",x=38,y=15,z=0,building=""}
M[#M+1] = {uid=35343,name="Academy Practice Fields",area="academy",terrain="forest",info="",notes="",x=37,y=15,z=0,building=""}
M[#M+1] = {uid=35344,name="Academy Practice Fields",area="academy",terrain="forest",info="",notes="",x=36,y=15,z=0,building=""}
M[#M+1] = {uid=35345,name="Shaded area",area="academy",terrain="forest",info="",notes="",x=35,y=15,z=0,building=""}
M[#M+1] = {uid=35346,name="A restful garden",area="academy",terrain="forest",info="",notes="",x=35,y=16,z=0,building=""}
M[#M+1] = {uid=35347,name="Shaded area",area="academy",terrain="forest",info="",notes="",x=35,y=11,z=0,building=""}
M[#M+1] = {uid=35348,name="Academy Gardens",area="academy",terrain="field",info="",notes="",x=24,y=11,z=0,building=""}
M[#M+1] = {uid=35349,name="Academy Gardens",area="academy",terrain="field",info="",notes="",x=24,y=16,z=0,building=""}
M[#M+1] = {uid=35350,name="Basement Practice Area",area="academy",terrain="underground",info="",notes="",x=30,y=12,z=-2,building=""}
M[#M+1] = {uid=35351,name="Basement Practice Area",area="academy",terrain="inside",info="",notes="",x=29,y=13,z=-2,building=""}
M[#M+1] = {uid=35352,name="Basement Passage",area="academy",terrain="underground",info="",notes="",x=27,y=13,z=-2,building=""}
M[#M+1] = {uid=35353,name="Entrance to the Archives",area="academy",terrain="underground",info="",notes="",x=26,y=13,z=-2,building=""}
M[#M+1] = {uid=35354,name="academy basement",area="academy",terrain="underground",info="",notes="",x=0,y=0,z=0,building=""}
M[#M+1] = {uid=35355,name="The Basement Storage Area",area="academy",terrain="underground",info="",notes="",x=1,y=0,z=0,building=""}
M[#M+1] = {uid=35356,name="Within the Academy Archives",area="academy",terrain="bookshelves_ns",info="",notes="",x=22,y=12,z=-2,building=""}
M[#M+1] = {uid=35357,name="Within the Academy Archives",area="academy",terrain="bookshelves_ns",info="",notes="",x=22,y=11,z=-2,building=""}
M[#M+1] = {uid=35358,name="Within the Academy Archives",area="academy",terrain="bookshelves_ns",info="",notes="",x=23,y=11,z=-2,building=""}
M[#M+1] = {uid=35359,name="Within the Academy Archives",area="academy",terrain="bookshelves_ns",info="",notes="",x=24,y=11,z=-2,building=""}
M[#M+1] = {uid=35360,name="Within the Academy Archives",area="academy",terrain="bookshelves_ns",info="",notes="",x=24,y=12,z=-2,building=""}
M[#M+1] = {uid=35361,name="Within the Academy Archives",area="academy",terrain="bookshelves_ns",info="",notes="",x=24,y=13,z=-2,building=""}
M[#M+1] = {uid=35362,name="Within the Academy Archives",area="academy",terrain="bookshelves_ns",info="",notes="",x=24,y=14,z=-2,building=""}
M[#M+1] = {uid=35363,name="Within the Academy Archives",area="academy",terrain="bookshelves_ns",info="",notes="",x=24,y=15,z=-2,building=""}
M[#M+1] = {uid=35364,name="Within the Academy Archives",area="academy",terrain="bookshelves_ns",info="",notes="",x=23,y=15,z=-2,building=""}
M[#M+1] = {uid=35365,name="Within the Academy Archives",area="academy",terrain="bookshelves_ns",info="",notes="",x=22,y=15,z=-2,building=""}
M[#M+1] = {uid=35366,name="Center of the Academy Archives",area="academy",terrain="office",info="",notes="",x=23,y=13,z=-2,building=""}
M[#M+1] = {uid=35367,name="Within the Academy Archives",area="academy",terrain="bookshelves_ns",info="",notes="",x=22,y=13,z=-2,building=""}
M[#M+1] = {uid=35368,name="Within the Academy Archives",area="academy",terrain="bookshelves_ns",info="",notes="",x=22,y=14,z=-2,building=""}
M[#M+1] = {uid=35369,name="Academy Basement Hallway",area="academy",terrain="underground",info="",notes="",x=25,y=13,z=-2,building=""}
M[#M+1] = {uid=35370,name="Academy Basement Hallway",area="academy",terrain="underground",info="",notes="",x=23,y=10,z=-2,building=""}
M[#M+1] = {uid=35371,name="Academy Basement Hallway",area="academy",terrain="underground",info="",notes="",x=23,y=9,z=-2,building=""}
M[#M+1] = {uid=35372,name="Academy Basement Hallway",area="academy",terrain="underground",info="",notes="",x=23,y=8,z=-2,building=""}
M[#M+1] = {uid=35373,name="Basement Practice Area",area="academy",terrain="inside",info="",notes="",x=29,y=12,z=-2,building=""}
M[#M+1] = {uid=35374,name="Basement Practice Area",area="academy",terrain="inside",info="",notes="",x=29,y=14,z=-2,building=""}
M[#M+1] = {uid=35375,name="An Alcove in the Basement",area="academy",terrain="inside",info="",notes="",x=21,y=13,z=-2,building=""}
M[#M+1] = {uid=35376,name="Center of the Furnace",area="academy",terrain="hell3",info="",notes="",x=29,y=4,z=-2,building=""}
M[#M+1] = {uid=35377,name="The Basement Furnace",area="academy",terrain="city_underground",info="",notes="",x=29,y=6,z=-2,building=""}
M[#M+1] = {uid=35378,name="Within the Academy Archives",area="academy",terrain="bookshelves_ns",info="",notes="",x=23,y=12,z=-2,building=""}
M[#M+1] = {uid=35379,name="Within the Academy Archives",area="academy",terrain="bookshelves_ns",info="",notes="",x=23,y=14,z=-2,building=""}
M[#M+1] = {uid=35380,name="Below the Basement Staircase",area="academy",terrain="stairs",info="",notes="",x=31,y=14,z=-2,building=""}
M[#M+1] = {uid=35381,name="Office of the Arch Mage",area="academy",terrain="inside",info="trainer",notes="",x=31,y=14,z=2,building=""}
M[#M+1] = {uid=35382,name="Hallway in the Academy",area="academy",terrain="inside",info="",notes="",x=30,y=11,z=0,building=""}
M[#M+1] = {uid=35383,name="Hallway in the Academy",area="academy",terrain="inside",info="",notes="",x=30,y=10,z=0,building=""}
M[#M+1] = {uid=35399,name="Dank Corridor",area="yurgach",terrain="dungeon",info="",notes="",x=2,y=36,z=1,building=""}
M[#M+1] = {uid=35400,name="Dank Stone Corridor",area="yurgach",terrain="dungeon",info="",notes="",x=3,y=36,z=1,building=""}
M[#M+1] = {uid=35401,name="Head of a Stairway",area="yurgach",terrain="dungeon",info="",notes="",x=4,y=36,z=1,building=""}
M[#M+1] = {uid=35402,name="Dank Corridor",area="yurgach",terrain="dungeon",info="",notes="",x=1,y=36,z=1,building=""}
M[#M+1] = {uid=35593,name="A Narrow Tunnel",area="terramire",terrain="underground",info="",notes="",x=45,y=3,z=0,building=""}
M[#M+1] = {uid=35594,name="An Intersection",area="terramire",terrain="underground",info="",notes="",x=46,y=3,z=0,building=""}
M[#M+1] = {uid=35595,name="A Dead End",area="terramire",terrain="underground",info="",notes="",x=46,y=4,z=0,building=""}
M[#M+1] = {uid=35596,name="The Mansion Of Burrows",area="terramire",terrain="underground",info="",notes="",x=47,y=3,z=0,building=""}
M[#M+1] = {uid=35597,name="A Civilian Burrow",area="terramire",terrain="underground",info="",notes="",x=47,y=4,z=0,building=""}
M[#M+1] = {uid=35598,name="A Messy Burrow",area="terramire",terrain="underground",info="",notes="",x=45,y=4,z=0,building=""}
M[#M+1] = {uid=35599,name="A Busy Burrow",area="terramire",terrain="underground",info="",notes="",x=46,y=5,z=0,building=""}
M[#M+1] = {uid=35600,name="Guard Station",area="terramire",terrain="underground",info="",notes="",x=45,y=4,z=0,building=""}
M[#M+1] = {uid=35602,name="An Underground Playground",area="terramire",terrain="underground",info="",notes="",x=44,y=5,z=0,building=""}
M[#M+1] = {uid=35603,name="A Playing Field",area="terramire",terrain="underground",info="",notes="",x=43,y=5,z=0,building=""}
M[#M+1] = {uid=35604,name="Veggies 'R Us",area="terramire",terrain="underground",info="shop",notes="",x=44,y=-2,z=0,building=""}
M[#M+1] = {uid=35605,name="A Back Alley",area="terramire",terrain="underground",info="",notes="",x=45,y=-1,z=0,building=""}
M[#M+1] = {uid=35606,name="A Garden",area="terramire",terrain="underground",info="",notes="",x=43,y=-2,z=0,building=""}
M[#M+1] = {uid=35607,name="A Garden",area="terramire",terrain="underground",info="",notes="",x=42,y=-2,z=0,building=""}
M[#M+1] = {uid=35608,name="A Hallway",area="terramire",terrain="underground",info="",notes="",x=40,y=1,z=0,building=""}
M[#M+1] = {uid=35609,name="The End Of The Hallway",area="terramire",terrain="underground",info="",notes="",x=40,y=2,z=0,building=""}
M[#M+1] = {uid=35610,name="Officer's Quarters",area="terramire",terrain="underground",info="",notes="",x=39,y=2,z=0,building=""}
M[#M+1] = {uid=35611,name="Officer's Quarters",area="terramire",terrain="underground",info="",notes="",x=41,y=2,z=0,building=""}
M[#M+1] = {uid=35612,name="A Shared Officer Burrow",area="terramire",terrain="underground",info="",notes="",x=39,y=1,z=0,building=""}
M[#M+1] = {uid=35613,name="Soldier's Sleeping Quarters",area="terramire",terrain="underground",info="",notes="",x=42,y=1,z=0,building=""}
M[#M+1] = {uid=35614,name="Soldier's Sleeping Quarters",area="terramire",terrain="underground",info="",notes="",x=43,y=0,z=0,building=""}
M[#M+1] = {uid=35615,name="The Family Community Center",area="terramire",terrain="inside",info="",notes="",x=46,y=2,z=0,building=""}
M[#M+1] = {uid=35616,name="An Underground Market",area="terramire",terrain="underground",info="",notes="",x=44,y=-1,z=0,building=""}
M[#M+1] = {uid=35679,name="Lost and Found",area="aylor",terrain="inside",info="",notes="",x=30,y=19,z=-1,building=""}
M[#M+1] = {uid=35700,name="Nearing a crowded beach",area="peninsula",terrain="forest",info="",notes="",x=50,y=13,z=0,building=""}
M[#M+1] = {uid=35701,name="A white sandy beach",area="peninsula",terrain="beach",info="",notes="",x=50,y=12,z=0,building=""}
M[#M+1] = {uid=35702,name="A white sandy beach",area="peninsula",terrain="beach",info="",notes="",x=50,y=11,z=0,building=""}
M[#M+1] = {uid=35703,name="Nearing a large boardwalk",area="peninsula",terrain="beach",info="",notes="",x=50,y=10,z=0,building=""}
M[#M+1] = {uid=35704,name="Beside a huge sandcastle",area="peninsula",terrain="beach",info="",notes="",x=50,y=9,z=0,building=""}
M[#M+1] = {uid=35705,name="A secluded path on the beach",area="peninsula",terrain="beach",info="",notes="",x=50,y=8,z=0,building=""}
M[#M+1] = {uid=35706,name="Northern end of the beach",area="peninsula",terrain="beach",info="",notes="",x=50,y=7,z=0,building=""}
M[#M+1] = {uid=35707,name="On the boardwalk",area="peninsula",terrain="bridge",info="",notes="",x=51,y=12,z=0,building=""}
M[#M+1] = {uid=35708,name="On the boardwalk",area="peninsula",terrain="bridge",info="",notes="",x=51,y=11,z=0,building=""}
M[#M+1] = {uid=35709,name="On the boardwalk",area="peninsula",terrain="bridge",info="",notes="",x=51,y=10,z=0,building=""}
M[#M+1] = {uid=35710,name="A vendor's shack",area="peninsula",terrain="cabin",info="",notes="",x=52,y=10,z=0,building=""}
M[#M+1] = {uid=35711,name="A vendor's shack",area="peninsula",terrain="cabin",info="",notes="",x=52,y=12,z=0,building=""}
M[#M+1] = {uid=35713,name="A secluded path",area="peninsula",terrain="jungle",info="",notes="",x=51,y=8,z=0,building=""}
M[#M+1] = {uid=35714,name="Entering a dense jungle",area="peninsula",terrain="jungle",info="",notes="",x=52,y=8,z=0,building=""}
M[#M+1] = {uid=35715,name="Inside the dense jungle",area="peninsula",terrain="jungle",info="",notes="",x=53,y=8,z=0,building=""}
M[#M+1] = {uid=35716,name="An intersection of paths",area="peninsula",terrain="jungle",info="",notes="",x=53,y=9,z=0,building=""}
M[#M+1] = {uid=35717,name="Approaching a small village",area="peninsula",terrain="forest",info="",notes="",x=54,y=9,z=0,building=""}
M[#M+1] = {uid=35718,name="Deeper in the jungle",area="peninsula",terrain="jungle",info="",notes="",x=53,y=10,z=0,building=""}
M[#M+1] = {uid=35719,name="A small path",area="peninsula",terrain="forest",info="",notes="",x=53,y=11,z=0,building=""}
M[#M+1] = {uid=35720,name="A Tairayden village",area="peninsula",terrain="jungle",info="",notes="",x=55,y=9,z=0,building=""}
M[#M+1] = {uid=35721,name="A Tairayden village",area="peninsula",terrain="jungle",info="",notes="",x=56,y=9,z=0,building=""}
M[#M+1] = {uid=35722,name="A Tairayden village",area="peninsula",terrain="jungle",info="",notes="",x=55,y=8,z=0,building=""}
M[#M+1] = {uid=35723,name="A Tairayden village",area="peninsula",terrain="jungle",info="",notes="",x=56,y=8,z=0,building=""}
M[#M+1] = {uid=35724,name="A Tairayden village",area="peninsula",terrain="jungle",info="",notes="",x=54,y=11,z=0,building=""}
M[#M+1] = {uid=35725,name="A Tairayden village",area="peninsula",terrain="jungle",info="",notes="",x=55,y=11,z=0,building=""}
M[#M+1] = {uid=35726,name="A Tairayden village",area="peninsula",terrain="jungle",info="",notes="",x=54,y=12,z=0,building=""}
M[#M+1] = {uid=35727,name="A Tairayden village",area="peninsula",terrain="jungle",info="",notes="",x=55,y=12,z=0,building=""}
M[#M+1] = {uid=35728,name="The weapon shack",area="peninsula",terrain="cabin",info="",notes="",x=56,y=10,z=0,building=""}
M[#M+1] = {uid=35729,name="A hostage hut",area="peninsula",terrain="cabin",info="pk",notes="",x=57,y=8,z=0,building=""}
M[#M+1] = {uid=35730,name="A Tairayden home",area="peninsula",terrain="cabin",info="",notes="",x=55,y=7,z=0,building=""}
M[#M+1] = {uid=35731,name="A Tairayden home",area="peninsula",terrain="cabin",info="",notes="",x=55,y=10,z=0,building=""}
M[#M+1] = {uid=35732,name="A hostage hut",area="peninsula",terrain="cabin",info="pk",notes="",x=56,y=12,z=0,building=""}
M[#M+1] = {uid=35733,name="A large wooden shack",area="peninsula",terrain="cabin",info="",notes="",x=54,y=13,z=0,building=""}
M[#M+1] = {uid=35736,name="In the water",area="peninsula",terrain="waterswim",info="",notes="",x=49,y=12,z=0,building=""}
M[#M+1] = {uid=35737,name="In the water",area="peninsula",terrain="waterswim",info="",notes="",x=49,y=11,z=0,building=""}
M[#M+1] = {uid=35738,name="Riding a wave",area="peninsula",terrain="waterswim",info="",notes="",x=49,y=10,z=0,building=""}
M[#M+1] = {uid=35739,name="Riding a wave",area="peninsula",terrain="waterswim",info="",notes="",x=49,y=9,z=0,building=""}
M[#M+1] = {uid=35740,name="Near a current",area="peninsula",terrain="waterswim",info="",notes="",x=49,y=8,z=0,building=""}
M[#M+1] = {uid=35741,name="A strong current",area="peninsula",terrain="waterswim",info="",notes="",x=49,y=7,z=0,building=""}
M[#M+1] = {uid=35742,name="Entering the deepest jungle",area="peninsula",terrain="jungle",info="",notes="",x=50,y=13,z=0,building=""}
M[#M+1] = {uid=35743,name="Southern jungle",area="peninsula",terrain="jungle",info="",notes="",x=50,y=12,z=0,building=""}
M[#M+1] = {uid=35744,name="Middle jungle",area="peninsula",terrain="jungle",info="",notes="",x=50,y=11,z=0,building=""}
M[#M+1] = {uid=35745,name="Northern jungle",area="peninsula",terrain="jungle",info="",notes="",x=50,y=10,z=0,building=""}
M[#M+1] = {uid=35746,name="Northern jungle",area="peninsula",terrain="jungle",info="",notes="",x=51,y=10,z=0,building=""}
M[#M+1] = {uid=35747,name="Middle jungle",area="peninsula",terrain="jungle",info="",notes="",x=51,y=11,z=0,building=""}
M[#M+1] = {uid=35748,name="Southern jungle",area="peninsula",terrain="jungle",info="",notes="",x=51,y=12,z=0,building=""}
M[#M+1] = {uid=35749,name="Tip of the peninsula",area="peninsula",terrain="rocks",info="",notes="",x=51,y=9,z=0,building=""}
M[#M+1] = {uid=36451,name="Approaching the Camp of the Gathering Horde",area="gathering",terrain="crossroad_ews",info="",notes="",x=9,y=26,z=0,building=""}
M[#M+1] = {uid=36453,name="Beneath an Imposing Watchtower",area="gathering",terrain="icemount",info="pk",notes="",x=9,y=25,z=0,building=""}
M[#M+1] = {uid=36454,name="Behind the Gates",area="gathering",terrain="hallway",info="",notes="",x=8,y=26,z=0,building=""}
M[#M+1] = {uid=36465,name="Further Into the Encampment",area="gathering",terrain="hallway",info="",notes="",x=7,y=26,z=0,building=""}
M[#M+1] = {uid=36492,name="Walking Through the Horde Encampment",area="gathering",terrain="hallway",info="",notes="",x=7,y=25,z=0,building=""}
M[#M+1] = {uid=36493,name="Keeping Along the Road",area="gathering",terrain="hallway",info="",notes="",x=7,y=24,z=0,building=""}
M[#M+1] = {uid=36495,name="Walking Through the Horde Encampment",area="gathering",terrain="hallway",info="",notes="",x=6,y=24,z=0,building=""}
M[#M+1] = {uid=36506,name="Another Intersection from the Main Road",area="gathering",terrain="hallway",info="",notes="",x=5,y=24,z=0,building=""}
M[#M+1] = {uid=36507,name="On the green prairie",area="nulan",terrain="field",info="",notes="",x=27,y=9,z=0,building=""}
M[#M+1] = {uid=36508,name="Well cropped grassland",area="nulan",terrain="field",info="",notes="",x=26,y=9,z=0,building=""}
M[#M+1] = {uid=36509,name="In soft grass",area="nulan",terrain="field",info="",notes="",x=25,y=9,z=0,building=""}
M[#M+1] = {uid=36510,name="A shady spot in the plains",area="nulan",terrain="field",info="",notes="",x=24,y=9,z=0,building=""}
M[#M+1] = {uid=36513,name="Entering a Tunneled Campsite",area="gathering",terrain="cave",info="",notes="",x=4,y=24,z=-1,building=""}
M[#M+1] = {uid=36514,name="Walking Through the Horde Encampment",area="gathering",terrain="hallway",info="",notes="",x=4,y=23,z=0,building=""}
M[#M+1] = {uid=36516,name="Walking Through the Horde Encampment",area="gathering",terrain="hallway",info="",notes="",x=4,y=22,z=0,building=""}
M[#M+1] = {uid=36517,name="Walking Through the Horde Encampment",area="gathering",terrain="hallway",info="",notes="",x=4,y=21,z=0,building=""}
M[#M+1] = {uid=36518,name="At a Tent Unparalleled in Size",area="gathering",terrain="hallway",info="",notes="",x=4,y=20,z=0,building=""}
M[#M+1] = {uid=36519,name="Entrance to the Gnomish Siege Factory",area="gathering",terrain="smallroad_ew",info="",notes="",x=5,y=20,z=0,building=""}
M[#M+1] = {uid=36540,name="A Hole in the Road",area="gathering",terrain="hallway",info="",notes="",x=4,y=24,z=0,building=""}
M[#M+1] = {uid=36545,name="A Convergence",area="gathering",terrain="cave",info="",notes="",x=4,y=23,z=-1,building=""}
M[#M+1] = {uid=36546,name="The Torturer's Tent",area="gathering",terrain="hellinside",info="",notes="",x=4,y=19,z=0,building=""}
M[#M+1] = {uid=36547,name="Inside a Tent, Seductively Comfortable",area="gathering",terrain="flowers1",info="",notes="",x=3,y=21,z=0,building=""}
M[#M+1] = {uid=36700,name="Before a small diner",area="diner",terrain="field",info="",notes="",x=5,y=25,z=0,building=""}
M[#M+1] = {uid=36701,name="Inside the foyer",area="diner",terrain="inside",info="",notes="",x=5,y=24,z=0,building=""}
M[#M+1] = {uid=36702,name="The hostess stand",area="diner",terrain="inside",info="",notes="",x=5,y=23,z=0,building=""}
M[#M+1] = {uid=36703,name="Aisle between tables",area="diner",terrain="inside",info="",notes="",x=5,y=22,z=0,building=""}
M[#M+1] = {uid=36704,name="Aisle between tables",area="diner",terrain="inside",info="",notes="",x=5,y=21,z=0,building=""}
M[#M+1] = {uid=36705,name="Near the kitchen",area="diner",terrain="inside",info="",notes="",x=5,y=20,z=0,building=""}
M[#M+1] = {uid=36706,name="Table B1",area="diner",terrain="inside",info="",notes="",x=4,y=23,z=0,building=""}
M[#M+1] = {uid=36707,name="Table B2",area="diner",terrain="inside",info="",notes="",x=4,y=22,z=0,building=""}
M[#M+1] = {uid=36708,name="Table B3",area="diner",terrain="inside",info="",notes="",x=4,y=21,z=0,building=""}
M[#M+1] = {uid=36709,name="Table A1",area="diner",terrain="inside",info="",notes="",x=3,y=23,z=0,building=""}
M[#M+1] = {uid=36710,name="Table A2",area="diner",terrain="inside",info="",notes="",x=3,y=22,z=0,building=""}
M[#M+1] = {uid=36711,name="Table A3",area="diner",terrain="inside",info="",notes="",x=3,y=21,z=0,building=""}
M[#M+1] = {uid=36712,name="Table C1",area="diner",terrain="inside",info="",notes="",x=6,y=23,z=0,building=""}
M[#M+1] = {uid=36713,name="Table C2",area="diner",terrain="inside",info="",notes="",x=6,y=22,z=0,building=""}
M[#M+1] = {uid=36714,name="Table C3",area="diner",terrain="inside",info="",notes="",x=6,y=21,z=0,building=""}
M[#M+1] = {uid=36715,name="Table D1",area="diner",terrain="inside",info="",notes="",x=7,y=23,z=0,building=""}
M[#M+1] = {uid=36716,name="Table D2",area="diner",terrain="inside",info="",notes="",x=7,y=22,z=0,building=""}
M[#M+1] = {uid=36717,name="Table D3",area="diner",terrain="inside",info="",notes="",x=7,y=21,z=0,building=""}
M[#M+1] = {uid=36718,name="The VIP section",area="diner",terrain="inside",info="",notes="",x=4,y=23,z=1,building=""}
M[#M+1] = {uid=36719,name="The VIP section",area="diner",terrain="inside",info="",notes="",x=4,y=22,z=1,building=""}
M[#M+1] = {uid=36720,name="The VIP section",area="diner",terrain="inside",info="",notes="",x=4,y=21,z=1,building=""}
M[#M+1] = {uid=36721,name="The VIP section",area="diner",terrain="inside",info="",notes="",x=3,y=21,z=1,building=""}
M[#M+1] = {uid=36722,name="The VIP section",area="diner",terrain="inside",info="",notes="",x=3,y=22,z=1,building=""}
M[#M+1] = {uid=36723,name="A server station",area="diner",terrain="inside",info="",notes="",x=3,y=23,z=1,building=""}
M[#M+1] = {uid=36724,name="The lounge area",area="diner",terrain="inside",info="",notes="",x=6,y=23,z=1,building=""}
M[#M+1] = {uid=36725,name="The lounge area",area="diner",terrain="inside",info="",notes="",x=6,y=22,z=1,building=""}
M[#M+1] = {uid=36726,name="The lounge area",area="diner",terrain="inside",info="",notes="",x=6,y=21,z=1,building=""}
M[#M+1] = {uid=36727,name="Behind the bar",area="diner",terrain="inside",info="",notes="",x=7,y=23,z=1,building=""}
M[#M+1] = {uid=36728,name="Behind the bar",area="diner",terrain="inside",info="",notes="",x=7,y=22,z=1,building=""}
M[#M+1] = {uid=36729,name="Behind the bar",area="diner",terrain="inside",info="",notes="",x=7,y=21,z=1,building=""}
M[#M+1] = {uid=36730,name="Men's restroom",area="diner",terrain="inside",info="",notes="",x=4,y=20,z=0,building=""}
M[#M+1] = {uid=36731,name="Women's restroom",area="diner",terrain="inside",info="",notes="",x=6,y=20,z=0,building=""}
M[#M+1] = {uid=36732,name="The waiting area",area="diner",terrain="inside",info="",notes="",x=4,y=24,z=0,building=""}
M[#M+1] = {uid=36755,name="Carriage parking area",area="diner",terrain="field",info="",notes="",x=6,y=25,z=0,building=""}
M[#M+1] = {uid=36756,name="Carriage parking area",area="diner",terrain="field",info="",notes="",x=4,y=25,z=0,building=""}
M[#M+1] = {uid=36757,name="A small walkway",area="diner",terrain="inside",info="",notes="",x=5,y=22,z=1,building=""}
M[#M+1] = {uid=36758,name="Between the server stations",area="diner",terrain="inside",info="",notes="",x=5,y=19,z=0,building=""}
M[#M+1] = {uid=36759,name="A server station",area="diner",terrain="inside",info="",notes="",x=4,y=19,z=0,building=""}
M[#M+1] = {uid=36760,name="A server station",area="diner",terrain="inside",info="",notes="",x=6,y=19,z=0,building=""}
M[#M+1] = {uid=36761,name="The Kitchen",area="diner",terrain="inside",info="",notes="",x=5,y=18,z=0,building=""}
M[#M+1] = {uid=36762,name="The Kitchen",area="diner",terrain="inside",info="",notes="",x=4,y=18,z=0,building=""}
M[#M+1] = {uid=36763,name="The Kitchen",area="diner",terrain="inside",info="",notes="",x=6,y=18,z=0,building=""}
M[#M+1] = {uid=36764,name="Back of the kitchen",area="diner",terrain="inside",info="",notes="",x=4,y=17,z=0,building=""}
M[#M+1] = {uid=36765,name="Back of the kitchen",area="diner",terrain="inside",info="",notes="",x=5,y=17,z=0,building=""}
M[#M+1] = {uid=36766,name="Back of the kitchen",area="diner",terrain="inside",info="",notes="",x=6,y=17,z=0,building=""}
M[#M+1] = {uid=36767,name="Dry storage",area="diner",terrain="cabin",info="",notes="",x=4,y=18,z=-1,building=""}
M[#M+1] = {uid=36771,name="Cold storage",area="diner",terrain="castle",info="",notes="",x=6,y=18,z=-1,building=""}
M[#M+1] = {uid=36779,name="A stairwell",area="diner",terrain="stairs",info="",notes="",x=5,y=19,z=1,building=""}
M[#M+1] = {uid=36780,name="Tumari's office",area="diner",terrain="inside",info="safe",notes="",x=5,y=18,z=1,building=""}
M[#M+1] = {uid=36781,name="Employee break room",area="diner",terrain="inside",info="",notes="",x=4,y=19,z=1,building=""}
M[#M+1] = {uid=36782,name="Employee restrooms",area="diner",terrain="inside",info="",notes="",x=6,y=19,z=1,building=""}
return M
